sendbird/sendbird-uikit-react

README.md

[<TICKET_ID>](https://sendbird.atlassian.net/browse/<TICKET_ID>)

Update readme quickly

---

src/index.d.ts
src/smart-components/ChannelList/index.jsx
src/smart-components/Conversation/components/ConversationScroll.jsx
src/smart-components/Conversation/components/MessageHOC.jsx
src/smart-components/OpenchannelConversation/components/MessageHOC.tsx
src/smart-components/OpenchannelConversation/components/OpenchannelConversationScroll.tsx
src/ui/UserProfile/index.scss
src/ui/UserProfile/index.tsx

[UK-940](https://sendbird.atlassian.net/browse/UK-940)
- Add a condition checking currentChannelUrl before getChannel
- Add params to renderChatItem with hasSeparator and menuDisabled

[UK-940] Bugfix: Add checking current channel condition and has separator

---

src/ui/MessageContent/index.tsx

[UK-945](https://sendbird.atlassian.net/browse/UK-945)
Fix alignment of pending message

[UK-945] Fix alignment of pending message

---

src/ui/MessageItemMenu/index.tsx

[Hotfix] Hide reply menu

---

CHANGELOG.md
package-lock.json
package.json

[UK-861](https://sendbird.atlassian.net/browse/UK-861)
- Bugfix:
* Fix issues of the event filter and add tests
* Add checking current channel condition before get channel
* Add hasSeparator and menuDisabled props to renderChatItem
* Fix alignment of pending message

[UK-861] Release/v2.4.1

---

src/index.d.ts
src/smart-components/Conversation/components/ConversationScroll.jsx
src/smart-components/Conversation/components/MessageHOC.jsx
src/smart-components/Conversation/hooks/useScrollToMessage.ts
src/smart-components/Conversation/index.jsx
src/smart-components/Conversation/index.scss
src/ui/MessageContent/index.tsx
src/ui/OGMessageItemBody/__tests__/__snapshots__/OGMessageItemBody.spec.js.snap
src/ui/OGMessageItemBody/index.scss
src/ui/OGMessageItemBody/index.tsx
src/ui/ReplyingMessageAttachment/index.tsx

- Implement js logic to scroll to message
- Add CSS highlight for scroll to message

[UK-767]Implement scroll to message

---

package-lock.json
package.json
src/smart-components/OpenchannelConversation/index.tsx
src/smart-components/OpenchannelConversation/stories/index.stories.js

* SENDING_MESSAGE_START payload didnt had channel object before
* Fix CSS issue with render custom message

Fix SENDING_MESSAGE_START payload mismatch

---

src/smart-components/ChannelList/utils.js

[SBISSUE-5745](https://sendbird.atlassian.net/browse/SBISSUE-5745)
Add a null check for sdk and sdk.ChannelHandler before calling createEventHandler

[SBISSUE-5745] Add null check for sdk before calling createEventHandler

---

src/ui/MessageContent/index.scss

[UK-959](https://sendbird.atlassian.net/browse/UK-959)
Apply deprecated CSS "end" and use "flex-end" instead

[UK-959] Use flex-end instead of end

---

src/ui/MessageContent/index.tsx
src/utils/index.ts

[Bugfix: issue link](https://community.sendbird.com/t/all-message-marked-as-outgoing-in-sendbird-react-app-component/3134)
Only use isMessageSentByMe function to calculate isByMe in the MessageContent

Bugfix: Only use isMessageSentByMe to calculate isByMe

---

src/smart-components/App/stories/index.stories.js
src/smart-components/Conversation/components/ConversationScroll.jsx
src/smart-components/Conversation/index.jsx
src/smart-components/OpenchannelConversation/hooks/useResendMessageCallback.ts
src/smart-components/OpenchannelConversation/index.tsx
src/ui/ContextMenu/index.jsx

Hotfix: Add console for announcement of renderCustomMessage props

---

.size-snapshot.json
CHANGELOG.md

Add change log of v2.4.4 release

Release v2.4.4

---

src/smart-components/App/index.jsx
src/smart-components/App/stories/index.stories.js
src/smart-components/ChannelList/dux/reducers.js
src/smart-components/Conversation/components/MessageHOC.jsx
src/smart-components/Conversation/components/MessageInputWrapper.tsx
src/smart-components/Conversation/components/RemoveMessage.jsx
src/smart-components/Conversation/index.jsx
src/smart-components/Conversation/utils.js
src/ui/Button/index.scss
src/ui/Button/stories/Button.stories.js
src/ui/FileViewer/__tests__/__snapshots__/FileViewer.spec.js.snap
src/ui/FileViewer/index.jsx
src/ui/FileViewer/index.scss
src/ui/Icon/index.scss
src/ui/Icon/stories/Icon.stories.js
src/ui/MessageInput/index.jsx
src/ui/Modal/index.jsx
src/ui/QuoteMessage/index.scss
src/ui/QuoteMessage/index.tsx
src/utils/index.ts

[QU-361](https://sendbird.atlassian.net/browse/QU-361)
[QU-382](https://sendbird.atlassian.net/browse/QU-382)
[QU-385](https://sendbird.atlassian.net/browse/QU-385)
* Lift restriction of replyType props of App and Channel components
* Do not allow the message grouping to pending and failed messages
* Disable delete button on FileViewer when the message has replies
* Disable message delete submit button on modal when the message has replies
* Clear message input value and quoted message when the current channel is changed
* Affect UI components to apply the on thread info updated event
* Check if the left user is me

[Bugfix] Final QA of message threading

---

CHANGELOG.md
package-lock.json
package.json

Add a CHANGELOG for an alpha release

[Release] Add a CHANGELOG for an alpha release

---

CHANGELOG.md
package-lock.json

- Features
* Support MessageThreading
* <App /> and <Channel /> can enable or disable message threading feature using prop: `replyType`
* `replyType="QUOTE_REPLY"` enable message threading
* `replyType="NONE"` disable message threading, and this is a default option
- Bugfix
* Change the message status component location from the bottom of the message to the side of the message content

[2.5.0] (Nov 23 2021)

---

CHANGELOG.md
package-lock.json
package.json

- Features
* Support MessageThreading
* <App /> and <Channel /> can enable or disable message threading feature using prop: `replyType`
* `replyType="QUOTE_REPLY"` enable message threading
* `replyType="NONE"` disable message threading, and this is a default option
- Bugfix
* Change the message status component location from the bottom of the message to the side of the message content

[2.5.0] (Nov 23 2021) including package.json

---

package-lock.json
src/smart-components/Conversation/utils.js
src/smart-components/OpenchannelConversation/utils.ts

- Add optional chaining into the utils function 'isSameGroup'
- Change OR operation to AND operation in the condition

Hotfix: Add optional chaining into the utils function

---

src/smart-components/Conversation/hooks/useSendFileMessageCallback.js

[SBISSUE-7442](https://sendbird.atlassian.net/browse/SBISSUE-7442)
Add quote message to onBeforeSendFileMessage params

[SBISSUE-7442]Add quote message to onBeforeSendFileMessage params

---

CHANGELOG.md
src/smart-components/Conversation/index.scss

[SDKRLSD-297](https://sendbird.atlassian.net/browse/SDKRLSD-297)

Release v2.5.2

---

.size-snapshot.json
src/smart-components/Conversation/components/MessageHOC.jsx
src/ui/MessageItemMenu/index.tsx

Modify type definition

---

.size-snapshot.json
package-lock.json
package.json

[UIKIT-1456](https://sendbird.atlassian.net/browse/UIKIT-1456)
[UIKIT-1456] Modify React dependencies to devide to peer and dev
[UIKIT-1456]: https://sendbird.atlassian.net/browse/UIKIT-1456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UIKIT-1456] Modify React dependencies to devide to peer and dev

---

src/smart-components/App/stories/index.stories.js
src/smart-components/Conversation/components/ConversationScroll.jsx

[SBISSUE-7325](https://sendbird.atlassian.net/browse/SBISSUE-7325)
Change PropTypes value of renderChatItem from element to func in ConversationScroll comp

[SBISSUE-7325] Invalid prop renderChatItem of type function

---

.size-snapshot.json
CHANGELOG.md

[SDKRLSD-302](https://sendbird.atlassian.net/browse/SDKRLSD-302)

Release v2.5.3

---

src/index.d.ts

[UIKIT-1502](https://sendbird.atlassian.net/browse/UIKIT-1502)
* Add sortChannelList props to the ChannelListProps

Fix: Add sortChannelList props to the ChannelListProps

---

src/ui/ContextMenu/items/EmojiListItems.jsx
src/ui/ContextMenu/items/MenuItems.jsx

This fixes compilation issues, something about `Element` not being defined.

Fix: Compilation issue Element not defined

---

.size-snapshot.json
CHANGELOG.md

[SDKRLSD-308](https://sendbird.atlassian.net/browse/SDKRLSD-308)

Release: v2.6.0

---

src/index.d.ts
src/lib/selectors.js

[UIKIT-1533](https://sendbird.atlassian.net/browse/UIKIT-1533)
* Add progressHandler into the GetSendFileMessage hook

Fix/v2/UIKIT-1533_Add progressHandler into the GetSendFileMessage hook

---

src/smart-components/Channel/components/ChannelUI/index.tsx
src/smart-components/Channel/components/MessageInput/index.tsx
src/smart-components/Channel/context/ChannelProvider.tsx
src/smart-components/Channel/context/dux/__tests__/reducers.spec.js

[qm-632](https://sendbird.atlassian.net/browse/qm-632)
* Add messageInputRef to the MessageInputWrapper component
* Modify params interface of sendMessage and sendFileMessage props

Fix: Fix sending message issue

---

src/index.d.ts
src/smart-components/Channel/components/ChannelUI/index.tsx
src/smart-components/Channel/context/ChannelProvider.tsx
src/smart-components/OpenChannel/context/OpenChannelProvider.tsx
src/smart-components/OpenChannel/context/dux/initialState.ts
src/smart-components/OpenChannel/context/dux/reducers.ts
src/smart-components/OpenChannel/context/hooks/useCheckScrollBottom.ts
src/smart-components/OpenChannel/context/hooks/useSendMessageCallback.ts
src/smart-components/OpenChannel/context/hooks/useSetChannel.ts
src/smart-components/OpenChannel/context/utils.ts
src/smart-components/OpenChannelApp/Community.tsx
src/smart-components/OpenChannelApp/components/CommunityChannelList.tsx
src/smart-components/OpenChannelApp/components/OpenChannelPreview.tsx
src/smart-components/OpenChannelApp/stories/index.stories.js

[QM-630](https://sendbird.atlassian.net/browse/QM-630)
**GroupChannel**
[QM-648](https://sendbird.atlassian.net/browse/QM-648)
* Call action type markAsRead in any case
**OpenChannel**
[QM-661](https://sendbird.atlassian.net/browse/QM-661)
* Modify the payload of the dispatcher on the SENDING_MESSAGE_FAILED action
[QM-662](https://sendbird.atlassian.net/browse/QM-662)
* Add the current user to the muted participant list when sending message failed by muted error
[QM-674](https://sendbird.atlassian.net/browse/QM-674)
* Fix typos that are related to those issues

Fix: [v3] Bugfix for Modularization QA 220222

---

src/smart-components/ChannelList/components/ChannelPreviewAction.jsx
src/smart-components/ChannelSettings/components/AdminPanel/AddOperatorsModal.tsx
src/smart-components/ChannelSettings/components/AdminPanel/InviteMembersModal.tsx
src/smart-components/ChannelSettings/components/AdminPanel/admin-panel.scss
src/smart-components/ChannelSettings/components/ChannelSettingsUI/index.tsx
src/smart-components/MessageSearch/context/hooks/useGetSearchedMessages.ts
src/smart-components/OpenChannel/components/OpenChannelMessage/index.tsx
src/smart-components/OpenChannel/components/OpenChannelMessageList/index.tsx
src/smart-components/OpenChannel/context/dux/reducers.ts
src/ui/Modal/index.scss
src/ui/OpenchannelFileMessage/__tests__/OpenchannelFileMessage.spec.js
src/ui/OpenchannelFileMessage/index.tsx
src/ui/OpenchannelFileMessage/mockMessages.ts
src/ui/OpenchannelOGMessage/__tests__/OpenchannelOGMessage.spec.js
src/ui/OpenchannelOGMessage/index.tsx
src/ui/OpenchannelThumbnailMessage/__tests__/OpenchannelThumbnailMessage.spec.js
src/ui/OpenchannelThumbnailMessage/index.tsx
src/ui/OpenchannelUserMessage/__tests__/OpenchannelUserMessage.spec.js
src/ui/OpenchannelUserMessage/index.tsx

[QM-630](https://sendbird.atlassian.net/browse/QM-630)
* Match the props name of LeaveChannelModal
* Remove status props and use message.sendingStatus instead in the Message components
* Set error icon's color to Error
* Handle edge case when a message failed first than a pending message
* Remove minimum height of Modal component
* Add inner scroll component into the Modal component
[QM-630](https://sendbird.atlassian.net/browse/QM-662)
[QM-671](https://sendbird.atlassian.net/browse/QM-671)
[QM-672](https://sendbird.atlassian.net/browse/QM-672)
[QM-673](https://sendbird.atlassian.net/browse/QM-673)

Fix: [v3] Modularization QA 220224

---

src/smart-components/ChannelSettings/components/AdminPanel/admin-panel.scss
src/ui/Modal/index.scss

[QM-673](https://sendbird.atlassian.net/browse/QM-673)
* Apply overflow scroll to the member list comp instead of Modal comp

Fix: [v3] Load member list by scroll event

---

src/smart-components/App/stories/utils.jsx
src/smart-components/Channel/components/FileViewer/index.tsx
src/smart-components/Channel/components/Message/index.tsx
src/smart-components/Channel/components/MessageList/index.tsx
src/smart-components/Channel/context/ChannelProvider.tsx
src/smart-components/Channel/context/dux/reducers.js
src/smart-components/Channel/context/hooks/useResendMessageCallback.js
src/smart-components/Channel/context/utils.js
src/ui/MessageContent/index.tsx
src/ui/MessageItemMenu/index.tsx
src/ui/MessageItemReactionMenu/index.tsx
src/ui/OpenchannelFileMessage/index.tsx
src/ui/OpenchannelOGMessage/index.tsx
src/ui/OpenchannelThumbnailMessage/index.tsx
src/ui/ThumbnailMessageItemBody/index.tsx
src/utils/index.ts

[QM-630](https://sendbird.atlassian.net/browse/QM-630)
* Set icon color to failed messages in open channel
* Disable appearing file viewer when message sending status is pending
* Pass the usingReaction props through the context
* Set unreadCount value to 0 when current channel changes
* Fetch message list by messageList scroll event
* Export messageActionTypes in ChannelProvider
* Update member when it's profileUrl, friendName, or nickname is changed

Fix: [v3] Modularization QA 220318

---

src/smart-components/Conversation/hooks/useGetChannel.js
src/smart-components/Conversation/hooks/useHandleChannelEvents.js
src/smart-components/Conversation/hooks/useHandleReconnect.ts
src/smart-components/Conversation/hooks/useInitialMessagesFetch.js
src/smart-components/Conversation/hooks/useScrollCallback.js
src/smart-components/Conversation/hooks/useScrollDownCallback.js
src/smart-components/Conversation/index.jsx

This error occurs in codesandbox
Especially when multiple users are running same sandbox
Error is command no ACK error that comes from markAsRead called in quick succession
This is a stop gap solution
Need to find proper fix.
Fixes: https://sendbird.atlassian.net/browse/UIKIT-1619

Fix: Suppress NO ACK error

---

package-lock.json
src/smart-components/ChannelList/components/ChannelPreview/utils.js
src/ui/ChannelPreview/index.jsx
src/ui/ChannelPreview/utils.js
src/ui/MessageSearchFileItem/utils.ts
src/ui/MessageSearchItem/getCreatedAt.ts

[UIKIT-1627](https://sendbird.atlassian.net/browse/UIKIT-1627)
* Manage a null state of the optional param in date-fns

Fix: [v3] Manage the optional param of localize

---

src/smart-components/Channel/components/MessageInput/index.tsx
src/smart-components/Channel/components/TypingIndicator.tsx

[<TICKET_ID>](https://sendbird.atlassian.net/browse/<TICKET_ID>)
* Call endTyping when sending user message

Fix: [v3] Call endTyping when sending user message

---

samples/groupchannel/src/CustomizedApp.js

[SLN-184](https://sendbird.atlassian.net/browse/SLN-184)
Updated the placement of the `showSettings` conditional in the groupChannel sample. 

fix: Corrected groupChannel sample setting placement

---

README.md

Add badges and introduction for v2

Add badges and introduction for v2

---

README.md

Fix [v3] badges

---

CHANGELOG.md
package.json
scripts/package.template.json
scripts/steps.md

Feature:
* Mention
* Add isMentionEnabled props to the <App /> and <SendbirdProvider />
* Add userMention into the config props of the <App /> andd <SendbirdProvider />
* <SendbirdProvider config={{ userMention: { maxMentionCount: 10, maxSuggestionCount: 15 } }} />
* maxMentionCount: A maximum count that you can mention in the message input
* maxSuggestionCount: A maximum user count that the SuggestedMentionList suggests for user mention
* Create SuggestedMentionList component under the Channel smart component
* Create SuggestedUserMentionItem component
* Create MentionUserLabel ui component
* Add string set
* MENTION_NAME__NO_NAME: '(No name)'
* MENTION_COUNT__OVER_LIMIT: 'You can mention up to %d times per message.'
Fix:
* Type definition file fix for TS project
For typescript projects, …

3.0.0-beta.2] (April 29 2022)

---

src/ui/FileViewer/index.jsx
src/ui/ThumbnailMessageItemBody/index.tsx

fixes: https://sendbird.atlassian.net/browse/UIKIT-1684

fix: message shouldnt be clikced while loading

---

src/smart-components/ChannelList/index.jsx
src/smart-components/ChannelList/utils.js

fixes: https://sendbird.atlassian.net/browse/UIKIT-1718

fix: Add rate limit to markAsDelivered call

---

.size-snapshot.json
CHANGELOG.md
package-lock.json
package.json

[SDKRLSD-368](https://sendbird.atlassian.net/browse/SDKRLSD-368)
Release v2.7.1
[2.7.1] (May 11 2022)
- Bugfix
* Add rate limit to markAsDelivered call
* Thumbnail message shouldnt be clikced while loading
* Fix sample: corrected groupChannel sample setting placement

Release v2.7.1

---

src/smart-components/ChannelList/components/ChannelListUI/index.tsx
src/smart-components/ChannelList/utils.js

fixes: https://sendbird.atlassian.net/browse/UIKIT-1718

fix: rate limit markAsDelivered call

---

src/smart-components/ChannelList/context/ChannelListProvider.tsx

Type definition expects useChannelList instead of useChannelListContext

fix: Export useChannelList

---

exports.js
scripts/index_d_ts
src/styles/_color-themes.scss
src/styles/_dark-theme.scss
src/styles/_light-theme.scss
src/ui/MentionLabel/index.scss
src/ui/MentionLabel/index.tsx
src/ui/UserProfile/index.tsx
src/ui/Word/__tests__/__snapshots__/Word.spec.js.snap
src/ui/Word/index.scss
src/ui/Word/index.tsx

* Show profile on clicking a mention
* Visual highlight when user is mention
Fixes:
https://sendbird.atlassian.net/browse/UIKIT-1786
https://sendbird.atlassian.net/browse/UIKIT-1787

feat: Mention improvements

---

scripts/index_d_ts
src/index.d.ts
src/smart-components/App/stories/index.stories.js
src/smart-components/Channel/components/Message/index.tsx
src/smart-components/Channel/components/MessageInput/index.tsx
src/smart-components/Channel/components/SuggestedMentionList/SuggestedUserMentionItem.tsx
src/smart-components/Channel/components/SuggestedMentionList/index.scss
src/smart-components/Channel/components/SuggestedMentionList/index.tsx
src/smart-components/Channel/context/utils.js
src/smart-components/ChannelList/components/ChannelPreview/channel-preview.scss
src/smart-components/ChannelList/components/ChannelPreview/index.tsx
src/ui/Label/index.scss
src/ui/MessageInput/__tests__/MessageInput.spec.js
src/ui/MessageInput/index.jsx

[QM-1392](https://sendbird.atlassian.net/browse/QM-1392)
[QM-1452](https://sendbird.atlassian.net/browse/QM-1452)
[QM-1453](https://sendbird.atlassian.net/browse/QM-1453)
[QM-1454](https://sendbird.atlassian.net/browse/QM-1454)
[QM-1458](https://sendbird.atlassian.net/browse/QM-1458)
[QM-1462](https://sendbird.atlassian.net/browse/QM-1462)
[QM-1463](https://sendbird.atlassian.net/browse/QM-1463)
[QM-1466](https://sendbird.atlassian.net/browse/QM-1466)
[QM-1469](https://sendbird.atlassian.net/browse/QM-1469)
[QM-1470](https://sendbird.atlassian.net/browse/QM-1470)
QM-1392
* Modify mention badge position
QM-1452
QM-1470
* Modify the onMouseOver event on the suggested mention list component
QM-1453
* Set the maximum …

Fix: [v3] Fix for QA mention and verse

---

scripts/index_d_ts
src/index.d.ts
src/lib/Sendbird.jsx
src/lib/dux/sdk/thunks.js

Interface:
```
// its recommended to memoize configureSession function
const memoizedConfigureSession = (sb) => {
const sessionHandler = new sb.SessionHandler();
sessionHandler.onSessionTokenRequired = (onSuccess, onError) => {
};
sessionHandler.onSessionClosed = () => {
};
sessionHandler.onSessionRefreshed = () => {
};
sessionHandler.onSessionError = err => {
};
return sessionHandler;
};
configureSession={memoizedConfigureSession}
/>
```
see: https://sendbird.com/docs/chat/v3/javascript/guides/authentication
Fixes: https://sendbird.atlassian.net/browse/UIKIT-1796

feat: Add session handler interface

---

CHANGELOG.md
src/smart-components/ChannelList/components/ChannelPreview/index.tsx

[QM-1476](https://sendbird.atlassian.net/browse/QM-1476)
QM-1476
* Add ' (edited)' text on the ChannelPreview(ChannelListItem) component for the edited last message

Bugfix: [v3] Fix for QA ChannelListItem

---

scripts/index_d_ts
src/smart-components/Channel/components/MessageInput/index.tsx
src/smart-components/OpenChannel/components/OpenChannelInput/index.tsx
src/smart-components/OpenChannel/context/OpenChannelProvider.tsx
src/smart-components/OpenChannel/context/hooks/useSendMessageCallback.ts
src/ui/MessageInput/index.jsx

[QM-1489](https://sendbird.atlassian.net/browse/QM-1489)
* Call endTyping when message input is empty

Fix: [v3] Call endTyping when message input is empty

---

src/smart-components/OpenChannelSettings/components/OpenChannelSettingsUI/index.tsx
src/smart-components/OpenChannelSettings/components/OpenChannelSettingsUI/open-channel-ui.scss

fixes: https://sendbird.atlassian.net/browse/QM-1567

fix: add parent class to openChannelSettings

---

src/smart-components/OpenChannelApp/components/CommunityChannelList.tsx
src/smart-components/OpenChannelApp/stories/index.stories.js
src/smart-components/OpenChannelSettings/components/DeleteOpenChannel.tsx
src/smart-components/OpenChannelSettings/context/OpenChannelSettingsProvider.tsx

fixes: https://sendbird.atlassian.net/browse/QM-1513

fix: delete option in open channel settings

---

src/smart-components/OpenChannelSettings/components/OpenChannelSettingsUI/index.tsx
src/smart-components/OpenChannelSettings/components/OpenChannelSettingsUI/open-channel-ui.scss
src/smart-components/OpenChannelSettings/components/OperatorUI/index.tsx
src/smart-components/OpenChannelSettings/components/ParticipantUI/index.tsx

Operator UI was also broken, figured out after participant fix
fixes: https://sendbird.atlassian.net/browse/QM-1567

fix: operator ui

---

src/smart-components/App/stories/index.stories.js
src/smart-components/ChannelList/context/ChannelListProvider.tsx

[QM-1571](https://sendbird.atlassian.net/browse/QM-1571)
* Update channel in the ChannelList
* when the unread member count changes of the last message
* when the undelivered member count changes of the last message

Fix [v3] Update channel when the last message status changes in ChannelList

---

src/smart-components/Channel/components/MessageList/index.tsx

[QM-1569](https://sendbird.atlassian.net/browse/QM-1569)
* QM-1569
* Fix scroll down condition on the MessageList

Fix [v3] scroll down condition on the MessageList

---

package-lock.json
package.json
src/smart-components/Channel/context/hooks/useInitialMessagesFetch.js
src/smart-components/Channel/context/hooks/useScrollCallback.js
src/smart-components/Channel/context/hooks/useScrollDownCallback.js

[QM-1523](https://sendbird.atlassian.net/browse/QM-1523)
* Apply `replyType` to only_reply_to_channel with Chat fix
* means: Fetch message list with replyToChannel option

Fix [v3] Apply replyType to only_reply_to_channel with Chat fix

---

src/ui/ContextMenu/index.scss
src/ui/ContextMenu/items/MenuItems.jsx
src/ui/MessageContent/index.scss

[QM-1576](https://sendbird.atlassian.net/browse/QM-1576)
* Remove useless CSS logic on ContextMenu menuItems

Fix [v3] text message style for mention label in message

---

src/smart-components/App/stories/index.stories.js
src/smart-components/Channel/components/SuggestedMentionList/SuggestedUserMentionItem.tsx

[QM-1540](https://sendbird.atlassian.net/browse/QM-1540)
* Change ScrollIntoView option 'block: nearest' on a mention on edit message
Thanks to
https://stackoverflow.com/a/67433987

Fix: [v3] Fix mention automatically scroll in message edit

---

.eslintrc.js
.eslintrc.json
package-lock.json
package.json
rollup.config.js
src/smart-components/Channel/components/ChannelHeader/utils.ts
src/smart-components/Channel/context/dux/__tests__/reducers.spec.js
src/smart-components/Channel/context/hooks/useDeleteMessageCallback.js
src/smart-components/Channel/context/hooks/useHandleChannelEvents.ts
src/smart-components/Channel/context/hooks/useHandleReconnect.ts
src/smart-components/Channel/context/hooks/useInitialMessagesFetch.js
src/smart-components/Channel/context/hooks/useResendMessageCallback.js
src/smart-components/Channel/context/hooks/useScrollCallback.js
src/smart-components/Channel/context/hooks/useScrollDownCallback.js
src/smart-components/Channel/context/hooks/useSendFileMessageCallback.js
src/smart-components/Channel/context/hooks/useSendMessageCallback.js
src/smart-components/Channel/context/hooks/useToggleReactionCallback.js
src/smart-components/Channel/context/hooks/useUpdateMessageCallback.js
src/smart-components/Channel/context/utils.js
src/smart-components/ChannelList/components/ChannelPreview/utils.js
src/smart-components/ChannelList/utils.js
src/smart-components/ChannelSettings/components/ChannelProfile/index.tsx
src/smart-components/OpenChannel/context/utils.ts
src/smart-components/OpenChannelSettings/components/ParticipantUI/index.tsx
src/ui/ChannelPreview/utils.js
src/ui/ChatHeader/utils.js
src/ui/ContextMenu/items/MenuItems.jsx

* Change the messageListParams property names to fit chat v4
* messageType to messageTypeFilter
* customTypes to customTypesFilter
* senderUserIds to senderUserIdsFilter
* Do not use optional chaining in null check with !== when it's used under lines
* Remove unused importing modules in the ParticipantUI component
* Install
* `eslint-plugin-babel`
* `@typescript-eslint/parser`
* `@typescript-eslint/eslint-plugin`
* Change eslintrc
* "no-unused-expressions": "off"
* "@typescript-eslint/no-unused-expressions": ["error"]
* Fix lint error
* Do not use optional chaining for methods in js file. so we can use it after translating to ts

Fix: [v3] Fix test failures on chat v4

---

samples/openchannel/src/components/CommunityChannelList.jsx
samples/openchannel/src/components/StreamingChannelList.jsx
src/hooks/useSendbirdStateContext.tsx
src/index.d.ts
src/index.js
src/lib/selectors.ts
src/lib/stories/index.stories.js
src/lib/stories/message.stories.js
src/lib/types.ts
src/smart-components/App/stories/index.stories.js
src/smart-components/CreateChannel/components/SelectChannelType.tsx
src/smart-components/CreateChannel/context/CreateChannelProvider.tsx
src/smart-components/OpenChannelApp/components/CommunityChannelList.tsx
src/smart-components/OpenChannelApp/components/StreamingChannelList.tsx
src/ui/UserProfile/index.tsx

This is a fix that I found out
* Change sendbirdSelectors importing path on the OpenChannel samples
* Rename sendBirdSelectors to sendbirdSelectors

Fix [v3] Change sendbirdSelectors importing path on sample

---

samples/openchannel/src/components/CommunityChannelList.jsx

[QM-1565](https://sendbird.atlassian.net/browse/QM-1565)
* Remove channel on the open channel list when it's banned or deleted

Fix: [v3] Remove channel from the channel list when banned or deleted

---

src/smart-components/OpenChannelSettings/components/EditDetailsModal.tsx
src/smart-components/OpenChannelSettings/components/OpenChannelProfile/channel-profile.scss
src/smart-components/OpenChannelSettings/context/OpenChannelSettingsProvider.tsx

[QM-1567](https://sendbird.atlassian.net/browse/QM-1567)
* Apply ellipsis to the title of the OpenChannelSettings component
* Update channel state when updating channel information in the OpenChannelSettings

Fix [v3] Update open channel info on settings

---

src/smart-components/OpenChannel/components/OpenChannelMessageList/index.tsx
src/smart-components/OpenChannel/components/OpenChannelMessageList/openchannel-message-list.scss

[QM-1563](https://sendbird.atlassian.net/browse/QM-1563)
* Set up again the scrollHandler, scrollRef, and CSS on the OpenChannel

Fix: [v3] Display scrollToBottom button in proper case

---

src/smart-components/Channel/components/SuggestedMentionList/index.tsx

[QM-1596](https://sendbird.atlassian.net/browse/QM-1596)
* Do not apply User me for the mention

Fix [v3] QM-1596_Fix mentioning myself

---

MIGRATION_v2-to-v3.md
src/index.d.ts

fixes: https://sendbird.atlassian.net/browse/UIKIT-1848

doc: Update migration guide to reflect chat v4 changes

---

src/lib/selectors.ts
src/lib/stories/index.stories.js
src/lib/stories/message.stories.js

Storybook didn't run because of this issue
* Fix sendbirdSelectors issue

Fix [v3] sendbirdSelectors issue

---

src/index.d.ts
src/smart-components/App/index.jsx
src/smart-components/App/stories/index.stories.js
src/smart-components/App/types.ts
src/smart-components/Channel/components/MessageList/index.tsx
src/smart-components/Channel/context/ChannelProvider.tsx
src/smart-components/Channel/index.tsx
src/smart-components/OpenChannel/components/OpenChannelMessageList/index.tsx
src/smart-components/OpenChannel/context/OpenChannelProvider.tsx
src/smart-components/OpenChannel/index.tsx

[UIKIT-1624](https://sendbird.atlassian.net/browse/UIKIT-1624)
* Rename useMessageGrouping to isMessageGroupingEnabled

Refactor [v3] Rename useMessageGrouping to isMessageGroupingEnabled

---

samples/openchannel/src/components/OpenChannelPreview.jsx
src/smart-components/Channel/components/Message/index.tsx
src/smart-components/Channel/components/MessageList/index.tsx
src/smart-components/Channel/context/hooks/useHandleChannelEvents.ts
src/smart-components/OpenChannel/components/OpenChannelMessage/index.tsx
src/smart-components/OpenChannel/components/OpenChannelMessageList/index.tsx
src/smart-components/OpenChannel/components/OpenChannelMessageList/openchannel-message-list.scss
src/smart-components/OpenChannel/components/OpenChannelUI/index.tsx
src/smart-components/OpenChannel/context/utils.ts
src/smart-components/OpenChannelApp/Streaming.tsx
src/ui/MessageContent/index.tsx

[QM-1619](https://sendbird.atlassian.net/browse/QM-1619)
* Set the correct div element class name for scroll handling
* Change some types

Fix: [v3] Scroll of OpenChannelMessageList

---

src/smart-components/Channel/context/dux/reducers.js

[QM-1631](https://sendbird.atlassian.net/browse/QM-1631)
* Append parent message when it's updated

Fix: [v3] Append parent message when it's updated

---

src/ui/MessageContent/__tests__/__snapshots__/MessageContent.spec.js.snap
src/ui/OGMessageItemBody/__tests__/__snapshots__/OGMessageItemBody.spec.js.snap
src/ui/OGMessageItemBody/index.scss
src/ui/OGMessageItemBody/index.tsx
src/ui/TextMessageItemBody/__tests__/__snapshots__/TextMessageItemBody.spec.js.snap
src/ui/TextMessageItemBody/index.scss
src/ui/TextMessageItemBody/index.tsx

To fix the console error
* Replace p tag to div tag in the text message item body

Fix [v3] Replace p tag to div tag in the text message item body

---

src/smart-components/ChannelList/context/ChannelListProvider.tsx

[QM-1629](https://sendbird.atlassian.net/browse/QM-1629)
* Update ChannelPreview when onMessageUpdated and onMentionReceived

Fix: [v3] Appear mention badge when user receive mention

---

src/smart-components/Channel/components/SuggestedMentionList/SuggestedUserMentionItem.tsx
src/smart-components/Channel/components/SuggestedMentionList/index.tsx

[QM-1630](https://sendbird.atlassian.net/browse/QM-1630)
* Use unique value instead of the `member.nickname` for key in the suggested member list

Fix: [v3] Fix suggested member list item duplication

---

src/smart-components/Channel/components/Message/index.tsx

[QM-1633](https://sendbird.atlassian.net/browse/QM-1633)
* Change the condition when deactivating edit message input

Fix: [v3] Deactivate edit message input in the frozen or muted channel

---

src/smart-components/OpenChannelApp/streaming.scss
src/ui/OpenchannelThumbnailMessage/index.scss

[QM-1621](https://sendbird.atlassian.net/browse/QM-1621)
* Set the additional CSS to the ThumbnailMessage width of the live streaming open channel sample

Fix: [v3] Change max-width of ThumbnailMessage

---

src/smart-components/OpenChannelApp/streaming.scss

fixes: https://sendbird.atlassian.net/browse/QM-1621

Fix: [v3] streaming sample CSS to handle max-width

---

src/smart-components/ChannelList/context/ChannelListProvider.tsx
src/smart-components/ChannelList/dux/reducers.js
src/smart-components/OpenChannelSettings/components/OpenChannelSettingsUI/open-channel-ui.scss

[QM-1567](https://sendbird.atlassian.net/browse/QM-1567)
[QM-1629](https://sendbird.atlassian.net/browse/QM-1629)
* Apply `display: line-block` to the participant list item
* Temporary use getChannelWithoutCache when mention count is updated

Fix: [v3] QA css issue and mention update

---

exports.js
package.json
src/smart-components/App/types.ts
src/smart-components/Channel/components/FileViewer/index.tsx
src/smart-components/Channel/components/Message/index.tsx
src/smart-components/MessageSearch/components/MessageSearchUI/index.tsx
src/smart-components/MessageSearch/context/dux/reducers.ts
src/smart-components/MessageSearch/context/hooks/useScrollCallback.ts
src/smart-components/OpenChannel/context/hooks/useCheckScrollBottom.ts
src/smart-components/OpenChannel/context/hooks/useDeleteMessageCallback.ts
src/smart-components/OpenChannel/context/hooks/useResendMessageCallback.ts
src/smart-components/OpenChannel/context/hooks/useTrimMessageList.ts
src/ui/MessageSearchFileItem/utils.ts
src/ui/MessageSearchItem/index.tsx

Remove some legacy types found during build inspection

hotfix: remove legacy types

---

MIGRATION_v2-to-v3.md
src/lib/selectors.ts

* Improve code of selectors
* Improve the migration guide docs

Fix: [v3] Trim code and docs

---

README.md
src/ui/Docs/Introduction.tsx
src/ui/Docs/stories/Doc.stories.js

doc: Prepare an introduction page for storybook

---

package-lock.json
package.json
rollup.config.js

Before: need to add stream and buffer libraries manually to webapck5 projects

fix: add node_module polyfills by defualt

---

src/smart-components/Channel/components/TypingIndicator.tsx

fixes: https://sendbird.atlassian.net/browse/UIKIT-1987

fix: safe call removeGroupChannelHandler in TypingIndicator

---

scripts/index_d_ts
src/index.d.ts

fixes: https://sendbird.atlassian.net/browse/UIKIT-1989

fix: add onCloseClick to MessageSearchProps

---

src/ui/OGMessageItemBody/index.tsx

[UIKIT-1911](https://sendbird.atlassian.net/browse/UIKIT-1911)
Detect url from string to divide it to normal string and url

Fix:Url should be identified even when merged with words

---

src/ui/Word/index.tsx

[UIKIT-1911](https://sendbird.atlassian.net/browse/UIKIT-1911)
Detect url from string to divide it to normal string and url

fix: Improve URL detection in OG messages

---

CHANGELOG.md
package-lock.json
package.json

Features:
* Accept customApiHost & customWebSocketHost as props to SendbirdProvider
* Add basic TS project sample
Fixes:
* Improve URL detection in OG message
* Add onCloseClick to MessageSearchProps
* Safe call removeGroupChannelHandler in TypingIndicator
* userListQuery
* Type definitions for channellist and setting

Release: [v3.0.1] (July 28 2022)

---

src/smart-components/OpenChannelSettings/components/OperatorUI/OperatorList.tsx
src/smart-components/OpenChannelSettings/components/OperatorUI/OperatorsModal.tsx
src/smart-components/OpenChannelSettings/components/ParticipantUI/index.tsx

[QM-1699](https://sendbird.atlassian.net/browse/QM-1699)
* Do not allow mute and ban me

fix: Do not allow mute and ban me

---

src/smart-components/OpenChannel/context/hooks/useSetChannel.ts

[QM-1702](https://sendbird.atlassian.net/browse/QM-1702)
* Update myMutedInfo when a participant enters the channel

Fix: Update myMutedInfo when participant enters channel

---

src/smart-components/OpenChannel/context/OpenChannelProvider.tsx
src/smart-components/OpenChannel/context/hooks/useSetChannel.ts
src/smart-components/OpenChannelSettings/components/ParticipantUI/index.tsx
src/smart-components/OpenChannelSettings/context/OpenChannelSettingsProvider.tsx

[QM-1705](https://sendbird.atlassian.net/browse/QM-1705)
* Exit channel when change the current channel or channel is unmounted

Fix: Exit channel when change the current channel or channel is unmounted

---

src/smart-components/ChannelList/components/utils.js
src/smart-components/ChannelSettings/components/ModerationPanel/InviteUsersModal.tsx
src/smart-components/CreateChannel/components/InviteUsers/utils.ts
src/ui/MentionLabel/index.tsx

[UIKIT-1920](https://sendbird.atlassian.net/browse/UIKIT-1920)
* Add optional chaining for createApplicationUserList

Fix: Add optional chaining for createApplicationUserList

---

src/lib/hooks/useOnlineStatus.js
src/smart-components/Channel/components/ChannelUI/index.tsx
src/smart-components/Channel/components/MessageList/index.tsx
src/smart-components/Channel/context/hooks/useGetChannel.js
src/smart-components/Channel/context/hooks/useHandleReconnect.ts
src/smart-components/ChannelList/components/ChannelListUI/index.tsx
src/smart-components/ChannelList/context/ChannelListProvider.tsx
src/smart-components/ChannelList/utils.js

fixes: https://sendbird.atlassian.net/browse/UIKIT-1958
Read: https://community.sendbird.com/t/sendbird-uikit-react-v2-with-nextjs-error-command-received-no-ack/5025
Read: https://community.sendbird.com/t/sendbirdexception-command-received-no-ack/1925/11?u=sravan_s

fix: Handle all chances of command not recieved error

---

src/smart-components/OpenChannelSettings/components/OpenChannelSettingsUI/open-channel-ui.scss
src/ui/UserListItem/index.scss

[QM-1725](https://sendbird.atlassian.net/browse/QM-1725)
* Reduce max-width of user list item title to 250px
* Undisplay the userId text on the participant list item on mouse hover

Fix: Manage long text nickname on the participant list

---

src/smart-components/OpenChannelSettings/components/OperatorUI/BannedUserList.tsx
src/smart-components/OpenChannelSettings/components/OperatorUI/BannedUsersModal.tsx
src/smart-components/OpenChannelSettings/components/OperatorUI/MutedParticipantList.tsx
src/smart-components/OpenChannelSettings/components/OperatorUI/MutedParticipantsModal.tsx
src/smart-components/OpenChannelSettings/components/OperatorUI/OperatorList.tsx
src/smart-components/OpenChannelSettings/components/OperatorUI/OperatorsModal.tsx
src/smart-components/OpenChannelSettings/components/ParticipantUI/ParticipantsModal.tsx
src/smart-components/OpenChannelSettings/components/ParticipantUI/index.tsx

[QM-1727](https://sendbird.atlassian.net/browse/QM-1727)
[QM-1729](https://sendbird.atlassian.net/browse/QM-1729)
* Do not allow operators to **unmute** themself on the muted user list and modal
* Do not allow operators to **unban** themself on the banned user list and modal
* Do now allow operators to **unregister** themself on the operator list and modal
* Do not allow operators to **moderate** themself on the participant list and modal

Fix: Do not allow operator to moderate himself

---

CHANGELOG.md
package-lock.json
package.json
rollup.config.js
src/lib/dux/sdk/thunks.js
src/lib/hooks/useOnlineStatus.js
src/smart-components/Channel/components/ChannelUI/index.tsx
src/smart-components/Channel/components/MessageList/index.tsx
src/smart-components/Channel/context/hooks/useGetChannel.js
src/smart-components/Channel/context/hooks/useHandleReconnect.ts
src/smart-components/ChannelList/components/ChannelListUI/index.tsx
src/smart-components/ChannelList/components/utils.js
src/smart-components/ChannelList/context/ChannelListProvider.tsx
src/smart-components/ChannelList/utils.js
src/smart-components/ChannelSettings/components/ModerationPanel/InviteUsersModal.tsx
src/smart-components/CreateChannel/components/InviteUsers/index.tsx
src/smart-components/CreateChannel/components/InviteUsers/utils.ts
src/ui/MentionLabel/index.tsx

Fixes:
* Explicitly export library as esm-module
ESM library should have "type": "module" (package.json file that is going to /dist)
This fixes Cannot use import outside module issue in next.js
* Add optional chaining for createApplicationUserList
* Cannot connect sometimes when customApiHost is empty
Connection couldnt be established with no error message when customApiHost and customWebSocketHost
were passed as empty string
* Handle all chances of command not received error
Handle chances of command not recieved error in markAsRead
Experimental markasread handling -> longer times, no more call after unmount
* Move typing handler in channellist into local variable

[v3.0.2-beta.0] (July 31 2022)

---

CHANGELOG.md
src/smart-components/OpenChannel/components/OpenChannelMessage/utils.ts
src/utils/index.ts

Fix: Add optional chaining for is user message

Fix: Add optional chaining for is user message

---

src/smart-components/ChannelSettings/context/ChannelSettingsProvider.tsx
src/smart-components/CreateChannel/components/InviteUsers/index.tsx
src/smart-components/OpenChannelSettings/components/OperatorUI/OperatorList.tsx
src/smart-components/OpenChannelSettings/context/OpenChannelSettingsProvider.tsx

[UIKIT-2043](https://sendbird.atlassian.net/browse/UIKIT-2043)
* Add an open channel handler into the OpenChannelSettings component
* Use operators property to render operator list on the OpenChannelSettings instead of fetching operators

Feat: Add channel handlers to the open channel settings

---

src/smart-components/ChannelList/context/ChannelListProvider.tsx

[UIKIT-2058](https://sendbird.atlassian.net/browse/UIKIT-2058)
* Fix typo of creating channelHandlerId on the ChannelList
* Thanks to https://github.com/sendbird/sendbird-uikit-react/pull/249

Fix: Fix typo of creating channelHandlerId on the ChannelList

---

scripts/index_d_ts
src/index.js

fixes: 
https://sendbird.atlassian.net/browse/UIKIT-2061

fix: add missing type defns from production file

---

scripts/index_d_ts

Change the type of MessageHandler.onFailed to FailedMessageHandler

Hotfix: Change the type of MessageHandler.onFailed to FailedMessageHandler

---

src/lib/selectors.ts

[UIKIT-2055](https://sendbird.atlassian.net/browse/UIKIT-2055)
Update SendableMessage to UserMessage and FileMessage

Fix: Update SendableMessage to UserMessage and FileMessage

---

SAMPLES.md

* Update codesandbox samples to work with UIKit v3
* Link new samples and doc links

doc: Update samples and  new sample links

---

exports.js
scripts/index_d_ts
src/lib/handlers/ConnectionHandler.ts
src/lib/handlers/GroupChannelHandler.ts
src/lib/handlers/OpenChannelHandler.ts
src/lib/handlers/README.md
src/lib/handlers/UserEventHandler.ts
src/lib/selectors.ts
src/lib/types.ts

fixes: https://sendbird.atlassian.net/browse/UIKIT-1993

fix: export Handlers thorough uikit

---

exports.js
src/ui/AdminMessage/adminMessageDummyData.mock.ts
src/ui/AdminMessage/index.tsx
src/ui/AdminMessage/stories/AdminMessage.stories.js

* Migrate AdminMessage component to TypeScript

feat: Migrate AdminMessage component to TypeScript

---

exports.js
scripts/index_d_ts
src/ui/Badge/__tests__/__snapshots__/Badge.spec.js.snap
src/ui/Badge/index.tsx
src/ui/Badge/stories/Badge.stories.js

Migrate Badge component to TypeScript

Refactor: Migrate Badge component to TypeScript

---

exports.js
src/ui/ConnectionStatus/index.tsx
src/ui/ConnectionStatus/stories/ConnectionStatus.stories.js

* Migrate ConnectionStatus to TypeScript

Refactor: Migrate ConnectionStatus to TypeScript

---

exports.js
src/ui/ChatHeader/index.tsx
src/ui/ChatHeader/stories/ChatHeader.stories.js
src/ui/ChatHeader/utils.ts

* Migrate ChannelHeader to TypeScript
* Warn this component will be deprecated
* Create a ticket to remove the ui/ChatHeader component in the next minor version up
* https://sendbird.atlassian.net/browse/UIKIT-2048 is made for v3.2.0

Refactor: Migrate ChannelHeader to TypeScript

---

exports.js
src/ui/SortByRow/index.tsx
src/ui/SortByRow/stories/SortByRow.stories.js

* Migrate SortByRow component to TypeScript

Refactor: Migrate SortByRow component to TypeScript

---

exports.js
src/ui/ReactionBadge/index.tsx
src/ui/ReactionBadge/stories/ReactionBadge.stories.js

* Migrate ReactionBadge to TypeScript

Refactor: Migrate ReactionBadge to TypeScript

---

exports.js
src/ui/PlaceHolder/index.tsx
src/ui/PlaceHolder/stories/PlaceHolder.stories.js
src/ui/PlaceHolder/type.ts

* Migrate PlaceHolder to TypeScript

Refactor: Migrate PlaceHolder to TypeScript

---

samples/groupchannel/src/CustomizedApp.js

per https://github.com/sendbird/sendbird-uikit-react/blob/main/MIGRATION_v2-to-v3.md#common-changes
and we'll evaluate if we can setup a [CLA](https://en.wikipedia.org/wiki/Contributor_License_Agreement) to allow for the contribution.
[<TICKET_ID>](https://sendbird.atlassian.net/browse/<TICKET_ID>)

fix: Open channel sample withSendBird to withSendbird

---

exports.js
src/smart-components/ChannelList/context/ChannelListProvider.tsx
src/ui/Input/__tests__/Input.spec.js
src/ui/Input/index.tsx
src/ui/Input/stories/Input.stories.js

* Migrate Input component to TypeScript

Refactor: Migrate Input component to TypeScript

---

src/ui/MessageStatus/messageDummyData.mock.ts

Migrate MessageStatus mock data to TypeScript

Refactor: Migrate MessageStatus mock data to TypeScript

---

exports.js
src/ui/Modal/index.tsx

Migrate Modal component to TypeScript

Refactor: Migrate Modal component to TypeScript

---

src/ui/TextButton/stories/TextButton.stories.js

remove .jsx in the storybook file of TextButton

fix: Modify the path of TextButton to remove .jsx

---

CHANGELOG_v2.md
scripts/index_d_ts

fix of https://github.com/sendbird/sendbird-uikit-react/pull/275
Use ReactNode and ReactElement

fix: Use ReactNode and ReactElement

---

MIGRATION_v2-to-v3.md
scripts/index_d_ts
src/index.d.ts
src/smart-components/Channel/components/ChannelUI/index.tsx
src/smart-components/Channel/components/Message/index.tsx
src/smart-components/Channel/components/MessageList/index.tsx
src/types.d.ts

[UIKIT-2178](https://sendbird.atlassian.net/browse/UIKIT-2178)
* Define `RenderCustomSeparatorProps`
* Apply the props into the renderCustomSeparator
* Fix typo sep**e**rator to sep**a**rator

fix: Modify render custom separator

---

src/smart-components/ChannelList/components/ChannelPreviewAction.jsx
src/ui/ContextMenu/MenuItems.tsx
src/ui/ContextMenu/index.scss
src/ui/ContextMenu/index.tsx
src/ui/MessageContent/__tests__/__snapshots__/MessageContent.spec.js.snap
src/ui/MessageItemMenu/__tests__/__snapshots__/MessageItemMenu.spec.js.snap
src/ui/MessageItemReactionMenu/__tests__/__snapshots__/MessageItemReactionMenu.spec.js.snap
src/ui/OpenchannelFileMessage/__tests__/__snapshots__/OpenchannelFileMessage.spec.js.snap
src/ui/OpenchannelOGMessage/__tests__/__snapshots__/OpenchannelOGMessage.spec.js.snap
src/ui/OpenchannelThumbnailMessage/__tests__/__snapshots__/OpenchannelThumbnailMessage.spec.js.snap
src/ui/OpenchannelUserMessage/__tests__/__snapshots__/OpenchannelUserMessage.spec.js.snap
src/ui/Word/__tests__/__snapshots__/Word.spec.js.snap

[UIKIT-2221](https://sendbird.atlassian.net/browse/UIKIT-2221)
* Rollback to the class component with MenuItems

fix: Modify the popup location of ContextMenu/MenuItems

---

scripts/index_d_ts
src/index.d.ts
src/lib/SendbirdState.tsx
src/lib/types.ts
src/smart-components/Channel/context/ChannelProvider.tsx

Apply the `isReactionEnabled` props from the SendbirdProvider to Channel component
* Add `isReactionEnabled` props into the SendBirdStateConfig (internal interface)
* Keep sync the properties of the interface ChannelContextProps

fix: Apply isReactionEnabled from SendbirdProvider to Channel

---

src/ui/Word/index.scss

Change the display property of Word component to 'inline-flex'

fix: Modify the display property of Word component

---

scripts/index_d_ts

Incorrect casing causing builds to fail on unix machines which is case sensitive for imports
and we'll evaluate if we can setup a [CLA](https://en.wikipedia.org/wiki/Contributor_License_Agreement) to allow for the contribution.
[<TICKET_ID>](https://sendbird.atlassian.net/browse/<TICKET_ID>)

fix: import `o`penChannel casing in type defn

---

scripts/index_d_ts

Use imported versions of GroupChannelListQueryParams and ApplicationUserListQueryParams

fix: use queries from @sendbird/chat

---

src/ui/Button/index.tsx
src/ui/Button/types.ts
src/ui/Button/utils.ts

Before:
Button imports utils
utils import Button
~~

fix: circular dependency in ButtonTypes

---

src/lib/Sendbird.jsx
src/lib/hooks/useOnlineStatus.js

ConnectionHandler seems to invalidate sessionHandler

fix: do not use connectionHandler when there is sessionHandler

---

src/ui/MessageInput/index.scss
src/ui/UserProfile/index.scss

[QM-1846](https://sendbird.atlassian.net/browse/QM-1846)
[QM-1848](https://sendbird.atlassian.net/browse/QM-1848)
* Apply scroll to the message input
* Apply font theme color to the ellipsis string of UserProfile

fix: Apply scroll to input and dark theme color to UserProfile

---

src/smart-components/CreateChannel/components/InviteUsers/index.tsx

[QM-1839](https://sendbird.atlassian.net/browse/QM-1839)
* Disable the create channel button when there is no user invite

fix: disable the create channel button when no user invite

---

src/smart-components/App/index.scss
src/ui/MessageSearchFileItem/__tests__/__snapshots__/MessageSearchFileItem.spec.js.snap
src/ui/MessageSearchFileItem/index.scss
src/ui/MessageSearchFileItem/index.tsx
src/ui/MessageSearchItem/index.scss

[QM-1837](https://sendbird.atlassian.net/browse/QM-1837)
[QM-1838](https://sendbird.atlassian.net/browse/QM-1838)
* Fix the text-overflow issue on the
* Sender nickname
* File name

fix: Modify text-overflow issue on the search pannel

---

src/ui/Word/index.scss

[QM-1840](https://sendbird.atlassian.net/browse/QM-1840)

fix: remove flex from Word to fix word-break issue

---

.eslintrc.json
exports.js
scripts/index_d_ts
src/index.d.ts
src/smart-components/Channel/context/utils.js
src/ui/MessageStatus/__tests__/MessageStatus.spec.js
src/ui/MessageStatus/index.tsx
src/utils/exports/__tests__/exportingUtils.spec.ts
src/utils/exports/getOutgoingMessageState.ts
src/utils/index.ts

[UIKIT-2159](https://sendbird.atlassian.net/browse/UIKIT-2159)
* Export the `getOutgoingMessageState` utils function
* Remove `getOutgoingMessageStates`
* Add tests for it

feat: Export getOutgoingMessageState util function

---

CHANGELOG.md
package-lock.json
package.json

[SDKRLSD-516](https://sendbird.atlassian.net/browse/SDKRLSD-516)
[v3.2.2] (Oct 13 2022)
Feature:
* Export a type `OutgoingMessageStates`
* Type: `enum OutgoingMessageStates { NONE, PENDING, SENT, FAILED, DELIVERED, READ }`
* Export a util function `getOutgoingMessageState`
* Importing path: "@sendbird/uikit-react/utils/message/getOutgoingMessageState"
* Interface: `function getOutgoingMessageState(channel, message): OutgoingMessageStates`
* Add a prop `disableMarkAsDelivered` into the <App /> and <SendbirdProvider />
Some of our customers do not use the markAsDelivery feature,
but we always have called the markAsDelivered on the ChannelList with every channel
It caused a rate-limit issue, so we add a new prop to disable the markAdDelivered call for that case
What types of changes does …

release: v3.2.2

---

CHANGELOG.md
package-lock.json
package.json

[SDKRLSD-523](https://sendbird.atlassian.net/browse/SDKRLSD-523)
```
Feature:
* Add a prop `disableMarkAsRead` into the <Channel />
This prop disables calling markAsRead in the Channel component
```

release: v3.2.3

---

scripts/index_d_ts
src/smart-components/ChannelList/components/ChannelListUI/index.tsx
src/smart-components/ChannelList/components/ChannelPreview/channel-preview.scss
src/smart-components/ChannelList/components/ChannelPreview/index.tsx
src/ui/Label/stringSet.js
src/ui/Modal/index.scss
src/ui/Modal/index.tsx

* Apply long press on ChannelPreview
* Apply isCloseOnClickOutside?: boolean prop to Modal
part of https://sendbird.atlassian.net/browse/UIKIT-2191

feat: long press support for channel preview

---

scripts/index_d_ts
src/smart-components/App/stories/mobile.stories.js
src/smart-components/Channel/components/ChannelHeader/channel-header.scss
src/smart-components/Channel/components/ChannelHeader/index.tsx
src/smart-components/Channel/context/ChannelProvider.tsx
src/smart-components/Channel/index.tsx
src/smart-components/ChannelSettings/components/ChannelProfile/channel-profile.scss
src/smart-components/ChannelSettings/components/ChannelSettingsUI/channel-settings-ui.scss
src/smart-components/ChannelSettings/components/EditDetailsModal/index.tsx
src/smart-components/ChannelSettings/components/LeaveChannel/index.tsx
src/smart-components/ChannelSettings/components/LeaveChannel/leave-channel.scss
src/smart-components/ChannelSettings/components/ModerationPanel/AddOperatorsModal.tsx
src/smart-components/ChannelSettings/components/ModerationPanel/BannedUsersModal.tsx
src/smart-components/ChannelSettings/components/ModerationPanel/InviteUsersModal.tsx
src/smart-components/ChannelSettings/components/ModerationPanel/MembersModal.tsx
src/smart-components/ChannelSettings/components/ModerationPanel/MutedMembersModal.tsx
src/smart-components/ChannelSettings/components/ModerationPanel/OperatorsModal.tsx
src/smart-components/ChannelSettings/components/ModerationPanel/admin-panel.scss
src/smart-components/ChannelSettings/components/UserListItem/user-list-item.scss
src/smart-components/ChannelSettings/context/ChannelSettingsProvider.tsx
src/smart-components/ChannelSettings/index.tsx

Features:
* Add back button to Channel
* Add onBackClick callback
* Add onLeaveChannel to ChannelList
* Convert all GroupChannel popups into FullScreeen

feat: Optimize Channel and ChannelSettings

---

src/smart-components/Channel/components/FileViewer/file-viewer.scss
src/ui/FileMessageItemBody/index.tsx
src/ui/MessageContent/index.scss
src/ui/OGMessageItemBody/index.scss
src/ui/ThumbnailMessageItemBody/index.scss
src/ui/ThumbnailMessageItemBody/index.tsx

feat: Fit messages and file viewer on mobile view

---

scripts/index_d_ts
src/lib/MediaQueryContext.tsx
src/smart-components/App/AppLayout.tsx
src/smart-components/App/DesktopLayout.tsx
src/smart-components/App/MobileLayout.tsx
src/smart-components/App/index.jsx
src/smart-components/App/mobile.scss
src/smart-components/App/stories/utils.jsx
src/smart-components/App/types.ts

* App component is now responsive
* MediaQuery accepts boolean value
Use case: Customer can detect the devices of their preference and setup mobile view
instead of only relying on width

feat: Responsive App component

---

.gitignore
src/smart-components/App/stories/index.stories.js
src/smart-components/ChannelList/components/ChannelPreview/channel-preview.scss
src/ui/ContextMenu/MenuItems.tsx
src/ui/MessageContent/index.tsx
src/ui/MobileMenu/MobileBottomSheet.tsx
src/ui/MobileMenu/MobileContextMenu.tsx
src/ui/MobileMenu/index.tsx
src/ui/MobileMenu/mobile-menu.scss
src/ui/MobileMenu/types.ts

interface BottomSheetProps {
className?: string;
children: React.ReactElement;
onBackdropClick?: () => void;
}

feat: BottomSheet style menu for Messages

---

SAMPLES.md

[UIKIT-2126](https://sendbird.atlassian.net/browse/UIKIT-2126)

chore: Add comments to notice the app attributes change

---

SAMPLES.md

[UIKIT-2126](https://sendbird.atlassian.net/browse/UIKIT-2126)

chore: Add comment to notice the app attribute change

---

src/smart-components/ChannelList/components/ChannelListUI/index.tsx
src/smart-components/ChannelList/components/utils.js

We do expect not to be the accurate height of the channel list
For example, It sometimes appears (0.99999 instead of 1)
Thanks, https://github.com/sendbird/sendbird-uikit-react/pull/322

fix: Expect not to be accurate height of channel list

---

src/smart-components/ChannelList/components/ChannelListUI/index.tsx

Before:
https://user-images.githubusercontent.com/46333979/199366276-a3ea6983-186b-4842-ae8b-7df725a34382.mp4
After:
https://user-images.githubusercontent.com/46333979/199366284-7218dace-1433-498b-bae8-c88911eb7e64.mp4

fix: Modify the placeholder condition using initialized of channel list

---

src/smart-components/OpenChannel/context/hooks/useSendMessageCallback.ts
src/ui/ContextMenu/MenuItems.tsx
src/ui/ContextMenu/index.tsx
src/ui/OpenchannelUserMessage/index.scss
src/ui/OpenchannelUserMessage/index.tsx

[UIKIT-2544](https://sendbird.atlassian.net/browse/UIKIT-2544)
* Apply pre-line into the OpenChannelUserMessage

fix: Apply pre-line into the OpenChannelUserMessage

---

scripts/index_d_ts

fix: Add props type isMentionEnabled to the App component

---

src/smart-components/ChannelList/index.jsx

[UIKIT-2819](https://sendbird.atlassian.net/browse/UIKIT-2819)
* Add buffer 5px when calculating the scroll of ChannelList
---
courtesy @angelhcp
[UIKIT-2819]: https://sendbird.atlassian.net/browse/UIKIT-2819

fix: [v2] Add buffer for Channel List scroll

---

src/ui/MessageInput/index.jsx

fixes: https://sendbird.atlassian.net/browse/UIKIT-2924

fix: edit should not be allowed when input is empty

---

src/hooks/useVoicePlayer/index.tsx
src/hooks/useVoicePlayer/useVoicePlayer.tsx
src/hooks/useVoiceRecorder/index.tsx
src/hooks/useVoiceRecorder/stories/index.stories.js
src/hooks/useVoiceRecorder/useVoiceRecorder.tsx

[UIKIT-2781](https://sendbird.atlassian.net/browse/UIKIT-2781)
* Add a voice recording logic
VoiceRecorder is composed of **VoiceRecorderProvider, useVoiceRecorderContext,** and **useVoiceRecorder**.
* **VoiceRecorderProvider** is a context provider component that has `start` and `stop` methods. You can start and stop voice recording using these methods. Also, there are events: `onRecordingStarted` and `onRecordingEnded`. You can set the event handler when you call the method `start` through the parameter.
* **useVoiceRecorderContext** is a context consumer hook function that provides the context from `VoiceRecorderProvider`. It has `start` and `stop` methods.
* **useVoiceRecorder** is a function that you need to use in each module. It provides more context than `VoiceRecorderProvider` …

feature: Voice Recorder&Player

---

src/lib/Sendbird.jsx

Dont need to use `useEffect` separately to initialize use state
fixes: https://sendbird.atlassian.net/browse/UIKIT-2825

fix: pubsub should be initialized with useState

---

SAMPLES.md

Converted onBeforeCreateChannel example from V3 to V4
- [ x] Documentation (correction or otherwise)

doc: update onBeforeCreateChannel example to V4

---

CHANGELOG.md

doc: add v3.5.0-beta.0 change-log

---

CHANGELOG.md
package-lock.json
package.json

Fixes:
* pubsub should be initialized with useState
* update onBeforeCreateChannel example to use chat V4
fixes: https://sendbird.atlassian.net/browse/SDKRLSD-672

[v3.3.6] (Feb 13 2023)

---

src/smart-components/ChannelSettings/components/ModerationPanel/InviteUsersModal.tsx
src/ui/Checkbox/index.scss

[UIKIT-2792](https://sendbird.atlassian.net/browse/UIKIT-2792)
* Disable the checkbox of the joined user on the InviteUsersModal
[UIKIT-2792]: https://sendbird.atlassian.net/browse/UIKIT-2792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Disable the checkbox of the joined user on the InviteUsersModal

---

src/smart-components/App/stories/integrated.stories.js
src/smart-components/Channel/components/ChannelUI/channel-ui.scss
src/smart-components/OpenChannel/components/OpenChannelInput/index.tsx
src/smart-components/Thread/components/ThreadUI/index.tsx
src/smart-components/Thread/context/hooks/useGetThreadList.ts
src/ui/MessageSearchFileItem/index.scss
src/ui/MessageSearchFileItem/index.tsx
src/ui/QuoteMessage/index.tsx
src/ui/VoiceMessageInput/controlerIcons.tsx
src/ui/VoiceMessageInput/index.tsx
src/ui/VoiceMessageItemBody/index.tsx

[UIKIT-3262](https://sendbird.atlassian.net/browse/UIKIT-3262)
* Integrated sample
* Ignore Korean string set
* Allow profile edit
* Disappear VoiceMessageInput in open channel
* Place MessageInput at the bottom of the Thread component
* Apply message highlight by message search for voice message
* Disappear file icon on the message search items if it's a voice message
*  Change the useEffect dependency of VoiceMessageItemBody from message.reactions to message.reactions.length for changing border-radius when reactions length is changed
* Change the useEffect dependency of useGetThreadList from parentMessage to parentMessage.messageId because it caused the refresh of the thread list when the parent message is updated
Put an …

fix: Voice message UI issues

---

src/hooks/VoiceRecorder/index.tsx

* Get stream when requesting record start to disappear the red record icon on the browser tap that always appears

fix: Ask for stream only when recording

---

src/smart-components/Channel/components/MessageInput/index.tsx
src/smart-components/Channel/components/MessageInput/message-input.scss
src/smart-components/Thread/components/ThreadMessageInput/index.scss
src/smart-components/Thread/components/ThreadMessageInput/index.tsx

[QM-2600](https://sendbird.atlassian.net/browse/QM-2600)
Add a border to VoiceMessageInput in channel and thread
[QM-2600]: https://sendbird.atlassian.net/browse/QM-2600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Add a border to VoiceMessageInput in channel and thread

---

src/hooks/VoicePlayer/useVoicePlayer.tsx
src/hooks/VoiceRecorder/index.tsx

[QM-2598](https://sendbird.atlassian.net/browse/QM-2598)
* Do not play voice message when VoiceRecorder is recording
[QM-2598]: https://sendbird.atlassian.net/browse/QM-2598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Do not play voice message when VoiceRecorder is recording

---

src/ui/VoiceMessageInput/index.tsx

[UIKIT-3327](https://sendbird.atlassian.net/browse/UIKIT-3327)
Compare minRecordTime and currentValue only when recording audio to disable submit button on the VoiceMessageInput component.
[UIKIT-3327]: https://sendbird.atlassian.net/browse/UIKIT-3327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Disabling voice message input submit button

---

src/smart-components/Channel/components/Message/index.tsx

To remove memory leak warnings~
fixes: https://sendbird.atlassian.net/browse/UIKIT-3320

fix: clear timeout in useLayoutEffect

---

CHANGELOG.md
package-lock.json
package.json

[SDKRLSD-714](https://sendbird.atlassian.net/browse/SDKRLSD-714)
[v3.4.1] (Mar 10 2023)
Fixes:
* Keep scroll if context menu is opened when receiving messages
* Handle Ephemeral channel
* Group channel list
* Remove the message receipt status (channel preview)
* Remove the unread message count (channel preview)
* Group channel
* Remove the message edit
* Remove the message delete
* Remove the message reactions
* Remove the message receipt status (message)
* Remove the message reply (quote_reply, thread)
* Group channel settings
* Remove the search in channel
* Open channel
* Remove the message edit
* Remove the message delete
* Clear timeout in useLayoutEffect of Message
* This removes memory leak warnings
[SDKRLSD-714]: https://sendbird.atlassian.net/browse/SDKRLSD-714?atlOrigin=eyJpIjoiN …

Release: 3.4.1

---

scripts/index_d_ts
src/smart-components/Channel/components/MessageInput/index.tsx
src/smart-components/Thread/components/ThreadMessageInput/index.tsx

fixes: https://sendbird.atlassian.net/browse/UIKIT-3422

feat: add prop to disable Channel & Thread inputs

---

src/smart-components/Thread/components/ThreadUI/index.scss
src/ui/Modal/index.scss

fixes: https://sendbird.atlassian.net/browse/UIKIT-3429

fix: replace outdated CSS rules

---

src/lib/Sendbird.jsx
src/lib/VoiceMessageProvider.tsx

[UIKIT-3260](https://sendbird.atlassian.net/browse/UIKIT-3260)
* Merge VoiceRecorderProvider and VoicePlayerProvider to VoiceMessageProvider
[UIKIT-3260]: https://sendbird.atlassian.net/browse/UIKIT-3260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: Merge Voice recorder and player providers to VoiceMessageProvider

---

src/smart-components/Channel/components/MessageInput/VoiceMessageInputWrapper.tsx

related to https://github.com/sendbird/sendbird-uikit-react/pull/455

fix: Pause playing audio before sending voice messages

---

.github/pull_request_template.md
package.json
rollup.config.js
scripts/package.template.json
scripts/post_build.js
scripts/steps.md

* Update readme
* Auto add version number to dist/index.d.ts
* Generate package.json in dist automatically
* Cleanup PR template
fixes: https://sendbird.atlassian.net/browse/UIKIT-3471

feat: improve release steps

---

CHANGELOG.md
bundle-analysis.json
exports.js
package-lock.json
package.json

```
[v3.4.4] (Mar 31 2023)
Features:
* Increase default maximum recording time of Voice Message to 10 minutes
* Add logger to VoicePlayer, VoiceRecorder, and useSendVoiceMessage hook
Fixes:
* Prevent whole page from scrolling when OpenChannel scrolls
This issue occurs when customer implements an OpenChannel in a web page with scroll
* Fix edgecase in which voice messages were sent twice
* Clean up Thread interface
If message.parentMessage doesnt exist, treat message as parentMessage
`<Thread message={message} />`
```

release: [v3.4.4] (Mar 31 2023)

---

.github/workflows/pr-comment-bot.yml
scripts/steps.md

and we'll evaluate if we can setup a [CLA](https://en.wikipedia.org/wiki/Contributor_License_Agreement) to allow for the contribution.
- Added comment bot workflow 
*Should add the bot's `CIRCLECI_API_TOKEN` to the secret. If you give me permission, I'll add it.

ci/cd: added pr-comment-bot.yml

---

.storybook/main.js
scripts/index_d_ts
src/smart-components/Channel/components/MessageList/index.tsx
src/smart-components/Channel/context/ChannelProvider.tsx
src/smart-components/Channel/index.tsx
src/smart-components/Channel/stories/index.stories.tsx

Add `Channel.filterMessageList?: (messages: BaseMessage): boolean;`, a UI level filter prop 
to Channel. This function will be used to filter messages in `<MessageList />`
example:
```
// set your channel URL
const channel = "";
export const ChannelWithFilter = () => {
const channelFilter = useCallback((message) => {
const now = Date.now();
const twoWeeksAgo = now - 1000 * 60 * 60 * 24 * 14;
return message.createdAt > twoWeeksAgo;
}, []);
return (
<Channel
channelUrl={channel}
filterMessageList={channelFilter}
/>
);
};
```
fixes: https://sendbird.atlassian.net/browse/UIKIT-3419

feat: add UI level filter for channel

---

src/hooks/VoiceRecorder/index.tsx

* Use dynamic import to lazy load the audio processor only when using the voice message feature
[UIKIT-3590](https://sendbird.atlassian.net/browse/UIKIT-3590)
[UIKIT-3590]: https://sendbird.atlassian.net/browse/UIKIT-3590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Use dynamic import for VoiceRecorder

---

rollup.config.js
src/smart-components/EditUserProfile/components/EditUserProfileUI/index.tsx

ts-pattern should be bundled inline, not as an external dep.
Also: Fix USER_ACTIONS import

hot-fix: ts-pattern bundle-inline

---

exports.js
scripts/index_d_ts
src/smart-components/ChannelSettings/components/ModerationPanel/index.tsx
src/ui/Toggle/ToggleContainer.tsx
src/ui/Toggle/ToggleContext.ts
src/ui/Toggle/ToggleUI.tsx
src/ui/Toggle/__tests__/Toggle.spec.js
src/ui/Toggle/__tests__/__snapshots__/Toggle.spec.js.snap
src/ui/Toggle/index.scss
src/ui/Toggle/index.tsx
src/ui/Toggle/stories/Toggle.stories.js
src/ui/Toggle/utils.ts

Dev Docs: https://sendbird.atlassian.net/wiki/spaces/UK/pages/2061664531/Toggle+component
path
```javascript
import { Toggle, ToggleContainer, ToggleUI,  useToggleContext } from '@sendbird/ui/Toggle';
```
Provide
* ToggleContainer: A context provider component that has only logic of managing the toggle status
* ToggleUI: An UI component that doesn't include managing logic
* Toggle: A combination of ToggleContainer and ToggleUI components
* useToggleContext: A custom `useContext` hook that you can get the context from ToggleContainer
[UIKIT-3631](https://sendbird.atlassian.net/browse/UIKIT-3631)
[UIKIT-3631]: https://sendbird.atlassian.net/browse/UIKIT-3631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature: Create new UI component Toggle

---

scripts/index_d_ts
src/lib/SendbirdState.tsx

* Modify the methods of Logger: from optional to demand

chore: Modify Logger type definition

---

src/hooks/useHandleOnScrollCallback/index.ts
src/modules/Channel/components/MessageList/index.tsx

Resolves [UIKIT-3790](https://sendbird.atlassian.net/browse/UIKIT-3790)
scrollRef.current could be null so added a safe guard for it. 
[UIKIT-3790]: https://sendbird.atlassian.net/browse/UIKIT-3790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: handle scrollRef.current == null case

---

src/utils/__tests__/utils.spec.js
src/utils/index.ts

https://github.com/sendbird/sendbird-uikit-react/pull/509 related. 
Reported by @sravan-s directly ;)

hotfix: isURL can't catch & included URL

---

CHANGELOG.md
bundle-analysis.json
package.json

Features: 
* Set Chat SDK v4.3.0 as the minimum required version.
* Add a new UI component, Toggle:
* `ToggleContainer`: A context provider component that manages only the toggle status.
* `ToggleUI`: A UI component that does not include the status managing logic.
* `Toggle`: A combination of ToggleContainer and ToggleUI components.
* `useToggleContext`: A custom useContext hook that provides context from ToggleContainer.
```javascript
import { Toggle, ToggleContainer, ToggleUI,  useToggleContext } from '@sendbird/ui/Toggle';
```
Fixes:
* Apply `isMuted` to the participant list. Operators can now unmute the muted participants from the participant list.
* Update the max mention count notice message.
* Modify the URL Regex to filter various types of formats.
* Give a left margin to the link …

Prepare release 3.4.7

---

scripts/index_d_ts
src/hooks/VoicePlayer/dux/initialState.ts
src/hooks/VoicePlayer/dux/reducer.ts
src/hooks/VoicePlayer/useVoicePlayer.tsx
src/modules/Channel/components/MessageInput/VoiceMessageInputWrapper.tsx
src/ui/VoiceMessageItemBody/index.tsx

* Rename VoicePlayerStatus for separating instance and type
* Use ModuleNameSpaces for type defining of Sdk instance

chore: Rename VoicePlayerStatus for separating object and type

---

README.md

* Add info about how to generate reducers
* Clarify generating - new components section

chore: Add info about plop on README

---

README.md

If husky is not activated using  `yarn husky install`, it wont register :(

doc: Add info on how to enable Husky

---

src/modules/App/stories/integrated-app.scss
src/modules/App/stories/integrated.stories.js

Fixes: https://sendbird.atlassian.net/browse/UIKIT-3857

feat: Mobile support for storybook login page

---

src/modules/App/stories/integrated.stories.js

Add a simple polyfill for localstorage that is used in storybook
to avoid errors in safari no-cookie mode and forefox incognito
`SecurityError: The operation is insecure` -> in safari
Fixes: https://sendbird.atlassian.net/browse/UIKIT-3933

fix: Add polyfill to localstorage in storybook

---

src/utils/__tests__/snakeToCamel.spec.ts
src/utils/snakeToCamel.ts

Applies https://sendbird.atlassian.net/browse/UIKIT-3974
The format of the UIKitConfiguration payload will consist of snake_case like [this](https://sendbird.atlassian.net/wiki/spaces/SDK/pages/2060618878/UIKit+Feature+configuration+RFC#JSON-Payload). So I made a utility function to convert it into camelCase, which is more natural in our application."

feat: add snakeToCamel util function

---

src/ui/MessageContent/index.tsx
src/ui/ReactionButton/index.tsx
src/ui/ThumbnailMessageItemBody/index.tsx

* Prevent opening the FileViewer by the reaction onClick event
[UIKIT-3977](https://sendbird.atlassian.net/browse/UIKIT-3977)
[UIKIT-3977]: https://sendbird.atlassian.net/browse/UIKIT-3977?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Prevent opening thumbnail by reaction click

---

src/ui/MobileMenu/MobileBottomSheet.tsx
src/ui/MobileMenu/MobileContextMenu.tsx
src/utils/__tests__/isParentMessage.spec.ts
src/utils/__tests__/isThreadMessage.spec.ts
src/utils/index.ts

* Modify string set for thread menu
* "Reply to Thread" -> "Reply in Thread"
* Do not display "Reply in Thread" to the reply messages
[UIKIT-3898](https://sendbird.atlassian.net/browse/UIKIT-3898)
[UIKIT-3916](https://sendbird.atlassian.net/browse/UIKIT-3916)
[UIKIT-3898]: https://sendbird.atlassian.net/browse/UIKIT-3898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UIKIT-3916]: https://sendbird.atlassian.net/browse/UIKIT-3916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Modify string set for thread menu

---

src/modules/App/MobileLayout.tsx
src/modules/App/types.ts
src/modules/Channel/components/Message/index.tsx
src/modules/Channel/context/ChannelProvider.tsx
src/modules/Channel/context/hooks/useInitialMessagesFetch.js
src/modules/Channel/context/hooks/useScrollToMessage.ts
src/modules/Channel/context/utils.js
src/modules/Thread/components/ThreadHeader/index.tsx
src/modules/Thread/components/ThreadUI/index.tsx

Fixes:
* Scroll into view when startingpoint is set~
* Navigation to message from Thread and Search ~
* Scroll into message on clicking quote reply
* Some type warnings :)
fixes:
https://sendbird.atlassian.net/browse/UIKIT-3899
https://sendbird.atlassian.net/browse/UIKIT-3966
https://sendbird.atlassian.net/browse/UIKIT-3978

fix: Scroll to given message

---

src/ui/OpenchannelOGMessage/index.tsx

Move applying onLongPress events to the top level element
[UIKIT-4001](https://sendbird.atlassian.net/browse/UIKIT-4001)
[UIKIT-4001]: https://sendbird.atlassian.net/browse/UIKIT-4001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Display menu for open channel OG message

---

src/modules/CreateChannel/components/InviteUsers/index.tsx

Scroll was not working in invite user on Chrome because of 
padding at bottom of modal
Also added a type warning error on setUsers
Fixes: https://sendbird.atlassian.net/browse/UIKIT-3866

fix: Mobile Scroll more invite user

---

.eslintignore
src/modules/Channel/components/Message/index.tsx
src/modules/Channel/components/MessageInput/index.tsx
src/modules/Message/context/MessageProvider.tsx
src/modules/Message/hooks/__tests__/__snapshots__/useDirtyGetMentions.spec.tsx.snap
src/modules/Message/hooks/__tests__/useDirtyGetMentions.spec.tsx
src/modules/Message/hooks/useDirtyGetMentions.ts
src/modules/Message/utils/getMentionNodes.ts
src/modules/Thread/components/ParentMessageInfo/index.tsx
src/modules/Thread/components/ThreadList/ThreadListItem.tsx
src/modules/Thread/components/ThreadMessageInput/index.tsx

Array of Users is de-duplicated, so max-mention count wouldnt work,
So, use DOM mutations to reliabily count correct no.of mentioned users
Bonus:
Improve MessageProvider type defn
Fixes: https://sendbird.atlassian.net/browse/UIKIT-3982

fix: Improve max mention count logic 

---

src/modules/App/stories/index.stories.js
src/modules/App/stories/integrated-app.scss

Fixes: https://sendbird.atlassian.net/browse/UIKIT-3960

feat: Improve welcome page of storybook

---

src/ui/MobileMenu/MobileBottomSheet.tsx

* Set label color when using Label component
before
after
[UIKIT-3896](https://sendbird.atlassian.net/browse/UIKIT-3896)
[UIKIT-3896]: https://sendbird.atlassian.net/browse/UIKIT-3896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Apply theme to MobileBottomSheet

---

src/ui/MessageContent/index.scss

* display message status on mobile
[UIKIT-3907](https://sendbird.atlassian.net/browse/UIKIT-3907)
[UIKIT-3907]: https://sendbird.atlassian.net/browse/UIKIT-3907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: display message status on mobile

---

src/lib/Sendbird.tsx

Provider markAsDeliveredScheduler from the config of SendbirdProvider
fix

fix: Provide markAsDeliveredScheduler from SendbirdProvider

---

src/modules/Channel/components/MessageInput/index.tsx
src/modules/Thread/components/ThreadMessageInput/index.tsx

[UIKIT-3902](https://sendbird.atlassian.net/browse/UIKIT-3902)
[UIKIT-3902]: https://sendbird.atlassian.net/browse/UIKIT-3902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Disable mention in the broadcast channel

---

src/ui/MobileMenu/MobileContextMenu.tsx

* Do not display the download option for super and broadcast channels
[UIKIT-3904](https://sendbird.atlassian.net/browse/UIKIT-3904)
[UIKIT-3904]: https://sendbird.atlassian.net/browse/UIKIT-3904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Donot show download option in super and broadcast channels

---

CHANGELOG.md
package.json

* Display a channel on channel list only when there's a message
* Remove edited message from ChannelPreview
* Batch markAsRead & markAsDelivered requests
* Various scroll issues in Channel component
* Shaky scroll on messages when fetching messages
* Scroll into view when starting point is set
* Scroll into message on clicking quote reply
* Inconsistent rendering on scrollToBottom button
* Improve max mention count logic in Messages
* Improve mention detection when there are curly braces in user's name
Mentions were not working when user nickname had curly braces
* Disable mention in the broadcast channel
* Change OpenChannelInput muted state notice text in broadcast channel
* Apply ellipsis to a sender of quote and admin message
* Add border bottom to the ParentMessageInfo component
* …

release: [v3.4.9] (June 02 2023)

---

samples/typescript_sample/src/App.tsx

SendbirdProvider should have only one child
Thanks @msell
Fixes: https://github.com/sendbird/sendbird-uikit-react/pull/540

hotfix: TSC error in typescript sample

---

src/utils/__tests__/isParentMessage.spec.ts
src/utils/index.ts

[UIKIT-4028](https://sendbird.atlassian.net/browse/UIKIT-4028)
[UIKIT-4028]: https://sendbird.atlassian.net/browse/UIKIT-4028?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: clarify the meaning of isParentMessage

---

src/ui/MobileMenu/MobileContextMenu.tsx

* Hide download option for only voice message
* Appear download option for the other file messages
[UIKIT-4079](https://sendbird.atlassian.net/browse/UIKIT-4079)
[UIKIT-4079]: https://sendbird.atlassian.net/browse/UIKIT-4079

fix: Hide download option for only voice message

---

src/modules/Thread/components/ThreadList/ThreadListItemContent.scss
src/ui/ThumbnailMessageItemBody/index.scss

* fix: Emoji reactions overflow in the thread
[UIKIT-3917](https://sendbird.atlassian.net/browse/UIKIT-3917)
[UIKIT-3917]: https://sendbird.atlassian.net/browse/UIKIT-3917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Emoji reactions overflow in thread

---

src/lib/Sendbird.tsx
src/lib/UIKitConfigProvider/index.tsx
src/lib/UIKitConfigProvider/types.ts
src/lib/types.ts
src/modules/OpenChannel/components/OpenChannelMessage/index.tsx
src/modules/Thread/components/ThreadList/ThreadListItemContent.tsx
src/ui/MessageContent/__tests__/MessageContent.spec.js
src/ui/MessageContent/index.tsx
src/utils/index.ts

Resolves part of https://sendbird.atlassian.net/browse/UIKIT-4085
I applied these two configs to proper places for each.

feat: Apply enableOgtag config set from Dashboard

---

src/modules/ChannelSettings/components/ModerationPanel/MembersModal.tsx

fixes: https://sendbird.atlassian.net/browse/UIKIT-4037

fix: Show context menu on click

---

src/modules/Channel/components/MessageInput/VoiceMessageInputWrapper.tsx

Fixes: https://sendbird.atlassian.net/browse/UIKIT-3901

fix: Stop voice player when recorder exits

---

src/hooks/VoiceRecorder/index.tsx
src/ui/Label/stringSet.js

Fixes: https://sendbird.atlassian.net/browse/UIKIT-3925

feat: Show warning when there is no voice permission

---

src/lib/Sendbird.tsx
src/lib/types.ts
src/modules/Channel/components/ChannelUI/index.tsx

https://sendbird.atlassian.net/browse/UIKIT-4085
Address enable_typing_indicator configs to ChannelUI component.

feat: apply groupChannel.enableTypingIndicator config flag

---

src/ui/OGMessageItemBody/index.scss

OG messages were not elastic, this caused issues when user added
reactions
Fixes: https://sendbird.atlassian.net/browse/UIKIT-4047

fix: OGMessage width while adding reaction

---

src/modules/OpenChannelList/components/OpenChannelPreview/index.scss

fixes: https://sendbird.atlassian.net/browse/QM-2107

fix: vertical scroll on labels in open channel list

---

src/modules/App/stories/index.stories.js
src/ui/QuoteMessage/index.scss

Setup alignment for quoted message
Also remove padding to make it look nicer
Fixes: https://sendbird.atlassian.net/browse/UIKIT-4130

fix: Quoted text alignment for reply outgoing message 

---

src/modules/Channel/components/MessageList/hooks/__test__/useSetScrollToBottom.spec.tsx
src/modules/Channel/components/MessageList/hooks/useSetScrollToBottom.ts
src/modules/Channel/components/MessageList/index.tsx

Clear `scrollBottom` on channel state loading
Fixes: https://sendbird.atlassian.net/browse/UIKIT-4137

fix: Clear scrollToMessage on loading

---

samples/router/README.md
samples/router/package-lock.json
samples/router/package.json
samples/router/src/App.css
samples/router/src/App.tsx
samples/router/src/DesktopLayout/Channel.tsx
samples/router/src/DesktopLayout/ChannelList.tsx
samples/router/src/DesktopLayout/ChannelSettings.tsx
samples/router/src/DesktopLayout/MessageSearch.tsx
samples/router/src/DesktopLayout/Router.tsx
samples/router/src/Error.tsx
samples/router/src/MobileLayout/Channel.tsx
samples/router/src/MobileLayout/ChannelList.tsx
samples/router/src/MobileLayout/ChannelSettings.tsx
samples/router/src/MobileLayout/MessageSearch.tsx
samples/router/src/MobileLayout/Router.tsx
samples/router/src/hooks/useNavigateOnBan.ts
samples/router/src/index.css
samples/router/src/main.tsx
samples/router/tsconfig.json

fixes: https://sendbird.atlassian.net/browse/QM-2172

chore: Add sample to reroute when customer is banned

---

src/lib/hooks/useOnlineStatus.js

fixes: https://sendbird.atlassian.net/browse/UIKIT-4179,
https://sendbird.atlassian.net/browse/SBISSUE-12733

fix: Set offline class on body when disconnected

---

CHANGELOG.md
bundle-analysis.json
package.json

```
[v3.5.2] (June 23 2023)
Fixes:
* Allow to reduce the mobile app height
It was not able to reduce the height of the mobile app with some wrapper component
* Do not display the UnreadCount(new message notification) comp when unreadSince is null
* Improve sampling and bitrate of Voice Recording
* sampling rate: 11025
* bit rate: 12000
* Move scroll every time when message height changes
It moved scroll only when the last message height changes
```
[SDKRLSD-882](https://sendbird.atlassian.net/browse/SDKRLSD-882)
[SDKRLSD-882]: https://sendbird.atlassian.net/browse/SDKRLSD-882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

release v3.5.2

---

.github/pull_request_template.md

Improve PR template to clarify more about conventional commits
Fixes: https://sendbird.atlassian.net/browse/UIKIT-4143

doc: Improve IC guide in PR Template

---

SAMPLES.md

https://sendbird.atlassian.net/browse/UIKIT-4198 to address https://github.com/sendbird/sendbird-uikit-react/pull/650#issuecomment-1598275220 by @sravan-s 
You can see the sample implementation in https://codesandbox.io/s/uikit-configuration-xgh3rw. I wrote some disclaimer too.

docs: add UIKit Configuration sample guide

---

CHANGELOG.md
SAMPLES.md
bundle-analysis.json
package.json

https://sendbird.atlassian.net/browse/SDKRLSD-886
* Official support for Feature Configuration
- You can now configure the features of UIKit through the `uikitOptions` prop of `<SendbirdProvider />` or `<App />` component. You can also find the detailed sample usage from [SAMPLE.md#UIKit-Configuration-Samples](./SAMPLES.md#UIKit-Configuration-Samples)
- The minimum `@sendbird/chat` version has been increased to 4.9.2.
```jsx
<SendbirdUIKitContainer
uikitOptions={{
common: {
enableUsingDefaultUserProfile: true,
},
groupChannel: {
enableMention: false,
enableOgtag: true,
enableReaction: true,
enableTypingIndicator: true,
input: {
camera: {
enablePhoto: true,
enableVideo: true,
},
gallery: {
enablePhoto: true,
enableVideo: true,
},
enableDocument: true,
},
},
groupChannelList: { …
```

release: v3.6.0 - official feature config support

---

SAMPLES.md

- Update all sample code to V4
- Convert CodeSandbox to StackBlitz
- Render all examples with Vite

doc: update all examples to V4 + StackBlitz

---

src/modules/CreateChannel/components/InviteUsers/index.tsx

Addresses https://sendbird.atlassian.net/browse/CLNP-251
Enabled the channel creation button if there's only the logged in user && users.length === 0.

feat: enable channel creation for logged-in user only

---

CHANGELOG.md
package.json

* Enable channel creation when no user present to select
* Mobile: Keep keyboard open after sending the message
* Update @sendbird/uikit-tools to 0.0.1-alpha.39
alpha.39 has CJS support, otherwise, UIKit wont work
on next-js page router
* Update all examples to V4 + StackBlitz
* Update all sample code to V4
* Convert CodeSandbox to StackBlitz
* Render all examples with Vite
* Thanks @tylerhammer

release: [v3.6.1] (June 30 2023)

---

src/ui/EmojiReactions/ReactionItem.tsx
src/ui/EmojiReactions/index.tsx

[CLNP-230](https://sendbird.atlassian.net/browse/CLNP-230)
[CLNP-230]: https://sendbird.atlassian.net/browse/CLNP-230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: hide tooltip in the super group channel

---

scripts/index_d_ts

Fixes: https://sendbird.atlassian.net/browse/CLNP-305

fix: Add UIKitConfigTypes to type defn

---

scripts/index_d_ts

Just added a missing type added by #676 to d ts file.

fix: add missing scrollBehavior to type defn

---

CHANGELOG.md
bundle-analysis.json
package.json

* Add new scrollBehavior prop to Channel (#676)
The default option is set to "auto," preserving the existing scroll behavior.
Possible to set smooth for smooth scroll effect.
* Move message list scroll when the last message is edited (#674)
Added optional parameters to moveScroll to scroll only when the last message reaches the bottom.
Scroll is now moved only when the updatedAt property of the last message is changed.
* Add missing `UIKitConfig` to type definition (#677)
Reported by [GitHub PR #650](https://github.com/sendbird/sendbird-uikit-react/pull/650#issuecomment-1622331367).

release: 3.6.3

---

package.json
scripts/package.template.json

Addresses https://sendbird.atlassian.net/browse/CLNP-442
Just fixed the incorrect path for common js module in pacakge.json.

fix: incorrect cjs path in package.json

---

scripts/post_build.js

Addresses https://sendbird.slack.com/archives/G01290GCDCN/p1689744629102179?thread_ts=1689719295.903759&cid=G01290GCDCN

feat: create separate package.json for cjs module on build time

---

src/index.d.ts
src/lib/Sendbird.tsx
src/lib/hooks/useConnect/__test__/data.mocks.ts
src/lib/hooks/useConnect/__test__/setupConnection.spec.ts
src/lib/hooks/useConnect/index.ts
src/lib/hooks/useConnect/setupConnection.ts
src/lib/hooks/useConnect/types.ts
src/modules/App/index.jsx

* feat: Add isUserIdUsedForNickname to the public interface
* feat: Apply isUserIdUsedForNickname into the connection logic
* feat: Set userId to nickname when isUserIdUsedForNickname is true
[UIKIT-2537](https://sendbird.atlassian.net/browse/UIKIT-2537)
[UIKIT-2537]: https://sendbird.atlassian.net/browse/UIKIT-2537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add a new props isUserIdUsedForNickname

---

package.json
src/lib/Sendbird.tsx
src/lib/hooks/useConnect/connect.ts
src/lib/hooks/useConnect/index.ts
src/lib/hooks/useConnect/setupConnection.ts
src/lib/hooks/useConnect/types.ts
yarn.lock

* feat: Add Sendbird Extensions in connection
[CLNP-197](https://sendbird.atlassian.net/browse/CLNP-197)
[CLNP-197]: https://sendbird.atlassian.net/browse/CLNP-197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add Sendbird Extensions in connection

---

CHANGELOG.md
package.json

* Add `customExtensionParams` for `sdk.addSendbirdExtensions` (#698)
The 3rd parameter customData to the `sdk.addSendbirdExtension` function, allowing it to be delivered from outside of UIKit React.
e.g.
```
customExtensionParams={{
a: 'a', // the key-value set will be passed when sdk.addSendbirdExtensions is called
}}
/>
```
* Call `sdk.addSendbirdExtensions` during the connection process (#682)
* Change the MessageInput cursor style from disabled to not-allowed; Thanks @roderickhsiao (#697)
* PendingMsg is missing isUserMessage method (#695)
This resolves the issue where spreading the message object in the reducer loses some methods like `isUserMessage` and `isFileMessage`
* fix util functions logic of verifying message type. We updated logic in util functions to …

release: 3.6.6

---

README.md

* Follow the Scaled Trunk-Based Development workflow(https://trunkbaseddevelopment.com/)
* Branch naming format -> `{type}/TICKET_ID/description`
* Where type = `feat` / `feature` / `fix` / `chore` / `doc` / `release`
* Always receive PR review approvals
* Rebase your branch with the main branch, and wait for CI to pass
* Follow the provided template for both the PR description and squashing to the main branch
* The template is very similar to conventional commits. [Read More](https://www.conventionalcommits.org/en/v1.0.0/)
Template
```
// Section: PR description (Optional)
Add a brief description of the changes that …
```

doc: Add Troubleshooting Guide to readme

---

src/modules/Channel/context/hooks/useGetChannel.js

Resolves https://sendbird.atlassian.net/browse/CLNP-542

fix: remove duplicated getEmoji API call

---

src/ui/ImageGrid/__tests__/ImageGrid.spec.js
src/ui/ImageGrid/__tests__/__snapshots__/ImageGrid.spec.js.snap
src/ui/ImageGrid/index.scss
src/ui/ImageGrid/index.tsx
src/ui/ImageGrid/stories/ImageGrid.stories.js
src/ui/ImageRenderer/__tests__/getBorderRadiusForImageRenderer.spec.ts
src/ui/ImageRenderer/index.tsx
src/utils/__tests__/numberToPx.spec.ts
src/utils/numberToPx.ts

"The cat is crying because the earth is dying 😿"

feat: Add ImageGrid ui component.

---

scripts/index_d_ts
src/modules/Thread/context/ThreadProvider.tsx
src/modules/Thread/context/hooks/useSendUserMessageCallback.ts

useChannelContext.setQuoteMessage -> Should accept `UserMessage | FileMessage `
useThreadContext.sendMessage -> Should be string
Fixes: https://sendbird.atlassian.net/browse/CLNP-673
Related: https://sendbird.atlassian.net/browse/SBISSUE-13170

fix: Types on useChannelContext & useThreadContext

---

exports.js
scripts/index_d_ts
src/modules/Channel/components/MessageList/getMessagePartsInfo.ts
src/modules/Channel/context/__test__/compareMessagesForGrouping.spec.ts
src/modules/Channel/context/compareMessagesForGrouping.ts
src/modules/Channel/context/utils.js
src/modules/Message/hooks/useDirtyGetMentions.ts
src/ui/MessageInput/hooks/usePaste/index.ts

Some customers requested these utils, looks quite useful for others also 
-> getMessagePartsInfo
-> compareMessagesForGrouping
-> MessageInput/hooks/usePaste
-> useDirtyGetMentions
Fixes: https://sendbird.atlassian.net/browse/CLNP-674

feat: Export misc. utils

---

scripts/index_d_ts
src/lib/Sendbird.tsx
src/lib/SendbirdState.tsx
src/lib/utils/uikitConfigMapper.ts
src/modules/App/index.jsx

Feature: [UIKIT-4291](https://sendbird.atlassian.net/browse/UIKIT-4291)
[UIKIT-4291]: https://sendbird.atlassian.net/browse/UIKIT-4291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add uikitMultipleFilesMessageLimit to sendbird provider

---

.eslintrc.json
package.json
src/modules/OpenChannel/context/hooks/useResendMessageCallback.ts
src/modules/Thread/components/RemoveMessageModal.tsx
src/modules/Thread/components/ThreadList/ThreadListItem.tsx
src/modules/Thread/context/dux/initialState.ts
src/modules/Thread/context/hooks/useGetChannel.ts
src/modules/Thread/context/hooks/useResendMessageCallback.ts
src/modules/Thread/context/hooks/useSendVoiceMessageCallback.ts
src/ui/MessageItemReactionMenu/index.tsx
src/ui/MobileMenu/types.ts
src/ui/OpenChannelMobileMenu/index.tsx
src/ui/QuoteMessageInput/index.tsx
src/utils/exports/getOutgoingMessageState.ts
yarn.lock

Resolves: [UIKIT-4361](https://sendbird.atlassian.net/browse/UIKIT-4361)
[UIKIT-4361]: https://sendbird.atlassian.net/browse/UIKIT-4361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: apply the unused import eslint rule

---

scripts/index_d_ts
src/lib/Sendbird.tsx
src/lib/types.ts
src/modules/App/index.jsx
src/modules/App/stories/integrated.stories.js
src/modules/Channel/components/MessageInput/index.tsx
src/modules/Channel/components/MessageInput/useHandleUploadFiles.ts
src/modules/Channel/context/ChannelProvider.tsx
src/modules/Channel/context/hooks/useSendMultipleFilesMessage.ts
src/modules/Thread/components/ThreadMessageInput/index.tsx
src/modules/Thread/context/ThreadProvider.tsx
src/modules/Thread/context/hooks/useSendFileMessage.ts
src/ui/MessageInput/index.jsx
src/utils/__tests__/utils.spec.js
src/utils/consts.ts
src/utils/index.ts

[UIKIT-4405](https://sendbird.atlassian.net/browse/UIKIT-4405)
* Create `useHandleUploadFiles` hook for handling each case of sending file&files messages
* Condition & Behavior
1. If selected only one file -> send file message
2. If selected multiple files
* If selected only images -> send MFM
* If selected several type of files -> send MFM for Images & send file message for the other files
[UIKIT-4405]: https://sendbird.atlassian.net/browse/UIKIT-4405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Attach multiple files in the MessageInput

---

scripts/index_d_ts
src/ui/MessageInput/index.jsx

made by https://github.com/sendbird/sendbird-uikit-react/pull/727#discussion_r1320971991

fix: Improve the MessageInput types

---

src/ui/MessageContent/index.tsx

[CLNP-966](https://sendbird.atlassian.net/browse/CLNP-966)
* Remove replyType === 'THREAD' because the quoted message should show the unavailable message regardless of the reply type.
* Use messageOffsetTimestamp instead of joinedAt because joinedAt can't cover the every case
[CLNP-966]: https://sendbird.atlassian.net/browse/CLNP-966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: use messageOffsetTimestamp instead of joinedAt

---

src/ui/MessageContent/index.tsx
src/ui/QuoteMessage/index.tsx
src/ui/QuoteMessage/utils.ts
src/ui/QuoteMessageInput/QuoteMessageThumbnail.tsx
src/ui/QuoteMessageInput/index.tsx
src/ui/ThumbnailMessageItemBody/index.tsx
src/utils/index.ts

feat: Support MFM quote message input

---

src/modules/Channel/components/RemoveMessageModal.tsx
src/modules/OpenChannel/components/OpenChannelMessage/RemoveMessageModal.tsx
src/modules/OpenChannel/components/OpenChannelMessage/index.tsx
src/modules/Thread/components/RemoveMessageModal.tsx
src/ui/Label/stringFormatterUtils.ts
src/ui/Modal/index.tsx

Resolves: [UIKIT-4462](https://sendbird.atlassian.net/browse/UIKIT-4462)
Figma: https://www.figma.com/file/SVbXU00FhjztekD8AiVukK/UIKit_Work-file_React?node-id=1407%3A29428&mode=dev
[UIKIT-4462]: https://sendbird.atlassian.net/browse/UIKIT-4462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Delete message prompt: MFM support.

---

src/ui/MessageSearchFileItem/index.tsx
src/ui/MessageSearchFileItem/utils.ts
src/utils/index.ts

MessageSearchFileItem MFM support.
Fixes: [UIKIT-4350](https://sendbird.atlassian.net/browse/UIKIT-4350)
[UIKIT-4350]: https://sendbird.atlassian.net/browse/UIKIT-4350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: MessageSearchFileItem MFM support

---

scripts/index_d_ts
src/lib/Sendbird.tsx
src/lib/SendbirdSdkContext.tsx
src/lib/SendbirdState.tsx
src/modules/App/DesktopLayout.tsx
src/modules/App/MobileLayout.tsx
src/modules/App/index.jsx
src/modules/App/types.ts
src/modules/Channel/context/ChannelProvider.tsx

[UIKIT-4466](https://sendbird.atlassian.net/browse/UIKIT-4466)
* Remove the uikitMultipleFilesMessageLimit from the public interface
* Add isMultipleFilesMessageEnabled props the the public interface
* add to the `App, SendbirdProvider, Channel, ChannelProvider` modules
[UIKIT-4466]: https://sendbird.atlassian.net/browse/UIKIT-4466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add isMultipleFilesMessageEnabled props

---

src/ui/MessageInput/index.jsx
src/ui/MessageInput/utils.js

Do not support MFM in super or broadcast channels.
Fixes: [CLNP-1045](https://sendbird.atlassian.net/browse/CLNP-1045)
[CLNP-1045]: https://sendbird.atlassian.net/browse/CLNP-1045?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bug-fix: Do not support MFM in super or broadcast channels.

---

src/modules/Channel/context/hooks/useResendMessageCallback.js
src/modules/Thread/context/hooks/useResendMessageCallback.ts

resendMultipleFilesMessage() support in useResendMessageCallback().
Fixes: [CLNP-1047](https://sendbird.atlassian.net/browse/CLNP-1047)
[CLNP-1047]: https://sendbird.atlassian.net/browse/CLNP-1047?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: resendMultipleFilesMessage() support in useResendMessageCallback().

---

src/hooks/useModal/index.tsx
src/lib/Sendbird.tsx
src/lib/SendbirdState.tsx
src/lib/types.ts
src/lib/utils/uikitConfigMapper.ts
src/modules/Channel/components/MessageInput/useHandleUploadFiles.tsx

* Add `uikitUploadSizeLimit` to the SendbirdProvider.config
* It is from appInfo.uploadSizeLimit
* The default value is 26 MB.

fix: apply appInfo.uploadSizeLimit to the files selection logic

---

src/ui/MessageContent/index.tsx

MFM support for useLongPress().
Fixes: [CLNP-1048](https://sendbird.atlassian.net/browse/CLNP-1048)
[CLNP-1048]: https://sendbird.atlassian.net/browse/CLNP-1048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: MFM support for useLongPress()

---

src/lib/types.ts
src/modules/App/stories/index.stories.js
src/modules/App/stories/integrated.stories.js
src/modules/Channel/components/MessageInput/index.tsx
src/modules/Thread/components/ThreadMessageInput/index.tsx

[UIKIT-4490](https://sendbird.atlassian.net/browse/UIKIT-4490)
* fix: add the type interface `isMultipleFilesMessageEnabled` to the SendbirdStateConfig
* feat: toss the props to the MessageInput components of the Channel&Thread
* chore: apply the props to the storybook samples
[UIKIT-4490]: https://sendbird.atlassian.net/browse/UIKIT-4490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Apply the props isMultipleFilesMessageEnabled

---

.eslintrc.json
scripts/index_d_ts
src/modules/Message/utils/getMentionNodes.ts
src/ui/MessageInput/index.jsx
src/utils/__tests__/getMimeTypesUIKitAccepts.spec.ts
src/utils/__tests__/utils.spec.js
src/utils/index.ts

Add mimeTypes specifier to MessageInput.
Resolves: [CLNP-1070](https://sendbird.atlassian.net/browse/CLNP-1070)
[CLNP-1070]: https://sendbird.atlassian.net/browse/CLNP-1070?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add mimeTypes specifier to MessageInput

---

src/modules/App/stories/index.stories.js
src/modules/App/stories/integrated.stories.js

Enable mobile web feature in some of the storybook samples

fix: Enable mobile web feature in some of storybook samples

---

src/utils/index.ts

* fix: add supported mime types in the message input
for the `text` and `application` mime types, and also add `.mov` to the video

fix: add supported mime types in the message input

---

src/modules/OpenChannel/context/hooks/useFileUploadCallback.ts

fix: accepting parameter type to Array<File> or File

---

src/modules/CreateChannel/components/InviteUsers/index.tsx
src/modules/CreateChannel/components/InviteUsers/invite-users.scss

[CLNP-1160](https://sendbird.atlassian.net/browse/CLNP-1160)
[CLNP-1160]: https://sendbird.atlassian.net/browse/CLNP-1160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: remove duplicated CSS line

---

scripts/index_d_ts
src/modules/Channel/components/MessageList/index.tsx
src/modules/Channel/context/ChannelProvider.tsx
src/ui/MessageInput/index.jsx

Pls merge this PR after approval

revert: the disabled features in v3.6.9

---

src/modules/Thread/context/hooks/useHandlePubsubEvents.ts

Fixes: [UIKIT-4523](https://sendbird.atlassian.net/browse/UIKIT-4523)
[UIKIT-4523]: https://sendbird.atlassian.net/browse/UIKIT-4523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bug-fix: Fixed a bug where pending mfm not displayed in thread

---

src/modules/Channel/components/RemoveMessageModal.tsx
src/modules/Channel/context/dux/reducers.js
src/ui/ContextMenu/index.scss
src/ui/MessageItemMenu/index.tsx

Fixes: [UIKIT-4520](https://sendbird.atlassian.net/browse/UIKIT-4520)
[UIKIT-4520]: https://sendbird.atlassian.net/browse/UIKIT-4520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bug-fix: Allow delete failed messages.

---

src/modules/CreateChannel/components/InviteUsers/index.tsx

[SBISSUE-13847](https://sendbird.atlassian.net/browse/SBISSUE-13847)
In the InviteUsers component, we've tried to fetch the ApplicationUserListQuery
even though the previous fetch request is not finished.
* check applicationUserListQuery.isLoading before trying to fetch the user list
[SBISSUE-13847]: https://sendbird.atlassian.net/browse/SBISSUE-13847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: check applicationUserListQuery.isLoading before fetching

---

src/modules/Channel/context/hooks/useDeleteMessageCallback.js

Fixes: [UIKIT-4520](https://sendbird.atlassian.net/browse/UIKIT-4520)
[UIKIT-4520]: https://sendbird.atlassian.net/browse/UIKIT-4520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bug-fix: Allow delete failed messages in offline state (re-fix)

---

scripts/index_d_ts
src/modules/Channel/context/ChannelProvider.tsx

Fixes: [CLNP-1248](https://sendbird.atlassian.net/browse/CLNP-1248)
[CLNP-1248]: https://sendbird.atlassian.net/browse/CLNP-1248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bug-fix: Fix missed or wrong type definition

---

src/ui/MobileMenu/MobileBottomSheet.tsx

Fixes: [UIKIT-4536](https://sendbird.atlassian.net/browse/UIKIT-4536)
[UIKIT-4536]: https://sendbird.atlassian.net/browse/UIKIT-4536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bug-fix: File save and download button in mobile should be based on connection state and sending status

---

src/modules/Channel/components/MessageInput/index.tsx

Fixes: [UIKIT-4528](https://sendbird.atlassian.net/browse/UIKIT-4528)
[UIKIT-4528]: https://sendbird.atlassian.net/browse/UIKIT-4528?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bug-fix: Set quote message to null onFileUpload in MessageInput

---

src/ui/MessageItemMenu/index.tsx

Fixes: [UIKIT-4535](https://sendbird.atlassian.net/browse/UIKIT-4535)
[UIKIT-4535]: https://sendbird.atlassian.net/browse/UIKIT-4535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bug-fix: Allow delete failed messages in offline state (second re-fix)

---

src/ui/QuoteMessageInput/QuoteMessageThumbnail.tsx
src/utils/index.ts

Fixes: [UIKIT-4525](https://sendbird.atlassian.net/browse/UIKIT-4525
)
[UIKIT-4525]: https://sendbird.atlassian.net/browse/UIKIT-4525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bug-fix: No video thumbnail on quote reply

---

src/modules/ChannelList/components/ChannelPreview/__tests__/ChannelPreview.spec.js
src/modules/ChannelList/components/ChannelPreview/index.tsx
src/modules/ChannelList/components/ChannelPreview/utils.js
src/ui/Label/stringSet.js

Fixes: [UIKIT-4514](https://sendbird.atlassian.net/browse/UIKIT-4514)
[UIKIT-4514]: https://sendbird.atlassian.net/browse/UIKIT-4514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bug-fix: Fix channel preview last message type.

---

src/modules/Channel/components/MessageInput/useHandleUploadFiles.tsx

Fixes: [UIKIT-4508](https://sendbird.atlassian.net/browse/UIKIT-4508)
[UIKIT-4508]: https://sendbird.atlassian.net/browse/UIKIT-4508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bug-fix: Change MB to MiB

---

src/modules/Channel/components/MessageInput/useHandleUploadFiles.tsx
src/modules/Channel/context/hooks/useSendFileMessageCallback.js
src/modules/Channel/context/hooks/useSendMultipleFilesMessage.ts
src/modules/Thread/context/hooks/useSendFileMessage.ts

Fixes: [UIKIT-4507](https://sendbird.atlassian.net/browse/UIKIT-4507)
[UIKIT-4507]: https://sendbird.atlassian.net/browse/UIKIT-4507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bug-fix: Chain send multiple selected files.

---

scripts/index.d.ts
src/lib/Sendbird.tsx
src/lib/types.ts
src/modules/App/index.jsx
src/modules/App/stories/index.stories.js
src/modules/App/types.ts
src/modules/Thread/components/ParentMessageInfo/ParentMessageInfoItem.tsx
src/modules/Thread/components/ThreadList/ThreadListItemContent.tsx
src/ui/ContextMenu/index.tsx
src/ui/EmojiReactions/index.tsx
src/ui/MessageContent/index.tsx
src/ui/MobileMenu/ReactedMembersBottomSheet.tsx
src/ui/UserListItem/index.tsx

Fixes: [CLNP-1148](https://sendbird.atlassian.net/browse/CLNP-1148)
[CLNP-1148]: https://sendbird.atlassian.net/browse/CLNP-1148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Added SBUEventHandlers and onPressUserProfile.

---

rollup.module-exports.js
scripts/index.d.ts

export this feature https://github.com/sendbird/sendbird-uikit-react/pull/733

feat: export useModal(GlobalModal)

---

src/modules/Channel/components/MessageList/index.tsx

chore: Fix scroll to bottom on reconnect.

---

src/lib/pubSub/index.ts
src/modules/Channel/context/hooks/useHandleChannelPubsubEvents.ts
src/modules/Thread/context/hooks/useHandleThreadPubsubEvents.ts

* pubSub subscriber has been undefined, so couldn't remove the previous subscriptions
* delete command has been used to Array, but it's for Object
* move the pubSub Subscriber into the useEffect sope for making effective
* use splice instead of delete in the pubSubFactory

fix: pubsub subscriber in useEffect

---

rollup.module-exports.js
scripts/index.d.ts
src/hooks/useSendbirdStateContext.tsx
src/lib/Sendbird.tsx

* feat: export pubSub topics
* fix: export SendbirdProvider and useSendbirdStateContext, not export default

feat: publish pubSub topics

---

src/modules/Channel/components/Message/index.tsx
src/utils/__tests__/getSuggestedReplies.spec.ts
src/utils/index.ts

- I fixed the runtime error that was occurring in the empty channel.

fix: lastMessage is nullable

---

CHANGELOG.md
package.json

* Added a feature to support predefined suggested reply options for AI chatbot trigger messages.
* Introduced custom date format string sets, allowing users to customize the date format for `DateSeparators` and `UnreadCount`.
* Exported the `initialMessagesFetch` callback from the hook to provide more flexibility in UIKit customization.
* Removed duplicate `UserProfileProvider` in `OpenChannelSettings``.
* Removed the logic blocking the addition of empty channels to the ChannelList.
* Fixed a runtime error in empty channels.
* Added precise object dependencies in effect hooks to prevent unnecessary re-renders in the Channel module.
* Migrated the rest of modules & UI components to TypeScript from Javascript.
* Introduced new build settings:
* Changes have been made to export modules using …

Release v3.8.0

---

src/modules/Channel/components/SuggestedMentionList/index.tsx
src/modules/Channel/components/SuggestedMentionList/utils.ts

Fixes: [CLNP-1099](https://sendbird.atlassian.net/browse/CLNP-1099)
[CLNP-1099]: https://sendbird.atlassian.net/browse/CLNP-1099?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bug-fix: Use channel members instead of fetch when searched.

---

src/modules/Channel/components/MessageList/index.tsx
src/ui/TypingIndicatorMessage/TypingDots.tsx
src/ui/TypingIndicatorMessage/index.tsx
src/ui/TypingIndicatorMessage/typingDots.scss

Fixes: [UIKIT-4563](https://sendbird.atlassian.net/browse/UIKIT-4563)
https://www.webmobilefirst.com/en/screencasts/m8A0hyjGJS/
figma design: https://www.figma.com/file/SVbXU00FhjztekD8AiVukK/UIKit_Work-file_React?node-id=1869%3A800&mode=dev
[UIKIT-4563]: https://sendbird.atlassian.net/browse/UIKIT-4563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add new TypingDots UI component

---

rollup.module-exports.mjs
src/lib/Sendbird.tsx
src/lib/pubSub/__tests__/pubSub.spec.ts
src/lib/pubSub/index.ts
src/lib/pubSub/topics.ts
src/lib/selectors.ts
src/lib/types.ts
src/modules/Channel/context/hooks/useHandleChannelPubsubEvents.ts
src/modules/Channel/context/hooks/useSendFileMessageCallback.ts
src/modules/Channel/context/hooks/useSendMessageCallback.ts
src/modules/Channel/context/hooks/useSendMultipleFilesMessage.ts
src/modules/Channel/context/hooks/useSendVoiceMessageCallback.ts
src/modules/Channel/context/hooks/useUpdateMessageCallback.ts
src/modules/ChannelList/utils.ts
src/modules/Thread/context/hooks/useHandleThreadPubsubEvents.ts
src/modules/Thread/context/hooks/useResendMessageCallback.ts
src/modules/Thread/context/hooks/useSendFileMessage.ts
src/modules/Thread/context/hooks/useSendUserMessageCallback.ts
src/modules/Thread/context/hooks/useSendVoiceMessageCallback.ts
src/modules/Thread/context/hooks/useUpdateMessageCallback.ts
src/modules/internalInterfaces.ts

- Fix runtime error due to publishing modules
- Refactor PubSub
ticket: [CLNP-1469]
[CLNP-1469]: https://sendbird.atlassian.net/browse/CLNP-1469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: publishing modules

---

src/modules/internalInterfaces.ts

chore: apply publishing module review

---

.github/pull_request_template.md

- Add changelogs section in PR template (internal)

chore: Add changelogs section in PR template

---

src/modules/Channel/components/Message/index.tsx
src/ui/EmojiReactions/index.tsx
src/ui/MessageContent/MessageProfile/index.tsx
src/ui/MessageContent/index.tsx
src/ui/MessageItemMenu/index.tsx
src/ui/MessageItemReactionMenu/index.tsx

[CLNP-1217](https://sendbird.atlassian.net/browse/CLNP-1217)
* Add props to the MessageContent component
* `renderMessageMenu`, `renderEmojiMenu`, and `renderEmojiReactions`
```tsx
<Channel
renderMessageContent={(props) => {
return <MessageContent
{...props}
renderMessageMenu={(props) => {
return <MessageMenu {...props> />
}}
renderEmojiMenu={(props) => {
return <MessageEmojiMenu {...props> />
}}
renderEmojiReactions={(props) => {
return <EmojiReactions {...props> />
}}
/>
}}
/>
```
[CLNP-1217]: https://sendbird.atlassian.net/browse/CLNP-1217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Support custom rendering message menus and reactions

---

src/modules/App/stories/index.stories.js
src/modules/Channel/components/ChannelUI/index.tsx
src/modules/Channel/components/MessageList/index.tsx
src/modules/Channel/index.tsx

Fixes: [CLNP-754](https://sendbird.atlassian.net/browse/CLNP-754)
- Added `renderFrozenNotification` in `ChannelUIProps`
```
<Channel
channelUrl={channelUrl}
...
renderFrozenNotification={() => {
return (
<div
className="sendbird-notification sendbird-notification--frozen sendbird-conversation__messages__notification"
>My custom Frozen Notification</div>
);
}}
/>
```
[CLNP-754]: https://sendbird.atlassian.net/browse/CLNP-754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Added renderFrozenNotification in ChannelUIProps

---

src/modules/Thread/context/hooks/useResendMessageCallback.ts

[UIKIT-4519](https://sendbird.atlassian.net/browse/UIKIT-4519)
When a current user resend failed messages from Thread, the failed messages are added to the Channel.
But it shouldn't do that.
* Do pubSub publish when resending message is succeeded
* Do not share the failed messages from Thread to the other modules, when resending them
[UIKIT-4519]: https://sendbird.atlassian.net/browse/UIKIT-4519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Do pubSub publish when resending message is succeeded

---

src/modules/ChannelList/components/AddChannel/index.tsx
src/modules/GroupChannelList/components/AddChannel/AddChannelView.tsx
src/modules/GroupChannelList/components/AddChannel/index.tsx

Implement presentation layer of AddChannel
Ticket: [CLNP-1572]
[CLNP-1572]: https://sendbird.atlassian.net/browse/CLNP-1572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: implement AddChannelView for presentation layer

---

.eslintrc.json
src/hooks/useOnScrollReachedEndDetector/index.ts
src/modules/ChannelList/components/ChannelListUI/index.tsx
src/modules/ChannelList/index.tsx
src/modules/GroupChannelList/components/ChannelListUI/ChannelListUIView.tsx
src/modules/GroupChannelList/components/ChannelListUI/index.tsx
src/modules/GroupChannelList/context/GroupChannelListProvider.tsx
src/modules/GroupChannelList/stories/index.stories.tsx

Implement presentation layer of ChannelList
Ticket: [CLNP-1572](https://sendbird.atlassian.net/browse/CLNP-1572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
[CLNP-1572]: https://sendbird.atlassian.net/browse/CLNP-1572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: implement ChannelListUIView for presentation layer

---

src/modules/Channel/components/MessageInput/useHandleUploadFiles.tsx
src/ui/Label/stringSet.ts

[CLNP-1627](https://sendbird.atlassian.net/browse/CLNP-1627)
[SBISSUE-14291](https://sendbird.atlassian.net/browse/SBISSUE-14291)
Move the count&size limit of the file uploading notification description to String Set
[SBISSUE-14291]: https://sendbird.atlassian.net/browse/SBISSUE-14291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CLNP-1627]: https://sendbird.atlassian.net/browse/CLNP-1627?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Apply StringSet for the file upload limit notification

---

src/ui/EmojiReactions/stories/EmojiReactions.stories.js

* Solve the error message on the EmojiReactions storybook by adding proper props
[Request from Slack](https://sendbird.slack.com/archives/C8TNVAPQT/p1701116218365719)

fix: Improve the storybook of the EmojiReactions

---

src/ui/EmojiReactions/ReactionItem.tsx
src/ui/EmojiReactions/index.tsx

Add a message prop to the ReactionItem component for when the Component is not contained by the MessageProvider
Add a message prop to the ReactionItem component for when the Component is not contained by the MessageProvider

fix: Add a message prop to the ReactionItem comp

---

src/ui/Avatar/__tests__/__snapshots__/Avatar.spec.js.snap
src/ui/Avatar/index.tsx
src/ui/FileViewer/__tests__/__snapshots__/FileViewer.spec.js.snap
src/ui/MessageContent/__tests__/__snapshots__/MessageContent.spec.js.snap
src/ui/MessageSearchFileItem/__tests__/__snapshots__/MessageSearchFileItem.spec.js.snap
src/ui/MessageSearchItem/__tests__/__snapshots__/MessageSearchItem.spec.js.snap
src/ui/OpenchannelConversationHeader/__tests__/__snapshots__/OpenchannelConversationHeader.spec.js.snap
src/ui/OpenchannelFileMessage/__tests__/__snapshots__/OpenchannelFileMessage.spec.js.snap
src/ui/OpenchannelOGMessage/__tests__/__snapshots__/OpenchannelOGMessage.spec.js.snap
src/ui/OpenchannelThumbnailMessage/__tests__/__snapshots__/OpenchannelThumbnailMessage.spec.js.snap
src/ui/OpenchannelUserMessage/__tests__/__snapshots__/OpenchannelUserMessage.spec.js.snap
src/ui/UserListItem/__tests__/__snapshots__/UserListItem.spec.js.snap

from this PR
https://github.com/sendbird/sendbird-uikit-react/pull/880#issuecomment-1835673772
* Fix the Avatar component's position on the member list of channel

fix: Remove left 0px from Avatar comp to fix ruined align

---

src/modules/Channel/context/dux/reducers.ts

Fixes: [CLNP-1741](https://sendbird.atlassian.net/browse/CLNP-1741)
- Fixed a bug where admin message disappears when sending a message
[CLNP-1741]: https://sendbird.atlassian.net/browse/CLNP-1741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bug-fix: Fixed a bug where admin message disappears when sending a message

---

CHANGELOG.md
package.json
src/modules/ChannelList/dux/actionTypes.ts
src/modules/ChannelList/dux/reducers.ts
src/modules/ChannelList/utils.ts

* Improved image loading speed by implementing lazy load with `IntersectionObserver`
* Replaced lamejs binary
* Applied the `uikitUploadSizeLimit` to the Open Channel Message Input
* Check the file size limit when sending file messages from Open Channel
* Display the modal alert when the file size over the limit
* Fixed a bug where the admin message disappears when sending a message
* Recognized the hash property in the URL
* Fixed a bug where resending MFM fails in the thread
* Group channel user left or banned event should not be ignored
* Removed left 0px from `<Avatar />` component to fix ruined align
* Applied StringSet for the file upload limit notification
* Updated currentUserId properly in the channel list initialize step.
* Fixed group channel doesn't move to the top in a …

release: 3.9.1

---

CHANGELOG.md
package.json

* Fixed scroll issues
* Maintain scroll position when loading previous messages.
* Maintain scroll position when loading next messages.
* Move the logic that delays rendering mmf to the correct location.
* Resolve an issue where scroll position wasn't adjusting correctly when the message content size was updated (caused by debouncing scroll events).
* Use `animatedMessage` instead of `highlightedMessage` in the smart app component.
* Reset text display issue
* Fix the appearance of incomplete text compositions from the previous input in the next input.
* Fixed type errors
* Resolve the type error related to `PropsWithChildren`.
* Address the issue of not being assignable to type error, where the property 'children' doesn't exist on type `PropsWithChildren`.
* Use …

release: 3.9.2

---

src/lib/hooks/useOnlineStatus.ts

Fixes https://sendbird.atlassian.net/browse/SBISSUE-14287 
The change is originally made by @AaronJamesKing 👍 https://github.com/notice-co/sendbird-uikit-react/commit/e393069793b344cf78c7cbc9db48b1473aeac7a4

fix: prevent access to window in SSR environment

---

src/modules/OpenChannel/context/hooks/useFileUploadCallback.tsx
src/modules/OpenChannel/context/hooks/useSendMessageCallback.ts

- ticket: [CLNP-1856]
[CLNP-1856]: https://sendbird.atlassian.net/browse/CLNP-1856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: should scroll to bottom when sending a message in open channel

---

src/ui/OGMessageItemBody/index.tsx

Fixes: [CLNP-1845](https://sendbird.atlassian.net/browse/CLNP-1845)
- Fixed cross site scripting vulnerability in OGTag
[CLNP-1845]: https://sendbird.atlassian.net/browse/CLNP-1845?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bug-fix: Fix cross site scripting vulnerability in OGTag

---

CHANGELOG.md
package.json

* **Refactor `--sendbird-vh` CSS Variable Logic in InviteUsers Component**
- Improved code readability by moving logic to the `InviteUsers` component.
- [GitHub PR #899](https://github.com/sendbird/sendbird-uikit-react/pull/899) (CLNP-1806)
* **Prevent Access to `window` in SSR Environments**
- Fixed server-side rendering issues in NextJS by preventing access to the `window` object.
- (Original Author: [Aaron James King](https://github.com/AaronJamesKing))
- [GitHub PR #900](https://github.com/sendbird/sendbird-uikit-react/pull/900) (SBISSUE-14287)
* **Update Channel View to Show `NO_CHANNEL` Placeholder**
- Channel view now displays `NO_CHANNEL` placeholder after leaving all channels. 
- (Original Author: [Alden Quimby](https://github.com/aldenquimby))
- [GitHub PR …

release: v3.9.3

---

src/lib/pubSub/topics.ts
src/modules/GroupChannel/components/MessageList/index.tsx
src/modules/GroupChannel/context/GroupChannelProvider.tsx

ticket: [CLNP-1849]
[CLNP-1849]: https://sendbird.atlassian.net/browse/CLNP-1849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: group channel list, group channel behavior backward check

---

src/modules/Channel/components/Message/index.tsx
src/modules/GroupChannel/components/Message/MessageView.tsx
src/modules/GroupChannel/components/Message/index.tsx

- MessageView presentation layer

feat: create a message presentation layer

---

package.json
src/modules/Channel/context/ChannelProvider.tsx
src/modules/ChannelList/components/AddChannel/index.tsx
src/modules/CreateChannel/components/InviteUsers/__tests__/index.spec.tsx
src/modules/CreateChannel/components/InviteUsers/index.tsx
src/modules/CreateChannel/context/CreateChannelProvider.tsx
src/modules/CreateChannel/index.tsx
src/modules/GroupChannel/context/GroupChannelProvider.tsx
src/modules/GroupChannelList/components/AddGroupChannel/AddGroupChannelView.tsx
src/modules/GroupChannelList/context/GroupChannelListProvider.tsx
yarn.lock

[CLNP-1848](https://sendbird.atlassian.net/browse/CLNP-1848)
* GroupChannelList has `channelListQueryParams`
* GroupChannel has `messageListQueryParams`
* Rename the `overrideInviteUser` to `onClickCreateChannel`
[CLNP-1848]: https://sendbird.atlassian.net/browse/CLNP-1848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Apply filters to the collections

---

package.json
src/lib/Sendbird.tsx
src/lib/types.ts
src/lib/utils/uikitConfigMapper.ts
src/modules/App/stories/integrated.stories.js
src/ui/MessageContent/index.tsx
yarn.lock

Fixes: [AC-984](https://sendbird.atlassian.net/browse/AC-984)
- Added `feedbackEnabled` in `UIKitOptions`
[AC-984]: https://sendbird.atlassian.net/browse/AC-984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Added feedbackEnabled in UIKitOptions

---

src/modules/Channel/components/MessageFeedbackModal/index.tsx
src/ui/FeedbackIconButton/index.scss
src/ui/FeedbackIconButton/index.tsx
src/ui/MessageContent/index.tsx

Fixes: [AC-992](https://sendbird.atlassian.net/browse/AC-992)
- N/A
Screeshots
Before
After
[AC-992]: https://sendbird.atlassian.net/browse/AC-992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bug-fix: Fix feedback icon button disabled

---

src/ui/Label/stringSet.ts

Fixes: [AC-986](https://sendbird.atlassian.net/browse/AC-986)
[AC-986]: https://sendbird.atlassian.net/browse/AC-986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bug-fix: Fix feedback form texts

---

src/ui/MessageContent/index.scss
src/ui/MessageContent/index.tsx

Fixes: [AC-1044](https://sendbird.atlassian.net/browse/AC-1044)
before
after
[AC-1044]: https://sendbird.atlassian.net/browse/AC-1044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bug-fix: Fixed a bug where replies button overlaps with feeedback buttons

---

src/modules/App/MobileLayout.tsx

from https://github.com/sendbird/sendbird-uikit-react/pull/901#issuecomment-1899118495

fix: handle exceptional case when channel is missing on mobile layout

---

src/modules/MessageSearch/context/hooks/useGetSearchedMessages.ts

[CLNP-1965](https://sendbird.atlassian.net/browse/CLNP-1965)
* Loading spinner doesn't finish if a user tries to search message during disconnected status
* Display the `something went wrong` message when message search fails
[CLNP-1965]: https://sendbird.atlassian.net/browse/CLNP-1965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Operate disconnection status of the MessageSearch

---

src/hooks/VoicePlayer/dux/actionTypes.ts
src/hooks/VoicePlayer/dux/reducer.ts
src/hooks/VoicePlayer/index.tsx

[CLNP-1987](https://sendbird.atlassian.net/browse/CLNP-1987)
* Loading spinner doesn't finish if a user try to play the voice message during disconnected status
* Reset the audio player status when failing to load the audio file with `file.fileURL`
[CLNP-1987]: https://sendbird.atlassian.net/browse/CLNP-1987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Manage disconnected status of VoiceMessage

---

src/modules/Channel/components/MessageFeedbackModal/index.tsx
src/ui/MessageContent/index.tsx

Fixes: [AC-1071](https://sendbird.atlassian.net/browse/AC-1071)
- Changed behaivour of the feedback process:
- old: On feedback icon button click -> open feedback form/menu
- new: On feedback icon button click -> submit feedback -> open feedback form/menu
[AC-1071]: https://sendbird.atlassian.net/browse/AC-1071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bug-fix: Change feedback process to submit on feedback icon click

---

src/modules/ChannelSettings/components/ModerationPanel/InviteUsersModal.tsx

- Apply UIKit policy to `InviteUsersModal`
ticket: [CLNP-2055]
[CLNP-2055]: https://sendbird.atlassian.net/browse/CLNP-2055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: invite users

---

src/modules/Channel/components/MessageInput/index.tsx
src/modules/Thread/components/ThreadMessageInput/index.tsx

[CLNP-2015](https://sendbird.atlassian.net/browse/CLNP-2015)
* Support accepting mimeTypes to the MessageInput
[CLNP-2015]: https://sendbird.atlassian.net/browse/CLNP-2015?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Support accepting mimeTypes to the MessageInput

---

src/hooks/VoicePlayer/dux/reducer.ts
src/hooks/VoicePlayer/index.tsx
src/hooks/VoiceRecorder/index.tsx
src/modules/GroupChannel/components/MessageInputWrapper/VoiceMessageInputWrapper.tsx

[CLNP-2056](https://sendbird.atlassian.net/browse/CLNP-2056)
[CLNP-2057](https://sendbird.atlassian.net/browse/CLNP-2057)
* Apply the `onRecordingStarted` to the `recorder.onstart` event
* Get the `duration` and `currentTime` from out of the reducer
[CLNP-2056]: https://sendbird.atlassian.net/browse/CLNP-2056?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CLNP-2057]: https://sendbird.atlassian.net/browse/CLNP-2057?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: VoiceMessage playback playtime issue

---

src/modules/ChannelList/dux/reducers.ts
src/ui/ChannelAvatar/index.tsx
src/utils/index.ts

Fixes: [CLNP-2121](https://sendbird.atlassian.net/browse/CLNP-2121)
- https://github.com/sendbird/sendbird-uikit-react/pull/937
- Fixed a bug where channel is being removed from my channel list when other member leaves the channel
- Fixed a bug where channel avatar image is not updated when a member leaves, or joins, or profileUrl changes
Note the video displays first fix only.
https://github.com/sendbird/sendbird-uikit-react/assets/16806397/a729c835-569d-4ad5-95f8-193bf44b2fb1
Co-authored-by: @aldenquimby
[CLNP-2121]: https://sendbird.atlassian.net/browse/CLNP-2121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bug-fix: Fixed a bug where channel is being removed from my channel list when other member leaves the channel

---

src/modules/App/index.tsx
src/modules/Channel/context/hooks/useHandleReconnectForChannelList.ts
src/modules/ChannelList/context/ChannelListProvider.tsx
src/modules/ChannelList/dux/actionTypes.ts
src/modules/ChannelList/dux/reducers.ts
src/modules/ChannelList/index.tsx
src/modules/ChannelList/utils.ts

Fixes: [CLNP-2136](https://sendbird.atlassian.net/browse/CLNP-2136)
- Fixed a bug where `ChannelListUI` is not updated when network is reconnected
https://github.com/sendbird/sendbird-uikit-react/assets/16806397/d5a86527-2cff-491a-90b9-424b4ced3902
[CLNP-2136]: https://sendbird.atlassian.net/browse/CLNP-2136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bug-fix: Fix bug where `ChannelListUI` is not updated when network is reconnected

---

src/modules/GroupChannel/components/FrozenNotification/index.tsx
src/modules/GroupChannel/components/GroupChannelUI/index.tsx
src/modules/GroupChannel/components/RemoveMessageModal/RemoveMessageModalView.tsx
src/modules/GroupChannel/components/RemoveMessageModal/index.tsx
src/modules/GroupChannel/components/UnreadCount/index.tsx
src/modules/GroupChannelList/components/GroupChannelListItem/index.tsx
src/modules/GroupChannelList/components/GroupChannelListUI/index.tsx
src/modules/GroupChannelList/components/GroupChannelPreviewAction.tsx

Add missing export for the GroupChannel and GroupChannelList modules

fix: Add missing export for the group channel modules

---

src/modules/Message/utils/tokens/__tests__/tokenizeMessage.spec.ts
src/modules/Message/utils/tokens/__tests__/tokenizeUtils.spec.ts
src/modules/Message/utils/tokens/tokenize.ts
src/ui/Word/index.scss
src/utils/index.ts

Fixes 
- https://sendbird.atlassian.net/browse/CLNP-2190
- https://sendbird.atlassian.net/browse/SBISSUE-14850
https://github.com/sendbird/sendbird-uikit-react/assets/10060731/cf24a5c2-809f-40de-befb-65f8a2514a59

fix: parsing URL within special characters

---

samples/README.md

Template
```
Fixes: https://sendbird.atlassian.net/browse/SBISSUE-14778

[fix]: Fix wrong stackblitz links

---

src/modules/Channel/components/MessageInputWrapper/index.tsx
src/modules/GroupChannel/components/MessageInputWrapper/index.tsx

`mentionedMessageTemplate ` should be passed to `sendMessage`
ticket: [CLNP-2261]
[CLNP-2261]: https://sendbird.atlassian.net/browse/CLNP-2261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: mentionTemplate should be passed when mapped to sendMessage

---

src/hooks/useAsyncRequest.ts
src/modules/ChannelSettings/components/ChannelSettingsUI/index.tsx
src/modules/ChannelSettings/context/ChannelSettingsProvider.tsx

https://github.com/sendbird/sendbird-uikit-react/assets/26326015/e99d17a2-555f-4638-8d54-1182a872d4b9
https://github.com/sendbird/sendbird-uikit-react/assets/26326015/5ee355b9-a0c7-497d-a857-d8c21dbaa0e6
ticket: [CLNP-2304]
[CLNP-2304]: https://sendbird.atlassian.net/browse/CLNP-2304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: show loading placeholder when fetching channel in ChannelSettings

---

src/hooks/useAsyncRequest.ts
src/modules/ChannelSettings/context/ChannelSettingsProvider.tsx

from https://github.com/sendbird/sendbird-uikit-react/pull/981

refactor: update useAsyncRequest, ChannelSettingsProvider

---

src/modules/Channel/context/ChannelProvider.tsx
src/modules/Channel/context/dux/actionTypes.ts

fix from https://github.com/sendbird/sendbird-uikit-react/pull/980
thanks to @tylerhammer

Improve MessageListParams interface in ChannelProvider

---

src/modules/GroupChannel/components/MessageInputWrapper/useHandleUploadFiles.tsx

[SBISSUE-15201](https://sendbird.atlassian.net/browse/SBISSUE-15201)
Apply the string set `FILE_UPLOAD_NOTIFICATION__COUNT_LIMIT` and `FILE_UPLOAD_NOTIFICATION__SIZE_LIMIT`
[SBISSUE-15201]: https://sendbird.atlassian.net/browse/SBISSUE-15201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Apply string set for file upload size and count limit

---

src/modules/Channel/components/Message/index.tsx
src/modules/Channel/context/ChannelProvider.tsx
src/modules/GroupChannel/components/GroupChannelUI/index.scss
src/modules/GroupChannel/components/Message/MessageView.tsx
src/modules/GroupChannel/context/GroupChannelProvider.tsx

[SBISSUE-15149](https://sendbird.atlassian.net/browse/SBISSUE-15149)
* Remove highlighted message system
* Set animated message id with null instead of 0
* Prevent bouncing pending message
[SBISSUE-15149]: https://sendbird.atlassian.net/browse/SBISSUE-15149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Prevent bouncing pending message

---

package.json
src/modules/GroupChannel/context/GroupChannelProvider.tsx
yarn.lock

chore: export dangerous api

---

MIGRATION_COLLECTION.md

docs: add renderMessage behavior changes

---

src/modules/ChannelSettings/components/ChannelSettingsUI/ChannelSettingsHeader.tsx
src/modules/ChannelSettings/components/ChannelSettingsUI/index.tsx

* Add a `renderHeader` props to the ChannelSettingsUIProps
```
<ChannelSettingsUI
renderHeader={() => ...}
/>
```

feature: Add renderHeader props to the ChannelSettingsUIProps

---

src/ui/Modal/index.tsx

[CLNP-2528](https://sendbird.atlassian.net/browse/CLNP-2528)
* Show X button on the Modal of mobile mode
[CLNP-2528]: https://sendbird.atlassian.net/browse/CLNP-2528?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Show X button on the Modal of mobile mode

---

src/ui/AdminMessage/index.tsx
src/ui/Avatar/index.tsx
src/ui/BottomSheet/index.tsx
src/ui/Button/utils.ts
src/ui/ChannelAvatar/utils.ts
src/ui/ContextMenu/MenuItems.tsx
src/ui/DateSeparator/index.tsx
src/ui/FileMessageItemBody/index.tsx
src/ui/FileViewer/index.tsx
src/ui/Icon/type.ts
src/ui/ImageGrid/index.tsx
src/ui/ImageRenderer/index.tsx
src/ui/ImageRenderer/useDynamicSideLength.ts
src/ui/ImageRenderer/utils.ts
src/ui/LegacyEditUserProfile/index.tsx
src/utils/index.ts
src/utils/numberToPx.ts

Fixed type errors when 'strictNullChecks' is 'true'.

fix: Fixed type error.

---

src/ui/UserListItem/index.tsx

* Replace the hardcoded text ` (You)` with the StringSet `CHANNEL_SETTING__MEMBERS__YOU` in the UserListItem

fix: Replace the text (You) with the stringSet

---

src/ui/MessageItemMenu/index.tsx

[SBISSUE-15392](https://sendbird.atlassian.net/browse/SBISSUE-15392)
* Add `renderMenuItem` to the MessageMenu component
```tsx
<GroupChannel
renderMessageContent={(props) => {
<MessageContent
{...props}
renderMessageMenu={(props) => {
<MessageMenu
{...props}
renderMenuItem={(props) => {
const {
className,
onClick,
dataSbId,
disable,
text,
} = props;
// Render Custom Menu Item
}}
/>
}}
/>
}}
/>
```
[SBISSUE-15392]: https://sendbird.atlassian.net/browse/SBISSUE-15392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature: Add renderMenuItem to the MessageMenu

---

src/modules/ChannelSettings/components/ModerationPanel/MembersModal.tsx
src/ui/OGMessageItemBody/index.scss
src/ui/OGMessageItemBody/index.tsx
src/ui/UserListItem/index.scss
src/ui/UserListItem/index.tsx

* Improve the stability of the ChannelSettings Modals
* Fix the width size of the OGMessageItemBody component to `320px`

fix: Improve the ChannelSettings Modal stability

---

package.json
src/lib/Sendbird.tsx
src/lib/types.ts
src/modules/Channel/context/ChannelProvider.tsx
src/modules/GroupChannel/context/GroupChannelProvider.tsx
src/modules/Thread/components/ParentMessageInfo/ParentMessageInfoItem.tsx
src/modules/Thread/components/ParentMessageInfo/index.tsx
src/modules/Thread/components/ThreadList/ThreadListItem.tsx
src/ui/EmojiReactions/index.tsx
src/utils/__tests__/getIsReactionEnabled.spec.ts
src/utils/getIsReactionEnabled.ts
yarn.lock

* Support reaction feature in the SuperGroupChannel
* modify the `getIsReactionEnabled`

feature: Support reactions in the SuperGroupChannel

---

rollup.module-exports.mjs
src/ui/MessageContent/index.tsx
src/ui/MessageFeedbackFailedModal/index.tsx
src/ui/MessageFeedbackModal/index.scss
src/ui/MessageFeedbackModal/index.tsx

chore: export MessageFeedbackFailedModal component

---

CHANGELOG.md
package.json

* Add support for the `Emoji Reactions` feature in super group channels.
* Note: The `Tooltip` that displays who has reacted will only appear in normal group channels, not in super group channels.
* Export the `MessageFeedbackFailedModal` component for consistency with other message feedback-related components.

release: v3.13.4

---

src/ui/TemplateMessageItemBody/index.tsx

Added error catch in malformed template payload

bug-fix: Added error catch in malformed template payload

---

src/ui/MessageContent/index.scss

spec-change: Move timestamp to bottom left for carousel

---

src/ui/Avatar/__tests__/__snapshots__/Avatar.spec.js.snap
src/ui/ChannelAvatar/__tests__/ChannelAvatar.spec.js
src/ui/ImageRenderer/index.tsx
src/ui/MessageContent/__tests__/__snapshots__/MessageContent.spec.js.snap
src/ui/MessageContent/index.scss
src/ui/OGMessageItemBody/__tests__/__snapshots__/OGMessageItemBody.spec.js.snap

Fixes: 
- [AC-1824](https://sendbird.atlassian.net/browse/AC-1824)
1. fix default profile not showing issue
2. fix scroll displayed in message sender title container
[AC-1824]: https://sendbird.atlassian.net/browse/AC-1824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bug-fix: fix template qa issues

---

src/hooks/tsconfig.json
src/lib/tsconfig.json
src/modules/tsconfig.json

프로젝트 전체 strictNullChecks 는 true로 두고
strictNullChecks 관련 에러가 수정되지 않은 아래 폴더는 strictNullChecks 하지 않도록 구성 하였습니다.
src/modules
src/lib
src/hooks

chore:sub tsconfig

---

src/ui/MessageInput/hooks/usePaste/index.ts

ticket: [CLNP-2896]
[CLNP-2896]: https://sendbird.atlassian.net/browse/CLNP-2896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: handle uri-list pasting

---

src/modules/GroupChannel/context/GroupChannelProvider.tsx
src/modules/GroupChannel/context/hooks/useMessageListScroll.ts

ticket: [CLNP-2897]
[CLNP-2897]: https://sendbird.atlassian.net/browse/CLNP-2897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: scroll bottom check properly in markAsRead

---

.github/workflows/bct.yml
.github/workflows/pr-comment-bot.yml

ci: add bct.yml for testing

---

.github/workflows/bct.yml
.github/workflows/pr-comment-bot.yml
.github/workflows/release-ticket-creation.yml

- Add dispatch step to BCT workflow

ci: add dispatch bct step

---

.github/workflows/bct.yml

ci: update

---

src/modules/GroupChannel/components/MessageList/index.scss
src/ui/MessageContent/index.scss

Fixes: [CLNP-2923](https://sendbird.atlassian.net/browse/CLNP-2923)
- Fixed a bug where right padding is added to messages sent by me in mobile devices
[CLNP-2923]: https://sendbird.atlassian.net/browse/CLNP-2923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Fixed a bug where right padding is added to messages sent by me

---

CHANGELOG.md
package.json

* Add outputFormat to the image compression options
```tsx
...
imageCompression={{
outputFormat: 'preserve' | 'png' | 'jpeg',
}}
>
```
* Set the message list padding with `12px` in the mobile mode

release: v3.14.3

---

src/modules/GroupChannel/components/Message/index.tsx

- bugfix
- ticket: [CLNP-2952]
[CLNP-2952]: https://sendbird.atlassian.net/browse/CLNP-2952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: should render suggested replies condition in group channel module

---

.github/workflows/deploy-github-pages.yml

* fix: typo in yml for Github page deployment

fix: typo in yml for Github page deployment

---

apps/testing/src/App.tsx
apps/testing/src/utils/paramsBuilder.ts
src/stories/apps/GroupChannelApp.stories.tsx

* Add a logger to samples for debugging

chore: Add a logger to samples for debugging

---

.github/workflows/package-publish.yml

A trial to fix https://sendbird.slack.com/archives/G01290GCDCN/p1716440635961049?thread_ts=1716354525.736339&cid=G01290GCDCN

fix: package publish script

---

src/stories/apps/GroupChannelApp.stories.tsx
src/stories/apps/OpenChannelCommunityApp.stories.tsx
src/stories/common/const.ts
src/stories/common/getSampleChannel.ts
src/stories/modules/ChannelSettings.stories.tsx
src/stories/modules/GroupChannel.stories.tsx
src/stories/modules/GroupChannelList.stories.tsx
src/stories/modules/MessageSearch.stories.tsx

[CLNP-3433](https://sendbird.atlassian.net/browse/CLNP-3433)
* Empty channel in the stories of module category, because user left the current channel
* Create a new channel if there's no channel in the my group channel list
[CLNP-3433]: https://sendbird.atlassian.net/browse/CLNP-3433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: storybook user leave channel issue

---

src/modules/GroupChannel/components/SuggestedReplies/index.scss

chore: adjust suggested reply bubble size

---

package.json

ref:
https://sendbird.slack.com/archives/G01290GCDCN/p1716974444514649
blocked PR: https://github.com/sendbird/chat-ai-widget/pull/253

chore: remove duplicate dependency

---

src/ui/MessageInput/index.tsx
yarn.lock

Fixes: [AC-2593](https://sendbird.atlassian.net/browse/AC-2593)
- Remove auto focus message input on user given disabled state set to false
[AC-2593]: https://sendbird.atlassian.net/browse/AC-2593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Remove auto focus message input on user given disabled state set to false

---

package.json
yarn.lock

blocker for
https://github.com/sendbird/chat-ai-widget/pull/260

chore: update chat sdk version

---

src/modules/GroupChannel/components/FileViewer/FileViewerView.tsx
src/ui/FileViewer/index.tsx
src/ui/Modal/index.tsx

[SBISSUE-15945](https://sendbird.atlassian.net/browse/SBISSUE-15945)
[SBISSUE-15945]: https://sendbird.atlassian.net/browse/SBISSUE-15945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Add close event to fileviewer modals

---

CHANGELOG.md
package.json

[SDKRLSD-1314](https://sendbird.atlassian.net/browse/SDKRLSD-1314)
- Replaced onlight-05 with onlight-03 since onlight-05 doesn't exist in the product design guide.
- Added the `onClose` event to the modals inside of the `FileViewer` components.
[SDKRLSD-1314]: https://sendbird.atlassian.net/browse/SDKRLSD-1314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

release: v3.14.10

---

src/lib/Sendbird.tsx
src/modules/GroupChannel/components/MessageInputWrapper/MessageInputWrapperView.tsx
src/ui/Label/stringSet.ts

ticket: [AC-2781]
[AC-2781]: https://sendbird.atlassian.net/browse/AC-2781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[widget] chore: add placeholder string for suggested replies

---

CHANGELOG.md
package.json
rollup.module-exports.mjs
src/modules/Message/utils/tokens/__tests__/asSafeUrl.spec.ts
src/modules/Message/utils/tokens/tokenize.ts
src/ui/MobileMenu/index.tsx

- Markdown Support for Text Messages
- Added `enableMarkdownForUserMessage` to `UIKitOptions`. When enabled, markdown syntaxes for bold and link are now applied to user messages.
- Descriptive Color Names Support
- Users can now customize the color set using more descriptive color names instead of numerical codes.
- Added a color map parsing utility function, `mapColorKeys`, to support both new and existing color names.
- Detailed color name mappings:
1. Primary, Secondary, Error, information
```
Primary-500 -> Primary-extra dark
Primary-400 -> Primary-dark
Primary-300 -> Primary-main
Primary-200 -> Primary-light
Primary-100 -> Primary-extra light
Secondary-500 -> Secondary-extra dark
Secondary-400 -> Secondary-dark
Secondary-300 -> Secondary-main
Secondary-200 -> Secondary-light …
```

release: 3.14.11

---

.github/pull_request_template.md

Addresses https://sendbird.atlassian.net/browse/CLNP-3856 
Added below to the README 
```
```
and cleaned up a bit for the better readability.

chore: add checklists to README

---

src/modules/ChannelSettings/components/ChannelSettingsUI/channel-settings-ui.scss
src/modules/ChannelSettings/components/UserPanel/user-panel.scss
src/ui/MessageSearchItem/index.scss
src/ui/ThreadReplies/index.scss

Fixed several UI issues mentioned in https://sendbird.slack.com/archives/C0794CS06EM/p1718940053725789

fix: apply 1st design QA items for RTL

---

src/ui/MessageContent/index.tsx

Trial to fix https://sendbird.slack.com/archives/G01290GCDCN/p1719802035388179?thread_ts=1718632804.126839&cid=G01290GCDCN
```
Fixes …
```

fix: pass an empty object not to get blocked on emojiContainer init

---

src/modules/ChannelSettings/components/ChannelProfile/index.tsx
src/modules/ChannelSettings/components/ModerationPanel/AddOperatorsModal.tsx
src/modules/ChannelSettings/components/ModerationPanel/BannedUserList.tsx
src/modules/ChannelSettings/components/ModerationPanel/BannedUsersModal.tsx
src/modules/ChannelSettings/components/ModerationPanel/InviteUsersModal.tsx
src/modules/ChannelSettings/components/ModerationPanel/MemberList.tsx
src/modules/ChannelSettings/components/ModerationPanel/MembersModal.tsx
src/modules/ChannelSettings/components/ModerationPanel/MutedMemberList.tsx
src/modules/ChannelSettings/components/ModerationPanel/MutedMembersModal.tsx
src/modules/ChannelSettings/components/ModerationPanel/OperatorList.tsx
src/modules/ChannelSettings/components/ModerationPanel/OperatorsModal.tsx
src/modules/ChannelSettings/components/UserListItem/index.tsx
src/modules/ChannelSettings/context/ChannelSettingsProvider.tsx
src/modules/OpenChannelSettings/components/OperatorUI/AddOperatorsModal.tsx
src/ui/ContextMenu/index.tsx
src/ui/MessageMenu/MessageMenuProvider.tsx
src/ui/MessageMenu/index.scss
src/ui/MessageMenu/menuItems/BasicItems.tsx
src/ui/MobileMenu/mobile-menu.scss
src/ui/UserListItem/__tests__/UserListItem.spec.js
src/ui/UserListItem/index.tsx
src/ui/UserListItemMenu/DefaultElements.tsx
src/ui/UserListItemMenu/UserListItemMenu.tsx
src/ui/UserListItemMenu/UserListItemMenuItems.tsx
src/ui/UserListItemMenu/context.tsx
src/ui/UserListItemMenu/hooks.tsx
src/ui/UserListItemMenu/index.tsx

[CLNP-3258](https://sendbird.atlassian.net/browse/CLNP-3258)
* Created a `UserListItemMenu` component
* Provided it as a module which also contains `UserListItemMenuProvider` and `useUserListItemMenuContext`
```tsx
import { UserListItemMenu, UserListItemMenuProvider, useUserListItemMenuContext } from '@sendbird/uikit-react/ui/UserListItemMenu';
```
How to use?
```tsx
<SomeUserListComponent
renderUserListItem={(props) => ( // TODO: will be added
<UserListItem {...props}
renderListItemMenu={(props) => (
<UserListItemMenu
{...props}
onToggleOperatorState={({ user, newState, error }) => {/** Handle operator state change */}}
onToggleMuteState={({ user, newState, error }) => {/** Handle mute state change */}}
onToggleBanState={({ user, newState, error }) => {/** Handle ban state change */}} …
```

refactor: UserListItem's Menu for better customization

---

src/modules/GroupChannel/components/FileViewer/index.scss
src/ui/FileViewer/index.scss

[AC-2608](https://sendbird.atlassian.net/browse/AC-2608)
[4 sprints - Client JS - Agile Board - Jira (1).webm](https://github.com/sendbird/sendbird-uikit-react/assets/16806397/5d62d14b-9aa9-47b1-b1c5-b16695aec380)
[AC-2608]: https://sendbird.atlassian.net/browse/AC-2608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix image file viewer header

---

.storybook/index.css
.storybook/preview.tsx
src/lib/Sendbird.tsx
src/lib/index.scss
src/ui/ContextMenu/EmojiListItems.tsx
src/ui/ContextMenu/MenuItems.tsx

[CLNP-4034](https://sendbird.atlassian.net/browse/CLNP-4034)
* Use the `APP_LAYOUT_ROOT` to get the area info of the UIKit
* Consider that area when calculating the correct `menu`s` position
[CLNP-4034]: https://sendbird.atlassian.net/browse/CLNP-4034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Calculate the sendbird-app size for context menu position

---

src/modules/ChannelSettings/components/ChannelProfile/channel-profile.scss
src/modules/ChannelSettings/components/ChannelSettingsUI/MenuItem.tsx
src/modules/ChannelSettings/components/ChannelSettingsUI/MenuListByRole.tsx
src/modules/ChannelSettings/components/ChannelSettingsUI/channel-settings-ui.scss
src/modules/ChannelSettings/components/ChannelSettingsUI/index.tsx
src/modules/ChannelSettings/components/ModerationPanel/admin-panel.scss

Fixes https://sendbird.slack.com/archives/C05AN1T4Z5Z/p1719981247117649?thread_ts=1719974936.887169&cid=C05AN1T4Z5Z 
https://github.com/sendbird/sendbird-uikit-react/assets/10060731/025695f0-62ad-4546-bfb7-5579fbe7a77a

fix: channel setting menu item style

---

src/modules/ChannelSettings/components/ModerationPanel/AddOperatorsModal.tsx
src/modules/ChannelSettings/components/ModerationPanel/BannedUserList.tsx
src/modules/ChannelSettings/components/ModerationPanel/BannedUsersModal.tsx
src/modules/ChannelSettings/components/ModerationPanel/InviteUsersModal.tsx
src/modules/ChannelSettings/components/ModerationPanel/MemberList.tsx
src/modules/ChannelSettings/components/ModerationPanel/MembersModal.tsx
src/modules/ChannelSettings/components/ModerationPanel/MutedMemberList.tsx
src/modules/ChannelSettings/components/ModerationPanel/MutedMembersModal.tsx
src/modules/ChannelSettings/components/ModerationPanel/OperatorList.tsx
src/modules/ChannelSettings/components/ModerationPanel/OperatorsModal.tsx
src/ui/UserListItem/index.tsx

* Remove the `key` props from the `UserListItem` comp
* Put key into the `UserListItem` using `React.Fragment`
to fix these warnings

fix: Put key into the UserListItem using React.Fragment

---

src/modules/GroupChannel/components/MessageInputWrapper/MessageInputWrapperView.tsx
src/modules/GroupChannel/context/utils.ts
src/ui/Label/stringSet.ts

Fixes [AC-3019](https://sendbird.atlassian.net/browse/AC-3019)
Added message form placeholder for widget
[AC-3019]: https://sendbird.atlassian.net/browse/AC-3019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: placeholder for form message

---

samples/README.md
src/modules/Channel/context/ChannelProvider.tsx
src/modules/Channel/index.tsx
src/modules/ChannelList/context/ChannelListProvider.tsx
src/modules/ChannelList/index.tsx
src/modules/ChannelSettings/components/ChannelSettingsUI/index.tsx

- Add deprecation mark on `Channel`, `ChannelProvider`, `ChannelList`, and `ChannelListProvider`

fix: Mark deprecation on Channel & ChannelList modules

---

src/modules/ChannelSettings/components/ModerationPanel/BannedUserList.tsx
src/modules/ChannelSettings/components/ModerationPanel/BannedUsersModal.tsx
src/modules/ChannelSettings/components/ModerationPanel/MemberList.tsx
src/modules/ChannelSettings/components/ModerationPanel/MembersModal.tsx
src/modules/ChannelSettings/components/ModerationPanel/MutedMemberList.tsx
src/modules/ChannelSettings/components/ModerationPanel/MutedMembersModal.tsx
src/modules/ChannelSettings/components/ModerationPanel/OperatorList.tsx
src/modules/ChannelSettings/components/ModerationPanel/OperatorsModal.tsx

[CLNP-3679](https://sendbird.atlassian.net/browse/CLNP-3679)
* Added `memberListQueryParams` to the `MemberList`, `MembersModal`, `MutedMemberList`, and `MutedMembersModal`
* Added `bannedUserListQueryParams` to the `BannedUserList` and `BannedUsersModal`
* Added `operatorListQueryParams` to the `OperatorList` and `OperatorsModal`
[CLNP-3679]: https://sendbird.atlassian.net/browse/CLNP-3679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add query params to the member list props

---

src/modules/ChannelSettings/context/ChannelSettingsProvider.tsx

[CLNP-4035](https://sendbird.atlassian.net/browse/CLNP-4035)
* Fixed the banned member doesn't affect to ChannelSettings/Profile
* `GroupChannelHandler` was missing in `ChannelSettingsProvider`
[CLNP-4035]: https://sendbird.atlassian.net/browse/CLNP-4035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Banned member doesn't affect to the ChannelSettings/Profile

---

CHANGELOG.md
package.json

- Added `forceLeftToRightMessageLayout` to enable LTR message layout display in RTL mode. This helps users who set `htmlTextDirection='rtl'` to keep the message layout in LTR format (outgoing messages on the right, incoming messages on the left).
```tsx
import SendbirdProvider from ‘@sendbird/uikit-react/SendbirdProvider’;
import ar from 'date-fns/locale/ar';
const YourComponent() => {
return (
htmlTextDirection="rtl" // for RTL display
forceLeftToRightMessageLayout={true} // to enforce the message layout to Left-to-Right direction even though htmlTextDirection is set to ‘rtl’
dateLocale={ar} // locale setting would be necessary too
{…other props}
>
{...other components}
)
}
```
- Banned members no longer affect the ChannelSettings/Profile.
- Fixed an …

release: 3.14.14

---

src/modules/GroupChannel/components/GroupChannelUI/GroupChannelUIView.tsx
src/modules/GroupChannel/components/MessageInputWrapper/MessageInputWrapperView.tsx
src/ui/Label/stringSet.ts

Fixes [AC-3495](https://sendbird.atlassian.net/browse/AC-3495)
Note that this change is for Widget so message inputs inn open channel and thread are not affected. 
[AC-3495]: https://sendbird.atlassian.net/browse/AC-3495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add offline input disabled placeholder

---

src/modules/Channel/components/MessageInputWrapper/index.tsx
src/modules/GroupChannel/components/MessageInputWrapper/MessageInputWrapperView.tsx
src/modules/GroupChannel/components/MessageInputWrapper/index.tsx
src/modules/GroupChannel/context/utils.ts

Fixes [AC-3597](https://sendbird.atlassian.net/browse/AC-3597)
[AC-3597]: https://sendbird.atlassian.net/browse/AC-3597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Fix message input not being disabled when form message is not submitted

---

src/modules/GroupChannel/context/const.ts
src/modules/GroupChannel/context/utils.ts

Fixes [AC-3624](https://sendbird.atlassian.net/browse/AC-3624)
[AC-3624]: https://sendbird.atlassian.net/browse/AC-3624?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: update isDisabledBecauseMessageForm

---

CHANGELOG.md
package.json

- Introduced new `message` event handlers for `onSendMessageFailed`, `onUpdateMessageFailed`, and `onFileUploadFailed` in the `eventHandlers` prop of the message input component. These handlers allow developers to respond to message send, update, and file upload failures.
* How to use?
```tsx
<Sendbird
eventHandlers={{
message: {
onSendMessageFailed: (message, error) => {
// You can use the message parameter to create specific conditions
if (message.isUserMessage()) {
alert(`Message failed to send: ${error?.message}`);
}
},
onUpdateMessageFailed: (message, error) => {
console.log(`Failed to update message: ${message.messageId}, Error: ${error}`);
},
onFileUploadFailed: (error) => {
console.error('File upload failed', error);
},
},
}}
```
- Fixed an issue where the channel UI's scroll did …

release: v3.15.2

---

src/modules/GroupChannel/components/FileViewer/FileViewerView.tsx
src/modules/GroupChannel/components/MessageInputWrapper/MessageInputWrapperView.tsx
src/modules/GroupChannel/components/MessageInputWrapper/useHandleUploadFiles.tsx
src/ui/Icon/index.tsx
src/ui/Label/index.tsx
src/ui/MessageInput/hooks/useFileUploadButton.tsx
src/ui/MessageInput/hooks/usePaste/index.ts
src/ui/MessageInput/index.scss
src/ui/MessageInput/index.tsx

```
Fixes [<TICKET_ID>](https://sendbird.atlassian.net/browse/<TICKET_ID>)
// Changelogs (Recommended)
// Add (internal) at the end of …
```

[AI Widget] file support

---

src/ui/Checkbox/index.scss

Fixes https://sendbird.atlassian.net/browse/CLNP-5095
- LTR
- RTL

[CLNP-5095] fix: ignore RTL handling - checkbox style

---

CHANGELOG.md
package.json

- Fixed incorrect styling for `Checkbox`.
- Fixed the issue where the channel list appears empty when the UIKit is rendered for the first time.

release: v3.15.3

---

CHANGELOG.md
package.json

- Added stringSet for date format and applied them
| Key | Value |
| --- | ----- |
| DATE_FORMAT__MESSAGE_CREATED_AT | `'p'` |
| DATE_FORMAT__UNREAD_SINCE | `'p MMM dd'` |
| DATE_FORMAT__LAST_MESSAGE_CREATED_AT__TODAY | `'p'` |
| DATE_FORMAT__LAST_MESSAGE_CREATED_AT__THIS_YEAR | `'MMM d'` |
| DATE_FORMAT__LAST_MESSAGE_CREATED_AT__PREVIOUS_YEAR | `'yyyy/M/d'` |

release: v3.15.4

---

src/ui/MessageInput/__tests__/utils.spec.ts
src/ui/MessageInput/hooks/usePaste/index.ts
src/ui/MessageInput/hooks/usePaste/insertTemplate.ts
src/ui/MessageInput/utils.ts

[CLNP-5419](https://sendbird.atlassian.net/browse/CLNP-5419)
[SBISSUE-17457](https://sendbird.atlassian.net/browse/SBISSUE-17457)
- Other languages' text was broken when pasting
- Modified the `sanitizeString` logic
[CLNP-5419]: https://sendbird.atlassian.net/browse/CLNP-5419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SBISSUE-17457]: https://sendbird.atlassian.net/browse/SBISSUE-17457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Modified sanitizeString logic

---

src/ui/Label/stringSet.ts

Fixes [AC-4068](https://sendbird.atlassian.net/browse/AC-4068)
[AC-4068]: https://sendbird.atlassian.net/browse/AC-4068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: for snapshot testing

---

apps/testing/src/utils/paramsBuilder.ts

```
Fixes [<TICKET_ID>](https://sendbird.atlassian.net/browse/<TICKET_ID>)
// Changelogs (Recommended)
// Add (internal) at the end of …
```

chore: regional host support for RQA

---

src/ui/TypingIndicatorBubble/index.tsx

Fixes https://sendbird.atlassian.net/browse/SBISSUE-17681

[CLNP-5592] Returning null after hook execution

---

src/lib/hooks/useConnect/__test__/setupConnection.spec.ts
src/lib/hooks/useConnect/setupConnection.ts

Fixes https://sendbird.atlassian.net/browse/SBISSUE-17702
- Fix Object.assign order to allow proper parameter override
- Add test case to verify localCacheEnabled override

[CLNP-5591] Allow localCacheEnabled override through sdkInitParams

---

src/modules/ChannelSettings/components/ChannelSettingsUI/channel-settings-ui.scss
src/modules/ChannelSettings/components/ModerationPanel/MemberList.tsx
src/ui/MessageInput/index.scss

[CLNP-5910](https://sendbird.atlassian.net/browse/CLNP-5910)
[CLNP-5909](https://sendbird.atlassian.net/browse/CLNP-5909)
* fixed broken UI on message input & channel settings operator menu
[CLNP-5910]: https://sendbird.atlassian.net/browse/CLNP-5910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CLNP-5909]: https://sendbird.atlassian.net/browse/CLNP-5909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [main branch] Broken UI - message input & settings menu

---

src/lib/Sendbird/context/SendbirdProvider.tsx

Used `useDeepCompareEffect` for the `updateState` of `SendbirdProvider`

Used useDeepCompareEffect for the updateState of SendbirdProvider

---

src/modules/GroupChannel/context/GroupChannelProvider.tsx
src/modules/GroupChannel/context/__tests__/GroupChannelProvider.spec.tsx
src/modules/GroupChannel/context/__tests__/useGroupChannel.spec.tsx

Fixes https://sendbird.atlassian.net/browse/CLNP-5981 and applied the same approach in https://github.com/sendbird/sendbird-uikit-react/pull/1272

[CLNP-5981] fix blinking GroupChannel on switching to another

---

.storybook/manager.ts
package.json
yarn.lock

[CLNP-5229](https://sendbird.atlassian.net/browse/CLNP-5229)
* Set the `panelPosition` of storybook controls to `right`
[CLNP-5229]: https://sendbird.atlassian.net/browse/CLNP-5229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Set panelPosition of storybook controls to right

---

src/modules/GroupChannel/context/GroupChannelProvider.tsx
src/modules/GroupChannel/context/hooks/useMessageActions.ts

[CLNP-5921](https://sendbird.atlassian.net/browse/CLNP-5921)
* Fixed an issue where editing a text parent message in a channel did not update the corresponding parent message in the Thread area in real-time.
[CLNP-5921]: https://sendbird.atlassian.net/browse/CLNP-5921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CLNP-5921] Sync thread message with groupchannel message update

---

rollup.config.mjs
src/hooks/useConnectionState.ts

* added optional chaining & useEffect to the useConnectionHandler

fix: Improve the useConnectionState hook

---

samples/README.md

[SBTW-2122](https://sendbird.atlassian.net/browse/SBTW-2122)
Add a Table of Contents (ToC) and Quick Links to the sample project markdown file.
[SBTW-2122]: https://sendbird.atlassian.net/browse/SBTW-2122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SBTW-2122] Add ToC into sample README.md

---

src/modules/OpenChannel/components/OpenChannelMessage/index.tsx
src/modules/OpenChannel/components/OpenChannelMessage/open-channel-message.scss
src/ui/OpenchannelFileMessage/__tests__/__snapshots__/OpenchannelFileMessage.spec.js.snap
src/ui/OpenchannelFileMessage/index.scss
src/ui/OpenchannelFileMessage/index.tsx
src/ui/OpenchannelOGMessage/index.scss

[CLNP-6094](https://sendbird.atlassian.net/browse/CLNP-6094)
* Fixed the min-width of the messages in open channel
[CLNP-6094]: https://sendbird.atlassian.net/browse/CLNP-6094?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: modified message width in open channel

---

CHANGELOG.md
package.json

- Added React 19 compatibility
- Added `messageSearchQuery.keyword` when searching in MessageSearch module
- `searchString` now takes higher priority, while `messageSearchQuery.keyword` is assigned secondary priority.
- Fixed the width of the messages in open channel

release: v3.15.13

---

package.json
src/lib/Sendbird/__tests__/useSendbird.spec.tsx
src/lib/Sendbird/context/hooks/useSendbird.tsx
src/modules/Thread/components/ParentMessageInfo/ParentMessageInfoItem.tsx
yarn.lock

Fixes [CLNP-6305](https://sendbird.atlassian.net/browse/CLNP-6305)
[CLNP-6305]: https://sendbird.atlassian.net/browse/CLNP-6305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CLNP-6305] Stabilization bug-fix

---

src/modules/ChannelSettings/context/index.tsx
src/modules/GroupChannel/context/index.tsx

[SBISSUE-18664](https://sendbird.atlassian.net/browse/SBISSUE-18664)
* Fixed the missing type export
[SBISSUE-18664]: https://sendbird.atlassian.net/browse/SBISSUE-18664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SBISSUE-18664]Fix the missing type export

---

src/modules/GroupChannel/__test__/MessageList.integration.test.tsx
src/modules/GroupChannel/context/GroupChannelProvider.tsx

[SBISSUE-18723](https://sendbird.atlassian.net/browse/SBISSUE-18723)
* Fix undefined error in MessageList.
[SBISSUE-18723]: https://sendbird.atlassian.net/browse/SBISSUE-18723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SBISSUE-18723] Fix undefined error in MessageList

---

CHANGELOG.md
package.json

- Fixed an unexpected error in `MessageList`

release: v3.16.1

---

src/lib/Sendbird/context/SendbirdContext.tsx

* Changelog
* Fix minor typo in comment

Fix minor typo in comment

---

src/modules/GroupChannel/context/GroupChannelProvider.tsx
src/modules/GroupChannel/context/__tests__/useGroupChannel.spec.tsx
src/modules/GroupChannel/context/hooks/useGroupChannel.ts

Fixes [CLNP-6698](https://sendbird.atlassian.net/browse/CLNP-6698)
- Fixed a bug that `GroupChannelProvider` with `startingPoint` throws an error
[CLNP-6698]: https://sendbird.atlassian.net/browse/CLNP-6698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CLNP-6698] resetWithStartingPoint not defined error

---

src/modules/Channel/context/ChannelProvider.tsx
src/modules/Channel/context/dux/__tests__/reducers.spec.js
src/modules/Channel/context/dux/data.mock.js
src/modules/Channel/context/dux/initialState.ts
src/modules/Channel/context/dux/reducers.ts
src/modules/Channel/context/utils.ts
src/modules/OpenChannel/context/utils.ts
src/modules/Thread/context/utils.ts
src/ui/MentionUserLabel/__tests__/renderToString.spec.js

[fix]: Fix rules of hook violation
Channel 컴포넌트의 Rules of React hook violation에 대한 케이스를 해결하는 PR입니다.
Fixes [CLNP-6835](https://sendbird.atlassian.net/browse/CLNP-6835)
- Fixed a bug that violates the rules of React hook in `Channel` component …

[CLNP-6835] Fix rules of hook violation

---

src/modules/GroupChannel/components/Message/MessageView.tsx
src/modules/GroupChannel/components/MessageList/getMessagePartsInfo.ts
src/modules/GroupChannel/components/MessageList/index.tsx
src/modules/GroupChannel/components/UnreadCountFloatingButton/index.tsx
src/modules/GroupChannel/context/GroupChannelProvider.tsx
src/modules/GroupChannel/context/hooks/useGroupChannel.ts
src/modules/GroupChannel/context/hooks/useMessageActions.ts
src/modules/GroupChannel/context/types.ts
src/ui/NewMessageSeparator/index.tsx

```
Fixes [<TICKET_ID>](https://sendbird.atlassian.net/browse/<TICKET_ID>)
// Changelogs (Recommended)
// Add (internal) at the end of …
```

Fixed QA Issue
