sendbird/sendbird-uikit-react

.gitignore
src/smart-components/App/stories/index.stories.js
src/smart-components/ChannelList/dux/__tests__/reducers.spec.js
src/smart-components/ChannelList/dux/data.mock.js
src/smart-components/ChannelList/dux/reducers.js
src/smart-components/Conversation/dux/__tests__/reducers.spec.js
src/smart-components/Conversation/dux/data.mock.js
src/smart-components/Conversation/dux/reducers.js
src/utils/__tests__/utils.spec.js
src/utils/index.ts

[UK-860](https://sendbird.atlassian.net/browse/UK-860)
- Do not check readMessageCount condition when channelListQuery exist
- Fix issue in CREATE_CHANNEL / create channel because of object destruction in reducers
- Fix messageId comparison in on message updated
- Fix binarySearch when targetIndex is 0 before it pushes the target item to the second position
- Add tests for events filter
Add tests

[UK-860] Fix issues of event filter and Add tests

---

src/ui/Label/stringSet.js

[UK-972](https://sendbird.atlassian.net/browse/UK-972)
Get back the string set legacy for message menus of open channel

[UK-972] Get back the string set legacy

---

CHANGELOG.md

- Bugfix
* Use OpenChannel in the getOpenChannelDeleteMessage
* Do not try to reconnect when current channel is not selected
* Do not update user info when nickname or profil url are empty string
* Update latest message value on channelListItem only if the latest message is edited
* Add string set for hardcorded strings that are used in the selecting channel type modal
* String set update

[2.4.3] (Nov 1 2021)

---

src/index.d.ts
src/smart-components/App/stories/index.stories.js
src/ui/MessageContent/__tests__/MessageContent.spec.js
src/ui/MessageContent/__tests__/__snapshots__/MessageContent.spec.js.snap
src/ui/MessageContent/index.scss
src/ui/MessageContent/index.tsx
src/ui/MessageInput/index.jsx
src/ui/OGMessageItemBody/__tests__/__snapshots__/OGMessageItemBody.spec.js.snap
src/ui/OGMessageItemBody/index.scss
src/ui/OGMessageItemBody/index.tsx
src/ui/TextMessageItemBody/__tests__/TextMessageItemBody.spec.js
src/ui/TextMessageItemBody/__tests__/__snapshots__/TextMessageItemBody.spec.js.snap
src/ui/TextMessageItemBody/index.scss
src/ui/TextMessageItemBody/index.tsx

[QU-390](https://sendbird.atlassian.net/browse/QU-390)
- Move the location of message status and timestamp into the message content
- Use paragraph tag in the Text message and OG message contents and set their word-break property to break-word
- Add type definition with `replyType` to the App and Channel components props

[QU-390] Sequel patch for message threading

---

CHANGELOG.md

* Implement experimentalMessageLimit for openChannel
This feature limits the no.of messages that are stored in
OpenChannel. This is intended for live streaming, where multiple
thousands of messages are expected to flow
Recommend a limit higher than 150 and less than 500
Usage:
```
<OpenChannel experimentalMessageLimit={number} />
```
Fixes:
* Fix time stamp position on message threading
* Add quote message to onBeforeSendFileMessage params

[CHANGELOG]Release 2.5.2.alpha.0

---

src/index.d.ts
src/smart-components/App/stories/index.stories.js
src/smart-components/Conversation/components/ConversationScroll.jsx
src/smart-components/Conversation/components/MessageHOC.jsx
src/smart-components/Conversation/components/conversation-scroll.scss
src/smart-components/Conversation/utils.js
src/ui/MessageItemMenu/index.tsx

[UIKIT-638](https://sendbird.atlassian.net/browse/UIKIT-638)
- Fix scroll to bottom issue
- Add type definition for quotedMessage in Channel component props

Fix scroll to bottom issue

---

src/lib/dux/sdk/thunks.js
src/smart-components/App/stories/index.stories.js

[UIKIT-1453](https://sendbird.atlassian.net/browse/UIKIT-1453)
[UIKIT-1453] Do not call updateUserInfo when nickname and profileUrl are empty string
[UIKIT-1453]: https://sendbird.atlassian.net/browse/UIKIT-1453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UIKIT-1453] Do not call updateUserInfo when nickname and profileUrl are empty string

---

src/lib/dux/sdk/thunks.js
src/utils/index.ts

[SBISSUE-5795](https://sendbird.atlassian.net/browse/SBISSUE-5795)

[SBISSUE-5795] Check if nickname and profileUrl are null or empty string

---

src/smart-components/App/stories/index.stories.js
src/smart-components/Conversation/components/ConversationScroll.jsx
src/ui/ContextMenu/index.scss
src/ui/ContextMenu/items/EmojiListItems.jsx
src/ui/ContextMenu/items/MenuItems.jsx
src/ui/Modal/index.jsx
src/ui/Modal/index.scss

[UIKIT-1461](https://sendbird.atlassian.net/browse/UIKIT-1461)
[UIKIT-1467](https://sendbird.atlassian.net/browse/UIKIT-1467)
* Block scrolling of body tag when pop-up components appear
* Prevent unexpected scrolling when fetching messages
* Add sample case for when chat app is smaller than page size

Fix: fix event leakage issues

---

src/legacy/message-refactor/FileMessage/index.jsx
src/ui/MessageStatus/index.jsx

localization parameter was not passed correctly to some
date-fn calls. Which caused some strings to be still in English
Refs:
* https://sendbird.atlassian.net/browse/UIKIT-1536
* https://sendbird.atlassian.net/browse/SBISSUE-7849

fix: localization parameter for some format calls

---

src/ui/ChannelPreview/utils.js
src/ui/MessageSearchFileItem/utils.ts
src/ui/MessageSearchItem/getCreatedAt.ts

no ticket
* Exclude the optional param when locale is undefined in the dateFns utils

Fix: [v2] Exclude the optional param when locale is undefined in the dateFns utils

---

src/ui/MessageStatus/index.scss

[UIKIT-1577](https://sendbird.atlassian.net/browse/UIKIT-1577)
* Fix the issue that inline-flex causes disappearing component in Safari

Fix: [v2] Appear MessageStatus component in Safari

---

src/ui/MessageStatus/__tests__/__snapshots__/MessageStatus.spec.js.snap
src/ui/MessageStatus/index.jsx
src/ui/MessageStatus/index.scss

[UIKIT-1577](https://sendbird.atlassian.net/browse/UIKIT-1577)
* Hide message status component using CSS instead of flag

Fix: [v3] Appear MessageStatus in Safari

---

rollup.config.js

This change was added during the rollup script
This is to reduce scope of the change

Hotfix - donot use exports: 'named'

---

src/index.d.ts
src/lib/LocalizationContext.tsx
src/lib/Sendbird.jsx
src/smart-components/App/index.jsx
src/smart-components/App/stories/index.stories.js
src/smart-components/App/types.tsx
src/smart-components/Channel/components/ChannelHeader/utils.ts
src/smart-components/Channel/components/Message/index.tsx
src/smart-components/ChannelList/components/ChannelPreview/index.tsx
src/smart-components/ChannelList/components/ChannelPreview/utils.js
src/smart-components/OpenChannel/components/OpenChannelMessage/index.tsx
src/ui/ChannelPreview/index.jsx
src/ui/ChannelPreview/utils.js
src/ui/MessageContent/index.tsx
src/ui/MessageSearchFileItem/index.tsx
src/ui/MessageSearchFileItem/utils.ts
src/ui/MessageSearchItem/getCreatedAt.ts
src/ui/MessageSearchItem/index.tsx
src/ui/MessageStatus/index.tsx
src/ui/OpenchannelFileMessage/index.tsx
src/ui/OpenchannelOGMessage/index.tsx
src/ui/OpenchannelThumbnailMessage/index.tsx
src/ui/OpenchannelUserMessage/index.tsx
src/utils/index.ts
src/utils/utils.js

Date can be localized using date-fns/locale
Example:
```
import kr from 'date-fns/locale/ko';
import {App} from 'sendbird-uikit';
<App appId="" userId="" dateLocale={kr}/>
```
[UIKIT-576](https://sendbird.atlassian.net/browse/UIKIT-576)

Feature - Setup date localization 

---

samples/groupchannel/package-lock.json
samples/groupchannel/package.json
samples/groupchannel/src/App.js
samples/groupchannel/src/CustomizedApp.js
scripts/README.md
scripts/package.template.json

Samples should point to v3 package, also modify some imports

chore: Update sample for v3

---

src/index.d.ts
src/lib/Sendbird.jsx
src/lib/SendbirdState.tsx
src/lib/types.ts
src/smart-components/App/index.jsx
src/smart-components/App/stories/index.stories.js
src/smart-components/App/types.ts
src/smart-components/Channel/components/TypingIndicator.tsx
src/smart-components/ChannelList/components/ChannelListUI/index.tsx
src/smart-components/ChannelList/components/ChannelPreview/channel-preview.scss
src/smart-components/ChannelList/components/ChannelPreview/index.tsx
src/smart-components/ChannelList/context/ChannelListProvider.tsx
src/smart-components/ChannelList/index.tsx
src/ui/MessageStatus/index.scss
src/ui/MessageStatus/stories/MessageStatus.stories.js

[UIKIT-1645](https://sendbird.atlassian.net/browse/UIKIT-1645)
[Development docs](https://sendbird.atlassian.net/wiki/spaces/UK/pages/1769603225/Typing+indicators+Delivery+Read+receipts+in+Channel+list)
App & SendbirdProvider
* Add props
* isTypingIndicatorEnabledOnChannelList
* isMessageReceiptStatusEnabledOnChannelList
Channel List
* Add props
* isTypingIndicatorEnabled
* isMessageReceiptStatusEnabled
* Add typing indicator into the Channel Preview component
* Add message status into the Channel Preview component

Add typing indicator and message status into the channel preview

---

README.md

fixes: https://sendbird.atlassian.net/browse/UIKIT-1717

doc: add fix for webpack 5 breaking change

---

rollup.config.js
scripts/steps.md

doc/chore: No need to copy CSS separately

---

src/smart-components/Channel/components/Message/index.tsx
src/smart-components/Channel/components/MessageInput/index.tsx
src/smart-components/Channel/components/SuggestedMentionList/index.tsx
src/smart-components/ChannelList/components/ChannelPreview/index.tsx
src/ui/ChannelAvatar/utils.ts
src/ui/ChannelPreview/index.jsx
src/ui/MentionLabel/index.tsx
src/ui/MessageContent/index.tsx
src/ui/UnknownMessageItemBody/index.tsx
src/ui/Word/index.tsx
src/utils/index.ts

[QM-1547](https://sendbird.atlassian.net/browse/QM-1547)
[QM-1552](https://sendbird.atlassian.net/browse/QM-1552)
[QM-1553](https://sendbird.atlassian.net/browse/QM-1553)
* QM-1547
* Keep the maximum suggestion count even current user is included in the fetch
* QM-1552
* Differentiate getting nickname and userId from stringObj
* Fetch the `User` using userId instead of the nickname
* Display mention text using the nickname
* QM-1553
* Enable sending 1:1 message on the user profile of the user mentioned text
So the nickname could be changed, but userId is unchangeable

Bugfix [v3] QM-1547_Keep suggested mention max count

---

src/ui/OpenchannelFileMessage/index.scss

[QM-1575](https://sendbird.atlassian.net/browse/QM-1575)
* Apply `white-space: nowrap` to the name text on fileMessage in OpenChannel

Fix [v3] Fix the name text on FileMessage of OpenChannel

---

src/ui/MessageStatus/__tests__/__snapshots__/MessageStatus.spec.js.snap
src/ui/MessageStatus/index.tsx

[QM-1635](https://sendbird.atlassian.net/browse/QM-1635)
* Change the message status appearing condition
* to display it when (the sending status is 'pending' or 'failed' in the special group channels)
* special group channels: super, broadcast, public

Fix: [v3] Display pending and failed status in the special group channels

---

CHANGELOG.md
package-lock.json
package.json
scripts/package.template.json
scripts/steps.md

Features:
* Support `modules` and `components` in the UIKit
* Upgraded to `@sendbird/chat@4`
* Support react 18
* See the Migration Guide for Converting V2 to V3. [[details](./MIGRATION_v2-to-v3.md)]
* See more details and breaking changes. [[details](./CHANGELOG.md)]

Release: [v3.0.0] (July 12 2022)

---

scripts/index_d_ts
src/index.d.ts
src/lib/Sendbird.jsx
src/lib/dux/sdk/thunks.js
src/smart-components/App/index.jsx
src/smart-components/App/types.ts

Accept customApiHost & customWebSocketHost on SendbirdProvider and App
These urls let the SDK to connect to custom domains
fixes: https://sendbird.atlassian.net/browse/UIKIT-1853

feat: accept customApiHost & customWebSocketHost

---

scripts/index_d_ts
src/index.d.ts
src/lib/SendbirdState.tsx
src/smart-components/ChannelSettings/components/ModerationPanel/InviteUsersModal.tsx
src/smart-components/CreateChannel/components/CreateChannelUI/index.tsx
src/smart-components/CreateChannel/components/InviteUsers/index.tsx
src/smart-components/CreateChannel/context/CreateChannelProvider.tsx
src/types.d.ts

[UIKIT-1920](https://sendbird.atlassian.net/browse/UIKIT-1920)
Use userListQuery when it's been given

fix: Apply userListQuery

---

package.json
rollup.config.js
scripts/package.template.json
scripts/steps.md

ESM library should have "type": "module" (package.json file that is going to /dist)
This fixes Cannot use import outside module issue in next.js
fixes: https://sendbird.atlassian.net/browse/UIKIT-1980

fix: Set package.json type as module

---

src/lib/dux/sdk/thunks.js

Connection cannot be established with no error message when customApiHost and customWebSocketHost
were passed as empty string

fix: cannot connect sometimes when customApiHost is empty (#231)

---

scripts/index_d_ts

To solve - cannot be used as a value when imports using the `import type` declaration

hotfix: remove type from handler type import

---

CHANGELOG.md
package-lock.json
package.json

Features:
* Add channel handlers to the open channel settings
* Add an open channel handler into the OpenChannelSettings component
* Use operators property to render operator list on the OpenChannelSetting
instead of fetching operators
* Export handlers through `@sendbird/uikit-react/handlers`, this is a workaround
to fix an issue where inhertiance chains break custom handler implementation
* ConnectionHandler -> `@sendbird/uikit-react/handlers/ConnectionHandler`
* GroupChannelHandler -> `@sendbird/uikit-react/handlers/GroupChannelHandler`
* OpenChannelHandler -> `@sendbird/uikit-react/handlers/OpenChannelHandler`
* UserEventHandler -> `@sendbird/uikit-react/handlers/UserEventHandler`
* Example: https://codesandbox.io/s/test-3-1-1-rc-5-f94w7i
Fixes:
* Update SendableMessage to UserMessage …

[v3.1.1] (Aug 17 2022)

---

src/smart-components/Channel/context/ChannelProvider.tsx
src/smart-components/OpenChannel/context/OpenChannelProvider.tsx

[UIKIT-2079](https://sendbird.atlassian.net/browse/UIKIT-2079)
* Set the default value of isMessageGroupingEnabled props to true in the Channel and OpenChannel

fix: set default of isMessageGroupingEnabled to true

---

CHANGELOG_v2.md
MIGRATION_v2-to-v3.md
scripts/index_d_ts
src/index.d.ts
src/lib/LocalizationContext.tsx
src/lib/SendbirdState.tsx
src/lib/types.ts
src/smart-components/App/types.ts
src/smart-components/Channel/components/ChannelUI/index.tsx
src/smart-components/Channel/context/ChannelProvider.tsx
src/smart-components/ChannelList/components/ChannelListHeader/index.tsx
src/smart-components/ChannelList/components/ChannelListUI/index.tsx
src/smart-components/ChannelList/components/ChannelPreview/index.tsx
src/smart-components/ChannelList/context/ChannelListProvider.tsx
src/smart-components/ChannelSettings/components/ChannelSettingsUI/index.tsx
src/smart-components/ChannelSettings/context/ChannelSettingsProvider.tsx
src/smart-components/CreateChannel/components/CreateChannelUI/index.tsx
src/smart-components/CreateChannel/context/CreateChannelProvider.tsx
src/smart-components/EditUserProfile/context/EditUserProfIleProvider.tsx
src/smart-components/MessageSearch/components/MessageSearchUI/index.tsx
src/smart-components/MessageSearch/context/MessageSearchProvider.tsx
src/smart-components/MessageSearch/context/hooks/useGetSearchedMessages.ts
src/smart-components/OpenChannel/context/OpenChannelProvider.tsx
src/smart-components/OpenChannelSettings/components/OpenChannelSettingsUI/index.tsx
src/smart-components/OpenChannelSettings/components/OperatorUI/index.tsx
src/smart-components/OpenChannelSettings/context/OpenChannelSettingsProvider.tsx
src/ui/LegacyEditUserProfile/index.tsx

[UIKIT-2053](https://sendbird.atlassian.net/browse/UIKIT-2053)
* Change every `React.ReactNode` and `React.Component` to `React.ReactElement`
* Use the type of SendbirdError
* Use the type MessageSearchQueryParams
* Use enum MessageSearchOrder.TIMESTAMP in the message search query params instead of `'ts' as const`
**ReactNode** could be `string | number | null | undefined | ReactElement | portal` and this(expecting string or number) causes **warning** when we use it like `<CustomComp />`
```typescript
// in the component
{ renderMessage } = props
const CustomMessage = useMemo(() => {
return renderMessage({ ... });
}, []);
return (
<div>
<CustomMessage />
</div>
);
```
so expecting **ReactElement** is better for our case
Put …

fix: Change type of react elements

---

src/smart-components/MessageSearch/context/hooks/useGetSearchedMessages.ts

MessageSearchOrder is an enum, which cannot be imported from
`@sendbird/chat/lib/__definition`
Todo: tell chat team to export it through @sendbird/chat

fix: Declare MessageSearchOrder in MessageSearch

---

CHANGELOG.md
package-lock.json
package.json

Migrate UI components into TypeScript
This doesnt affect anyone, it a step in task to migrate the project source code into TS
Fixes:
* Type defn: Change type of react elements to `React.ReactElement`
* Change every `React.ReactNode` and `React.Component` to `React.ReactElement`
* Use the type of SendbirdError
* Use the type MessageSearchQueryParams
* Use enum MessageSearchOrder.TIMESTAMP in the message search query params instead of `'ts' as const`
**ReactNode** could be `string | number | null | undefined | ReactElement | portal` and this(expecting string or number) causes **warning** when we use it like `<CustomComp />`
```typescript
// in the component
{ renderMessage } = props
const CustomMessage = useMemo(() => {
return renderMessage({ ... });
}, []);
return (
<div>
<CustomMessage /> …
```

[v3.1.2] (Aug 31 2022)

---

scripts/index_d_ts
src/lib/Sendbird.jsx
src/lib/__experimental__typography.scss
src/smart-components/App/index.jsx
src/smart-components/App/stories/index.stories.js
src/smart-components/MessageSearch/index.scss
src/types.d.ts
src/ui/MessageInput/index.jsx

Rem is better unit for accessibility support/mobile
So, we are adding rem as unit for typography/font size
We expect font-size 16px as base font-size, but to avoid breaking change,
customers should pass `config.isREMUnitEnabled` prop to `SendbirdProvider` to use "rem" units
ticket: https://sendbird.atlassian.net/browse/UIKIT-2176

feat: allow customers to use rem units for typography

---

src/lib/dux/sdk/thunks.js

Before: setSessionHandler was called when `accessToken` was null

fix: sessionHandler should be added with configureSession #293

---

scripts/index_d_ts
src/index.d.ts
src/smart-components/Channel/context/ChannelProvider.tsx
src/ui/FileMessageItemBody/__tests__/FileMessageItemBody.spec.js
src/ui/FileMessageItemBody/__tests__/__snapshots__/FileMessageItemBody.spec.js.snap
src/ui/FileMessageItemBody/index.tsx
src/ui/MessageContent/index.tsx
src/ui/OGMessageItemBody/index.tsx
src/ui/TextMessageItemBody/__tests__/TextMessageItemBody.spec.js
src/ui/TextMessageItemBody/__tests__/__snapshots__/TextMessageItemBody.spec.js.snap
src/ui/TextMessageItemBody/index.tsx
src/ui/ThumbnailMessageItemBody/__tests__/__snapshots__/ThumbnailMessageItemBody.spec.js.snap
src/ui/ThumbnailMessageItemBody/index.tsx
src/ui/UnknownMessageItemBody/__tests__/UnknownMessageItemBody.spec.js
src/ui/UnknownMessageItemBody/__tests__/__snapshots__/UnknownMessageItemBody.spec.js.snap
src/ui/UnknownMessageItemBody/index.tsx

Make the border of each message roundly when `isReactionEnabled` is true
* Apply `isReactionEnabled` props to each message item body component
* Text, File, Thumbnail, OG, Unknown

fix: Set border radius of message by is reaction enabled

---

src/smart-components/ChannelSettings/components/ModerationPanel/MemberList.tsx
src/smart-components/ChannelSettings/components/UserListItem/index.tsx
src/ui/UserListItem/index.scss

* Display menu only for operators on the participant list
* <img width="320" alt="image" src="https://user-images.githubusercontent.com/46333979/190959688-0e91976f-88e9-4f65-8594-624e2267ec9c.png">
* Hide muted icon when pop-up component is appeard
* <img width="273" alt="image" src="https://user-images.githubusercontent.com/46333979/190959850-03d3e850-27a0-4c3c-8760-957fc66b7c06.png">

fix: Do not show menu for non-admin user(ChannelSettings)

---

CHANGELOG.md
package-lock.json
package.json

[v3.1.3] (Sep 18 2022)
Features:
* Export SessionHandler through `@sendbird/uikit-react/handlers/SessionHandler`
* This is a workaround to fix an issue where inhertiance chains break custom handler implementation
* `import SessionHandler from '@sendbird/uikit-react/handlers/SessionHandler'`
* Rem units can be used for typography
* Pass prop `config.isREMUnitEnabled` -> true on SendbirdProvider
to use "rem" units
* We are adding rem as unit for typography/font size
Fixes:
* Fix the position of ContextMenu
* Do not exit the current open channel when the channel state is changed
* Display menu only for operators on the member list
* Hide muted icon when pop-up component is appeared
* Set message context's border roundly by the state using the reaction feature
* Add props `isReactionEnabled` …

release [v3.1.3] (Sep 16 2022)

---

scripts/index_d_ts
src/smart-components/Channel/components/MessageInput/index.tsx
src/smart-components/OpenChannel/components/OpenChannelInput/index.tsx
src/ui/MessageInput/index.jsx

Message wrappers get new prop `value`
through which we can set value from outside ~
value is reset when channelURL changes

feat: add prop?.value to MessageWrappers

---

src/ui/Tooltip/index.scss

[QM-1845](https://sendbird.atlassian.net/browse/QM-1845)
Apply the text-overflow ellipsis to the words of emoji tooltip

fix: Apply the text overflow ellipsis to the words of emoji tooltip

---

src/ui/Word/index.tsx

[QM-1844](https://sendbird.atlassian.net/browse/QM-1844)
* Word should return null when the received string is empty

fix: Return null when Word comp received empty string

---

src/smart-components/Channel/components/MessageInput/index.tsx

Fixes warning in which ref wasnt provided to forwardRef
if present, use the ref from component(MessageInputWrapper)
else use the one from context

fix: Use ref from MessageInputWrapper props if present

---

CHANGELOG.md
package-lock.json
package.json

Features:
* OpenChannelList component
* Create new smart components (modules)
* CreateOpenChannel
* OpenChannelList
* Add a renderHeader props into the ui/Modal component
* Add stringSet for OpenChannelLisit and CreateOpenChannel components
* OPEN_CHANNEL_LIST__TITLE: 'Channels',
* CREATE_OPEN_CHANNEL_LIST__TITLE: 'New channel profile',
* CREATE_OPEN_CHANNEL_LIST__SUBTITLE__IMG_SECTION: 'Channel image',
* CREATE_OPEN_CHANNEL_LIST__SUBTITLE__IMG_UPLOAD: 'Upload',
* CREATE_OPEN_CHANNEL_LIST__SUBTITLE__TEXT_SECTION: 'Channel name',
* CREATE_OPEN_CHANNEL_LIST__SUBTITLE__TEXT_PLACE_HOLDER: 'Enter channel name',
* CREATE_OPEN_CHANNEL_LIST__SUBMIT: 'Create',
* Add prop?.value to MessageWrappers
* @sendbird/uikit-react/Channel/components/MessageInput
* …

[v3.2.0] (Sep 27 2022)

---

rollup.config.js

Compiled UIKit code that is distributed through npm shouldnt have Chat SDK minified code included in it
Chat SDK should be a dependency of UIKit
Advantages:
* Chat SDK bug fixes will be added for free
* Eliminate the need for handlers
---
So what was the issue:
If you are usig rollup for bundling
in config.external you have to be specific
ie>
This works:
```
external: [
'@sendbird/chat',
'@sendbird/chat/groupChannel', 
'@sendbird/chat/openChannel', 
'@sendbird/chat/message',
]
```
This doesnt:
```
external: [ '@sendbird/chat', ]
```
fixes: https://sendbird.atlassian.net/browse/UIKIT-2274

fix: Donot bundle chat sdk with uikit compiled code

---

package-lock.json
package.json
scripts/package.template.json

For npm >= v7, npm autoinstall peerDependency packages
According to https://docs.npmjs.com/cli/v8/configuring-npm/package-json#peerdependencies You want to express the compatibility of your package with a host tiool or library while not necessarily doing a require of this host Even though react is required, its better to show that react is the host tool

fix: Only react and react-dom should be peerDependencies

---

CHANGELOG.md
package-lock.json
package.json

Fixes:
* Donot bundle chat sdk with uikit compiled code
Compiled UIKit code that is distributed through npm shouldnt have Chat SDK minified code included in it Chat SDK should be a dependency of UIKit
Advantages:
* Chat SDK bug fixes will be added for free
* Eliminate the need for handlers What caused the issue:
If you are usig rollup for bundling
in config.external you have to be specific
ie>
This works:
```
external: [
'@sendbird/chat',
'@sendbird/chat/groupChannel',
'@sendbird/chat/openChannel',
'@sendbird/chat/message',
]
```
This doesnt:
```
external: [ '@sendbird/chat', ]
```
* Only react and react-dom should be peerDependencies
For npm >= v7, npm autoinstall peerDependency packages According to https://docs.npmjs.com/cli/v8/configuring-npm/package-json#peerdependencies You want to …

[v3.2.1] (Oct 04 2022)

---

scripts/index_d_ts
src/index.d.ts
src/smart-components/Channel/components/ChannelUI/index.tsx
src/smart-components/Channel/components/MessageList/index.tsx
src/smart-components/Channel/context/ChannelProvider.tsx
src/smart-components/Channel/context/hooks/useGetChannel.js
src/smart-components/Channel/context/hooks/useHandleChannelEvents.ts
src/smart-components/Channel/context/hooks/useHandleReconnect.ts
src/smart-components/Channel/index.tsx

[UIKIT-2385](https://sendbird.atlassian.net/browse/UIKIT-2385)
* Add `disableMarkAsRead` to the Channel comp
* This prop disables calling `markAsRead` in the Channel component, so you can create 

feat: Add disableMarkAsRead to the Channel comp

---

scripts/index_d_ts
src/lib/MediaQueryContext.tsx
src/lib/Sendbird.jsx
src/smart-components/App/index.jsx

* Add props App?.mediaQueryBreakPoint, SendbirdProvider?.mediaQueryBreakPoint
* mediaQueryBreakPoint accepts a valid screensize in pixels, under which UIKit will work in mobile-mode
* Default is 768px
* Example: <App mediaQueryBreakPoint="568px" />
Internal:
* Implement MediaQueryProvider to manage mobile-mode
* Implement hook: const { mediaQueryBreakPoint, isMobile } = useMediaQueryContext();
* Add MOBILE_CLASSNAME = 'sendbird--mobile-mode'; to <body /> to identify mode
fixes: https://sendbird.atlassian.net/browse/UIKIT-2390

feat: implement MediaQueryProvider

---

src/hooks/useLongPress.tsx
src/lib/MediaQueryContext.tsx

Internal hook to handle longPresses
* Works only in mobile mode
* Can vibrate on longpress in few devices/browsers
https://caniuse.com/mdn-api_navigator_vibrate
Interface:
```
interface PressHandlers<T> {
onLongPress: (e: React.MouseEvent<T> | React.TouchEvent<T>) => void;
onClick?: (e: React.MouseEvent<T> | React.TouchEvent<T>) => void;
}
interface Options {
delay?: number; // threshold as described before
shouldPreventDefault?: boolean;
}
---
interface UseLongPressType<T> {
onMouseDown: (e: React.MouseEvent<T>) => void;
onTouchStart: (e: React.TouchEvent<T>) => void;
onMouseUp: (e: React.MouseEvent<T>) => void;
onMouseLeave: (e: React.MouseEvent<T>) => void;
onTouchEnd: (e: React.TouchEvent<T>) => void;
}
---
function useLongPress<T> (
pressHandlers: PressHandlers<T>,
Options: Options, …
```

feat: implement hooks/useLongPress

---

SAMPLES.md
scripts/index_d_ts
src/index.d.ts
src/lib/stories/index.stories.js
src/lib/types.ts

[UIKIT-2445](https://sendbird.atlassian.net/browse/UIKIT-2445)
* Modify ts interface in selectors
* getLeaveChannel to getLeaveGroupChannel
* https://sendbird.com/docs/uikit/v3/react/core-components/sendbirdselectors#1-sendbirdselectors

fix: Modify ts interface getLeaveChannel to getLeaveGroupChannel in selectors

---

scripts/index_d_ts
src/smart-components/Channel/components/ChannelUI/index.tsx
src/smart-components/Channel/context/dux/__tests__/reducers.spec.js
src/smart-components/Channel/context/dux/initialState.js
src/smart-components/Channel/index.tsx
src/smart-components/ChannelList/components/ChannelListUI/index.tsx
src/smart-components/ChannelList/dux/__tests__/reducers.spec.js
src/smart-components/ChannelList/dux/initialState.js

It is better to have seperate prop to show loader in channel,
becuase, other customers might have used empty/null to show invalid channel
and it would be a breaking change for them
Usage:
```
<Channel channelUrl={currentChannelUrl} isLoading={!currentChannelUrl} />
```## External Contributions

feat: add new props isLoading to ChannelUI

---

CHANGELOG.md
package-lock.json
package.json

Features:
* For Channel component, added separate prop isLoading?.boolean Usage: ```<Channel channelUrl {currentChannelUrl} isLoading={!currentChannelUrl} />```
* For flicker in ChannelList, without extra props
Fixes:
* React UIKit placeholder rendering issue
* Fix scroll issue in ChannelList where user cannot load more channels
* Modify TS interface getLeaveChannel to getLeaveGroupChannel in selectors

[v3.2.4] (Nov 1 2022)

---

scripts/index_d_ts
src/index.d.ts

[UIKIT-2445](https://sendbird.atlassian.net/browse/UIKIT-2445)
(TS) Change the parameter types of sendbird selector functions from `channel` to `channelUrl`
* getLeaveGroupChannel
* getEnterOpenChannel
* getExitOpenChannel

fix: Change the parameter types of sendbird selector functions

---

src/smart-components/Channel/context/ChannelProvider.tsx
src/smart-components/Channel/context/hooks/useHandleChannelEvents.ts
src/smart-components/Channel/context/hooks/useHandleReconnect.ts
src/smart-components/Channel/context/hooks/useInitialMessagesFetch.js
src/smart-components/Channel/context/hooks/useSendFileMessageCallback.js
src/smart-components/Channel/context/hooks/useSendMessageCallback.js
src/smart-components/Channel/context/utils.js
src/smart-components/OpenChannel/components/OpenChannelUI/index.tsx
src/smart-components/OpenChannel/context/OpenChannelProvider.tsx
src/smart-components/OpenChannel/context/hooks/useFileUploadCallback.ts
src/smart-components/OpenChannel/context/hooks/useHandleChannelEvents.ts
src/smart-components/OpenChannel/context/hooks/useInitialMessagesFetch.ts
src/smart-components/OpenChannel/context/hooks/useSendMessageCallback.ts
src/smart-components/OpenChannel/context/utils.ts
src/ui/MessageInput/index.jsx

QuerySelector is inaccurate when multiple channels are rendered parallel
This doesnt include root for dropdowns/fileviewer etc

fix: use ref instead of querySelector for DOM manipulation

---

src/smart-components/Channel/context/ChannelProvider.tsx
src/smart-components/Channel/context/hooks/useHandleChannelEvents.ts
src/smart-components/Channel/context/hooks/useHandleReconnect.ts
src/smart-components/Channel/context/hooks/useInitialMessagesFetch.js
src/smart-components/Channel/context/hooks/useSendFileMessageCallback.js
src/smart-components/Channel/context/hooks/useSendMessageCallback.js
src/smart-components/Channel/context/utils.js
src/smart-components/OpenChannel/components/OpenChannelUI/index.tsx
src/smart-components/OpenChannel/context/OpenChannelProvider.tsx
src/smart-components/OpenChannel/context/hooks/useFileUploadCallback.ts
src/smart-components/OpenChannel/context/hooks/useHandleChannelEvents.ts
src/smart-components/OpenChannel/context/hooks/useInitialMessagesFetch.ts
src/smart-components/OpenChannel/context/hooks/useSendMessageCallback.ts
src/smart-components/OpenChannel/context/utils.ts
src/ui/MessageInput/index.jsx

QuerySelector is inaccurate when multiple channels are rendered
parallel

fix: use ref instead of querySelector to target actions

---

CHANGELOG.md
package-lock.json
package.json

Fix:
* Use ref instead of querySelector for DOM manipulation
Fixes the issue where input is not cleared when multiple channels are open at the same time
* Apply pre-line into the OpenChannelUserMessage
Fixes the issue where OpenChannel UserMessage doesnt have new line

[v3.2.6] (Nov 14 2022)

---

CHANGELOG.md
package-lock.json
package.json
scripts/index_d_ts
src/smart-components/Channel/context/ChannelProvider.tsx

[v3.3.0] (Nov 23 2022)
Features:
* Provide new module `Thread`. See the specific informations of this module on the [Docs page](https://sendbird.com/docs/uikit)
* You can use a combined component `Thread`. Import it with
```typescript
import Thread from "@sendbird/uikit-react/Thread"
```
* Also you can use `ThreadProvider` and `useThreadContext` for customization. Import it with
```typescript
import { ThreadProvider, useThreadContext } from "@sendbird/uikit-react/Thread/context"
```
* And the other UI components are provided under the Thread. `ThreadUI`, `ThreadHeader`, `ParentMessageInfo`, `ParentMessageInfoItem`, `ThreadList`, `ThreadListItem`, and `ThreadMessageInput` are it
* Add channel props
* `threadReplySelectType`: Type of the value should be
```typescript
enum …
```

Release v3.3.0

---

CHANGELOG.md
package-lock.json
package.json
scripts/index_d_ts
src/smart-components/ChannelSettings/components/ModerationPanel/MembersModal.tsx
src/smart-components/ChannelSettings/components/ModerationPanel/MutedMembersModal.tsx
src/smart-components/ChannelSettings/components/ModerationPanel/OperatorsModal.tsx
src/smart-components/Thread/components/ThreadList/ThreadListItem.tsx
src/smart-components/Thread/components/ThreadUI/index.tsx
src/smart-components/Thread/components/ThreadUI/useMemorizedParentMessageInfo.tsx
src/smart-components/Thread/components/ThreadUI/useMemorizedThreadList.tsx
src/smart-components/Thread/context/ThreadProvider.tsx
src/smart-components/Thread/context/dux/initialState.ts
src/smart-components/Thread/context/dux/reducer.ts
src/smart-components/Thread/context/hooks/useGetNextThreadsCallback.ts
src/smart-components/Thread/context/hooks/useGetPrevThreadsCallback.ts
src/smart-components/Thread/types.tsx
src/ui/UserListItem/index.tsx

[v3.3.1] (Nov 23 2022)
Fixes:
* Rename properties of `useThreadContext`
* `channelStatus` to `channelState`
* `parentMessageInfoStatus` to `parentMessageState`
* `threadListStatus` to `threadListState`
* Change the state types to enum
```typescript
enum ChannelStateTypes {
NIL = 'NIL',
LOADING = 'LOADING',
INVALID = 'INVALID',
INITIALIZED = 'INITIALIZED',
}
enum ParentMessageStateTypes {
NIL = 'NIL',
LOADING = 'LOADING',
INVALID = 'INVALID',
INITIALIZED = 'INITIALIZED',
}
enum ThreadListStateTypes {
NIL = 'NIL',
LOADING = 'LOADING',
INVALID = 'INVALID',
INITIALIZED = 'INITIALIZED',
}
```

[v3.3.1] (Nov 23 2022)

---

scripts/index_d_ts
src/smart-components/Thread/components/ThreadUI/index.tsx

[UIKIT-2646](https://sendbird.atlassian.net/browse/UIKIT-2646)
renderMessage?: (props: { message: UserMessage | FileMessage }) => React.ReactElement;
renderMessage?: (props: {
message: UserMessage | FileMessage,
chainTop: boolean,
chainBottom: boolean,
hasSeparator: boolean,
}) => React.ReactElement;

fix: Add types for renderMessage of ThreadUI

---

src/smart-components/App/index.jsx
src/ui/UserProfile/index.tsx

use sendbird state to access currentUserID and use it incase prop value is empty
Also, remove legacy HOC pattern

fix: create channel sometimes had empty operatorID

---

src/lib/Sendbird.jsx
src/lib/hooks/useOnlineStatus.js

This feature was disabled because of a bug in sessionHandler in SDK now,
we can re-enable this
see: https://github.com/sendbird/sendbird-uikit-react/pull/307
fixes: https://sendbird.atlassian.net/browse/SBISSUE-10323

fix: onlinestatus should work even configureSession is provided

---

src/smart-components/Channel/components/MessageList/index.tsx
src/smart-components/Channel/context/hooks/useHandleChannelEvents.ts
src/ui/MessageStatus/index.tsx

[UIKIT-2686](https://sendbird.atlassian.net/browse/UIKIT-2686)
We have called `markAsRead` when a newly received message is inserted into the UI message list.
But the condition that calculates if the scroll reached the bottom was broken due to the fine pixel difference.
Add 10px as a buffer when calculating **if the scroll reached the bottom**

Fix: Mark as read definitely when receiving message

---

scripts/index_d_ts
src/smart-components/ChannelList/components/AddChannel/index.tsx
src/smart-components/ChannelList/context/ChannelListProvider.tsx
src/smart-components/ChannelList/index.tsx
src/smart-components/ChannelSettings/components/ModerationPanel/InviteUsersModal.tsx
src/smart-components/ChannelSettings/context/ChannelSettingsProvider.tsx
src/smart-components/ChannelSettings/index.tsx
src/smart-components/CreateChannel/components/InviteUsers/index.tsx
src/smart-components/CreateChannel/context/CreateChannelProvider.tsx
src/smart-components/CreateChannel/index.tsx

Add overrideInviteUser to ChannelList, CreateChannel and ChannelSettings
This interface overrides InviteMember functionality. Customer has to create the channel
and close the popup manually
```
export type OverrideInviteUserType = {
users: Array<string>;
onClose: () => void;
channelType: 'group' | 'supergroup' | 'broadcast';
};
ChannelList.overrideInviteUser?(params: OverrideInviteUserType): void;
CreateChannel.overrideInviteUser?(params: OverrideInviteUserType): void;
```
```
export type OverrideInviteMemberType = {
users: Array<string>;
onClose: () => void;
channel: GroupChannel;
};
ChannelSettings.overrideInviteUser?(params: OverrideInviteMemberType): void;
```
example: 
```
<ChannelList
overrideInviteUser={({users, onClose, channelType}) => {
createMyChannel(users, …
```

feat: add interface overrideInviteUser

---

src/smart-components/MessageSearch/context/hooks/useGetSearchedMessages.ts

[UIKIT-2666](https://sendbird.atlassian.net/browse/UIKIT-2666)
Couldn't search messages in multiple channels by using `messageSearchQuery`
Allow overriding entire message search query

fix: Allow overriding entire message search query

---

scripts/index_d_ts
src/index.d.ts
src/smart-components/ChannelList/components/ChannelListHeader/index.tsx
src/smart-components/ChannelList/components/ChannelListUI/index.tsx

[UIKIT-2654](https://sendbird.atlassian.net/browse/UIKIT-2654)
The create channel button range has been displayed even `renderHeader` props are set
Include the `create channel button & renderIconButton` into the `renderHeader and ChannelListHeader` range

fix: Include renderIconButton into the renderHeader range

---

scripts/index_d_ts
src/index.d.ts
src/smart-components/MessageSearch/context/MessageSearchProvider.tsx
src/smart-components/MessageSearch/context/hooks/useGetSearchedMessages.ts

[UIKIT-2666](https://sendbird.atlassian.net/browse/UIKIT-2666)
Set the type definition of messageSearchQuery to MessageSearchQueryParams

fix: Change the type definition of messageSearchQuery

---

CHANGELOG.md
package-lock.json
package.json

Fix:
* Change default value of the image compression rate to 70%(0.7)

Release v3.3.3

---

src/ui/MessageInput/index.jsx
src/ui/MessageInput/utils.js

[UIKIT-2807](https://sendbird.atlassian.net/browse/UIKIT-2807)
* Sanitize that special characters of HTML tags cause XSS issue
* ~~Create a util function to encode a string to HTML~~
* ~~Apply the encoding function when filling the message input value with text~~
[UIKIT-2807]: https://sendbird.atlassian.net/browse/UIKIT-2807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: Message input XSS

---

CHANGELOG.md
package-lock.json
package.json

[v3.3.4] (Jan 6 2023)
Fix:
* Add the time stamp rendering case for before this year on the ChannelList
* Improve the message input security
* Possibility of XSS has been discovered
* Recommend to do a version up, if you are using UIKit version 3.0.0 or higher

Release v3.3.4

---

src/smart-components/ChannelList/dux/__tests__/reducers.spec.js
src/smart-components/ChannelList/dux/reducers.js

[UIKIT-2790](https://sendbird.atlassian.net/browse/UIKIT-2790)
* Do not set the current channel with newly created channel
* when the current user receives the invitation from it
[UIKIT-2790]: https://sendbird.atlassian.net/browse/UIKIT-2790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: New channel interrupts the current conversation

---

src/smart-components/App/stories/integrated.stories.js
src/smart-components/ChannelSettings/components/ModerationPanel/AddOperatorsModal.tsx
src/smart-components/ChannelSettings/components/ModerationPanel/BannedUserList.tsx
src/smart-components/ChannelSettings/components/ModerationPanel/BannedUsersModal.tsx
src/smart-components/ChannelSettings/components/ModerationPanel/InviteUsersModal.tsx
src/smart-components/ChannelSettings/components/ModerationPanel/MutedMemberList.tsx
src/smart-components/ChannelSettings/components/ModerationPanel/MutedMembersModal.tsx
src/smart-components/OpenChannelApp/components/CommunityChannelList.tsx
src/smart-components/OpenChannelSettings/components/OperatorUI/AddOperatorsModal.tsx
src/ui/Label/stringSet.js
src/ui/Modal/index.scss

[UIKIT-2766](https://sendbird.atlassian.net/browse/UIKIT-2766)
* Add string set
* CHANNEL_SETTING__OPERATORS__ADD_BUTTON: 'Add'
* CHANNEL_SETTING__MODERATION__EMPTY_BAN: 'No banned members yet'
* CHANNEL_SETTING__MODERATION__ALL_BAN: 'All banned members'
* Apply string set
* on the BannedUserList component
* `No banned members yet`
* `All banned members`
* `Unban` on the context menu of the banned user list
* on the BannedUsersModal component
* `Unban` on the context menu of the banned user list
* on the AddOperatorsModal component
* `Add` for the submit button
* on the InviteUsersModal component
* `Invite` for the submit button
* on the MutedMembersModal component
* `Unmute` on the context menu of the muted user list
* Remove string set
* CHANNEL_SETTING__UNMUTE: 'Unmute'
* Replace the …

fix: Apply string set into the moderation section

---

src/ui/MessageContent/__tests__/__snapshots__/MessageContent.spec.js.snap
src/ui/OGMessageItemBody/index.scss
src/ui/OGMessageItemBody/index.tsx
src/ui/TextMessageItemBody/__tests__/__snapshots__/TextMessageItemBody.spec.js.snap
src/ui/TextMessageItemBody/index.tsx
src/ui/Word/index.scss

[UIKIT-2759](https://sendbird.atlassian.net/browse/UIKIT-2759)
* Use the same word-splitting logic on the TextMessage and OGMessage
* TextMessage will also allow opening the URL links
* Use the same word wrapping style on the TextMessage and OGMessage
[UIKIT-2759]: https://sendbird.atlassian.net/browse/UIKIT-2759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Use same word break and URL activation logic on messages

---

src/smart-components/App/stories/index.stories.js
src/smart-components/ChannelList/context/ChannelListProvider.tsx
src/smart-components/ChannelList/dux/__tests__/reducers.spec.js
src/utils/index.ts

[UIKIT-2789](https://sendbird.atlassian.net/browse/UIKIT-2789)
A customer said the `userIdsFilter` of ChannelListQuery doesn't work when receiving messages
There's been an internal channel filtering logic with custom channelListQuery, but it's broken because we've used the outdated interface of Chat SDK.
We migrated the outdated interface `_searchFilter` and `_userIdsFilter` to new things `searchFilter` and `userIdsFilter`
[UIKIT-2789]: https://sendbird.atlassian.net/browse/UIKIT-2789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Migrate the outdated ChannelListQuery interface

---

CHANGELOG.md
package-lock.json
package.json

Features:
* Voice Recorder&Player logic(not public yet)
* Add a voice record logic: VoiceRecorderProvider, useVoiceRecorderContext, useVoiceRecorder
* Add an audio play logic: VoicePlayerProvider, useVoicePlayerContext, useVoicePlayer
* Create an integrated sample for the group channel
Fix:
* Migrate the outdated ChannelListQuery interface
* Issue: A customer said the `userIdsFilter` of ChannelListQuery doesn't work when receiving messages There's been an internal channel filtering logic with custom channelListQuery, but it's broken because we've used the outdated interface of Chat SDK.
* Fix: We migrated the outdated interface `_searchFilter` and `_userIdsFilter` to new things `searchFilter` and `userIdsFilter
* Use the same word-splitting logic on the TextMessage and OGMessage
* …

Release: [v3.3.5] (Feb 3 2023)

---

src/ui/Checkbox/index.tsx

To remove warning:
A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component.

fix: Checkbox: set checked as false

---

package.json
scripts/index_d_ts
src/lib/types.ts
src/smart-components/Channel/components/ChannelUI/index.tsx
src/smart-components/Channel/components/MessageInput/index.tsx
src/smart-components/Channel/index.tsx
src/smart-components/Thread/components/ParentMessageInfo/index.tsx
src/smart-components/Thread/components/ThreadList/ThreadListItem.tsx
src/smart-components/Thread/components/ThreadMessageInput/index.tsx
src/smart-components/Thread/components/ThreadUI/index.tsx
src/smart-components/Thread/index.tsx
src/ui/MessageInput/index.jsx
src/ui/MessageItemMenu/index.tsx

Add props:
```
renderFileUploadIcon?: () =>  React.ReactElement;
renderVoiceMessageIcon?: () =>  React.ReactElement;
renderSendMessageIcon?: () =>  React.ReactElement;
```
To Channel & Thread
> Important: renderVoiceMessageIcon and renderSendMessageIcon only customizes IconUI
But, renderFileUploadIcon helps you customize/extend functionality
For example: it can be extended to open camera, open a new modal to drag and drop files, convert files before upload ~

feat: options to render icons on MessageInput

---

scripts/index_d_ts
src/smart-components/ChannelList/context/ChannelListProvider.tsx
src/smart-components/ChannelList/context/hooks/useActiveChannelUrl.ts
src/smart-components/ChannelList/index.tsx
src/smart-components/ChannelList/stories/index.stories.js
src/smart-components/ChannelList/utils.js

Add prop: activeChannelUrl 
activeChannelUrl gives customer an option to pragmatically set a channel from a parent component/ router
If channel is present in client side, it is used
If not present in client side, channel is fetched from backend and added to end of the list and set as selected
If not present, no errors will be thrown
If user clicks other channel, the item set from outside is removed and clicked channel will be selected 
If activeChannelUrl is present, ChannelList behaves similar to "disableAutoSelect" is true
example
```
const MyChat = () => {
const {my_active_channel} = useRouter();
return (
<ChannelList activeChannelUrl={my_active_channel} />
);
```
fixes: https://sendbird.atlassian.net/browse/UIKIT-3180

feat: add prop `activeChannelUrl` to ChannelList

---

src/smart-components/MessageSearch/context/hooks/useGetSearchedMessages.ts

[UIKIT-2979](https://sendbird.atlassian.net/browse/UIKIT-2979)
* If you set the `channel.invitedAt` with the other timestamp by force, you will get the message search list which is fetched from the timestamp
* Refresh the channel before fetching message search list, to get the real value of the channel property
[UIKIT-2979]: https://sendbird.atlassian.net/browse/UIKIT-2979?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Refresh channel before fetching message search list

---

src/smart-components/Channel/context/ChannelProvider.tsx
src/smart-components/Channel/context/__test__/utils.spec.js
src/smart-components/Channel/context/dux/__tests__/reducers.spec.js
src/smart-components/Channel/context/dux/data.mock.js
src/smart-components/Channel/context/dux/reducers.js
src/smart-components/Channel/context/hooks/useHandleChannelEvents.ts
src/smart-components/Channel/context/utils.js

We decided not to filter at event handler, instead we filter, clean at reducer
fixes: [UIKIT-2877](https://sendbird.atlassian.net/browse/UIKIT-2877)
[UIKIT-2877]: https://sendbird.atlassian.net/browse/UIKIT-2877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: fix not showing newly recived messages

---

CHANGELOG.md
package-lock.json
package.json

[SDKRLSD-690](https://sendbird.atlassian.net/browse/SDKRLSD-690)
[v3.3.7] (Feb 24 2023)
Features:
* Add props `activeChannelUrl` to ChannelList to give an option to pragmatically set a channel from a parent component router
```javascript
const MyChannelList = () => {
const [myActiveChannel] = useState()
return (<ChannelList activeChannelUrl={myActiveChannel.url} />)
}
```
Fixes:
* Fix not showing newly recived messages in channel which has less messages
* Use a real `channel.invitedAt` value when trying to fetch MessageSearchQuery
* Disable the checkbox of the joined users on the InviteUsersModal
* Set the default value of CheckBox component: `@sendbird/uikit-react/ui/CheckBox` as false …

Release v3.3.7

---

src/ui/OGMessageItemBody/__tests__/OGMessageItemBody.spec.js
src/ui/OGMessageItemBody/__tests__/__snapshots__/OGMessageItemBody.spec.js.snap
src/ui/OGMessageItemBody/index.tsx

Add classname: `sendbird-og-message-item-body__og-thumbnail__empty` to
identify faulty images in OG message
Clients can use CSS to target this class~
```
.sendbird-og-message-item-body__og-thumbnail__empty {
display: none;
}
```
fixes: https://sendbird.atlassian.net/browse/UIKIT-3304

fix: add classname for empty OG-image

---

src/smart-components/ChannelSettings/components/ModerationPanel/InviteUsersModal.tsx
src/smart-components/ChannelSettings/components/UserPanel/index.tsx
src/smart-components/ChannelSettings/components/UserPanel/user-panel.scss

* use applicationuserlistQuery from ChannelSetting
* some visual issues in User Panel

fix: use applicationuserlistQuery from ChannelSetting

---

src/smart-components/Channel/components/MessageInput/VoiceMessageInputWrapper.tsx

[QM-2595](https://sendbird.atlassian.net/browse/QM-2595)
* Use uuid for useVoicePlayer of VoiceMessageInput to divide each VoiceMessageInput comp
[QM-2595]: https://sendbird.atlassian.net/browse/QM-2595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Use uuid for useVoicePlayer of VoiceMessageInput

---

src/hooks/VoicePlayer/useVoicePlayer.tsx
src/ui/VoiceMessageInput/index.tsx
src/utils/consts.ts

[QM-2594](https://sendbird.atlassian.net/browse/QM-2594)
[QM-2601](https://sendbird.atlassian.net/browse/QM-2601)
* Apply throttling to the VoiceMessageInput component
* Do not pause voice player when empty useVoicePlayer is unmounted
[QM-2594]: https://sendbird.atlassian.net/browse/QM-2594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[QM-2601]: https://sendbird.atlassian.net/browse/QM-2601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Modify handling click event of VoiceMessageInput

---

scripts/index_d_ts
src/smart-components/Channel/components/ChannelHeader/index.tsx
src/smart-components/ChannelList/components/AddChannel/index.tsx
src/smart-components/ChannelList/components/ChannelListUI/index.tsx
src/smart-components/ChannelList/components/ChannelPreview/index.tsx
src/smart-components/OpenChannel/components/OpenChannelMessage/index.tsx
src/smart-components/Thread/components/ThreadList/ThreadListItemContent.tsx
src/ui/MessageContent/index.tsx
src/ui/MessageItemMenu/index.tsx
src/ui/OpenChannelMobileMenu/index.tsx
src/ui/OpenchannelFileMessage/index.tsx
src/ui/OpenchannelOGMessage/index.tsx
src/ui/OpenchannelThumbnailMessage/index.tsx
src/ui/OpenchannelUserMessage/index.tsx

[UIKIT-3245](https://sendbird.atlassian.net/browse/UIKIT-3245)
[Ephemeral channel support - policy](https://sendbird.atlassian.net/wiki/spaces/UK/pages/2027325814/Ephemeral+channel+support)
Ephemeral channel policy
* Group channel list
* Remove the message receipt status (channel preview)
* Remove the unread message count (channel preview)
* Group channel
* Remove the message edit
* Remove the message delete
* Remove the message reactions
* Remove the message receipt status (message)
* Remove the message reply (quote_reply, thread)
* Group channel settings
* Remove the search in channel
* Open channel
* Remove the message edit
* Remove the message delete
[UIKIT-3245]: …

fix: Operate ephemeral channel

---

src/smart-components/Channel/components/ChannelHeader/index.tsx
src/smart-components/Channel/components/ChannelUI/index.tsx
src/smart-components/Channel/components/FrozenNotification/index.tsx
src/smart-components/Channel/components/Message/index.tsx
src/smart-components/Channel/components/MessageList/__test__/getMessagePartsInfo.spec.js
src/smart-components/Channel/components/MessageList/getMessagePartsInfo.ts
src/smart-components/Channel/components/MessageList/index.tsx
src/smart-components/Channel/components/MessageList/message-list.scss
src/smart-components/Channel/components/UnreadCount/index.tsx
src/smart-components/Channel/components/UnreadCount/unread-count.scss
src/smart-components/Channel/context/const.ts
src/smart-components/Channel/context/hooks/useHandleChannelEvents.ts
src/ui/ContextMenu/index.tsx
src/utils/useDidMountEffect.ts

[UIKIT-2872](https://sendbird.atlassian.net/browse/UIKIT-2872)
* Refactor
* Replace `FrozenNotification`, `UnreadCount` (Also notification bar), and `LoadingPlaceHolder` into the `MessageList` component from `ChannelUI`
* Bugfix
* Do not `scrollIntoBottom` if the message is not reached the bottom
scrollIntoBottom is a function moving scroll when a new message is received
* Do not `handleScroll` when a message is initially mounted
handleScroll is a function moving scroll when the last message's layout is changed
[UIKIT-2872]: https://sendbird.atlassian.net/browse/UIKIT-2872?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Keep scroll if context menu is opened when receiving messages

---

src/utils/typeHelpers/objectValues.ts

Example:
```
const LOG_LEVEL = {
INFO: 'INFO',
WARN: 'WARN',
ERROR: 'ERROR',
} as const;
type logLevel = ObjectValues<typeof LOG_LEVEL>;
both of the below options are valid
const logLevel: logLevel = LOG_LEVEL.INFO;
const logLevel: logLevel = 'INFO';
```

feat: add ObjectValues helper

---

CHANGELOG.md
package-lock.json
package.json

Features:
* Mentions should be preserved when copy pasted from sendbird-messages and message input
* Make sure you are posting mentions of users from same channel
* We dont support pasting of rich text from other applications
* For copying simple text, we recommend using paste option in message context-menu
* Conditions tested:
1. paste simple text
2. paste text with mention
3. paste text with mention and text
4. paste text with mention and text and paste again before and after
5. copy message with mention(only one mention, no other text) and paste
6. copy message with mention from input and paste(before and after)
Chores:
* Arrange the order of the string set table Some string-set were missing on the current string set table, so our customers werent able to use the latest state of the …

[v3.4.1] (Mar 17 2023)

---

src/ui/MentionUserLabel/__tests__/__snapshots__/MentionUserLabel.spec.js.snap
src/ui/MentionUserLabel/__tests__/renderToString.spec.js
src/ui/MentionUserLabel/consts.ts
src/ui/MentionUserLabel/index.tsx
src/ui/MentionUserLabel/renderToString.ts
src/ui/MessageInput/hooks/usePaste/insertTemplate.ts
src/ui/MessageInput/hooks/usePaste/insertTemplate.tsx
src/ui/MessageInput/index.jsx

Replace renderToString from react-dom/server with custom function
This function was creating issue in customers with cra@4 & react@17
fixes: https://sendbird.atlassian.net/browse/UIKIT-3403

feat: replace renderToString(react-dom) with custom fn

---

src/ui/ContextMenu/MenuItems.tsx

* condition where some menus get clipped in left side:
* usually user profile in channel moderation
* context menu of last item in channel gets clipped under
fixes 1. & 3. from: https://sendbird.atlassian.net/browse/SBISSUE-10883

fix: menu position in tight screens

---

.size-snapshot.json
CHANGELOG.md
package-lock.json
package.json

Features:
* Add rollup-plugin-size-snapshot for bundle-size Run rollup-plugin-size-snapshot on build, we will check bundle size before every release
* Move old samples to use vite React team these days are using vite for their samples, CRA is discourged
* Run code coverage on commenting `./coverage` Check code coverage on PR comment
* Add prop to disable Channel & Thread inputs Add prop: `disabled?: false` for Channel & Thread MessageInputWrapper
* Replace renderToString(react-dom) with custom fn Replace renderToString from react-dom/server with custom function This function was creating issue in customers with cra@4 & react@17
Fixes:
* Replace outdated CSS rules `justify-content: start;` and  `height: fill-available;`
* Menu position in tight screens
* Condition where some menus get …

[v3.4.3] (Mar 24 2023)

---

src/smart-components/Channel/components/MessageInput/VoiceMessageInputWrapper.tsx

[UIKIT-3260](https://sendbird.atlassian.net/browse/UIKIT-3260)
Issue:
* Sending two voice messages when the playing status has been changed before sending voice message
Fixes:
* Remove the dependency `playingStatus` from onSubmitClick in the VoiceMessageInputWrapper component
* Clean up the states after sending a voice message in the VoiceMessageInputWrapper component
[UIKIT-3260]: https://sendbird.atlassian.net/browse/UIKIT-3260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Reduce sending two messages from VoiceMessageInputWrapper

---

scripts/index_d_ts
src/index.d.ts
src/smart-components/App/DesktopLayout.tsx
src/smart-components/Channel/context/ChannelProvider.tsx
src/smart-components/OpenChannel/context/OpenChannelProvider.tsx
src/smart-components/Thread/context/ThreadProvider.tsx
src/smart-components/Thread/context/__test__/utils.spec.ts
src/smart-components/Thread/context/hooks/useGetParentMessage.ts
src/smart-components/Thread/context/utils.ts

Issue
* Had to cover parent message with brackets before putting it to the Thread. So it caused confusing work around
Fix
* Check if the message is parent message or thread message inside of the Thread
* Use case (Before)
```javascript
<Thread
message={message}
// or
message={{ parentMessage }}
/>
```
* Use case (After)
```javascript
<Thread
message={message}
// or
message={parentMessage}
/>
```
* Remove props on the interface: `includePollDetails`
* Add util functions `isParentMessage` and `isThreadMessage`
[UIKIT-3325](https://sendbird.atlassian.net/browse/UIKIT-3325)
[UIKIT-3325]: https://sendbird.atlassian.net/browse/UIKIT-3325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: clean up the interface of thread module

---

src/smart-components/Channel/components/MessageList/index.tsx
src/smart-components/Channel/context/const.ts
src/smart-components/OpenChannel/components/OpenChannelMessageList/index.tsx
src/smart-components/OpenChannel/components/OpenChannelMessageList/useHandleOnScrollCallback.ts
src/smart-components/OpenChannelList/components/OpenChannelListUI/index.tsx
src/utils/consts.ts

Issue
* If customer had setup OpenChannel on a Page that has scroll, it used to scroll the whole page, unintentionally
* The function `scrollIntoView` has affected the outside element.
So it triggers weird scroll behavior that we didn't expect of the parent elements.
Fix
* Move message list scroll using element.scrollTop instead of the function scrollIntoView in the OpenChannelMessageList
[UIKIT-3420](https://sendbird.atlassian.net/browse/UIKIT-3420)
[UIKIT-3420]: https://sendbird.atlassian.net/browse/UIKIT-3420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Move scroll of message list without scrollIntoView

---

src/utils/consts.ts

Performance
* It takes 5~6 seconds to convert 10 minute audio file  
* It takes 2 seconds to send a voice message
[UIKIT-3514](https://sendbird.atlassian.net/browse/UIKIT-3514)
[UIKIT-3514]: https://sendbird.atlassian.net/browse/UIKIT-3514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Update the default maximum recording time to 10 minutes

---

src/smart-components/Thread/context/ThreadProvider.tsx
src/smart-components/Thread/context/__test__/utils.spec.ts
src/smart-components/Thread/context/utils.ts

* Do not check threadInfo to improve the parent message, because every normal messages potentially can be a parent message
* The type of messageId should be the number

fix: Modify condition of checking parent and thread messages

---

README.md

When I try to run `npm run ...`, I encountered below error since I'm using node.js 19
```
at sendbird-uikit-react/.yarn/cache/loader-runner-npm-2.4.0-c414104c2f-e27eebbca5.zip/node_modules/loader-runner/lib/LoaderRunner.js:205:4 {
opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
library: 'digital envelope routines',
reason: 'unsupported',
code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```
Seems it happens in node.js >= 17 version. So I'm adding a solution how other ppl can avoid it.  
Referred this https://github.com/webpack/webpack/issues/14532#issuecomment-947012063

chore: add workaround for ERR_OSSL_EVP_UNSUPPORTED

---

src/smart-components/App/DesktopLayout.tsx

Issue:
* The ChannelPreview item is not selected when opening the channel from the ParentMessage of the Thread
Fix:
* Set activeChannelUrl of ChannelList
[QM-2277](https://sendbird.atlassian.net/browse/QM-2277)
[QM-2277]: https://sendbird.atlassian.net/browse/QM-2277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Set current channel on ChannelList when opening channel from Thread

---

src/smart-components/Channel/components/Message/index.tsx

I'm proposing a variable renaming.
The current variable name is: `useMessageScrollRef`. This is not ideal, because React treats it as a custom hook. Since it is not a custom hook, it doesn't follow the [rules of hooks](https://legacy.reactjs.org/docs/hooks-rules.html), and so it produces a bunch of error messages in the console, making it so hard to debug.

fix: Rename useMessageScrollRef to messageScrollRef

---

src/ui/MessageInput/index.jsx

safari puts `<div>text</div>` for new lines inside content editable div(input)
Other browsers put newline or `br`
fixes: https://sendbird.atlassian.net/browse/UIKIT-3577

fix: MessageInput - detect new lines in safari

---

src/smart-components/Channel/components/MessageList/index.tsx
src/smart-components/Channel/context/ChannelProvider.tsx
src/smart-components/Channel/context/hooks/useHandleChannelEvents.ts
src/smart-components/Channel/context/hooks/useHandleReconnect.ts

Missed refactor markAsReadScheduler in `Channel/components/MessageList`

hotfix: Use markAsReadScheduler in MessageList

---

CHANGELOG.md
bundle-analysis.json
exports.js
package-lock.json
package.json

Features:
* Add a message list filter of UI level in the `Channel` module
* Add `Channel.filterMessageList?: (messages: BaseMessage): boolean;`, a UI level filter prop
to Channel. This function will be used to filter messages in `<MessageList />`
example:
```javascript
// set your channel URL
const channel = "";
export const ChannelWithFilter = () => {
const channelFilter = useCallback((message) => {
const now = Date.now();
const twoWeeksAgo = now - 1000 * 60 * 60 * 24 * 14;
return message.createdAt > twoWeeksAgo;
}, []);
return (
<Channel
channelUrl={channel}
filterMessageList={channelFilter}
/>
);
};
```
* Improve structure of message UI for copying
Before:
* The words inside messages were kept in separate spans
* This would lead to unfavourable formatting when pasted in other …

release: [v3.4.5] (Apr 07 2023)

---

src/hooks/VoicePlayer/index.tsx
src/smart-components/Channel/components/MessageInput/VoiceMessageInputWrapper.tsx
src/smart-components/ChannelList/components/ChannelPreview/channel-preview.scss
src/smart-components/ChannelList/components/ChannelPreview/index.tsx
src/smart-components/OpenChannel/components/OpenChannelMessageList/index.tsx
src/ui/MessageContent/index.scss

Fix bugs
* Call `VoiceRecorder.cancel` when closing the VoiceMessageInputWrapper
* solved issue: VoicePlayer doesn't play after VoiceMessageInputWrapper is closed
this is because VoicePlayer doesn't allow to play during recording, so it should specify the recording is done
Fix styles
* Reduce the maximum width of a message because of overflow
* Fix the text-overflow on the channel preview
* Remove the div tag containing the string to apply the ellipsis on the channel preview
Chore
* Fix typo `isSubmited` to `isSubmitted`
* Leave comments and Optimize the VoiceMessageInputWrapper
* Add a logger to find out the path through which AudioFile is obtained
[UIKIT-3473](https://sendbird.atlassian.net/browse/UIKIT-3473)
[UIKIT-3473]: https://sendbird.atlassian.net/browse/UIKIT-3473?atlOrigin=eyJpIj …

fix: Clean up UI of voice message in mobile mode

---

.eslintrc.json

It's a following task after #490 merged. \w previous config, I got these lint error since the lint config couldn't resolve the `d.ts` file extension. So I just off-ed the `import/extensions` rule at the PR and left a comment. 
So I found the workaround and enabled the rule again.

chore: add type.d.ts import resolver

---

.yarnrc.yml
src/lib/dux/sdk/reducers.ts
src/lib/dux/user/reducers.ts

Applies a comment in https://sendbird.slack.com/archives/C050Z6DA70A/p1681698139040799?thread_ts=1681693613.459129&cid=C050Z6DA70A. 
I introduced yarn 3 but there's an issue \w ts-pattern that it throws an weird TS error even though we used it correctly. 
But realized that it's gone \w `nodeLinker: node-modules` setting 🤷 
This won't be a permanent fix but will find another workaround including the pkg manager replacement yarn -> pnpm maybe.

feat: add nodeLinker to yarnrc

---

src/smart-components/App/stories/index.stories.js

When we removed package-lock, this info was removed~

fix: Bring back version of deps. to storybook

---

CHANGELOG.md
bundle-analysis.json
package.json

[v3.4.6] (Apr 21 2023)
Fixes:
* Use markAsReadScheduler in MessageList.
* Apply common scroll hook to GroupChannel MessageList.
* Prevent whole page from scrolling when <GroupChannel /> scrolls. This issue occurs when customer implements an <GroupChannel /> in a web page with scroll.
* This is a same fix that we fixed OpenChannel in `v3.4.4`.
* Unify send btn display condition
* Issue: We could send the empty message which is consisted of only white spaces. Also, a sent message which contains white spaces at the beginning of it is shown like it's trimmed.
* Solution: Two things have been changed on displayed. message & message input each.
* New line, spaces only text do not show sending button
* No trim before sending
* Use dynamic import to lazy load the audio converting …

release v3.4.6

---

package.json
yarn.lock

From: https://github.com/sendbird/sendbird-uikit-react/pull/500#issuecomment-1521620718
@bang9 Thanks for catching
Description
* To support the muted participants in the participant list of OpenChannel, the Chat SDK version ^3.4.0 is required

chore: Require for more than v3.4.0 Chat SDK version

---

.gitignore
jest.config.js
package.json

[UIKIT-3775](https://sendbird.atlassian.net/browse/UIKIT-3775)
Probably we will get more exact coverage value \w https://github.com/sendbird/sendbird-uikit-react/pull/461 once it's merged I guess. Until then, I just wanna have another way to get this \w one line command. 
[UIKIT-3775]: https://sendbird.atlassian.net/browse/UIKIT-3775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: modify jest config to get exact coverage value

---

src/ui/Label/stringSet.js

* Change the max mention count notice message
* from: `'You can mention up to %d times per message.'`
* to: `'You can mention up to %d times at a time.'`
[QM-1466](https://sendbird.atlassian.net/browse/QM-1466)
[QM-1466]: https://sendbird.atlassian.net/browse/QM-1466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Change the max mention count notice message

---

src/utils/__tests__/utils.spec.js
src/utils/index.ts

Resolves [UIKIT-3707](https://sendbird.atlassian.net/browse/UIKIT-3707)
**AS-IS**
A string \w $ sign(e.g. `$123.12`) or @ sign(e.g.`team_engineering@inkle.io`) created unnecessary underline with link
**TO-BE**
[UIKIT-3707]: https://sendbird.atlassian.net/browse/UIKIT-3707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: modify url regex to filter

---

src/ui/Word/index.scss

Resolves [UIKIT-3722](https://sendbird.atlassian.net/browse/UIKIT-3722)
[UIKIT-3722]: https://sendbird.atlassian.net/browse/UIKIT-3722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: give left-margin to the link text

---

src/smart-components/Message/utils/tokens/__tests__/tokenizeUtils.spec.ts
src/smart-components/Message/utils/tokens/tokenize.ts

Resolves [UIKIT-3792](https://sendbird.atlassian.net/browse/UIKIT-3792)
Regex lookbehind pattern doesnt work on safari
See: https://caniuse.com/js-regexp-lookbehind
https://stackoverflow.com/a/51568859
After this patch uikit works on safari
[UIKIT-3792]: https://sendbird.atlassian.net/browse/UIKIT-3792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: remove lookbehind pattern in getWhiteSpacePreservedText

---

scripts/index_d_ts
src/modules/Channel/components/Message/index.tsx
src/modules/Channel/components/MessageList/index.tsx
src/ui/MessageContent/index.tsx
src/ui/OGMessageItemBody/index.tsx

* Move the scroll of the message list after loading the OG message's thumbnail image
[UIKIT-3724](https://sendbird.atlassian.net/browse/UIKIT-3724)
[UIKIT-3724]: https://sendbird.atlassian.net/browse/UIKIT-3724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Move message list scroll after OG image is loaded

---

scripts/index_d_ts
src/ui/Toggle/ToggleContainer.tsx
src/ui/Toggle/ToggleContext.ts
src/ui/Toggle/index.tsx

Fix the build error issue 
> [!] Error: 'ToggleContainerProps' is not exported by src/ui/Toggle/ToggleContainer.tsx, imported by src/ui/Toggle/index.tsx

hotfix: Separate exporting components and types

---

scripts/index_d_ts
src/lib/hooks/useConnect/types.ts

Issue
* Customer had to use the type assertion for removing type error
```javascript
const globalState = useSendbirdStateContext()
const getSdk = sendbirdSelectors.getSdk(globalState) as SendbirdGroupChat;
getSdk.groupChannel.getTotalUnreadMessageCount();
```
Fix
* Specify the `getSdk` returns SendbirdGroupChat or SendbirdOpenChat

fix: Add types of GroupChat and OpenChat for SendbirdChat

---

src/modules/App/AppLayout.tsx
src/modules/App/MobileLayout.tsx
src/modules/App/index.jsx
src/modules/App/types.ts
src/modules/ChannelList/context/ChannelListProvider.tsx
src/modules/ChannelList/context/hooks/useActiveChannelUrl.ts

Issue 
* The activated channel flickers between the previous current channel and a new channel after creating the new group channel
* Infinite loop
* (1) `Creating a channel` causes the change of the channel list
* (2) `useActiveChannelUrl` is triggered by the channel list change
* (3) `useActiveChannelUrl` set the current channel to the previous channel
Fix
* Remove the channel list dependency from the `useEffect` of useActiveChannelUrl to fix the current channel flickers on the channel list

fix: Active channel url causes flicker of current channel on the channel list

---

.eslintrc.json
src/lib/hooks/useMarkAsReadScheduler.ts
src/modules/OpenChannel/components/OpenChannelMessage/index.tsx
src/ui/MessageInput/hooks/usePaste/index.ts

Part of https://sendbird.atlassian.net/browse/UIKIT-3837
Enabled [no-useless-return](https://eslint.org/docs/latest/rules/no-useless-return) rule off-ed by https://github.com/sendbird/sendbird-uikit-react/pull/490 previously.

chore: no-useless-return rule

---

.eslintrc.json
src/modules/CreateChannel/components/InviteUsers/index.tsx

Part of https://sendbird.atlassian.net/browse/UIKIT-3837
Enabled [no-floating-decimal](https://eslint.org/docs/latest/rules/no-floating-decimal#rule-details) rule off-ed by https://github.com/sendbird/sendbird-uikit-react/pull/490 previously.

chore: enable no-floating-decimal eslint rule

---

src/modules/ChannelSettings/index.tsx

Resolves https://sendbird.atlassian.net/browse/UIKIT-3832
Just replaced a incorrect prop passing `renderChannelProfile` -> `renderUserProfile`

fix: incorrect prop passing in ChannelSetting component

---

.eslintrc.json
src/hooks/VoicePlayer/useVoicePlayer.tsx
src/modules/Channel/components/Message/index.tsx
src/modules/Channel/components/MessageInput/index.tsx
src/modules/Channel/components/MessageList/index.tsx
src/modules/Channel/components/SuggestedMentionList/SuggestedUserMentionItem.tsx
src/modules/Channel/context/ChannelProvider.tsx
src/modules/ChannelList/components/ChannelListHeader/index.tsx
src/modules/OpenChannelSettings/components/EditDetailsModal.tsx
src/modules/Thread/components/ParentMessageInfo/index.tsx
src/types.d.ts
src/ui/MessageContent/index.tsx
src/ui/MessageStatus/index.tsx
src/ui/MobileMenu/MobileBottomSheet.tsx
src/ui/OpenchannelThumbnailMessage/index.tsx
src/utils/exports/getOutgoingMessageState.ts
src/utils/index.ts

Addressed a comment in https://github.com/sendbird/sendbird-uikit-react/pull/526#discussion_r1188223665 to bring back `no-unsafe-optional-chaining` rule again which is useful to have. 
As I mentioned [here](https://sendbird.slack.com/archives/C050Z6DA70A/p1683624307711019),  I found there're several places(actually many) we're doing optional chaining unnecessarily. Some of them are caught by lint(fixed in this PR) but others are still there. We'd better revisit them too.

chore: turn on no-unsafe-optional-chaining rule again

---

.husky/post-merge

Running yarn install on every git pull would be unnecessary. So I added a condition in post-merge hook to check if package.json has been changed. 
https://sendbird.slack.com/archives/C050Z6DA70A/p1683788237121899?thread_ts=1683787988.006319&cid=C050Z6DA70A

feat: run yarn install only when pkg.json has changes

---

src/ui/MessageInput/__tests__/utils.spec.ts
src/ui/MessageInput/hooks/usePaste/utils.ts
src/ui/MessageInput/index.jsx
src/ui/MessageInput/utils.js

NodeList cannot use Array methods, but our conversion was not really explicit.
So, during the ESLint upgrade, NodeList -> Array(Nodes) conversion was deleted
As a fix, we make explicit function to convert NodeList to Array(Nodes)

hot-fix: NodeList conversion on MessageInput.Paste

---

package.json
src/ui/MessageInput/__tests__/MessageInput.spec.js
src/ui/MessageInput/index.jsx
yarn.lock

Resolves https://sendbird.atlassian.net/browse/UIKIT-3869
Previously, even I made the send btn invisible when there's only empty spaces(+ new lines) in the input field, but still the empty white spaces could be sent by hitting an enter button 😅
So I made a fix to block sending like below (see what I'm pressing)
Plus I added more unit tests to prevent any further mistakes.

fix: prevent white space only text sending

---

src/modules/Message/utils/tokens/__tests__/tokenizeUtils.spec.ts
src/modules/Message/utils/tokens/tokenize.ts

Fixes https://sendbird.atlassian.net/browse/UIKIT-3890
Currently, the mentioned user template is not working correctly if a userId includes some patterns need to be escaped in regex. So made a fix to make the parsed message token have escaped pattern if one of `.*+?^${}()|[\]\\` is detected.

fix: mentioned user Regex parsing

---

.circleci/config.yml
package.json
yarn.lock

We have decided to use Circle CI as the main CI tool 
- Reduce cost from github
- Parity with other JS projects in the company
* Add circle CI
* Setup Lint, Test
* Update Jest minor version
* Remove GH-Action
* Setup coverage
[CORE-5381](https://sendbird.atlassian.net/browse/CORE-5381)
[CORE-5381]: https://sendbird.atlassian.net/browse/CORE-5381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Setup CircleCI for lint and test

---

src/modules/Message/utils/tokens/__tests__/tokenizeUtils.spec.ts
src/modules/Message/utils/tokens/tokenize.ts
src/ui/MessageContent/__tests__/__snapshots__/MessageContent.spec.js.snap
src/ui/OpenchannelOGMessage/__tests__/__snapshots__/OpenchannelOGMessage.spec.js.snap
src/ui/TextMessageItemBody/__tests__/__snapshots__/TextMessageItemBody.spec.js.snap
src/ui/TextMessageItemBody/index.tsx
src/ui/Word/index.scss

Words were breaking midword because all white spaces
were converted into nbsps. CSS couldnt discern that nbsps
are whitespaces, so wrapping didnt work well
Fixes: https://sendbird.atlassian.net/browse/UIKIT-3889

fix: Words-breaks happening mid word

---

CHANGELOG.md
package.json
scripts/index_d_ts

Fixes:
* Prevent white space only text sending
* Mentioned user Regex parsing Mention will now work even
if userId has `.*+?^${}()|[\]\\` characters
* ChannelList blink when when message is send
Happened when  there were two channelLists in the same page with different query params
* ChannelSetting `renderUserProfile` prop
We were applying `renderChannelProfile` in place of `renderUserProfile`
* MessageBody: Words break mid word
Words were breaking midword because all white spaces were converted into nbsps
CSS couldnt distinguish nbsps as whitespaces, so wrapping didnt work well
Chores:
* Setup CircleCI
* We are moving from Github Actions to CircleCI
* Setup Husky
* Setup lint on post push
* Auto run yarn install on post pull
* Update EsLint
* Update version to 8.40.x
* Apply more strict …

[v3.4.8] (May 19 2023)

---

scripts/index_d_ts
src/hooks/VoiceRecorder/index.tsx
src/hooks/useLongPress.tsx
src/lib/MediaQueryContext.tsx
src/modules/Thread/components/ParentMessageInfo/ParentMessageInfoItem.tsx
src/modules/Thread/components/ParentMessageInfo/index.tsx
src/modules/Thread/components/ThreadList/ThreadListItemContent.tsx
src/types.d.ts
src/ui/ContextMenu/EmojiListItems.tsx
src/ui/ContextMenu/MenuItems.tsx
src/ui/EmojiReactions/AddReactionBadgeItem.tsx
src/ui/EmojiReactions/ReactionItem.tsx
src/ui/EmojiReactions/index.tsx
src/ui/MessageContent/index.tsx
src/ui/MessageItemReactionMenu/index.tsx
src/ui/MobileMenu/MobileContextMenu.tsx
src/ui/MobileMenu/MobileEmojisBottomSheet.tsx
src/ui/MobileMenu/ReactedMembersBottomSheet.tsx
src/ui/MobileMenu/index.tsx
src/ui/MobileMenu/mobile-menu-emojis.scss
src/ui/MobileMenu/mobile-menu-reacted-members.scss
src/ui/UserListItem/index.tsx
src/utils/consts.ts
src/utils/index.ts

* Create components
* ReactedMembersBottomSheet
* MobileEmojisReactions
* Add util function: getEmojiUrl
* you can get the emoji URL from the emojiContainer with this util function
* Add some menu options to the MobileContextMenu
* Reply in Thread
* Reply to Thread
* Add a new props `avatarSize` to the UserListItem comp
* Set the type of `breakpoint` to string and boolean
* Apply browserSupportMimeType to record voice messages in several browsers
[UIKIT-3882](https://sendbird.atlassian.net/browse/UIKIT-3882)
[UIKIT-3882]: https://sendbird.atlassian.net/browse/UIKIT-3882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Critical issues for mobile compatibility

---

src/ui/MobileMenu/mobile-menu-reacted-members.scss

Set the minimum height of UserListItem on the ReactedMembersBottomSheet
[UIKIT-3995](https://sendbird.atlassian.net/browse/UIKIT-3995)
[UIKIT-3995]: https://sendbird.atlassian.net/browse/UIKIT-3995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Set minimum height of UserListItem of ReactedMembersBottomSheet

---

src/modules/ChannelList/utils.js

Resolves https://sendbird.atlassian.net/browse/UIKIT-3969 
A newly created channel should be displayed on the invitee's channel list only when there's a message not right after the channel is created.

fix: display a channel only when there's a msg

---

src/modules/Channel/components/Message/index.tsx
src/modules/Channel/components/MessageList/index.tsx

Keep the scrollBottom value after fetching a new message list

hotfix: Keep the scrollBottom value after fetching new message list

---

src/modules/Channel/components/MessageList/hooks/__test__/useSetScrollToBottom.spec.tsx
src/modules/Channel/components/MessageList/hooks/useSetScrollToBottom.ts
src/modules/Channel/components/MessageList/index.tsx

While refactor, we removed scrollToButton, it got coupled with `handleOnScroll`
which means, it would be called only when data fetching is involved
Seperating these logics would fix this
fixes: https://sendbird.atlassian.net/browse/UIKIT-3972

fix: Inconsistent rendering on scrollToBottom button

---

src/modules/Thread/components/ThreadList/ThreadListItemContent.tsx

* Move the location of `longPress` event from ThreadListItem to the middle element of it
to prevent exposing the context menu again when clicking outside of the context menu
in the broadcast channel (mobile)

fix: Mobile context menu does not disappear when clicking outside

---

src/modules/Channel/context/hooks/useHandleChannelEvents.ts
src/ui/ThumbnailMessageItemBody/index.tsx

Issue
* Stopping event propagation has blocked opening long press event of MessageContent
Fix
* Do not stop event propagation on the ThumbnailMessageItem
[UIKIT-4026](https://sendbird.atlassian.net/browse/UIKIT-4026)
[UIKIT-4026]: https://sendbird.atlassian.net/browse/UIKIT-4026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Thumbnail message longpress on mobile

---

src/modules/Message/utils/tokens/__tests__/tokenizeUtils.spec.ts
src/modules/Message/utils/tokens/tokenize.ts

The modification in the code was to escape the curly braces ({}) by replacing them with \{ and \}.
This ensures that the curly braces are treated as literal characters in the regular expression, addressing the issue caused by their metacharacter usage.
[UIKIT-4027](https://sendbird.atlassian.net/browse/UIKIT-4027)
[UIKIT-4027]: https://sendbird.atlassian.net/browse/UIKIT-4027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: curly brace escaping in regular expression

---

src/modules/Channel/context/ChannelProvider.tsx
src/modules/Channel/context/hooks/useHandleChannelEvents.ts

disableMarkAsRead should be passed down as a param in useHandleChannelEvents

hotfix: disableMarkAsRead should be passed

---

src/lib/Sendbird.tsx
src/lib/UIKitConfigProvider/index.tsx
src/lib/UIKitConfigProvider/utils/__tests__/getConfigsByPriority.spec.ts
src/lib/UIKitConfigProvider/utils/__tests__/type.spec.ts
src/lib/UIKitConfigProvider/utils/getConfigsByPriority.ts
src/lib/UIKitConfigProvider/utils/types.ts

Addresses https://sendbird.atlassian.net/browse/UIKIT-4014 
`UIKitConfigProvider` which handles Uikit Configuration in context has been added by my prev PR #561 and I commented two parts 
1. return valid configs depends on their each priorities 
i.e. local configs set in code level should have higher priority than the configs set by Dashboard feature configuration setting
2. save the Dashboard feature configurations in storage(React won't use this feature for now) 
So, this PR is for 1.

feat: handle configuration priorities

---

src/lib/Sendbird.tsx
src/modules/Channel/context/ChannelProvider.tsx
src/modules/Thread/components/ParentMessageInfo/index.tsx
src/modules/Thread/components/ThreadList/ThreadListItem.tsx
src/utils/__tests__/getIsReactionEnabled.spec.ts
src/utils/getIsReactionEnabled.ts

* Do not show emoji reactions in the Supergroup channel & Broadcast group channel
* Create a util func: getIsReactionEnabled
* Use the function to everywhere calculate the condition of isReactionEnabled
[UIKIT-4008](https://sendbird.atlassian.net/browse/UIKIT-4008)
[UIKIT-4008]: https://sendbird.atlassian.net/browse/UIKIT-4008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Un-expose reactions menu in special channels

---

src/utils/__tests__/getIsReactionEnabled.spec.ts

Add test case for getIsReactionEnabled
* It should disable if only one special channel type is true

chore: Add test case for getIsReactionEnabled

---

scripts/index_d_ts
src/lib/MediaQueryContext.tsx
src/lib/Sendbird.tsx
src/modules/App/index.jsx

For readability
See: https://github.com/sendbird/sendbird-uikit-react/pull/530#discussion_r1190564066
Fixes: https://sendbird.atlassian.net/browse/UIKIT-4046

feat: Rename MediaQueryBreakpoint to  breakpoint

---

src/modules/Thread/components/ThreadList/ThreadListItemContent.tsx
src/ui/MessageContent/index.tsx

Use 100% width to ThumbnailMessage in Mobile mode
before
after
[UIKIT-3909](https://sendbird.atlassian.net/browse/UIKIT-3909)
[UIKIT-3909]: https://sendbird.atlassian.net/browse/UIKIT-3909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Flexible thumbnail width

---

src/modules/Thread/components/ParentMessageInfo/index.scss

before
after
[UIKIT-3915](https://sendbird.atlassian.net/browse/UIKIT-3915)
[UIKIT-3915]: https://sendbird.atlassian.net/browse/UIKIT-3915?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Prevent hover style of ParentMessageInfo comp

---

src/modules/Thread/components/ThreadList/ThreadListItemContent.scss

before
after
* Remove max-width of thread message item body
[UIKIT-3917](https://sendbird.atlassian.net/browse/UIKIT-3917)
[UIKIT-3917]: https://sendbird.atlassian.net/browse/UIKIT-3917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Reactions width on mobile

---

src/modules/OpenChannelList/components/OpenChannelListUI/index.scss

before
after
[UIKIT-4000](https://sendbird.atlassian.net/browse/UIKIT-4000)
[UIKIT-4000]: https://sendbird.atlassian.net/browse/UIKIT-4000?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Apply theme to the OpenChannelList header

---

src/modules/Channel/components/MessageInput/index.tsx

before
after
[UIKIT-3911](https://sendbird.atlassian.net/browse/UIKIT-3911)
[UIKIT-3911]: https://sendbird.atlassian.net/browse/UIKIT-3911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Use short muted message in message input of mobile mode

---

src/modules/Thread/components/ThreadUI/index.scss

The design request has been changed
Desktop
Mobile
Desktop
mobile
[UIKIT-3914](https://sendbird.atlassian.net/browse/UIKIT-3914)
[UIKIT-3914]: https://sendbird.atlassian.net/browse/UIKIT-3914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Add border bottom to the ParentMessageInfo component

---

src/modules/ChannelList/components/ChannelPreview/index.tsx

* remove the (edited) text from ChannelPreview component
before
after
[UIKIT-3992](https://sendbird.atlassian.net/browse/UIKIT-3992)
[UIKIT-3992]: https://sendbird.atlassian.net/browse/UIKIT-3992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Remove edited message from ChannelPreview

---

src/lib/UIKitConfigProvider/UIKitConfigStorageManager/__tests__/index.spec.ts
src/lib/UIKitConfigProvider/UIKitConfigStorageManager/index.ts
src/lib/UIKitConfigProvider/const/initialConfig.ts
src/lib/UIKitConfigProvider/index.tsx

Implemented storage manager class to store UIKitConfig response. This will be used to decide whether we call the sdk.getUIKitConfiguration() again or not by comparing `lastUpdatedAt` field value. 
UIKit React doesn't have plan to use this feature for now but probably will be used in RN. 
After this PR  is merged, we will move the whole logic under `lib/UIKitConfigProvider` to https://github.com/sendbird/sendbird-uikit-core-ts/tree/main/packages/uikit-tools.

feat: add UIKitConfigStorageManager

---

src/ui/MobileMenu/MobileContextMenu.tsx

In the mode: `replyType="QUOTE_REPLY"`
* show a reply menu item in the broadcast channel
* apply disabled text color
* apply disabled icon color
[UIKIT-4016](https://sendbird.atlassian.net/browse/UIKIT-4016)
[UIKIT-4016]: https://sendbird.atlassian.net/browse/UIKIT-4016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Improve MobileContextMenu

---

src/ui/AdminMessage/index.scss
src/ui/MessageContent/index.scss
src/ui/MessageContent/index.tsx
src/ui/QuoteMessage/index.scss

* fix: apply ellipsis to the QuoteMessage
* fix: break-word of AdminMessage
[UIKIT-3986](https://sendbird.atlassian.net/browse/UIKIT-3986)
[UIKIT-3986]: https://sendbird.atlassian.net/browse/UIKIT-3986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: apply ellipsis to quote and admin msg

---

src/modules/OpenChannel/components/OpenChannelInput/index.tsx

* Notice disabled message input because of muted state
[UIKIT-4055](https://sendbird.atlassian.net/browse/UIKIT-4055)
before
after
[UIKIT-4055]: https://sendbird.atlassian.net/browse/UIKIT-4055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Change OpenChannelInput muted state notice text

---

src/ui/ThumbnailMessageItemBody/__tests__/ThumbnailMessageItemBody.spec.js
src/ui/ThumbnailMessageItemBody/__tests__/__snapshots__/ThumbnailMessageItemBody.spec.js.snap
src/ui/ThumbnailMessageItemBody/index.tsx

Remove the old loader on thumbnail message because they look
a bit weird
Fixes: https://sendbird.atlassian.net/browse/UIKIT-4044

fix: Remove loading placeholder on image

---

src/hooks/VoicePlayer/index.tsx

Race condition occurs when two audio files are requested from
backend clear previous player and play only the last arrived file
Cleanup - Do not need to fetch audio file if its already in cache
Fixes: https://sendbird.atlassian.net/browse/UIKIT-3952

fix: Race condition in playing audio file

---

src/hooks/VoicePlayer/index.tsx
src/modules/App/MobileLayout.tsx
src/ui/VoiceMessageItemBody/index.tsx

Is better not to handle this in Message Component
because this is a layout edge case. Customer can decide the 
layout, so they should be able to dictate the UX 
Fixes: https://sendbird.atlassian.net/browse/UIKIT-4031

fix: Pause voice when moved back

---

src/modules/Channel/context/hooks/useScrollToMessage.ts
src/ui/QuoteMessage/index.tsx

Clicks were triggered on preceding messages while scrolling
This opens other thumbnail messages on the way to parent
Avoid this by disabling events on MessageList
fixes: https://sendbird.atlassian.net/browse/UIKIT-4048

fix: Triggering random clicks while scroll to parent

---

src/modules/OpenChannel/components/OpenChannelMessage/index.tsx
src/modules/OpenChannel/components/OpenChannelMessage/utils.ts
src/ui/OpenchannelFileMessage/index.tsx
src/ui/OpenchannelOGMessage/index.tsx
src/ui/OpenchannelThumbnailMessage/index.tsx
src/ui/OpenchannelUserMessage/index.tsx

In Mobile,
Touch from contextMenus were getting leaked to MessageBody
To avoid this, move context menu outside of MessageBody's JSX
```
<div longPress>
<Message />
<Menu/>
</div>
```
to 
```
<>
<div longPress>
<Message />
</div>
{
<Menu/>
}
</>
```
Bonus * OGMessage should fallback to text-messages
Fixes: https://sendbird.atlassian.net/browse/UIKIT-4029

fix: OpenChannel Context menu click leak

---

package.json
src/lib/UIKitConfigProvider/index.tsx
yarn.lock

Currently storybook is throwing a runtime error due to the wrong json format access which is caused by my prev PR.

hotfix: modify uikit config payload format

---

scripts/index_d_ts
src/lib/Sendbird.tsx
src/lib/types.ts
src/modules/App/index.jsx
src/modules/Channel/context/ChannelProvider.tsx

https://sendbird.atlassian.net/browse/UIKIT-4085
Applied enable_message_search config flag by adding `showSearchIcon` to lib/Sendbird component prop which is not a completely new one but it can be passed from `App` component which already has `showSearchIcon` prop.

feat: apply groupchannel enableMessageSearch config flag

---

scripts/index_d_ts
src/lib/MediaQueryContext.tsx
src/lib/Sendbird.tsx
src/modules/App/index.jsx

`breakpoint?: boolean`  open on `@sendbird/uikit-react/App`
and `@sendbird/uikit-react/SendbirdProvider`
```
const isMobile = true
// or ---
// const isMobile = /iPhone|iPad|iPod|Android/i.test(navigator.userAgent);
// or ---
// const isMobile = /^https?:\/\/m\./i.test(window.location.href)
// ^^checks of url is like `m.sendbird.com`
// or ---
// const isMobile = "768px"
// ^^ UIKit will behave like mobile under 768px browser width
breakpoint={isMobile}
/>
```
fixes: https://sendbird.atlassian.net/browse/UIKIT-4107

feat: Open prop breakpoint

---

scripts/index_d_ts
src/ui/MessageInput/__tests__/MessageInput.spec.js
src/ui/MessageInput/index.jsx
src/ui/MessageInput/messageInputUtils.ts

If customer is using MessageInput inside our modules(ie: Channel, Thread, etc),
we should use the config from the module.
If customer is using MessageInput outside our modules(ie: custom UI),
we expect Channel to be undefined and customer gets control to show/hide file-upload.

feat: Use channel optionally inside MessageInput

---

samples/groupchannel/package-lock.json
samples/groupchannel/package.json
samples/openchannel/package-lock.json
samples/openchannel/package.json
samples/typescript_sample/package-lock.json
samples/typescript_sample/package.json

Fix for security alert
Vite Server Options (server.fs.deny) can be bypassed using double forward-slash (//)
Read more: https://github.com/vitejs/vite/security/advisories/GHSA-353f-5xf4-qw67
Fixes: https://sendbird.atlassian.net/browse/UIKIT-4109

chore: Samples -> Upgrade vite to 4.3.9

---

src/modules/App/index.jsx

The current default value setting via prop-types makes every configs' value have default value from the App component level. This makes Sendbird config priotization logic unnecessary. 
So I reset configs' value to `undefined` to make them set in Sendbird component instead.

feat: reset default value of duplicated configs in modules/App

---

src/ui/Label/index.scss

On Desktop, text select got disabled on messages to cleanup
long presses. We scope down the CSS rule for mobile only
Fixes: https://sendbird.atlassian.net/browse/UIKIT-4112
Thanks: @jawakarD

fix: Desktop - allow text select on Labels

---

scripts/index_d_ts
src/lib/Sendbird.tsx
src/lib/types.ts
src/modules/Channel/components/Message/index.tsx
src/modules/OpenChannel/components/OpenChannelInput/index.tsx
src/modules/OpenChannel/components/OpenChannelMessage/index.tsx
src/modules/Thread/components/ParentMessageInfo/index.tsx
src/modules/Thread/components/ThreadList/ThreadListItem.tsx
src/ui/MessageInput/__tests__/MessageInput.spec.js
src/ui/MessageInput/index.jsx
src/ui/MessageInput/messageInputUtils.ts

https://sendbird.atlassian.net/browse/UIKIT-4085
Address `enable_document`  configs to MessageInput component.

feat: apply xxChannel.input.enableDocument dashboard config 

---

scripts/index_d_ts
src/modules/App/MobileLayout.tsx
src/modules/Thread/context/ThreadProvider.tsx

When user sends direct message from Thread, it should open Channel Panel
Removal of `onUserProfileMessage` from `ThreadProvider` is not a breaking change
because, it was not connected from  `<Thread />` anyways
Fixes: https://sendbird.atlassian.net/browse/UIKIT-4102

fix: Mobile layout / Navigation on DM from Thread

---

src/lib/Sendbird.tsx
src/modules/App/stories/integrated-app.scss
src/modules/App/stories/integrated.stories.js

I was preparing a sample app environment for Feature Configuration war room but realized that there's no way to set `undefined` for the toggle items but only possible to choose `true` or `false` in this integration app.
So I added a checkbox next to the each toggle button like this (yeah couldn't come up with a better UI :smile: Any suggestion is welcome!)
Like the above in the gif, we can make each config value to `undefined` from boolean value by uncheck the checkbox.

feat: make integrated toggle config options resettable

---

src/modules/Thread/components/ParentMessageInfo/index.tsx
src/ui/MobileMenu/MobileBottomSheet.tsx
src/ui/MobileMenu/MobileContextMenu.tsx
src/ui/MobileMenu/index.tsx
src/ui/MobileMenu/types.ts

message?.threadInfo?.replyCount is not getting updated dynamically
This is a temporary prop that we wont open to public, if this is SDK issue,
then we can remove later 
Fixes: https://sendbird.atlassian.net/browse/UIKIT-4098

fix: Thread / Add extra state to show/hide delete menu

---

src/ui/AdminMessage/index.scss

We added ellipsis and left align Admin Message in #584
But, admin messages should be center aligned and shouldn't
have ellipsis
Fixes: https://sendbird.atlassian.net/browse/QM-2155

fix: Center align & remove ellipsis from admin message

---

src/hooks/useUnmount.ts
src/lib/Sendbird.tsx

Address https://sendbird.atlassian.net/browse/UIKIT-4132
I found that the sdk is not disconnected on Sendbird component unmount which makes the connection is being kept even though we want it to be destroyed. 
So I made sdk.disconnect() is called when it's unmount.
p.s. I made a separate RC to test in Dashboard project and confirmed that their issue is gone with this patch.

feat: make sdk disconnected on Sendbird component umount

---

src/modules/Channel/context/ChannelProvider.tsx

Resolves https://sendbird.atlassian.net/browse/UIKIT-4138
If ChanneContext doesn't have a prop value for`replyType` but only lib/Sendbird component has the value, the latter is not reflected correctly. So I put a fallback value so the global config can be used. If both are undefined (for some customer who only uses the ChannelContext only), then the replyType will be set as undefined.

fix: use global config's replyType if channel one is undefined

---

src/modules/App/AppLayout.tsx

Fixes https://sendbird.atlassian.net/browse/UIKIT-4140
Since the component level in `modules/App` is like below 
```
const { replyType, isReactionEnabled, showSearchIcon } = props;
<Sendbird <-- lib/Sendbird
replyType={replyType}
isReactionEnabled={isReactionEnabled}
showSearchIcon={showSearchIcon}
>
<AppLayout
replyType={replyType}
isReactionEnabled={isReactionEnabled}
showSearchIcon={showSearchIcon}
>
```
there's a chance that any of replyType / isReactionEnabled / showSearchIcon can be undefined even thought their values are set from Dashboard since the Dashboard values are set inside of `lib/Sendbird`. So AppLayout props still can have undefined values for these three configs. 
So I put fallback value setting logic \w global configs in `AppLayout`.

fix: set fallback values \w global configs in App comp

---

src/modules/Channel/context/ChannelProvider.tsx
src/modules/ChannelList/context/ChannelListProvider.tsx
src/modules/ChannelSettings/context/ChannelSettingsProvider.tsx
src/modules/OpenChannel/context/OpenChannelProvider.tsx
src/modules/OpenChannelSettings/context/OpenChannelSettingsProvider.tsx
src/modules/Thread/context/ThreadProvider.tsx

Resolves https://sendbird.atlassian.net/browse/UIKIT-4139
If any provider which uses `UserProfileContext` doesn't have a prop value for `disableUserProfile`  but only global config has the value, the latter is not reflected properly. 
So I put a fallback value so the global config can be used. If both are undefined, then the `disableUserProfile` will be set as undefined.

fix: use global disableUserProfile if each context's one is defined

---

src/ui/MessageContent/index.tsx

Resolves https://sendbird.atlassian.net/browse/UIKIT-4142
Fixes a runtime error caused by clicking "Reply in thread" menu from a parent message. 
It happens only when `replyType: THREAD & threadReplySelectType: PARENT`.

fix: runtime error on accessing null parentMessage data

---

src/utils/__tests__/isVoiceMessage.spec.ts
src/utils/index.ts

issue: Screen error shows up intermittently and says that the `message.type` property is undefined
fix: Check if the type property is empty and return false when it is

fix: Handle undefined message type in is voice message

---

CHANGELOG.md
bundle-analysis.json
package.json
yarn.lock

CHANGELOG
```
Fixes:
* Set fallback values \w global configs in App comp
* Use global config's replyType if channel one is undefined
* Use global disableUserProfile if each context's one is defined
* Clear `scrollBottom` on channel state loading
* Fixes a runtime error
caused by clicking "Reply in thread" menu from a parent message
* Check if the `message.type` property is empty
and return false when it is empty in the isVoiceMessage function
```
[SDKRLSD-864](https://sendbird.atlassian.net/browse/SDKRLSD-864)
[SDKRLSD-864]: https://sendbird.atlassian.net/browse/SDKRLSD-864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

release: Release UIKit React v3.5.1

---

rollup.config.js

If a path is set on Rollup.config.externals, it wont be bundled
to the library during rollup build step. We have removed react-dom/server
in: https://github.com/sendbird/sendbird-uikit-react/pull/449
So, its okay to remove it
Fixes: https://sendbird.atlassian.net/browse/UIKIT-4191

chore: Remove react-dom/server from rollup.config

---

src/lib/hooks/useConnect/__test__/setupConnection.spec.ts
src/lib/hooks/useConnect/setupConnection.ts

When there is only single instance of SDK,
and disconnect call take longer than next connect call
Solution: Set `newInstance: true` when initializing SDK instance
Fixes: https://sendbird.atlassian.net/browse/UIKIT-4193

fix: Race condition in disconnect/connect

---

src/index.d.ts
src/lib/Sendbird.tsx
src/lib/types.ts
src/lib/utils/__tests__/uikitConfigMapper.spec.ts
src/lib/utils/uikitConfigMapper.ts
src/modules/App/index.jsx
src/utils/typeHelpers/partialDeep.ts

Apply https://sendbird.atlassian.net/browse/UIKIT-4194
By enabling user to pass `uikitOptions` to Sendbird or App like root component, we're able to control configs in both way  e.g. 
```
<Sendbird isReactionEnable={true} />
// or 
<Sendbird uikitOptions={{ groupChannel: { enableReaction: true }}  />
```
Also, there were some configs that we had't have previously such as `enableOgtag` / `enableDocument` or any openChannel related configs. By passing uikitOptions, user can control the related configs without dashboard config setting (since configs passed from directly from App component take precedence over dashboard ones)
```
<Sendbird 
uikitOptions={{
groupChannel: {
enableOgtag: true,
input: {
enableDocument: true,
},
},
openChannel: {
enableOgTag: false,
} 
}} 
/>
```

feat: add uikitOptions prop to App & SendbirdProvider

---

src/modules/App/MobileLayout.tsx
src/modules/App/mobile.scss
src/modules/App/stories/index.stories.js
src/modules/App/stories/utils.jsx

issue: It was not able to reduce the height of the mobile app with some wrapper component
* fix: Set the height of MobileApp to 100% & do not use 'vh'
[UIKIT-4188](https://sendbird.atlassian.net/browse/UIKIT-4188)
[UIKIT-4188]: https://sendbird.atlassian.net/browse/UIKIT-4188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Allow to reduce mobile app height

---

src/modules/Channel/components/MessageList/index.tsx
src/modules/Channel/context/dux/initialState.js

* fix: Do not display the UnreadCount comp when unreadSince is null
[UIKIT-4189](https://sendbird.atlassian.net/browse/UIKIT-4189)
[UIKIT-4189]: https://sendbird.atlassian.net/browse/UIKIT-4189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Prevent displaying unread count with empty unread since

---

src/hooks/VoiceRecorder/WebAudioUtils.ts
src/hooks/VoiceRecorder/index.tsx
src/utils/consts.ts

fix: change const of Voice Recording to
* sampling rate: 11025
* bit rate: 12000
[UIKIT-4209](https://sendbird.atlassian.net/browse/UIKIT-4209)
[UIKIT-4209]: https://sendbird.atlassian.net/browse/UIKIT-4209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Improve sampling and bitrate of Voice Recording

---

src/modules/Channel/components/Message/index.tsx
src/modules/Channel/components/MessageList/index.tsx

* fix: move scroll every time when message height changes
* prev: moving scroll only when the last message height changes
[UIKIT-4042](https://sendbird.atlassian.net/browse/UIKIT-4042)
[UIKIT-4042]: https://sendbird.atlassian.net/browse/UIKIT-4042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: move scroll every time when message height changes

---

.circleci/config.yml
.github/workflows/release-ticket-creation.yml

Addresses https://sendbird.atlassian.net/browse/CLNP-176 
This PR is a very beginning the project of automating our release process. Two small things are done in this PR, 
👉🏻 This enables to create a release Jira ticket without navigating to Jira board or Github. 
(Got an idea from [a proposal](https://sendbird.atlassian.net/wiki/spaces/UIKitreact/pages/2101838231/Release+Automation#Concrete-Proposal-(June-23---2023)) from @sravan-s, see the Slack bot section)
Once this workflow file is merged into `main` branch, running this below command from a Slack channel will create a ticket.  Note that the command accepts only `branch_name` at the moment. 
```
/github workflow dispatch sendbird/sendbird-uikit-react --workflow release-ticket-reaction.yml -i branch_name=your-branch-name
```
The newly …

feat: add gh workflow for auto release ticket creation

---

.github/workflows/release-ticket-creation.yml

This is a following PR after #658 merged.  `CIRCLECI_API_TOKEN` is the right name not `CIRCLE_CI_API_TOKEN`.

fix: incorrect Circle CI secret env name

---

src/ui/MessageInput/index.jsx

This is default how it is in Mobile world
Also, its good practice to focus on Input on desktop
Fixes: https://sendbird.atlassian.net/browse/SBISSUE-12824

feat: Keep keyboard open after sending the message

---

package.json
yarn.lock

alpha.39 has CJS support, otherwise, UIKit wont work on next-js page router
Fixes: https://sendbird.atlassian.net/browse/CLNP-250

fix: Update @sendbird/uikit-tools to 0.0.1-alpha.39

---

package.json
yarn.lock

UIKit@3.6.0 wouldnt work with zero config on CRA
because of module resolution error
This is fixed in uikit-tools, and released in 40.alpha
see: https://github.com/sendbird/sendbird-uikit-core-ts/pull/55
Fixes: https://sendbird.atlassian.net/browse/SBISSUE-12931,
https://sendbird.atlassian.net/browse/CLNP-259

fix: UIKit@3.6.0 build error on CRA

---

src/modules/CreateChannel/components/InviteUsers/__tests__/index.spec.tsx
src/modules/CreateChannel/components/InviteUsers/index.tsx

Following PR after #665 
Couldn't realized that `users` list include the logged-in user as well and shouldn't count the user in this condition.
Reported by https://sendbird.slack.com/archives/C04TSUD6KV1/p1688111690523829?thread_ts=1688003922.764459&cid=C04TSUD6KV1

hotfix: modify invitation modal submit btn disable cond

---

CHANGELOG.md
package.json

* UIKit@3.6.0 build error on CRA (#668)
UIKit@3.6.0 wouldnt work by default on CRA
because of module resolution error on uikit-tools
This is fixed in uikit-tools, and released in 40.alpha
see: https://github.com/sendbird/sendbird-uikit-core-ts/pull/55
Fixes: https://sendbird.atlassian.net/browse/SDKRLSD-892

[v3.6.2] (June 30 2023)

---

src/modules/Channel/components/Message/index.tsx
src/modules/Channel/components/MessageList/index.tsx

* remove the duplicated functions: handleMessageHeightChange, and handleMessageListHeightChange
AND combine them into one function: `moveScroll`
* add optional params to the `moveScroll`
for moving the scroll only when the last message is reached to the bottom
* move scroll only when the last message's updatedAt is changed

fix: Move message list scroll when the last message is edited

---

src/index.d.ts
src/modules/Channel/components/MessageList/hooks/__test__/useScrollBehavior.spec.ts
src/modules/Channel/components/MessageList/hooks/useScrollBehavior.ts
src/modules/Channel/components/MessageList/index.tsx
src/modules/Channel/context/ChannelProvider.tsx
src/modules/Channel/index.tsx

Addresses one of request in https://sendbird.atlassian.net/browse/AC-12
Added [`scrollBehavior`](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior) prop to allow user to pass `"smooth"` option on scroll event via Channel component(provider).
But I set the default option to `auto` which is an initial value of this CSS property not to change the existing behavior.
You can see the difference of the each values of `scrollBahavior` in the[ mozilla docs site](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior) :)

feat: add scrollBehavior option to Channel

---

samples/typescript_sample/package-lock.json
samples/typescript_sample/src/const.ts

To make `Cross-realm object access in Webpack 5` go away
See: https://nvd.nist.gov/vuln/detail/CVE-2023-28154
Webpack is somewhere down below in dependency list,
so just update package-lock ~
Bonus: Remove APP_ID from consts
Fixes: https://sendbird.atlassian.net/browse/CLNP-308

fix: Update webpack to 5.88.1

---

src/modules/Channel/context/dux/__tests__/reducers.spec.js
src/modules/Channel/context/dux/reducers.js

fix: Verify the fetched message list size
- if it's the same as the requested size of the MessageListParams
chore: Add test case for verifying fetched message list size
[CLNP-430](https://sendbird.atlassian.net/browse/CLNP-430)
[CLNP-430]: https://sendbird.atlassian.net/browse/CLNP-430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Verify the fetched message list size with MessageListParams

---

src/modules/Channel/context/dux/__tests__/reducers.spec.js
src/modules/Channel/context/dux/reducers.js

In some customer's case, the server returns 32 messages even when we
asked for 31. Even though its an issue coming from server, we shouldnt set
`hasMorePrev` to false when result size is larger than query
Fixes: https://sendbird.atlassian.net/browse/SBISSUE-12994
Fixes: https://sendbird.atlassian.net/browse/CLNP-349

fix: Fetch more messages even if result size is larger

---

scripts/index_d_ts
src/index.d.ts
src/modules/Channel/context/ChannelProvider.tsx
src/modules/Channel/context/hooks/__test__/useHandleReconnect.spec.ts
src/modules/Channel/context/hooks/useHandleReconnect.ts
src/modules/Channel/context/hooks/useReconnectOnIdle.ts
src/modules/Channel/index.tsx

Addresses https://sendbird.atlassian.net/browse/AC-200 
Some users might not want to refetch the message list when the active browser tab is in the background and then comes back to the foreground. 
So, I added an option to the ChannelProvider: `reconnectOnIdle` (default: true), which prevents data refresh in the background.

feat: add `reconnectOnIdle` option to ChannelProvider

---

CHANGELOG.md
bundle-analysis.json
package.json

* Create a separate package.json for CommonJS (cjs) module during build time. This package.json is located under dist/cjs directory. (#687)
* Add a new prop `isUserIdUsedForNickname` to the public interface. This prop allows using the userId as the nickname. (#683)
* Add an option to the ChannelProvider: `reconnectOnIdle`(default: true), which prevents data refresh in the background. (#690)
* Fix an issue where the server returns 32 messages even when requesting 31 messages in the Channel. Now, hasMorePrev will not be set to false when the result size is larger than the query. (#688)
* Verify the fetched message list size with the requested size of the MessageListParams. Added a test case for verifying the fetched message list size. (#686)
* Address the incorrect cjs path in package.json. …

release: 3.6.4

---

scripts/index_d_ts
src/lib/Sendbird.tsx
src/lib/hooks/useConnect/__test__/setupConnection.spec.ts
src/lib/hooks/useConnect/connect.ts
src/lib/hooks/useConnect/index.ts
src/lib/hooks/useConnect/setupConnection.ts
src/lib/hooks/useConnect/types.ts
src/lib/types.ts
src/modules/App/index.jsx
src/modules/App/types.ts

Addresses https://sendbird.atlassian.net/browse/AC-217
Currently, there's no way to customize `sdk.init()` parameters outside of UIKit since sdk.init() is called internally within UIKit.
So I'm going to add a new prop called sdkInitParams that allows passing custom parameters from outside of UIKit(e.g. chat-ai-widget).
Then user will be able to pass any `SendbirdChatParams` listed in https://sendbird.com/docs/chat/v4/javascript/ref/interfaces/_sendbird_chat.SendbirdChatParams.html via `sdkInitParams`.

feat: add sdkInitParams prop

---

src/lib/hooks/useConnect/setupConnection.ts
src/lib/types.ts
src/modules/App/types.ts

Addressing a feedback from @sravan-s after #692 merged. `appId` is better not to override just to be safe.

feat: omit 'appId' from SendbirdChatInitParams

---

CHANGELOG.md
package.json

* Add a new prop `sdkInitParams` that allows passing custom parameters when `sdk.init(params)` is called from outside of UIKit.
e.g.
```
sdkInitParams={{
appStateToggleEnabled: false,
debugMode: true,
// more options can be found here https://sendbird.com/docs/chat/v4/javascript/ref/interfaces/_sendbird_chat.SendbirdChatParams.html
}}
/>
```

release: 3.6.5

---

src/modules/Channel/context/dux/reducers.js

If you spread message object in reducer, it will loose
some methods such as `isUserMessage`
Fixes: https://sendbird.atlassian.net/browse/CLNP-523

fix: Pending message doesnt have isUserMessage method

---

.github/pull_request_template.md

I wrote Trunk-Based Development before, but in strict sense,
everyone commit directly to trunk in this method.
Scaled Trunk-Based Development is more apt to describe our flow. 
Scaled Trunk-Based Development is best done with short-lived
feature branches: one person over a couple of days (max) and flowing
through Pull-Request style code-review & build automation before
"integrating" (merging) into main

chore: Change Trunk-Based Development to Scaled

---

src/ui/MessageInput/index.scss

Fixes: https://github.com/sendbird/sendbird-uikit-react/pull/691
Thanks @roderickhsiao

fix: MessageInout cursor - use not-allowed instead of disabled

---

scripts/index_d_ts
src/lib/Sendbird.tsx
src/lib/hooks/useConnect/__test__/setupConnection.spec.ts
src/lib/hooks/useConnect/connect.ts
src/lib/hooks/useConnect/index.ts
src/lib/hooks/useConnect/setupConnection.ts
src/lib/hooks/useConnect/types.ts
src/lib/types.ts
src/modules/App/index.jsx
src/modules/App/types.ts

Addresses https://sendbird.atlassian.net/browse/AC-264
chat-ai-widget is internally using UIKit React and it also has a requirement for tracking a user agent data via the logic added by #682. 
But [the 3rd parameter in the `sdk.addSendbirdExtension`; customData](https://github.com/sendbird/chat-js/pull/1104/files#diff-b1f1de7e79042a6f46acdd47d27f64e33177077d9a28b7a8740cfdbf0c60266aR509) is missing yet. So I added in this PR so this customData can be delivered from the outside of UIKit React.

feat: add customExtensionParams for sdk.addSendbirdExtensions

---

src/utils/__tests__/utils.spec.js
src/utils/index.ts

fix: util functions logic of verifying message type
refer to the `is~~~` method first rather than the messageType to verify each message type
* isAdminMessage, isUserMessage, isFileMessage
refer to the messageType only when those methods don't exist
[UIKIT-4301](https://sendbird.atlassian.net/browse/UIKIT-4301)
[UIKIT-4301]: https://sendbird.atlassian.net/browse/UIKIT-4301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: util functions logic of verifying message type

---

CHANGELOG.md
package.json

* Added a new ImageGrid UI component (for internal use only) (#703)
* Introduced `fetchChannelList` to the `ChannelListContext`.
* Implemented a custom hook function `useFetchChannelList`.
* Utilized this function to fetch the channel list within the `ChannelListUI` component.
* Added relevant tests for this function.
* Provided the method through the `ChannelListContext`: `fetchChannelList`.
Example Usage:
```jsx
import SendbirdProvider from '@sendbird/uikit-react/SendbirdProvider'
import useSendbirdStateContext from '@sendbird/uikit-react/useSendbirdStateContext'
import { ChannelListProvider, useChannelListContext } from '@sendbird/uikit-react/ChannelList/context'
const isAboutSame = (a, b, px) => (Math.abs(a - b) <= px);
const CustomChannelList = () => {
const {
allChannels, …
```

release: 3.6.7

---

src/modules/ChannelList/context/ChannelListProvider.tsx
src/modules/ChannelList/context/hooks/__tests__/useFetchChannelList.spec.ts
src/modules/ChannelList/context/hooks/useFetchChannelList.ts

https://github.com/sendbird/sendbird-uikit-react/pull/708#discussion_r1290975624
* remove setMarkAsDelivered from the useFetchChannelList
* calculate from outside whether to ignore the delivery receipt

fix: Remove setMarkAsDelivered from the useFetchChannelList

---

src/ui/FileViewer/hooks/mapProps.ts
src/ui/FileViewer/hooks/useKeyPress.ts
src/ui/FileViewer/hooks/useViewerState.ts
src/ui/FileViewer/index.tsx
src/ui/FileViewer/types.ts

This is a n example to merge single/multi file viewer ~
There are two ways to do this, and this is one ->
Option 1. As in this PR, I made a `ViewerTypes` flag to deterministically detect the kind of props to recive(If single/undefined -> we assume single file, for backward compactability. Multi has to be explicitly flagged)
Option 2. We deduce ViewerTypes from list of files in the Message -> if there is only one, assume it is single, otherwise multi
Anyways, generic idea is -> calculate the current picture inside ``useViewerState``
Keep click handlers in separate hook..

Combine single and multi file viewer

---

src/modules/Channel/context/dux/reducers.js
src/modules/Channel/context/hooks/__test__/useSendMultipleFilesMessage.spec.ts
src/modules/Channel/context/hooks/useSendMultipleFilesMessage.ts
src/modules/Thread/context/hooks/useSendMultipleFilesMessage.ts
src/utils/testMocks/error.ts
src/utils/testMocks/message.ts
src/utils/testMocks/messageRequestHandler.ts

[UIKIT-4246](https://sendbird.atlassian.net/browse/UIKIT-4246)
* Create a custom hook `useSendMultipleFilesMessage`
* Add some mock util functions for the MessageRequestHandler, Message, and Error instances
> Internal: You can import this hook from the `context/hooks` under the Channel and Thread modules.
```javascript
import { useSendMultipleFilesMessage } from '~/context/hooks/useSendMultipleFilesMessage'
const MultipleFilesInput = () => {
return (
<input
type="file"
onChange={(event) => {
sendMultipleFilesMessage(event.target.files)
}}
/>
)
}
```
[UIKIT-4246]: https://sendbird.atlassian.net/browse/UIKIT-4246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: create a custom hook useSendMultipleFilesMessage

---

.eslintrc.js
src/modules/ChannelList/components/ChannelPreview/__tests__/ChannelPreview.spec.js
src/modules/ChannelList/components/ChannelPreview/utils.js
src/modules/ChannelList/stories/index.stories.js

Fixes: [UIKIT-4351](https://sendbird.atlassian.net/browse/UIKIT-4351)
Displays name of the first file in mfm.fileInfoList
[UIKIT-4351]: https://sendbird.atlassian.net/browse/UIKIT-4351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Update ChannelPreview to support MFM lastMessage.

---

CHANGELOG.md
bundle-analysis.json
package.json
scripts/index_d_ts
src/ui/FileViewer/index.tsx

* Improve the index_d_ts
* Add props types for Channel/component/FileViewer
* Add props types for ui/FileViewer
* Import CoreMessageType and SendableMessageType from SendbirdUIKitGlobal
* Use destructuring import for SendbirdUIKitGlobal
* Add ChangeLog for v3.6.8
```
* Update `ui/FileViewer` to support multiple images
* Modify the props structure
```typescript
export enum ViewerTypes {
SINGLE = 'SINGLE',
MULTI = 'MULTI',
}
interface SenderInfo {
profileUrl: string;
nickname: string;
}
interface FileInfo {
name: string;
type: string;
url: string;
}
interface BaseViewer {
onClose: (e: React.MouseEvent) => void;
}
interface SingleFileViewer extends SenderInfo, FileInfo, BaseViewer {
viewerType?: typeof ViewerTypes.SINGLE;
isByMe?: boolean;
disableDelete?: boolean;
onDelete: (e: …

Release: v3.6.8

---

src/ui/MessageSearchFileItem/utils.ts

fix: error -> Cannot read properties of undefined (reading ‘match’) in MessageSearch module

fix: Error - properties of undefined in MessageSearch

---

src/modules/App/MobileLayout.tsx

Fixed a bug in MobileLayout where panel is not switched to channel list from channel when current user is banned or channel is deleted.
Fixes: [UIKIT-3999](https://sendbird.atlassian.net/browse/UIKIT-3999)
[UIKIT-3999]: https://sendbird.atlassian.net/browse/UIKIT-3999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bug-fix: Fixed a bug in MobileLayout where panel is not switched to channel list from channel when current user is banned or channel is deleted.

---

src/hooks/useModal/index.tsx
src/modules/Channel/components/MessageInput/useHandleUploadFiles.tsx
src/ui/Modal/index.tsx

* feat: add a props - hideCancelButton to the ui/Modal component
* fix: change the childElement props type to a function returning element
* feat: alert file selection limit using global modal

feat: Alert file selection limit using global modal

---

scripts/index_d_ts
src/modules/Channel/context/ChannelProvider.tsx
src/modules/Channel/context/hooks/__test__/useSendMultipleFilesMessage.spec.ts
src/modules/Channel/context/hooks/useSendMultipleFilesMessage.ts
src/modules/Channel/context/hooks/useSendVoiceMessageCallback.ts
src/modules/Channel/index.tsx
src/modules/Thread/context/ThreadProvider.tsx
src/modules/Thread/context/hooks/useSendFileMessage.ts
src/modules/Thread/context/hooks/useSendUserMessageCallback.ts
src/modules/Thread/index.tsx

[UIKIT-4450](https://sendbird.atlassian.net/browse/UIKIT-4450)
* Create a props `onBeforeSendMultipleFilesMessage` to the Channel and Thread module
* Add some props types that we have missed in the public interface
* Channel: onBeforeSendVoiceMessage
* Thread: onBeforeSendUserMessage, onBeforeSendFileMessage, onBeforeSendVoiceMessage
* Apply onBeforeSendUserMessage & onBeforeSendFileMessage to the Thread.
We have missed applying these customizing props in the Thread module
[UIKIT-4450]: https://sendbird.atlassian.net/browse/UIKIT-4450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add interface of customizing message CURD actions

---

src/modules/Channel/context/hooks/__test__/useSendMultipleFilesMessage.spec.ts
src/modules/Channel/context/hooks/useSendMultipleFilesMessage.ts
src/utils/index.ts

[UIKIT-4468](https://sendbird.atlassian.net/browse/UIKIT-4468)
* Generate URLs and put them into the pending MFM
* Expect the property fileInfoList of the pending MFM in the test code
[UIKIT-4468]: https://sendbird.atlassian.net/browse/UIKIT-4468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Handling pending message for MFM

---

scripts/index_d_ts
src/modules/App/stories/integrated-app.scss
src/modules/ChannelList/stories/index.stories.js
src/ui/ImageRenderer/index.scss
src/ui/ImageRenderer/index.tsx
src/ui/MessageInput/index.scss
src/ui/MobileMenu/mobile-menu-reacted-members.scss
src/ui/MultipleFilesMessageItemBody/index.tsx
src/ui/ThumbnailMessageItemBody/index.scss
src/utils/index.ts

Add shade on hover over MFM ImageRenderer + GIF Icon for gif.
Fixes: [CLNP-4494](https://sendbird.atlassian.net/browse/CLNP-4494)

Add shade on hover over MFM ImageRenderer + GIF Icon for gif

---

scripts/index_d_ts
src/modules/Channel/components/MessageList/index.tsx
src/modules/Channel/context/ChannelProvider.tsx
src/modules/Channel/context/dux/__tests__/reducers.spec.js
src/modules/Channel/context/dux/data.mock.js
src/modules/Channel/context/dux/initialState.js
src/modules/Channel/context/dux/reducers.js

When succeding to sending multiple messages in a very short time, some of the pending messages are not removed from the message list.
We anticipate this is a timing issue.
* To operate the message list safely, we are going to make another message list `localMessages` inside of the MessagesStore.
* From the next minor version `v3.7.0`, the `allMessages` will be deprecated or changed.
* The current `allMessages` will only include the 'succeeded' messages, and the `localMessages` will contain the 'pending' and 'failed' messages.

feat: Divide message list in the MessagesStore

---

src/modules/Thread/components/ParentMessageInfo/ParentMessageInfoItem.scss
src/modules/Thread/components/ParentMessageInfo/ParentMessageInfoItem.tsx
src/ui/ImageRenderer/index.scss
src/ui/ImageRenderer/index.tsx
src/ui/QuoteMessage/index.tsx
src/ui/ThumbnailMessageItemBody/index.scss
src/ui/ThumbnailMessageItemBody/index.tsx

Update GIF/Video icon color.
Fixes: [UIKIT-4499](https://sendbird.atlassian.net/browse/UIKIT-4499)
[UIKIT-4499]: https://sendbird.atlassian.net/browse/UIKIT-4499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Update GIF/Video icon color.

---

src/modules/ChannelList/components/ChannelPreview/__tests__/ChannelPreview.spec.js
src/modules/ChannelList/components/ChannelPreview/utils.js

bug-fix: Channel preview of lastMessage being MFM should display first file type not first file name.
Fixes: [UIKIT-4512](https://sendbird.atlassian.net/browse/UIKIT-4512)
TOBE
THIS PR
[UIKIT-4512]: https://sendbird.atlassian.net/browse/UIKIT-4512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bug-fix: Channel preview of lastMessage being MFM should display first file type not first file name.

---

src/modules/OpenChannel/context/hooks/useFileUploadCallback.ts
src/ui/MessageInput/index.jsx

* fix: accepting parameter type to Array<File> or File in the useFileUploadCallback

fix: Image, video, and file transfer is not possible in open channels

---

package.json
src/modules/Channel/context/hooks/useResendMessageCallback.js
src/modules/OpenChannel/context/hooks/useResendMessageCallback.ts
yarn.lock

~Fixes https://sendbird.atlassian.net/browse/CLNP-905~
`message.isResendable` type is function, and its return type is boolean.  So the way we've checked the value like 
```
if (failedMessage?.isResendable) { ... }
```
has been wrong but it should be if we really want to check its existence. 
```
if (typeof failedMessage?.isResendable === 'boolean') { ... }
```

fix: wrong isResendable cond check in openChannel/useResendMessageCallback 

---

src/modules/ChannelList/dux/reducers.js

[SBISSUE-13601](https://sendbird.atlassian.net/browse/SBISSUE-13601)
* The channel item hasn't moved to the top when the current user sends messages from different devices
* Move to the top in the ChannelList when the current user but a different peer sends a message
[SBISSUE-13601]: https://sendbird.atlassian.net/browse/SBISSUE-13601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Move to the top in the ChannelList

---

CHANGELOG.md
package.json
src/modules/Channel/components/MessageList/index.tsx

* (in Safari) Display the placeholder of the MessageInput when the input text is cleared
* Remove duplicated CSS line
* (in iOS) fix focusing on the chat screen starts from the top in Mobile device

release: 3.6.10

---

yarn.lock

I ran `npx update-browserslist-db@latest` locally.
when running `yarn lint:fix`, I get
```
Browserslist: caniuse-lite is outdated. Please run:
npx update-browserslist-db@latest
Why you should do it regularly: https://github.com/browserslist/update-db#readme
```
so I ran the command to fix it.

chore: Ran 'npx update-browserslist-db@latest'

---

src/ui/QuoteMessageInput/index.tsx

Fixes: [UIKIT-4524](https://sendbird.atlassian.net/browse/UIKIT-4524)
[UIKIT-4524]: https://sendbird.atlassian.net/browse/UIKIT-4524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bug-fix: Display "n Photos" for MFM in quote reply

---

scripts/package.template.json
scripts/post_build.js

- Fix CJS entry file path
```
@sendbird/uikit-react
├── cjs
│   └── index.js  >> should point here (cjs/index.js)
└── dist  >> but, point here (dist/cjs/index.js)
└── index.css 
```
- Remove unused fields in `cjs/package.json`

fix: cjs entry path and package.json

---

src/ui/MessageItemMenu/index.tsx

Fixes: [UIKIT-4535](https://sendbird.atlassian.net/browse/UIKIT-4535)
- if sending status is failed, delete without propmpt irregardless of network connection state.
- if all other sending status, show delete prompt IFF disabled is false.
[UIKIT-4535]: https://sendbird.atlassian.net/browse/UIKIT-4535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bug-fix: Allow delete failed messages when offline third refix.

---

scripts/index.d.ts
src/modules/Thread/components/ThreadList/index.tsx
src/modules/Thread/components/ThreadUI/index.tsx
src/modules/Thread/context/ThreadProvider.tsx
src/modules/Thread/context/dux/initialState.ts
src/modules/Thread/context/dux/reducer.ts
src/modules/Thread/context/hooks/useSendUserMessageCallback.ts

Fix
* Divide the `allThreadMessages` into the `allThreadMessages` and `localThreadMessages`
* The `localThreadMessages` includes the pending and failed messages
* The `allThreadMessages` won't include those sending status messages

feat: apply localThreadMessages to the ThreadContext

---

src/modules/Thread/components/ThreadList/ThreadListItemContent.tsx

Error when opening Thread component
> Cannot read properties of undefined (reading 'deleteMessage')
* fix: use useThreadContext instead useChannelContext in Thread

fix: use useThreadContext instead useChannelContext in Thread

---

src/modules/Channel/context/ChannelProvider.tsx
src/modules/Thread/context/ThreadProvider.tsx

* fix: toss isMultipleFilesMessageEnabled props in ThreadProvider
* fix: do not set the default value of isMultipleFilesMessageEnabled in Module

fix: Apply isMultipleFilesMessageEnabled to channel and thread

---

CHANGELOG.md
package.json

[v3.7.0] (Oct 23 2023)
Now we are supporting Multiple Files Message feature!<br/>
You can select some **multiple files** in the message inputs, and send **multiple images** in one message.<br/>
If you select several types of files, only images will be combined in the message and the other files will be sent separately.
Also we have resolved many issues found during QA.
You can turn it on in four places.
1. App Component
```tsx
import App from '@sendbird/uikit-react/App'
<App
...
isMultipleFilesMessageEnabled
/>
```
2. SendbirdProvider
```tsx
import { SendbirdProvider } from '@sendbird/uikit-react/SendbirdProvider'
...
isMultipleFilesMessageEnabled
>
{...}
```
3. Channel
```tsx
import Channel from '@sendbird/uikit-react/Channel';
import { …
```

release: v3.7.0

---

src/modules/OpenChannelSettings/components/OpenChannelSettingsUI/index.tsx

There has been UserProfileProvider in both places in the OpenChannelSettings module
1. OpenChannelSettingsProvider
2. OpenChannelSettingsUI
We applied the `renderUserProfile` props to the UserProfileProvider under the OpenChannelSettingsProvider
However, the other one under the OpenChannelSettingsUI blocked it.
* remove the duplicated UserProfileProvider from OpenChannelSettings to apply the `renderUserProfile` props

fix: Remove the duplicated UserProfileProvider from OpenChannelSettings

---

src/modules/ChannelList/dux/reducers.ts

[CLNP-1196](https://sendbird.atlassian.net/browse/CLNP-1196)
We have blocked adding a new empty channel to the ChannelList. But it's not considered with the ChannelListQuery, and there was a use case that needed to add super group channels to the ChannelList.
It's fine to remove this logic because ChannelListQuery filters the empty channels by referring to its `includeEmpty` options.
* Remove the logic blocking adding an empty channel to the ChannelList because the ChannelListQuery should judge it
[CLNP-1196]: https://sendbird.atlassian.net/browse/CLNP-1196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Remove a logic blocking adding an empty channel to the ChannelList

---

package.json
src/modules/Channel/components/Message/index.tsx
src/modules/Channel/components/SuggestedReplies/index.scss
src/modules/Channel/components/SuggestedReplies/index.tsx
yarn.lock

Addresses https://sendbird.atlassian.net/browse/AC-581 
The feature request is from AI chat bot. 
If a trigger message(can be set from the dashboard) is sent to the channel from a user (e.g. `Show me suggested replies` in this case), the predefined suggested reply options will be displayed. 
Once the user clicks an option from the list, the option list will be gone and the message will be sent.

feat: add suggested replies

---

src/modules/App/stories/index.stories.js
src/modules/Channel/components/Message/index.tsx
src/modules/Channel/components/MessageList/index.tsx
src/modules/Channel/components/UnreadCount/index.tsx
src/modules/Channel/context/ChannelProvider.tsx
src/modules/Channel/context/dux/initialState.ts
src/modules/Channel/context/dux/reducers.ts
src/modules/OpenChannel/components/OpenChannelMessage/index.tsx
src/modules/Thread/components/ThreadList/ThreadListItem.tsx
src/ui/Label/stringSet.ts

Add `DATE_FORMAT__THREAD_LIST__DATE_SEPARATOR` to customize date format of `DateSeparator`
Add `DATE_FORMAT__MESSAGE_LIST__DATE_SEPARATOR` to customize date format of `DateSeparator`
> ![image](https://github.com/sendbird/sendbird-uikit-react/assets/26326015/3a66f7af-080b-4036-a7ae-492aba38a76b)
Add `DATE_FORMAT__MESSAGE_LIST__NOTIFICATION__UNREAD_SINCE` to customize date format of `UnreadCount`
> ![image](https://github.com/sendbird/sendbird-uikit-react/assets/26326015/02936378-88f5-4a2d-b343-47e6785a4bfe)
* Provide new string sets, you can directly customize the date format of `DateSeparator` and `UnreadCount`.
- `DATE_FORMAT__THREAD_LIST__DATE_SEPARATOR`: 'MMM dd, yyyy' → Used on the date separator of thread list
- `DATE_FORMAT__MESSAGE_LIST__DATE_SEPARATOR`: 'MMMM dd, yyyy' → Used on …

feat(CLNP-1344): add date format string set

---

rollup.module-exports.mjs
src/modules/Channel/context/hooks/useInitialMessagesFetch.ts

Addresses https://sendbird.atlassian.net/browse/AC-690
I took the logic inside of useInitialMessagesFetch's effect hook and made a callback function. And made the function to be returned from the hook to make it be from outside of UIKit. 
```
function useInitialMessagesFetch(params): void {
useEffect(() => {
all the logics..
}, [deps]}
}
```
```
function useInitialMessagesFetch(params): () => void {
const fetchMessages() => useCallback(() => {
all the logics..
, [deps]}
useEffect(() => {
fetchMessages();
}, [fetchMessages]}
return fetchMessages;
}
```

feat: export initialMessagesFetch callback from hook

---

src/modules/ChannelList/context/ChannelListProvider.tsx

Found the issue while I was testing https://sendbird.atlassian.net/browse/SBISSUE-14025.
If user passes custom `queries(: object)` prop to Channel module, it'll cause unnecessary re-rendering in this effect hook. So I just made it more precise so the deps array don;t waste the resource to compare the object diff and make unnecessary side effect.

fix: precise object dependency in effect hook

---

src/modules/Channel/components/UnreadCount/index.tsx

- add missing date locale in `DATE_FORMAT__MESSAGE_LIST__NOTIFICATION__UNREAD_SINCE`
ticket: [CLNP-1344]
[CLNP-1344]: https://sendbird.atlassian.net/browse/CLNP-1344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: add missing date locale to unread since string

---

src/modules/Channel/components/MessageInput/index.tsx
src/modules/Channel/components/MessageInput/useHandleUploadFiles.tsx
src/modules/Channel/context/hooks/useSendFileMessageCallback.ts
src/modules/Thread/components/ThreadMessageInput/index.tsx
src/utils/compressImage.ts
src/utils/compressImages.ts
src/utils/pxToNumber.ts

[CLNP-1320](https://sendbird.atlassian.net/browse/CLNP-1320)
* Use the more impactful value between the `resizingWidth` and `resizingHeight`
* So, the original images' ratio won't be broken
* Apply the ImageCompression to the Thread module
* Apply the ImageCompression for sending `file message` and `multiple files message`
* Create a `compressImages` util function
* Compress the images in the `useHandleUploadFiles` hook
* Do not compress the image inside of the `useSendFileMessageCallback` hook of the Channel module
[CLNP-1320]: https://sendbird.atlassian.net/browse/CLNP-1320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Improve Image Compression feature

---

src/ui/MessageContent/MessageProfile/index.tsx
src/ui/MessageContent/index.tsx

MessageContentInternalProps should not be made interal for backward compatibility.

chore: Put back message content props

---

src/lib/Sendbird.tsx
src/lib/hooks/useConnect/__test__/setupConnection.spec.ts
src/lib/hooks/useConnect/connect.ts
src/lib/hooks/useConnect/index.ts
src/lib/hooks/useConnect/setupConnection.ts
src/lib/hooks/useConnect/types.ts
src/lib/types.ts

Aims to resolve https://sendbird.atlassian.net/browse/CLNP-1562
Added support for `eventHandlers.connection.onFailed callback` in `setupConnection`.
The new callback is invoked in case of a connection failure, providing a way to handle errors and take appropriate actions. The addition of the `onFailed` callback aims to enhance the flexibility of the `setupConnection` function, allowing users to implement custom error handling logic when a connection fails.
**Example usage**
```
<Sendbird
appId={appId}
userId={undefined} // this will cause an error 
eventHandlers={{
connection: {
onFailed: (error) => {
alert(error?.message); // display a browser alert and print the error message inside
}
}
}}
>
```

feat: add eventHandler.connection.onFailed to handle connection error

---

src/modules/App/stories/integrated.stories.js
src/modules/ChannelList/components/ChannelListUI/index.tsx
src/modules/EditUserProfile/components/EditUserProfileUI/index.tsx
src/modules/EditUserProfile/index.tsx

[UIKIT-4542](https://sendbird.atlassian.net/browse/UIKIT-4542)
Also, internal troubleshooting
* The props, `onProfileEditSuccess` has been not applied..
* Apply the `onProfileEditSuccess` props to the App and ChannelList components
* Apply the profile edition in the Integrated App storybook sample
* Apply the `onProfileEditSuccess` props to the App and ChannelList components
[UIKIT-4542]: https://sendbird.atlassian.net/browse/UIKIT-4542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: apply onProfileEditSuccess props

---

src/modules/Channel/context/__test__/utils.spec.js
src/modules/Channel/context/utils.ts

Copy code
Addresses [AC-670](https://sendbird.atlassian.net/browse/AC-670)
Currently, users can set the position of the first displayed message using the `startingPoint` (or `scrollToMessage`) prop via the Channel component. However, the scroll stops at the middle of the target message element, requiring users to scroll up to see long content.
The scroll stops at the middle position of the message element.
- Mobile view
- Desktop view
[AC-670]: https://sendbird.atlassian.net/browse/AC-670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: scroll to the top of the target message element in Channel component

---

src/modules/Channel/context/dux/reducers.ts

The failed or pending messages were not removed from the message list when changing the current channel.
* Clear pending and failed messages from the message list when changing the current channel

fix: Clear localMessages when initializing message list

---

src/ui/OGMessageItemBody/__tests__/__snapshots__/OGMessageItemBody.spec.js.snap
src/ui/OGMessageItemBody/index.tsx

Before & After
* Add width:100% to the ImageRenderer of OGMessage
* Fit the OGMessage Thumbnail Image to the minimal width length

fix: Fit the OGMessage Thumbnail Image to the minimal width length

---

src/hooks/useOnScrollReachedEndDetector/__tests__/useHandleOnScrollCallback.spec.ts
src/hooks/useOnScrollReachedEndDetector/index.ts
src/modules/Channel/components/Message/index.tsx
src/modules/Channel/components/MessageList/index.tsx
src/modules/ChannelList/components/ChannelPreview/index.tsx
src/modules/Thread/context/hooks/useResendMessageCallback.ts
src/ui/OGMessageItemBody/__tests__/__snapshots__/OGMessageItemBody.spec.js.snap
src/ui/OGMessageItemBody/index.tsx

Fixes: [CLNP-1524](https://sendbird.atlassian.net/browse/CLNP-1524)
- Added and applied `useOnScrollReachedEndDetector()` in `MessageList` to mark new messages as read when scroll reaches bottom
- Channel list no longer displays unread message count for focused channel
The second change was due to limitation where isScrollBottom and hasNext states needs to be added globally but they are from channel context so channel list cannot see them with the current architecture.
[CLNP-1524]: https://sendbird.atlassian.net/browse/CLNP-1524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bug-fix: Added and applied useOnScrollReachedEndDetector() in MessageList to mark new messages as read when scroll reaches bottom.

---

rollup.module-exports.mjs
src/modules/Channel/components/MessageInput/index.tsx

- Export `VoiceMessageInputWrapper` and `useHandleUploadFiles`
```tsx
import { useHandleUploadFiles } from '@sendbird/uikit-react/Channel/hooks/useHandleUploadFiles'
import { VoiceMessageInputWrapper, VoiceMessageInputWrapperProps } from '@sendbird/uikit-react/Channel/components/MessageInput'
```

chore: export modules

---

package.json
src/modules/App/stories/index.stories.js
src/modules/ChannelList/context/ChannelListProvider.tsx
src/modules/ChannelList/utils.ts
src/modules/GroupChannelList/components/AddGroupChannel/AddGroupChannelView.tsx
src/modules/GroupChannelList/components/AddGroupChannel/index.tsx
src/modules/GroupChannelList/components/GroupChannelListUI/index.tsx
src/modules/GroupChannelList/context/GroupChannelListProvider.tsx
src/modules/GroupChannelList/index.tsx
yarn.lock

* Use uikit-tools 0.0.1-alpha.44
* Update the `GroupChannelListQueryParamsInternal` with the recent supporting types
* Call `onChannelSelect` in the GroupChannelList
* Add a `channelListQuery` to the GruopChannelList props
* Add the `onChannelCreate` props to the CreateGroupChannel component
* Use the `onChannelCreate` props to set the current channel in the Custom App of storybook sample

fix: Complete GroupChannelList props interface

---

src/modules/Channel/context/ChannelProvider.tsx
src/modules/Channel/context/dux/reducers.ts
src/modules/Channel/context/hooks/useResendMessageCallback.ts
src/modules/Channel/context/hooks/useSendMultipleFilesMessage.ts
src/modules/Thread/context/dux/reducer.ts
src/modules/Thread/context/hooks/useResendMessageCallback.ts

Fixes: [UIKIT-4518](https://sendbird.atlassian.net/browse/UIKIT-4518)
- Fixed a bug where resending failed `MultipleFilesMessage` fails in `Thread`
- Fixed a bug where resending failed `MultipleFilesMessage` not updating its `sendingStatus` to pending
[UIKIT-4518]: https://sendbird.atlassian.net/browse/UIKIT-4518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bug-fix: Fixed a bug where resending MFM fails in thread. 

---

src/modules/Channel/context/hooks/useHandleChannelEvents.ts

Fixes: [<TICKET_ID>](https://sendbird.atlassian.net/browse/<TICKET_ID>)
- Fixed a bug where  `currentGroupChannel` of `useChannelContext()` not being updated when non-current user has left or been banned while `ChannelList` is not being used

bug-fix: Group channel user left or banned event should not be ignored

---

src/modules/ChannelList/dux/actionTypes.ts
src/modules/ChannelList/dux/reducers.ts
src/modules/ChannelList/utils.ts

- Fix group channel doesn't move to the top in a channel list even though latest_last_message is the default order.
- ticket: [CLNP-1697]
[CLNP-1697]: https://sendbird.atlassian.net/browse/CLNP-1697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: update currentUserId properly in channel list initialize step

---

src/hooks/useModal/index.tsx
src/lib/Sendbird.tsx

* [Can't use `PropsWithChildren` because of type error](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60641)
* Not assignable to type error, property 'children' doesn't exist on type `PropsWithChildren`
* [Can't use `PropsWithChildren<{}>` because of lint error](https://stackoverflow.com/questions/65548388/react-propswithchildren-with-no-props-other-than-children)
* Use Use `PropsWithChildren<unknown>` instead `PropsWithChildren`
* Fix a type error from SendbirdProvider
* Not assignable to type error, property 'children' doesn't exist on type `PropsWithChildren`

fix: Use PropsWithChildren<unknown> instead PropsWithChildren

---

src/ui/MessageInput/index.tsx
src/utils/__tests__/utils.spec.ts
src/utils/utils.ts

- fix: even though reset the input with innerHTML, incomplete text compositions from the previous input are displayed in the next input.
- ticket: [CLNP-1698]
[CLNP-1698]: https://sendbird.atlassian.net/browse/CLNP-1698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: the reset text appears in the next input

---

src/hooks/VoicePlayer/useVoicePlayer.tsx
src/lib/hooks/useOnlineStatus.ts
src/modules/Channel/context/hooks/useHandleReconnect.ts

[CLNP-1779](https://sendbird.atlassian.net/browse/CLNP-1779)
* Include `metaArray` to the message list when fetching messages again by connecting
* Resolve `NaN` message on VoiceMessage after reconnection
[CLNP-1779]: https://sendbird.atlassian.net/browse/CLNP-1779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Include metaArray to messages when reconnecting

---

src/modules/App/MobileLayout.tsx
src/modules/CreateChannel/components/InviteUsers/index.tsx
src/modules/CreateChannel/components/InviteUsers/invite-users.scss

Addresses https://sendbird.atlassian.net/browse/CLNP-1806
We have been calculating the height value of the modules/InviteUsers modal using the --sendbird-vh CSS variable in the following manner: [GitHub Link](https://github.com/sendbird/sendbird-uikit-react/blob/main/src/modules/CreateChannel/components/InviteUsers/invite-users.scss#L13).
I believe this approach was taken to adjust the dynamic scrollable area height, especially in mobile view. However, it hampers code readability as we need to search for the keyword to locate where it is defined.
Therefore, I propose relocating this logic to the InviteUsers component and consolidating all related logic within a single file.
Confirmed that it's working as before on mobile window size change.

refactor: move --sendbird-vh css variable setting logic to comp

---

src/hooks/VoicePlayer/dux/reducer.ts

The change is from #893 and made by @aldenquimby

fix: replay voice memos

---

src/modules/ChannelList/context/ChannelListProvider.tsx
src/modules/ChannelList/dux/reducers.ts

The change comes from #894 and made by @aldenquimby

fix: channel view should show NO_CHANNEL placeholder after leaving all channels

---

src/utils/compressImages.ts

[CLNP-1832](https://sendbird.atlassian.net/browse/CLNP-1832)
* Image Compression feature upsizes the images when the resizing values are greater than the origin length
* Add optional chaining for the case when a logger doesn't exist
* Do not use the resizing value if it's greater than the origin length
* Do not upsize the images when the resizing values are greater than the origin length
[CLNP-1832]: https://sendbird.atlassian.net/browse/CLNP-1832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Do not upsize the images in ImageCompression

---

src/modules/Channel/components/ChannelUI/index.tsx
src/modules/Channel/components/Message/index.tsx
src/modules/Channel/components/MessageList/index.tsx
src/modules/Channel/index.tsx
src/types.ts
src/utils/__tests__/omitObjectProperties.spec.ts
src/utils/omitObjectProperty.ts

The `renderMessage` and the `renderMessageContent` props are diffrent.
Customers can easily customize the `renderMessageContent` after we provide several sub-components of the `MessageContent` component.
* Add missing props `renderMessageContent` in Channel
* Add missing props `renderMessageContent` in Channel
* Create a util function, `omitObjectProperties`
1. Customize with `renderMessage`
```tsx
<Channel
renderMessage={(props) => (
<Message
{...props}
renderMessageContent={(props) => (
<MessageContent {...props} />
)}
/>
)}
/>
```
2. **[More Simple Way]** Customize with `renderMessageContent`
```tsx
<Channel
renderMessageContent={(props) => (
<MessageContent {...props} />
)}
/>
```

fix: Add missing props renderMessageContent

---

src/modules/Thread/components/ThreadMessageInput/index.tsx
src/modules/Thread/index.tsx

We don't currently support local caching for threads, so it should be disabled when it goes offline.
ticket: [CLNP-1973]
[CLNP-1973]: https://sendbird.atlassian.net/browse/CLNP-1973?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(CLNP-1973): thread input should be disabled when it goes offline

---

src/modules/Channel/components/Message/index.tsx
src/modules/Thread/components/ParentMessageInfo/ParentMessageInfoItem.tsx
src/ui/OGMessageItemBody/index.tsx
src/ui/OpenchannelOGMessage/index.tsx
src/ui/TextMessageItemBody/index.tsx

> This change is originally made by @ishubham21 at https://github.com/sendbird/sendbird-uikit-react/pull/916. Please refer to this PR for more detailed background.
`message.updateAt` won't be updated if the message is coming from a bot especially in streaming. Its value gets just `0`. I added one more field `message.message` to the dependency array so we can make sure the hook is being executed again.

Add message.message to message tokenize hook deps array

---

src/lib/hooks/useOnlineStatus.ts
src/modules/ChannelList/components/ChannelListUI/index.tsx
src/modules/GroupChannel/components/MessageInputWrapper/MessageInputWrapperView.tsx
src/modules/GroupChannel/context/GroupChannelProvider.tsx
src/modules/GroupChannelList/components/GroupChannelListUI/index.tsx

[CLNP-1958](https://sendbird.atlassian.net/browse/CLNP-1958)
* `MessageInput` and `ChannelPreview` are disabled during disconnected status even if the local caching is enabled
* Enable the `MessageInput` and `ChannelPreview` during disconnection if the local cache is enabled
[CLNP-1958]: https://sendbird.atlassian.net/browse/CLNP-1958?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Enable the MessageInput if cache is enabled during disconnection

---

src/ui/Badge/index.scss
src/ui/Button/index.scss

[SBISSUE-14550](https://sendbird.atlassian.net/browse/SBISSUE-14550)
We've used `display: inline-block` inside of the Badge and Button.
But it breaks the center alignment in the **FireFox** browser, so need to change to using `display: inline-flex` and add more properties for center alignment
* Apply the center alignment to the Badge and Button components (in FireFox)
[SBISSUE-14550]: https://sendbird.atlassian.net/browse/SBISSUE-14550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Apply the center alignment to the Badge and Button

---

src/modules/Channel/components/MessageList/index.tsx
src/modules/Channel/context/utils.ts

https://github.com/sendbird/sendbird-uikit-react/assets/26326015/1f31230f-6c64-4893-9872-19c7676c95ec
https://github.com/sendbird/sendbird-uikit-react/assets/26326015/f3f89752-0d9d-474d-a655-5fc46ee51c5f
ticket: [CLNP-2050]
[CLNP-2050]: https://sendbird.atlassian.net/browse/CLNP-2050?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: avoid max_safe_integer to scroll to bottom behavior

---

src/utils/__tests__/utils.spec.ts
src/utils/index.ts

Fixes https://sendbird.atlassian.net/browse/SBISSUE-14740
```
// A subdomain has a hyphen
'https://send-bird.slack.com/archives/C065N4UQ77W/p1699931368643169?thread_ts=1699925671l395019&cid-Co65N4UQ77W',
// with long top-level domain
'https://send.bird.business/archives/C065N4UQ77W/p1699931368643169?thread_ts=1699925671l395019&cid-Co65N4UQ77W',
```
^ these like domain couldn't be checked by the URL_REG, so I modified it a bit.

fix: URL_REG subdomain / top-level domain

---

src/modules/ChannelSettings/components/ModerationPanel/MutedMemberList.tsx
src/modules/ChannelSettings/components/ModerationPanel/OperatorList.tsx

Fixes: [CLNP-2099](https://sendbird.atlassian.net/browse/CLNP-2099)
- Fixed a bug where muted member list is not being updated after a member had been unmuted
- Fixed a bug where operator list is not being updated after an operator had been removed
[CLNP-2099]: https://sendbird.atlassian.net/browse/CLNP-2099?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bug-fix: Fixed a bug where operator list and muted members list not being updated

---

src/modules/App/DesktopLayout.tsx
src/ui/Avatar/index.tsx
src/ui/ThreadReplies/index.tsx

fix: when open-in-channel pressed, scrolling to message should work properly
fix: remove uuid in key (to avoid re-mount of image components)
- ticket: [CLNP-2122]
[CLNP-2122]: https://sendbird.atlassian.net/browse/CLNP-2122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: when open-in-channel pressed, scrolling to message should work properly

---

src/modules/GroupChannel/context/GroupChannelProvider.tsx

- Remove `filterMessageList` from GroupChannel module
```tsx
// You can filter message like this.
const GroupChannelPage = () => {
return (<GroupChannel
renderMessage={({ message }) => {
if(message.type === 'filtered') return <></>; // render empty component.
return null; // render default component.
}}
/>);
}
```

chore: remove filterMessageList from GroupChannel module

---

src/modules/ChannelList/dux/__tests__/reducers.spec.js
src/modules/ChannelList/dux/reducers.ts

Fixes: [CLNP-2162](https://sendbird.atlassian.net/browse/CLNP-2162)
The bug has been reported by an external user, @aldenquimby
original PR: https://github.com/sendbird/sendbird-uikit-react/pull/950
This PR duplicates above.
- Fixed a bug in `ChannelList` where `activeChannelUrl` is set but `onChannelSelect` fires with null after loading `ChannelList`
[CLNP-2162]: https://sendbird.atlassian.net/browse/CLNP-2162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bug-fix: Fix a bug in ChannelList where activeChannelUrl is set but onChannelSelect fires with null after loading ChannelList

---

package.json
yarn.lock

v4.10.8 includes following changes:
- **Fixed issue where the parent message retrieved from the cache is a multiple files message and is not parsed correctly**
- **Fixed bug where `onMessagesUpdated()` event do not called if localCacheEnable is `false`**
- _Added appState check when throwing network exception_
- _Fixed a bug where onMentionReceived event is called when a mention is deleted_
- _Fixed a bug: sendbird.min.js does not set the SDK to global object_
- _Fixed bug in LogLevel order_
- _Added extendedMessagePayload to UserMessageCreateParams_

chore: update chat sdk version

---

package.json
src/lib/Sendbird.tsx
src/lib/types.ts
src/lib/utils/uikitConfigMapper.ts
src/modules/App/stories/integrated.stories.js
src/modules/Channel/components/ChannelUI/index.tsx
src/modules/Channel/components/Message/index.tsx
src/modules/Channel/components/MessageInputWrapper/index.tsx
src/modules/CreateChannel/components/InviteUsers/utils.ts
src/modules/GroupChannel/components/GroupChannelUI/index.tsx
src/modules/GroupChannel/components/Message/index.tsx
src/modules/GroupChannel/components/MessageInputWrapper/MessageInputWrapperView.tsx
src/modules/GroupChannel/components/MessageInputWrapper/index.tsx
src/utils/index.ts
yarn.lock

Fixes: [AC-1106](https://sendbird.atlassian.net/browse/AC-1106)
- Added `enableSuggestedReplies` global option
- How to use?
```tsx
<App
appId={appId}
userId={userId}
uikitOptions={{
groupChannel: {
// Below turns on the suggested replies feature. Default value is false.
enableSuggestedReplies: true,
}
}}
/>
```
- `MessageInput` is now being disabled if `channel.lastMessage.extendedMessagePayload['disable_chat_input']` is true
[AC-1106]: https://sendbird.atlassian.net/browse/AC-1106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Apply lastMessage suggestedReplies disable chat input flag

---

src/modules/Channel/components/ChannelUI/index.tsx
src/modules/Channel/components/MessageList/index.tsx
src/modules/GroupChannel/components/GroupChannelUI/GroupChannelUIView.tsx
src/modules/GroupChannel/components/GroupChannelUI/index.tsx

- Fixed a bug where `renderChannelHeader` is not passed properly
ticket: [CLNP-2209]
[CLNP-2209]: https://sendbird.atlassian.net/browse/CLNP-2209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: should pass render props properly in channel module

---

src/utils/__tests__/getMimeTypesUIKitAccepts.spec.ts
src/utils/index.ts

- Fixed `acceptableMimeTypes` to support web standard format.

fix: acceptableMimeTypes to support web standard format.

---

src/lib/hooks/useConnect/index.ts

1. When the `accessToken` is changed, `disconnect` and `connect` are called again.
2. If the customer controls the `accessToken`, the session_key refresh performed by the SDK is canceled(API request cancel) due to the `disconnect` triggered in (1).
3. Even if the `accessToken` has already expired, it is refreshed by the SDK(**SessionHandler**). Therefore, UIKit does not need to rely on this value to handle the connect logic.
ticket: [CLNP-2257]
[CLNP-2257]: https://sendbird.atlassian.net/browse/CLNP-2257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: do not disconnect and connect when the accessToken is changed

---

src/modules/Message/utils/tokens/__tests__/tokenizeUtils.spec.ts
src/modules/Message/utils/tokens/tokenize.ts
src/ui/Word/index.tsx

- The regex has been modified to prevent numbers from being included in the top-level domain.
- In the Word component, the URL validation for the URL type has been removed.
- In the Word component, the use of UUID in the key has been removed.
ticket: [CLNP-2262]
[CLNP-2262]: https://sendbird.atlassian.net/browse/CLNP-2262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: avoid numbered top-level domain

---

src/modules/Channel/context/hooks/useHandleChannelEvents.ts
src/modules/Channel/context/hooks/useHandleChannelPubsubEvents.ts
src/modules/Channel/context/hooks/useHandleReconnect.ts
src/modules/Channel/context/hooks/useInitialMessagesFetch.ts
src/modules/Channel/context/hooks/useSendFileMessageCallback.ts
src/modules/Channel/context/hooks/useSendMessageCallback.ts
src/modules/Channel/context/hooks/useSendMultipleFilesMessage.ts
src/modules/Channel/context/hooks/useSendVoiceMessageCallback.ts
src/modules/Channel/context/utils.ts
src/modules/Thread/context/hooks/useSendFileMessage.ts
src/modules/Thread/context/hooks/useSendVoiceMessageCallback.ts
src/utils/consts.ts

- Now that rendering of MFM messages is consistent, unnecessary delays have been removed.
- Adjusted message delay after message transmission to be consistent.
- Fixed the scroll-to-bottom functionality to work properly with messages sent in threads

fix: ensure consistent scroll to bottom delay after message send in channel module

---

src/modules/Channel/context/const.ts
src/modules/GroupChannel/components/MessageInputWrapper/MessageInputWrapperView.tsx
src/modules/Thread/components/ThreadMessageInput/index.tsx
src/ui/MessageInput/index.tsx
src/ui/MessageInput/utils.ts

[CLNP-2319](https://sendbird.atlassian.net/browse/CLNP-2319)
In a desktop layout, prevent line breaks from occurring even when the 'Enter' key is pressed.
It triggers sending the message.
But in the Mobile layout, this behavior doesn't fit mobile UX.
So need to allow line breaks when users press the 'Enter' key.
* Add a prop `isMobile` to the ui/MessageInput
* Fix the `updateMessage` logic in the MessageInput to apply the line break
[CLNP-2319]: https://sendbird.atlassian.net/browse/CLNP-2319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Allow multiple line in the MessageInput of Mobile env

---

package.json
src/ui/Avatar/__tests__/__snapshots__/Avatar.spec.js.snap
src/ui/ImageRenderer/index.tsx
src/ui/MessageContent/__tests__/__snapshots__/MessageContent.spec.js.snap
src/ui/OGMessageItemBody/__tests__/__snapshots__/OGMessageItemBody.spec.js.snap
yarn.lock

Fixes: [SBISSUE-15134](https://sendbird.atlassian.net/browse/SBISSUE-15134)
- Fixed `ImageRenderer` not to load image if the source URL is null or empty.
[SBISSUE-15134]: https://sendbird.atlassian.net/browse/SBISSUE-15134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CLNP-2332] Not to load image if url is empty or null in ImageRenderer

---

src/modules/Channel/components/ChannelUI/index.tsx
src/modules/Channel/components/MessageInputWrapper/index.tsx
src/modules/Channel/components/MessageList/index.tsx
src/modules/GroupChannel/components/GroupChannelUI/GroupChannelUIView.tsx
src/modules/GroupChannel/components/Message/MessageView.tsx
src/modules/GroupChannel/components/MessageInputWrapper/index.tsx
src/modules/GroupChannel/components/MessageList/index.tsx

- Resolved an infinite loop issue occurring when using the `GroupChannel/components/Message`, `Channel/components/Message` in the `renderMessage` method of the `GroupChannel`,`Channel` module.
- The `renderMessage` method of the `GroupChannel` module no longer nests messages under the `Message` component. If a container element for the `Message` component is needed, use it as follows:
```tsx
import { GroupChannel } from '@sendbird/uikit-react/GroupChannel';
import { Message } from '@sendbird/uikit-react/GroupChannel/components/Message';
const GroupChannelPage = () => {
return (
<GroupChannel
renderMessage={(props) => {
return (
<Message message={props.message}>
<div>{props.message.messageId}</div>
</Message>
)
}}
/>
)
})
```
- The `renderMessage` prop of the `Channel/components/Message` …

fix: message render structure

---

src/hooks/useAsyncRequest.ts
src/modules/ChannelSettings/context/ChannelSettingsProvider.tsx

Channel requests should occur after the sdk is initialized.
ticket: [CLNP-2440]
[CLNP-2440]: https://sendbird.atlassian.net/browse/CLNP-2440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: channel requests should occur after the sdk is initialized

---

src/ui/MessageInput/index.tsx

- When `body.offsetHeight` is 0, the height of the input is not accurately calculated.
from: https://sendbird.slack.com/archives/C0585965FFA/p1709545490650569

fix: add default chat view height to calculate input max height

---

src/utils/index.ts

[CLNP-2528](https://sendbird.atlassian.net/browse/CLNP-2528)
* Display the normal `FileMessage` for the `.mov` video
[CLNP-2528]: https://sendbird.atlassian.net/browse/CLNP-2528?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Display the normal file message for the mov video

---

src/modules/ChannelSettings/components/ModerationPanel/BannedUsersModal.tsx
src/modules/ChannelSettings/components/ModerationPanel/MembersModal.tsx
src/modules/ChannelSettings/components/ModerationPanel/MutedMembersModal.tsx
src/modules/ChannelSettings/components/ModerationPanel/OperatorsModal.tsx
src/modules/ChannelSettings/components/ModerationPanel/index.tsx
src/ui/MobileMenu/ReactedMembersBottomSheet.tsx
src/ui/Modal/index.scss
src/ui/UserListItem/index.tsx

* Fixed a specific environment issue (Android emulator) - Resolved an issue in modals used in ChannelSettings such as MembersModal, MutedMembersModal, OperatorsModal, BannedUsersModal, where even when scrolling to the end, additional members were not fetched
* Fixed a specific environment issue (Safari) - Similarly addressed an issue within lists inside modals, where overflow occurred instead of scrolling
* Deprecated the `onClick` prop in `UserListItem` and added `onUserAvatarClick`. The deprecated prop will be removed in the next major version

fix: Scroll issue in the member list of the Modal

---

src/modules/ChannelSettings/components/ModerationPanel/BannedUsersModal.tsx

[SBISSUE-15260](https://sendbird.atlassian.net/browse/SBISSUE-15260)
* Modify the incorrect stringSet on the BannedUsersModal
* `CHANNEL_SETTING__MUTED_MEMBERS__TITLE` to `CHANNEL_SETTING__BANNED_MEMBERS__TITLE`
* `CHANNEL_SETTING__MODERATION__BAN` to `CHANNEL_SETTING__MODERATION__UNBAN`
* also fixed the `dataSbId` of the MenuItem: `channel_setting_banned_user_context_menu_ban` to `channel_setting_banned_user_context_menu_unban`
[SBISSUE-15260]: https://sendbird.atlassian.net/browse/SBISSUE-15260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Modify the incorrect stringSet on the Banned user list

---

src/modules/ChannelSettings/components/ModerationPanel/AddOperatorsModal.tsx
src/modules/ChannelSettings/components/ModerationPanel/MutedMembersModal.tsx

* Fixed a specific environment issue (Android emulator) - Resolved an issue in modals used in ChannelSettings such as MembersModal, MutedMembersModal, OperatorsModal, BannedUsersModal, **AddOperatorsModal**, where even when scrolling to the end, additional members were not fetched

fix: Fix scroll issue on the AddOperatorsModal and MutedMembersModal

---

CHANGELOG.md
package.json
rollup.module-exports.mjs

* Add a `renderHeader` props to the ChannelSettingsUIProps
```
<ChannelSettingsUI
renderHeader={() => ...}
/>
```
* Deprecated the `onClick` prop in `UserListItem` and added `onUserAvatarClick`. The deprecated prop will be removed in the next major version
* Added throttling in `mute/unmute` operation
* Added throttling in `add/remove` operator operation
* Fixed that the Chat SDK is not initialized more than once
* Display the normal `FileMessage` for the `.mov` video
* Show `X` button on the ModalHeader of mobile mode
* Modify the incorrect stringSet on the BannedUsersModal
* `CHANNEL_SETTING__MUTED_MEMBERS__TITLE` to `CHANNEL_SETTING__BANNED_MEMBERS__TITLE`
* `CHANNEL_SETTING__MODERATION__BAN` to `CHANNEL_SETTING__MODERATION__UNBAN`
* also modified the dataSbId, …

release v3.13.2

---

src/ui/MessageTemplate/messageTemplateErrorBoundary.tsx
src/ui/TemplateMessageItemBody/index.tsx

Fixes: [<TICKET_ID>](https://sendbird.atlassian.net/browse/<TICKET_ID>)
-

bug-fix: Add fallback logic on template rendering error

---

src/ui/Carousel/index.tsx
src/ui/MessageTemplate/index.scss

- Fixed a bug where swiping carousel in mobile view displaying flickering effect
- Added missing default font-family value to template root

bug-fix: Fix carousel swipe flickering issue + Add missing default font-family to template root

---

CHANGELOG.md
package.json
scripts/steps.md

* Fixed a bug where swiping `Carousel` in mobile view displaying flickering effect
* Added missing default `font-family` value to `sendbird-message-template__root`

v3.14.0-beta.2

---

src/modules/GroupChannel/components/FileViewer/FileViewerView.tsx
src/modules/GroupChannel/components/FileViewer/index.tsx
src/modules/GroupChannel/components/Message/MessageView.tsx
src/modules/GroupChannel/components/Message/index.tsx
src/modules/GroupChannel/context/GroupChannelProvider.tsx
src/modules/GroupChannel/index.tsx
src/modules/Thread/components/ParentMessageInfo/ParentMessageInfoItem.tsx
src/modules/Thread/components/ParentMessageInfo/index.tsx
src/modules/Thread/components/ThreadList/ThreadListItem.tsx
src/modules/Thread/components/ThreadList/ThreadListItemContent.tsx
src/modules/Thread/context/ThreadProvider.tsx
src/ui/FileMessageItemBody/index.tsx
src/ui/FileViewer/index.tsx
src/ui/FileViewer/types.ts
src/ui/MessageContent/MessageBody/index.tsx
src/ui/MessageContent/index.tsx
src/ui/MobileMenu/MobileBottomSheet.tsx
src/ui/MobileMenu/MobileContextMenu.tsx
src/ui/MobileMenu/index.tsx
src/ui/MobileMenu/types.ts
src/ui/MultipleFilesMessageItemBody/index.tsx

[CLNP-2565](https://sendbird.atlassian.net/browse/CLNP-2565)
* There was no interface available to decide whether to proceed with the file download or not
* Added `onBeforeDownloadFileMessage` to the `<GroupChannel />` and `<Thread />` modules
* Added `onDownloadClick` to the `FileViewer`, `FileViewerView`, `MobileBottomSheet`, `MobileContextMenu`, and `MobileMenu`
```tsx
const ONE_MB = 1024 * 1024;
/**
* Use this list to check if it's displayed as a ThumbnailMessage.
* (https://github.com/sendbird/sendbird-uikit-react/blob/main/src/utils/index.ts)
*/
const ThumbnailMessageTypes = [
'image/jpeg',
'image/jpg',
'image/png',
'image/gif',
'image/svg+xml',
'image/webp', // not supported in IE
'video/mpeg',
'video/ogg',
'video/webm',
'video/mp4',
];
<GroupChannel // or Thread …
```

feature: Add an interface for confirming file download

---

src/lib/Sendbird.tsx

* Replace the root components order because dropdown menu is hided by modals
before
after

fix: Replace the root components order

---

CHANGELOG.md
package.json

* Added a `renderMenuItem` to the `MessageMenu` component
* How to use?
```tsx
<GroupChannel
renderMessageContent={(props) => (
<MessageContent
{...props}
renderMessageMenu={(props) => (
<MessageMenu
{...props}
renderMenuItem={(props) => {
const {
className,
onClick,
dataSbId,
disable,
text,
} = props;
return <MenuItem /> // Render Custom Menu Item
}}
/>
)}
/>
)}
/>
```
* Added `onBeforeDownloadFileMessage` to the `<GroupChannel />` and `<Thread />` modules
* How to use?
```tsx
const ONE_MB = 1024 * 1024;
/**
* Use this list to check if it's displayed as a ThumbnailMessage.
* (https://github.com/sendbird/sendbird-uikit-react/blob/main/src/utils/index.ts)
*/
const ThumbnailMessageTypes = [
'image/jpeg',
'image/jpg',
'image/png',
'image/gif',
'image/svg+xml',
'image/webp', // not supported …
```

release: v3.13.3

---

src/lib/dux/appInfo/utils.ts
src/ui/MessageContent/MessageBody/index.tsx
src/ui/MessageContent/index.tsx
src/ui/MessageTemplate/messageTemplateErrorBoundary.tsx
src/ui/TemplateMessageItemBody/FallbackTemplateMessageItemBody.tsx
src/ui/TemplateMessageItemBody/index.tsx
src/ui/TemplateMessageItemBody/types.ts
src/utils/index.ts

1. Carousel templates created with direct simple templates in items (no reservations keys) should be suppported as fallback logic.
ex.
2. timestamp location of carousel template body must be dynamically updated.
3. For composite template, template version should be max of (composite + its simple templstes).

feat: support carousel template with simple templates

---

src/ui/TemplateMessageItemBody/index.tsx

- Fix bug where argb conversion step is skipped for carousel without reservation key
- string to numeric conversion skipped

bug-fix: Fix bug where argb conversion step is skipped for carousel without reservation key

---

CHANGELOG.md
package.json

* Add a logger to the GroupChannelProvider for failing get channel
* Reduce the OGTag height in the mobile layout
* Prevent force refreshing of the ChannelSettings
* Keep context menu when failing the member operations (register/unregister operator, mute/unmute)
* Keep profile image during member operations on the MembersModal

release: v3.13.5

---

src/modules/GroupChannel/components/GroupChannelUI/index.scss
src/modules/GroupChannel/components/Message/MessageView.tsx
src/modules/OpenChannel/components/OpenChannelUI/open-channel-ui.scss
src/ui/ThreadReplies/index.scss

Confirmed that this change doesn't make any effect
* Fix typo
* Remove CSS `order` props because it's meaningless

chore: fix typo and unused css props

---

src/modules/Channel/context/hooks/useSendFileMessageCallback.ts
src/modules/OpenChannel/components/OpenChannelMessage/index.tsx
src/modules/OpenChannel/components/OpenChannelMessageList/index.tsx
src/modules/OpenChannel/components/OpenChannelUI/index.tsx
src/modules/OpenChannel/context/hooks/useFileUploadCallback.tsx
src/modules/OpenChannel/index.tsx
src/modules/Thread/context/hooks/useSendFileMessage.ts
src/modules/Thread/context/hooks/useSendVoiceMessageCallback.ts
src/ui/MessageContent/index.tsx
src/ui/QuoteMessageInput/QuoteMessageThumbnail.tsx
src/utils/index.ts

- Update the type of `renderMessage` in the OpenChannel module.
- Deprecate the `renderInput` prop and add a new `renderMessageInput` prop.
- Refactor `isXXXMessage` utils and removed redundant type-casting

fix: update open channel interface properly

---

CHANGELOG.md
package.json
yarn.lock

* Fixed a bug where injecting an optional property with null value not rendering the expected default component
* Updated the type of renderMessage in the OpenChannel module
* Deprecated the renderInput prop and add a new `renderMessageInput` prop

release v3.14.1

---

src/modules/Thread/components/ParentMessageInfo/ParentMessageInfoItem.tsx
src/ui/FileMessageItemBody/index.tsx
src/ui/LinkLabel/index.tsx
src/ui/OGMessageItemBody/__tests__/OGMessageItemBody.spec.js
src/ui/OGMessageItemBody/__tests__/__snapshots__/OGMessageItemBody.spec.js.snap
src/ui/OGMessageItemBody/index.tsx
src/ui/OpenchannelFileMessage/index.tsx
src/ui/OpenchannelOGMessage/index.tsx
src/utils/utils.ts

- Removed image section in the OGMessageItemBody if there is no og image
- Fixed that safely opens URL to prevent XSS
tickets: [CLNP-2924] [CLNP-2843]
[CLNP-2924]: https://sendbird.atlassian.net/browse/CLNP-2924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CLNP-2843]: https://sendbird.atlassian.net/browse/CLNP-2843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: remove image section in og message if there is no og image

---

CHANGELOG.md
package.json

* Fixed a bug where right padding is added to messages sent by me in mobile devices
* Removed image section in the OGMessageItemBody if there is no og image
* Fixed that safely opens URL to prevent XSS
* Fixed that copying URI-list issue in the iOS device/Safari
* Fixed that channel badge count is not updated on iOS Webview

release: v3.14.2

---

src/lib/Sendbird.tsx
src/lib/types.ts
src/lib/utils/uikitConfigMapper.ts
src/modules/OpenChannel/context/hooks/useFileUploadCallback.tsx
src/utils/compressImages.ts

[CLNP-2718](https://sendbird.atlassian.net/browse/CLNP-2718)
[SBISSUE-14611](https://sendbird.atlassian.net/browse/SBISSUE-14611)
* Add `outputFormat` to the image compression options
```tsx
...
imageCompression={{
outputFormat: 'preserve' | 'png' | 'jpeg',
}}
>
```
[CLNP-2718]: https://sendbird.atlassian.net/browse/CLNP-2718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SBISSUE-14611]: https://sendbird.atlassian.net/browse/SBISSUE-14611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Support setting output file type in image compression process

---

src/modules/GroupChannel/components/MessageInputWrapper/index.scss
src/modules/GroupChannel/components/MessageList/index.scss

* Set the message list padding with `12px` in the mobile mode

fix: Set the message list padding with 12px in the mobile layout

---

src/utils/compressImages.ts

* it couldn't convert to the target fileType, if original file's name doesn't contain the file extension

fix: Add target subType to fileName in every case

---

.storybook/main.js

The updated TypeScript version is not compatible with the `@storybook/react-docgen-typescript-plugin`.
Removing the unused `addon-docs` in Storybook resolves this issue.

fix: remove unused addon-docs from storybook addons

---

src/modules/GroupChannel/components/MessageList/index.scss
src/modules/GroupChannel/components/SuggestedReplies/index.scss
src/modules/GroupChannel/components/SuggestedReplies/index.tsx
src/styles/_variables.scss

* Follow the Scaled Trunk-Based Development workflow(https://trunkbaseddevelopment.com/)
* Branch naming format -> `{type}/TICKET_ID/description`
* Where type = `feat` / `feature` / `fix` / `chore` / `doc` / `release`
* Always receive PR review approvals
* Rebase your branch with the main branch, and wait for CI to pass
* Follow the provided template for both the PR description and squashing to the main branch
* The template is very similar to conventional commits. [Read More](https://www.conventionalcommits.org/en/v1.0.0/)
Template
```
// Section: PR description (Optional)
Add a brief description of the changes that …
```

chore: horizontal scroll view

---

apps/testing/src/utils/paramsBuilder.ts
src/hooks/VoiceRecorder/index.tsx
src/lib/Sendbird.tsx
src/lib/types.ts
src/lib/utils/uikitConfigMapper.ts
src/modules/App/AppLayout.tsx
src/modules/App/index.tsx
src/modules/Channel/context/ChannelProvider.tsx
src/modules/ChannelList/context/ChannelListProvider.tsx
src/modules/ChannelSettings/context/ChannelSettingsProvider.tsx
src/modules/GroupChannel/components/Message/MessageView.tsx
src/modules/GroupChannel/components/MessageInputWrapper/MessageInputWrapperView.tsx
src/modules/GroupChannel/context/GroupChannelProvider.tsx
src/modules/GroupChannelList/components/GroupChannelListItem/GroupChannelListItemView.tsx
src/modules/GroupChannelList/context/GroupChannelListProvider.tsx
src/modules/Thread/components/ParentMessageInfo/ParentMessageInfoItem.tsx
src/modules/Thread/components/ParentMessageInfo/index.tsx
src/modules/Thread/components/ThreadList/ThreadListItem.tsx
src/modules/Thread/components/ThreadList/index.tsx
src/modules/Thread/components/ThreadMessageInput/index.tsx
src/modules/Thread/context/ThreadProvider.tsx
src/ui/MessageContent/MessageBody/index.tsx

- We agreed with the team to deprecate legacy configs, but since they were not handled, I've deprecated them.
```ts
/** @deprecated Please use `common.enableUsingDefaultUserProfile` instead * */
disableUserProfile: boolean;
/** @deprecated Please use `groupChannel.enableReactions` instead * */
isReactionEnabled: boolean;
/** @deprecated Please use `groupChannel.enableMention` instead * */
isMentionEnabled: boolean;
/** @deprecated Please use `groupChannel.enableVoiceMessage` instead * */
isVoiceMessageEnabled?: boolean;
/** @deprecated Please use `groupChannel.replyType` instead * */
replyType: ReplyType;
/** @deprecated Please use `groupChannelSettings.enableMessageSearch` instead * */
showSearchIcon?: boolean;
/** @deprecated Please use `groupChannelList.enableTypingIndicator` instead * …
```

refactor: mark deprecated in legacy configs where marks are missing

---

src/lib/types.ts
src/ui/Modal/index.tsx
src/utils/utils.ts

- Added `modal.onMounted` handler to global eventHandlers.
This event handler is triggered within the `useEffect` of the Modal component at mounting time.
---
Example usage
```tsx
const App = () => {
return (
eventHandlers={{
modal: {
onMounted({ id, close }) {
// Push the state to prevent the browser's back button press
window.history.pushState({ id }, '');
// Close the modal if the back button is pressed
const onPopState = (e: PopStateEvent) => {
e.preventDefault(); // Prevents the default back action
close(); // Closes the modal
};
window.addEventListener('popstate', onPopState);
// Cleanup function
return () => {
// Clear the current state when the modal is closed without using the back button
if (window.history.state?.id === id) window.history.back(); …
```

feat: added modal.onMounted handler

---

src/modules/GroupChannel/components/Message/MessageView.tsx

- Fix scroll bottom not working properly when last message is updated with suggested replies
ticket: [AC-2222]
[AC-2222]: https://sendbird.atlassian.net/browse/AC-2222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: scroll view when message height changed with suggested replies

---

rollup.config.mjs

Fixes: [CLNP-3084](https://sendbird.atlassian.net/browse/CLNP-3084)
- Fixed a bug where import statements are not located at the top of the extracted index.css file
[CLNP-3084]: https://sendbird.atlassian.net/browse/CLNP-3084?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Move import statements to the top of extracted index.css file.

---

src/ui/MessageInput/index.tsx

- Fix the issue where the mention feature does not work properly in the input component
- Fix the issue where unnecessary spaces are added between mention texts when editing an already mentioned message

fix: mention

---

src/modules/ChannelSettings/components/ChannelSettingsUI/ChannelSettingsHeader.tsx
src/modules/ChannelSettings/index.tsx

[CLNP-3211](https://sendbird.atlassian.net/browse/CLNP-3211)
* Clean up the props of the ChannelSettings for applying missed props
* Export default the ChannelSettingsHeader component
[CLNP-3211]: https://sendbird.atlassian.net/browse/CLNP-3211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Clean up the props of the ChannelSettings

---

src/utils/compressImages.ts

[CLNP-3111](https://sendbird.atlassian.net/browse/CLNP-3111)
The files are not sent when failing to compress them, because the files that failed to compress have not added into the sending file list.
* Put the files that failed to compress into the compressedFiles
* Fixed issue where files that failed to compress were not being sent
[CLNP-3111]: https://sendbird.atlassian.net/browse/CLNP-3111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Put the files that failed to compress into the compressedFiles

---

src/modules/GroupChannel/components/MessageInputWrapper/MessageInputWrapperView.tsx
src/ui/Label/stringSet.ts

Fixes: [AC-2293](https://sendbird.atlassian.net/browse/AC-2293)
- Added `MESSAGE_INPUT__PLACE_HOLDER__FROZEN` to `StringSet`
[AC-2293]: https://sendbird.atlassian.net/browse/AC-2293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added MESSAGE_INPUT__PLACE_HOLDER__FROZEN to StringSet

---

.github/workflows/package-publish.yml

Our current release steps are like below. 
1. Preparation
a. Create a release branch; `release/v{version}`
b. Update package.json
c. Write CHANGELOG
d. Push to remote
e. create a PR
2. Run `/bot create ticket` to create a release ticket and get an approval from a manager
3. Once 2 is done, run `yarn run build` -> `cd dist` -> `yarn npm publish`
This workflow will cover step 3. Step 1 & 2 need to be done manually as we've done.
```mermaid
graph TD
A[Start: Run workflow] --> B[Check if release branch exists]
B --> C{npm_tag provided?}
C -- Yes --> E[Update version in package.json]
C -- No --> F[Install and Build]
E --> F
F --> G[Publish to npm]
G --> H{npm_tag provided?}
H -- Yes --> I[Publish with tag] --> End
H -- No --> J[Publish without tag]
J --> L[Tag new target and push to origin]
L …
```

[CLNP-3380] chore: add release automation workflow

---

src/ui/MessageInput/index.tsx

- Auto focus message input on disabled set to false
related to:
https://github.com/sendbird/chat-ai-widget/pull/237
Fixes: [AC-2293](https://sendbird.atlassian.net/browse/AC-2293)
[Sendbird AI ChatBot (7).webm](https://github.com/sendbird/sendbird-uikit-react/assets/16806397/aa227395-bbc7-4272-ab20-488ae1f3e275)
for some reason recording is now showing. go here instead:
https://sendbird.slack.com/archives/C0585965FFA/p1716450373337189?thread_ts=1716364563.896959&cid=C0585965FFA
[AC-2293]: https://sendbird.atlassian.net/browse/AC-2293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Auto focus message input on disabled set to false

---

src/modules/GroupChannel/components/MessageList/InfiniteList.tsx
src/modules/GroupChannel/components/MessageList/index.tsx

- scroll to bottom is not working properly in the widget after applying the list refactoring
https://github.com/sendbird/sendbird-uikit-react/assets/26326015/bb5c3d5e-923e-4ec2-864a-62905d8a2558

fix: scroll to the bottom of the list when mounted before painting

---

src/lib/MediaQueryContext.tsx
src/lib/hooks/useConnect/__test__/data.mocks.ts
src/lib/hooks/useConnect/__test__/setupConnection.spec.ts
src/lib/hooks/useConnect/index.ts
src/lib/hooks/useConnect/setupConnection.ts
src/lib/types.ts

- When attempting to `connect` with an expired or invalid session token, an error will be returned.
In such cases, the error message is checked, and if a `SessionHandler` is available, it will extract a valid session token and retry the `connect`.
- The `eventHandlers.connection.onFailed(SendbirdError)` will not be called when userId and appId are missing.
This should not be triggered as it is not related to connection errors. (In the first place, this logic should not be reached without an app ID and user ID.)
- Added `eventHandlers.connection.onConnected(User)`
https://github.com/sendbird/sendbird-uikit-react/assets/26326015/ab529a97-7fe8-4e47-aa2c-9047886f22c8
- ticket: [AC-2476]
[AC-2476]: https://sendbird.atlassian.net/browse/AC-2476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhY …

fix: retry connect when failed with token expired error

---

src/ui/MessageInput/index.tsx

contentEditable does not work as expected in mobile WebKit (Safari).
Events and properties related to composing, necessary for combining characters like Hangul, do not seem to be passed to IME properly.
When resetting the input with innerHTML, the previous context should be cleared.
However, if the last text of the previous input was a composable string, it appears in the next input.
1. If the last string is not a composable string, it is not affected. This is why preventing the `e.preventDefault()` call when sending a message with Enter prevents the bug, as the Enter (newline) string is the last text in the IME context and is not affected by this bug.
2. The bug can be avoided by resetting the IME context(blur or moving caret) of the last string. This is similar to how moving the cursor …

fix: add workaround to reset IME in mobile webkit

---

src/stories/common/getSampleChannel.ts
src/stories/common/useSampleChannel.ts
src/stories/modules/ChannelSettings.stories.tsx
src/stories/modules/GroupChannel.stories.tsx
src/stories/modules/MessageSearch.stories.tsx

[CLNP-3433](https://sendbird.atlassian.net/browse/CLNP-3433)
```
Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)
```
[CLNP-3433]: https://sendbird.atlassian.net/browse/CLNP-3433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Use await inside of the Component, not in global scope

---

src/modules/GroupChannel/components/FileViewer/FileViewerView.tsx
src/modules/OpenChannel/components/OpenChannelMessage/utils.ts
src/ui/FileViewer/types.ts
src/ui/MessageInput/index.tsx
src/ui/ThumbnailMessageItemBody/__tests__/ThumbnailMessageItemBody.spec.js
src/utils/__tests__/utils.spec.ts
src/utils/browser.ts
src/utils/index.ts
src/utils/utils.ts

Addresses https://sendbird.atlassian.net/browse/SBISSUE-16031?focusedCommentId=270601 
Quoted a comment left by @jayden-lee-sb
>Not supporting ‘MOV’: This is not a bug since we display ‘MOV’ as a normal file message exactly described in the changelog(v3.13.2) → But we need to consider supporting ‘ThumbnailMessage’ only for some browser environments like Safari where MOV can be displayed without any problem

feat: support mov file type rendering only in Safari browser

---

src/modules/GroupChannel/components/SuggestedReplies/index.scss
src/modules/GroupChannel/components/SuggestedReplies/index.tsx

Fixes: [AC-2521](https://sendbird.atlassian.net/browse/AC-2521)
- Fixed a bug where horizontal suggested reply items contents are not wrapping to multiple lines.
https://www.figma.com/design/SVbXU00FhjztekD8AiVukK/UIKit_Work-file_React?node-id=2393-13688&t=cyEn8F21R1sNrdNx-0
[AC-2521]: https://sendbird.atlassian.net/browse/AC-2521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Fixed a bug where horizontal suggested reply items contents are not wrapping to multiple lines.

---

CHANGELOG.md
package.json

- Resolved the issue of storybook user leaving the channel
- Added a workaround to reset IME in mobile webkit for better input handling
- This fix involves creating a ghost input to manage focus transitions, preventing the virtual keyboard from closing and ensuring the proper composition of characters like Hangul
- The ghost input is used to reset the IME context, and focus is moved back to the original input using `requestAnimationFrame` to avoid delays
- Retry connection when failed with a token expired error
- Ensure scroll to the bottom of the list when mounted before painting
- Minor bug fixes and adjustments for `SuggestedReplyItem` component:
- Fixed a bug where horizontal suggested reply items contents are not wrapping to multiple lines
- Adjusted bubble size
- Added missing …

release: v3.14.8

---

src/modules/ChannelList/dux/__tests__/reducers.spec.js
src/modules/ChannelList/dux/reducers.ts
src/utils/index.ts

Fixes https://sendbird.atlassian.net/browse/CLNP-3607
https://github.com/sendbird/sendbird-uikit-react/assets/10060731/3d19dc9e-a1f1-46b6-8196-09a9ecbdeec4

fix: prevent the newly created channel from being filtered out from ChannelList

---

src/hooks/VoicePlayer/__tests__/utils.spec.ts
src/hooks/VoicePlayer/index.tsx
src/hooks/VoicePlayer/useVoicePlayer.tsx
src/hooks/VoicePlayer/utils.ts
src/ui/VoiceMessageItemBody/index.tsx
src/utils/consts.ts

Fixes https://sendbird.atlassian.net/browse/CLNP-2997
Voice audio files created on platforms other than the web, such as Android/iOS, are in M4A format. When attempting to convert these M4A files to `audio/mp3` or `audio/mpeg` format for playback on the web, Safari browser cannot find the correct codec and throws an error: `Unhandled Promise Rejection: NotSupportedError: The operation is not supported.`
This results in the file not being playable.
For Safari browser only, if the message file type is M4A, ensure it is played in this format. However, the file must be parsed as `audio/x-m4a` instead of `audio/m4a` to be correctly played in the Safari browser.
| Browser  | .m4a file(created in iOS / Android UIKit) | .mp3 File(created in React UIKit) |
|----------|----------|----------|
| …

[CLNP: 2977] fix: m4a format audio file playing in Safari

---

.storybook/main.ts
apps/testing/vite.config.ts
package.json
rollup.config.mjs
src/modules/App/AppLayout.tsx
src/modules/App/DesktopLayout.tsx
src/modules/App/MobileLayout.tsx
src/modules/App/const.ts
src/modules/App/hooks/useApplyTextDirection.ts
src/ui/ContextMenu/EmojiListItems.tsx
src/ui/ContextMenu/MenuItems.tsx
src/ui/ContextMenu/index.scss
src/ui/ContextMenu/index.tsx
src/ui/FileViewer/index.scss
src/ui/Toggle/index.scss
yarn.lock

Applied [postcss-rtlcss plugin](https://github.com/elchininet/postcss-rtlcss) for the better RTL support without tedious manual CSS style modifications. 
postcss-rtlcss automates the conversion of LTR CSS to RTL, ensuring consistency and reducing manual errors.
It automates CSS transformation by converting LTR styles to RTL, ensuring proper alignment and display in RTL mode.
You can play around in here https://elchininet.github.io/postcss-rtlcss/ to see what kind of modifications could be made by this plugin.

[CLNP-3692] Apply postcss-rtlcss plugin for RTL support

---

src/ui/MessageMenu/index.scss
src/ui/MessageMenu/items.tsx
src/ui/MobileMenu/MobileBottomSheet.tsx
src/ui/MobileMenu/MobileContextMenu.tsx
src/ui/MobileMenu/bottomSheetMenuItem.tsx
src/ui/MobileMenu/types.ts

[CLNP-3379](https://sendbird.atlassian.net/browse/CLNP-3379)
* Added `renderMenuItems` to `MobileBottomSheet` and `MobileContextMenu` components.
Now you can use the pre-build menu items to make a custom message menu via `renderMobileMenuOnLongPress` of `MessageContent` component
[CLNP-3379]: https://sendbird.atlassian.net/browse/CLNP-3379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: Support customizing message menu on mobile

---

src/lib/hooks/useTheme.ts
src/lib/utils/__tests__/colorMapper.spec.ts
src/lib/utils/colorMapper.ts
src/modules/App/index.tsx

Addresses https://sendbird.atlassian.net/browse/CLNP-3254 
Users who want to customize the color set can use below new more descriptive color name instead of `001` / `002` ... `005`. I added a color map parsing util function; `mapColorKeys` to ,a the new & existing color name but we'll be still using the existing names. Refer to [this Slack thread](https://sendbird.slack.com/archives/G01290GCDCN/p1716881782621069) for more detailed discussion.
1. Primary, Secondary, Error, information 
```
Primary-500 -> Primary-extra dark
Primary-400 -> Primary-dark
Primary-300 -> Primary-main
Primary-200 -> Primary-light
Primary-100 -> Primary-extra light
Secondary-500 -> Secondary-extra dark
Secondary-400 -> Secondary-dark
Secondary-300 -> Secondary-main
Secondary-200 -> Secondary-light
Secondary-100 …
```

[CLNP-3254] feat: support descriptive color name 

---

rollup.module-exports.mjs
src/ui/MobileMenu/index.tsx

Export the MobileMenu
```tsx
import { MobileMenu, MobileContextMenu, MobileBottomSheet } from '@sendbird/uikit-react/ui/MobileMenu';
```

fix: Export the UI MobileMenu

---

src/modules/Message/utils/tokens/__tests__/asSafeUrl.spec.ts
src/modules/Message/utils/tokens/tokenize.ts

discussion:
https://sendbird.slack.com/archives/G01290GCDCN/p1718676602610299

fix: Fixed a bug where spreading matchAll() result not working with built files

---

src/ui/Accordion/index.scss

I found one more after #1147 merged 😅
**as-is** 
**to-be**

fix: accordion chevron direction in RTL

---

.storybook/main.ts
apps/testing/src/utils/paramsBuilder.ts
apps/testing/vite.config.ts
package.json
rollup.config.mjs
src/lib/Sendbird.tsx
src/lib/types.ts
src/modules/App/AppLayout.tsx
src/modules/App/DesktopLayout.tsx
src/modules/App/MobileLayout.tsx
src/modules/App/const.ts
src/modules/App/hooks/useApplyTextDirection.ts
src/modules/App/index.tsx
src/modules/App/types.ts
src/modules/ChannelSettings/components/ChannelSettingsUI/channel-settings-ui.scss
src/modules/ChannelSettings/components/UserPanel/user-panel.scss
src/stories/apps/GroupChannelApp.stories.tsx
src/types.ts
src/ui/Accordion/index.scss
src/ui/ContextMenu/MenuItems.tsx
src/ui/ContextMenu/index.scss
src/ui/ContextMenu/index.tsx
src/ui/FileViewer/index.scss
src/ui/MessageSearchItem/index.scss
src/ui/ThreadReplies/index.scss
src/ui/Toggle/index.scss
yarn.lock

Addresses https://sendbird.atlassian.net/browse/CLNP-3543 
I added `htmlTextDirection` prop(The original element attribute name is `dir` but I chose to be more elaborate in our app) to SendbirdProvider to support Right To Left(RTL) text direction display for the middle east customers. 
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dir

[CLNP-3674] feat: RTL(Right To Left) display support

---

rollup.module-exports.mjs
src/modules/ChannelSettings/components/ChannelSettingsUI/MenuItem.tsx
src/modules/ChannelSettings/components/ChannelSettingsUI/MenuListByRole.tsx
src/modules/ChannelSettings/components/ChannelSettingsUI/hooks/useMenuItems.tsx
src/modules/ChannelSettings/components/ChannelSettingsUI/index.tsx
src/modules/ChannelSettings/components/ModerationPanel/admin-panel.scss
src/modules/ChannelSettings/components/ModerationPanel/index.tsx
src/modules/ChannelSettings/components/UserPanel/index.tsx
src/ui/Label/index.tsx

Addresses [CLNP-3259](https://sendbird.atlassian.net/browse/CLNP-3259)
This change addresses the need to easily add new settings and show/hide existing settings in the Channel Settings UI.
Check the comments from [CLNP-2384](https://sendbird.atlassian.net/browse/CLNP-2384)
- Ability to add new settings:
- The previous implementation made it impossible to reuse existing menus because some components were not exported.
- This meant it was only an option when completely changing the settings.
- Ability to show/hide existing settings:
- Concerns were raised about guiding users to control visibility using CSS, which is not a best practice and considered hacky.
- Using CSS overrides for visibility can lead to issues with internal changes such as class name or structure modifications, …

[CLNP-3259] refactor: enable ChannelSetting > MenuItem customization

---

src/lib/Sendbird.tsx
src/lib/types.ts

Addresses https://sendbird.atlassian.net/browse/CLNP-3581
- A deprecation warning from `uikit-tools`
- from `lib/types.ts`

feat: deprecate uikitOption.groupChannel.enableReactionsSupergroup

---

CHANGELOG.md
package.json
src/ui/UserListItemMenu/index.tsx

- **RTL Support**
- Added `htmlTextDirection` prop to `SendbirdProvider` to support Right-To-Left (RTL) text direction for Middle East customers. [Read more](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dir).
```tsx
import ar from 'date-fns/locale/ar';
...
htmlTextDirection={'rtl' | 'ltr'}
// Setting a proper value to dateLocale would be necessary
dateLocale={ar}
>
```
- **DX Improvements: ChannelSetting SettingMenu**
- Added new components and hooks to make the menu items in the `ChannelSettingsUI` more modular and customizable.
- New Files:
- `useMenuItems.tsx`: Custom hook for menu items based on user roles.
- `MenuItem.tsx`: Reusable and customizable menu item component.
- `MenuListByRole.tsx`: Renders a list of menu items based on …

release: v3.14.12

---

rollup.module-exports.mjs
src/modules/ChannelSettings/components/ChannelSettingsUI/MenuListByRole.tsx
src/modules/ChannelSettings/components/ChannelSettingsUI/hooks/useMenuItems.tsx
src/modules/ChannelSettings/components/ChannelSettingsUI/index.tsx
src/modules/ChannelSettings/context/ChannelSettingsProvider.tsx
src/modules/GroupChannelList/context/GroupChannelListProvider.tsx

- Improve stability about useMenuItems
- Export the ChannelListQueryParamsType
- Move the renderUserListItem props to the Provider from UI comp
- Export the component `ChannelSettingsMenuItem`

chore: Improve stability about useMenuItems

---

rollup.config.mjs

https://sendbird.atlassian.net/browse/CLNP-4373
Aims to enhance the compatibility between ESM and CJS by updating the Rollup configuration to include  `interop: "compat"` setting for the CommonJS output. 
This change ensures better interoperability and resolves potential issues when using the @sendbird/chat SDK in mixed module environments (ESM <-> CJS).
```
const chatSDK = require('path-to-chat-sdk');
console.log(chatSDK);
console.log(chatSDK.default);
if (chatSDK.default) {
chatSDK.default.init();
} else {
chatSDK.init();
}
```

chore: improve ESM <-> CJS compatibility with rollup interop: "compat"

---

src/modules/GroupChannel/index.tsx
src/modules/Thread/components/ParentMessageInfo/index.scss
src/modules/Thread/components/ParentMessageInfo/index.tsx
src/modules/Thread/components/ThreadList/ThreadListItem.tsx
src/modules/Thread/components/ThreadList/ThreadListItemContent.tsx
src/modules/Thread/components/ThreadList/index.tsx
src/modules/Thread/components/ThreadUI/index.tsx
src/modules/Thread/components/ThreadUI/useMemorizedParentMessageInfo.tsx
src/modules/Thread/index.tsx

[CLNP-4083](https://sendbird.atlassian.net/browse/CLNP-4083)
* Supported message menu customization in Thread
* Added `renderMessageMenu` and `renderEmojiMenu` props to the `<ParentMessageInfo />`, `<ThreadListItem />`, and `<ThreadListItemContent />` components.
How to use?
```tsx
<Thread
renderMessage={(props) => <ThreadListItem {...props} renderMessageMenu={(props) => (
// render your custom message menu here
<MessageMenu {...props} renderMenuItems={({ items }) => (
<>
<items.CopyMenuItem />
<items.DeleteMenuItem />
</>
)} />
)} />}
/>
```
[CLNP-4083]: https://sendbird.atlassian.net/browse/CLNP-4083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: Apply message menu to the Thread module

---

src/ui/Modal/index.scss

Dropped a changed added by #1173 since we internally decided not to make this change. 
https://sendbird.slack.com/archives/C076TB1AN7K/p1721266348343959?thread_ts=1721045636.638979&cid=C076TB1AN7K

revert: dialog footer button position in RTL mode Dialog

---

CHANGELOG.md
package.json

- **Address RTL UI Feedback**
- Fixed an issue where the `htmlTextDirection` prop didn't work when using `SendbirdProvider`, but only worked in the App module.
- Updated the paper plane icon to point left instead of right in RTL mode.
- **Message Menu Customization in Threads**
- Added `renderMessageMenu` and `renderEmojiMenu` props to the `<ParentMessageInfo />`, `<ThreadListItem />`, and `<ThreadListItemContent />` components.
- **Example usage:**
```tsx
<Thread
renderMessage={(props) => (
<ThreadListItem {...props} renderMessageMenu={(props) => (
<MessageMenu {...props} renderMenuItems={({ items }) => (
<>
<items.CopyMenuItem />
<items.DeleteMenuItem />
</>
)} />
)} />
)}
/>
```
- **Deprecation Marks on Channel & ChannelList Modules**
- Marked `Channel`, `ChannelProvider`, …

release v3.14.13

---

src/ui/MessageContent/index.tsx

Fixes [AC-3370](https://sendbird.atlassian.net/browse/AC-3370)
- Fixed a bug where feedback modal not being displayed on feedback button click in mobile view
https://sendbird.slack.com/archives/C0585965FFA/p1721798651897159?thread_ts=1719659850.599669&cid=C0585965FFA
[Testing App (7).webm](https://github.com/user-attachments/assets/7720d18d-4f48-453e-a638-33638bb8b4ba)
No change in desktop view behaviour
[Testing App (8).webm](https://github.com/user-attachments/assets/b8c87b40-af65-4320-a751-755578356acc)
[AC-3370]: https://sendbird.atlassian.net/browse/AC-3370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Display feedback modal on button click in mobile

---

src/modules/ChannelSettings/index.tsx

[Issue reported](https://sendbird.slack.com/archives/C06H8UN4A13/p1721359735095629?thread_ts=1716256655.710659&cid=C06H8UN4A13)
- Omit renderUserListItem of ChannelSettingsUIProps from the ChannelSettingsProps

fix: Remove the deprecation mark of renderUserListItem from the ChannelSettingsProps

---

src/modules/ChannelSettings/components/ChannelSettingsUI/channel-settings-ui.scss
src/ui/ChannelAvatar/index.scss

Fixes 
- https://sendbird.atlassian.net/browse/CLNP-4582 : leave channel icon
- https://sendbird.atlassian.net/browse/CLNP-4581 : broadcast channel icon
**Before**
**After**

[CLNP-4581][CLNP-4582] fix: direction of some icons in RTL

---

src/ui/MessageContent/index.scss

Fixes [AC-1080](https://sendbird.atlassian.net/browse/AC-1080)
- Fixed a bug where replied child message width does not fit content
[AC-1080]: https://sendbird.atlassian.net/browse/AC-1080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: child message width should fit content

---

src/modules/GroupChannelList/context/GroupChannelListProvider.tsx

[CLNP-4233](https://sendbird.atlassian.net/browse/CLNP-4233)
When customers used channelListQueryParams in GroupChannelList, the channel list was not refreshed with the new query parameters when their values were changed.
The channel list now refreshes when the values of channelListQueryParams are changed.
[CLNP-4233]: https://sendbird.atlassian.net/browse/CLNP-4233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Recreates the GroupChannelCollection when channelListQueryParams change

---

.storybook/main.ts
apps/testing/src/utils/paramsBuilder.ts
apps/testing/vite.config.ts
postcssRtlOptions.mjs
rollup.config.mjs
src/hooks/useHTMLTextDirection.tsx
src/lib/Sendbird.tsx
src/lib/index.scss
src/lib/types.ts
src/modules/App/index.tsx
src/modules/App/types.ts
src/modules/Channel/context/ChannelProvider.tsx
src/modules/GroupChannel/context/GroupChannelProvider.tsx
src/modules/Thread/components/ThreadUI/index.tsx
src/modules/Thread/context/ThreadProvider.tsx
src/stories/apps/GroupChannelApp.stories.tsx
src/styles/_postcss-rtl.scss
src/utils/index.ts

Addresses https://sendbird.atlassian.net/browse/CLNP-4596
This PR addresses the layout issues and CSS [specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) improvements for right-to-left (RTL) text direction in the Sendbird UIKit React components. 
The background for adding the `forceLeftToRightMessageLayout` flag is that some of our users in the middle-east want to set `htmlTextDirection='rtl'` while keeping the message layout in left-to-right (LTR) format (outgoing messages on the right, incoming messages on the left).

[CLNP-4596] feat: add forceLeftToRightMessageLayout to enable LTR message layout display in RTL mode

---

src/ui/MessageContent/index.scss

Fixes https://sendbird.slack.com/archives/G01290GCDCN/p1722563778502959?thread_ts=1722407758.659719&cid=G01290GCDCN
- Fixed a bug where child message width is broken when emojis are added

fix: Fix child message width broken with reactions

---

src/ui/OpenchannelOGMessage/__tests__/__snapshots__/OpenchannelOGMessage.spec.js.snap
src/ui/OpenchannelOGMessage/index.tsx

fond issue in: [CLNP-4638](https://sendbird.atlassian.net/browse/CLNP-4638)
[CLNP-4638]: https://sendbird.atlassian.net/browse/CLNP-4638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: OG message's thumbnail width in OpenChannel

---

src/lib/Sendbird.tsx
src/lib/UserProfileContext.tsx
src/lib/types.ts
src/modules/App/index.tsx
src/modules/Channel/context/ChannelProvider.tsx
src/modules/ChannelList/context/ChannelListProvider.tsx
src/modules/ChannelSettings/context/ChannelSettingsProvider.tsx
src/modules/GroupChannel/context/GroupChannelProvider.tsx
src/modules/GroupChannelList/context/GroupChannelListProvider.tsx
src/modules/OpenChannelSettings/components/ParticipantUI/ParticipantItem.tsx
src/modules/Thread/components/ParentMessageInfo/index.tsx
src/modules/Thread/components/ThreadList/ThreadListItemContent.tsx
src/modules/Thread/context/ThreadProvider.tsx
src/ui/MessageContent/MessageProfile/index.tsx
src/ui/OpenchannelFileMessage/index.tsx
src/ui/OpenchannelOGMessage/index.tsx
src/ui/OpenchannelThumbnailMessage/index.tsx
src/ui/OpenchannelUserMessage/index.tsx
src/ui/UserListItem/index.tsx
src/ui/UserProfile/index.tsx

[CLNP-4601](https://sendbird.atlassian.net/browse/CLNP-4601)
* Made `useUserProfileContext` hook and applied it
* Renamed the prop `onUserProfileMessage` to `onStartDirectMessage`
* Deprecated `onUserProfileMessage` prop in `SendbirdProvider` and `UserProfileProvider`
* Deprecated `onUserProfileMessage` interface in `SendbirdStateContext` and `UserProfileContext`
* Use a `onStartDirectMessage` instead.
[CLNP-4601]: https://sendbird.atlassian.net/browse/CLNP-4601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: rename onUserProfileMessage to onStartDirectMessage

---

apps/testing/index.html
samples/groupchannel/index.html
samples/openchannel/index.html
samples/router/index.html
samples/typescript_sample/public/index.html

Fixes [AC-3554](https://sendbird.atlassian.net/browse/AC-3554)
In mobile device, when users touches message input field, the device automatically zoom in to the input field. This is bad UX because user would have to manually zoom out. Disable auto zoom feature by adding user-scalable=no option.
- N/A
[AC-3554]: https://sendbird.atlassian.net/browse/AC-3554?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Fix auto zoom in on focus message input in mobile view

---

src/ui/Modal/index.scss

Fixes [AC-3324](https://sendbird.atlassian.net/browse/AC-3324)
- Fixed a bug where y-scroll not working in `EditUserProfileUIView` when app is being displayed in horizontal view of mobile devices
[AC-3324]: https://sendbird.atlassian.net/browse/AC-3324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: scroll not working for profile modal in horizontal mobile

---

src/modules/GroupChannelList/components/GroupChannelListItem/GroupChannelListItemView.tsx
src/modules/GroupChannelList/components/GroupChannelListItem/__tests__/GroupChannelListItem.spec.js
src/modules/GroupChannelList/components/GroupChannelListItem/index.scss
src/modules/GroupChannelList/components/GroupChannelListItem/utils.ts
src/modules/Message/utils/tokens/__tests__/tokenizeUtils.spec.ts
src/modules/Message/utils/tokens/tokenize.ts

Fixes [CLNP-4063](https://sendbird.atlassian.net/browse/CLNP-4063)
- Fixed a bug where markdown messages are incorrectly displayed in channel preview
[CLNP-4063]: https://sendbird.atlassian.net/browse/CLNP-4063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Fixed markdown message in channel preview

---

src/ui/MessageContent/MessageBody/index.tsx
src/ui/MessageContent/MessageHeader/index.tsx
src/ui/MessageContent/MessageProfile/index.tsx
src/ui/MessageContent/index.tsx

made from: https://github.com/sendbird/sendbird-uikit-react/pull/1190
* Exported subcomponents of `MessageContent`
```tsx
import { MessageBody, MessageHeader, MessageProfile } from '@sendbird/uikit-react/ui/MessageContent';
```

fix: Subcomponent export of MessageContent

---

src/modules/Thread/components/ParentMessageInfo/ParentMessageInfoItem.scss
src/modules/Thread/components/ThreadUI/index.tsx
src/modules/Thread/context/ThreadProvider.tsx

* Fixed broken CSS in Thread:
* Style was not applied to `ParentMessageInfo` until the first message was received on the thread list.
* Scroll functionality was not working on the thread list.
* Use `channelState`, `parentMessageState` and `threadListState` to calculate the loading status in `useMessageLayoutDirection`
* Fix typo for className

fix: broken CSS in the ParentMessageInfo component

---

src/modules/Thread/components/ThreadList/ThreadListItem.tsx
src/modules/Thread/components/ThreadList/ThreadListItemContent.tsx
src/ui/MessageContent/MessageBody/index.tsx
src/ui/MessageContent/MessageProfile/index.tsx
src/ui/MessageContent/index.tsx

* Added sub-rendering props to the `ThreadListItem` and `ThreadListItemContent` components.
* Added props list: `renderSenderProfile`, `renderMessageBody`, `renderMessageHeader`, `renderEmojiReactions`, and `renderMobileMenuOnLongPress`.
* How to use:
```tsx
const CustomThread = () => (
<ThreadProvider>
<ThreadUI
renderMessage={(props) => (
<ThreadListItem
{...props}
renderSenderProfile={() => <></>}
/>
)}
/>
</ThreadProvider>
)
```

feat: Support rendering subcomponents of ThreadListItem

---

src/ui/MessageInput/hooks/usePaste/index.ts

Fixes the issue https://sendbird.atlassian.net/browse/CLNP-4962 
where HTML entities like `&sect` or `&lt` were being automatically converted to their corresponding symbols (§ or >) when pasting content into a contentEditable element.
The `document.execCommand('insertHTML', false, sanitizeString(text))` command was replaced with `document.execCommand('insertText', false, sanitizeString(text))`.
This change ensures that HTML entities are inserted as plain text rather than being interpreted and converted by the browser. Now it prevents unintended conversion of HTML entities, maintaining the original text as expected when pasting content.
Try this on the preview.
Type `&sect` and copy & paste the text to the input box. The exact same text(=`&sect`) should be on the input not `§`.

[CLNP-4962] fix: prevent HTML entity conversion by using insertText in document.execCommand

---

CHANGELOG.md
package.json

- UIKit now supports form messages! Messages with `messageForm` will be displayed as form messages.
- Added `enableFormTypeMessage` global option
- How to use?
```tsx
<App
appId={appId}
userId={userId}
uikitOptions={{
groupChannel: {
// Below turns on the form message feature. Default value is false.
enableFormTypeMessage: true,
}
}}
/>
```
- `MessageInput` is now being disabled if a channel has a form message that is not submitted and its `extendedMessagePayload['disable_chat_input']` value is true
- Added `FormMessageItemBody`, and `FormInput`
- Added support for EmojiCategory. You can now filter emojis for different messages when adding Reactions to a message.
- Added `filterEmojiCategoryIds` to `GroupChannelProvider` and `ThreadProvider`.
- How to Use
```tsx
const …
```

release: v3.15.0

---

src/modules/GroupChannelList/components/GroupChannelListItem/index.scss

hotfix
* fix unread count position on the ChannelPreview item

hotfix: fix unread count position on channel preview

---

CHANGELOG.md
package.json

- Fixed unread count badge position on the ChannelPreview item component.

release: v3.15.1

---

src/lib/types.ts
src/ui/MessageInput/__tests__/MessageInput.spec.js
src/ui/MessageInput/index.tsx

Addresses https://sendbird.atlassian.net/browse/CLNP-5022
```
eventHandlers?: {
...
message?: {
onSendMessageFailed?: (message: CoreMessageType, error: unknown) => void;
onUpdateMessageFailed?: (message: CoreMessageType, error: unknown) => void;
onFileUploadFailed?: (error: unknown) => void;
// any message related event handlers can be added here
}
}
```
The original request is only about sending message related event, but just added two more (onUpdateMessageFailed / onFileUploadFailed)

[CLNP-5022] feat: add message input related eventHandlers

---

src/lib/Sendbird.tsx
src/lib/hooks/useConnect/__test__/data.mocks.ts
src/lib/hooks/useConnect/__test__/disconnectSdk.spec.ts
src/lib/hooks/useConnect/disconnectSdk.ts

Addresses https://sendbird.atlassian.net/browse/CLNP-5111
Changed the method we call when SendbirdProvider is unmounted from `disconnect()` to `disconnectWebsocket()` since `disconnect()` is equal to "logout" not just "disconnect". 

[CLNP-5111] feat: replace sdk.disconnect -> sdk.disconnectWebsocket

---

src/ui/MessageInput/hooks/usePaste/index.ts
src/ui/MessageInput/hooks/usePaste/types.ts
src/ui/MessageInput/index.scss
src/ui/MessageInput/index.tsx

[CLNP-5328](https://sendbird.atlassian.net/browse/CLNP-5328)
[SBISSUE-17384](https://sendbird.atlassian.net/browse/SBISSUE-17384)
Fixes
* Modified the `MessageInput` to scroll to the caret position when pasting text.
* The maximum height of the `MessageInput` has been extended to `'92px'`
Functions
* Created a `scrollToCaret` and replaced the `displayCaret`
* Created a `handleCommonBehavior` for the common behavior of event handling logics
* Removed an unused logic `setHeight`
Variables
* Set a default value to the `internalRef`
CSS
* Extended the maximum input height from `56px` to `92px`
Chores
* Fixed typo 'easiily' to 'easily'
[CLNP-5328]: https://sendbird.atlassian.net/browse/CLNP-5328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

fix: Doesn't scroll in the MessageInput when pasting

---

src/modules/ChannelSettings/components/ChannelSettingsUI/MenuItem.tsx

[CLNP-5329](https://sendbird.atlassian.net/browse/CLNP-5329)
[SBISSUE-17339](https://sendbird.atlassian.net/browse/SBISSUE-17339)
- Fixed an error message on MenuItemAction when the children prop is undefined
- Handle the case when prop children is undefined in MenuItemAction comp
[CLNP-5329]: https://sendbird.atlassian.net/browse/CLNP-5329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SBISSUE-17339]: https://sendbird.atlassian.net/browse/SBISSUE-17339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Handle the case when prop children is undefined in MenuItemAction component

---

rollup.module-exports.mjs
src/hooks/useLocalization.ts
src/lib/LocalizationContext.tsx
src/modules/Channel/context/ChannelProvider.tsx
src/modules/GroupChannel/context/GroupChannelProvider.tsx

[CLNP-5330](https://sendbird.atlassian.net/browse/CLNP-5330)
[SBISSUE-17397](https://sendbird.atlassian.net/browse/SBISSUE-17397)
Features:
- Exported `useLocalization` Hook:
- Provided access to stringSet and dateLocale.
- Note: Required SendbirdProvider to wrap your component for proper usage.
- Import Path: `"@sendbird/uikit-react/hooks/useLocalization"`
- Exported `ThreadReplySelectType`:
- Import Paths:
- `"@sendbird/uikit-react/Channel/context"`
- `"@sendbird/uikit-react/GroupChannel/context"`
[CLNP-5330]: https://sendbird.atlassian.net/browse/CLNP-5330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SBISSUE-17397]: https://sendbird.atlassian.net/browse/SBISSUE-17397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2 …

feat: Export useLocalization hook & ThreadReplySelectType

---

CHANGELOG.md
package.json

[SDKRLSD-1433](https://sendbird.atlassian.net/browse/SDKRLSD-1433)
- Exported `useLocalization` Hook:
- Provided access to stringSet and dateLocale.
- Note: Required SendbirdProvider to wrap your component for proper usage.
- Import Path: `"@sendbird/uikit-react/hooks/useLocalization"`
- Exported `ThreadReplySelectType`:
- Import Paths:
- `"@sendbird/uikit-react/Channel/context"`
- `"@sendbird/uikit-react/GroupChannel/context"`
- Modified the `MessageInput` to scroll to the caret position when pasting text.
- The maximum height of the `MessageInput` has been extended to `'92px'`
- Fixed an `error message` on `MenuItemAction` when the children prop is `undefined`
[SDKRLSD-1433]: https://sendbird.atlassian.net/browse/SDKRLSD-1433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUi …

release: v3.15.6

---

rollup.module-exports.mjs
src/modules/ChannelSettings/components/ChannelProfile/index.tsx
src/modules/ChannelSettings/components/ChannelSettingsUI/MenuListByRole.tsx
src/modules/ChannelSettings/components/ChannelSettingsUI/hooks/useMenuItems.tsx
src/modules/ChannelSettings/components/ChannelSettingsUI/index.tsx
src/modules/ChannelSettings/components/EditDetailsModal/index.tsx
src/modules/ChannelSettings/components/LeaveChannel/index.tsx
src/modules/ChannelSettings/components/ModerationPanel/AddOperatorsModal.tsx
src/modules/ChannelSettings/components/ModerationPanel/BannedUserList.tsx
src/modules/ChannelSettings/components/ModerationPanel/BannedUsersModal.tsx
src/modules/ChannelSettings/components/ModerationPanel/InviteUsersModal.tsx
src/modules/ChannelSettings/components/ModerationPanel/MemberList.tsx
src/modules/ChannelSettings/components/ModerationPanel/MembersModal.tsx
src/modules/ChannelSettings/components/ModerationPanel/MutedMemberList.tsx
src/modules/ChannelSettings/components/ModerationPanel/MutedMembersModal.tsx
src/modules/ChannelSettings/components/ModerationPanel/OperatorList.tsx
src/modules/ChannelSettings/components/ModerationPanel/OperatorsModal.tsx
src/modules/ChannelSettings/components/ModerationPanel/index.tsx
src/modules/ChannelSettings/components/UserPanel/index.tsx
src/modules/ChannelSettings/context/ChannelSettingsProvider.tsx
src/modules/ChannelSettings/context/hooks/useChannelHandler.ts
src/modules/ChannelSettings/context/hooks/useSetChannel.ts
src/modules/ChannelSettings/context/index.tsx
src/modules/ChannelSettings/context/types.ts
src/modules/ChannelSettings/context/useChannelSettings.ts
src/modules/ChannelSettings/index.tsx
src/utils/storeManager.ts

[CLNP-5044](https://sendbird.atlassian.net/browse/CLNP-5044)
ChannelSettingsProvider migration
- Created a hook `useChannelSettings` for replacing `useChannelSettingsContext`
- Created hooks `useSetChannel` and `useChannelHandler` to separate the logics from the ChannelSettingsProvider
[CLNP-5044]: https://sendbird.atlassian.net/browse/CLNP-5044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: ChannelSettingsProvider migration

---

src/modules/GroupChannelList/components/AddGroupChannel/index.tsx
src/modules/GroupChannelList/components/GroupChannelListItem/index.tsx
src/modules/GroupChannelList/components/GroupChannelListUI/index.tsx
src/modules/GroupChannelList/context/GroupChannelListProvider.tsx
src/modules/GroupChannelList/context/useGroupChannelList.ts

This is a part of state management migration. This PR migrate 'GroupChannelListProvider' and related files to the new style.
* Created `useGroupChannelList()` hook. It'll replace the previous `useGroupChannelContext()` hook.

refactor: GroupChannelList migration

---

src/utils/__tests__/getMimeTypesUIKitAccepts.spec.ts
src/utils/index.ts

Resolves https://sendbird.atlassian.net/browse/SBISSUE-17456 
This change enhances the flexibility of file type handling in our application, allowing for both MIME types and file extensions to be processed. It also improves the robustness of the function by handling case-insensitivity and removing duplicates.

[CLNP-5476] Enhance getMimeTypesUIKitAccepts to support file extensions along with mime types

---

src/modules/ChannelSettings/__test__/ChannelSettingsProvider.spec.tsx
src/modules/ChannelSettings/__test__/ChannelSettingsUI.integration.test.tsx
src/modules/ChannelSettings/__test__/useChannelHandler.spec.ts
src/modules/ChannelSettings/__test__/useChannelSettings.spec.ts
src/modules/ChannelSettings/__test__/useSetChannel.spec.ts
src/modules/ChannelSettings/context/hooks/useChannelHandler.ts
src/modules/ChannelSettings/context/hooks/useSetChannel.ts

fix: Prevent destroy error by adding `AbortController` in `useSetChannel`
- Added `AbortController` to cancel async operations when the component unmounts.
- Ensured that state updates are skipped if the operation is aborted.
- Prevented potential memory leaks and the `'destroy is not a function'` error.
- Updated `useEffect` cleanup to properly handle pending async calls.
feat: Add tests for ChannelSettings migration

refactor: Add tests for ChannelSettings migration

---

src/utils/__tests__/isThumbnailMessage.spec.ts
src/utils/index.ts

* Support `.bmp` and `.heic` to be rendered properly in `MessageBody`.
* `.bmp` file will rendered as `ThumbnailMessage`. `.heic` file will be rendered as regular `FileMessage`, for consistency between browsers.

[CLNP-5230] Support .bmp and .heic

---

src/ui/MessageInput/hooks/usePaste/index.ts
src/ui/MessageInput/index.scss
src/ui/MessageInput/index.tsx

[CLNP-5528](https://sendbird.atlassian.net/browse/CLNP-5528)
[SBISSUE-17384](https://sendbird.atlassian.net/browse/SBISSUE-17384)
This PR resolves an issue where `getBoundingClientRect()` would return `(0, 0, 0, 0)` after a paste operation due to improper caret placement. The following changes ensure accurate caret positioning and consistent rect values:
1. **Zero-width space (`\u200B`)**: Appended to the pasted content to ensure the caret has a valid text node to reside in.
2. **Selection and Range Synchronization**: The range is collapsed and selection is reset to align with the updated DOM.
3. **Caret Adjustment**: The caret is moved to the end of the newly inserted content to maintain user expectation.
[CLNP-5528]: https://sendbird.atlassian.net/browse/CLNP-5528?atlOrigin=eyJpIjoiNWRkN …

fix: Ensure correct caret placement and rect calculation after paste

---

src/modules/OpenChannel/context/utils.ts

[CLNP-5487](https://sendbird.atlassian.net/browse/CLNP-5487)
[SBISSUE-17529](https://sendbird.atlassian.net/browse/SBISSUE-17529)
- OpenChannel scroll doesn't move when fetching the initial messages on mobile(iPhone)
- Applied scroll after rendering DOM using `setTimeout`
[CLNP-5487]: https://sendbird.atlassian.net/browse/CLNP-5487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SBISSUE-17529]: https://sendbird.atlassian.net/browse/SBISSUE-17529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Applied scroll after rendering DOM using setTimeout

---

CHANGELOG.md
package.json

[SDKRLSD-1442](https://sendbird.atlassian.net/browse/SDKRLSD-1442)
- **Added support for new file types and extensions.**
- **Added mime types:** `'application/zip', 'application/x-rar-compressed', 'application/x-7z-compressed', 'application/x-tar', 'application/gzip', 'application/x-bzip', 'application/x-bzip2', 'application/x-xz', 'application/x-iso9660-image'`
- **Added extensions:**
- **Image:** `'.apng', '.avif', '.gif', '.jpg', '.jpeg', '.jfif', '.pjpeg', '.pjp', '.png', '.svg', '.webp', '.bmp', '.ico', '.cur', '.tif', '.tiff'`
- **Video:** `'.mp4', '.webm', '.ogv', '.3gp', '.3g2', '.avi', '.mov', '.wmv', '.mpg', '.mpeg', '.m4v', '.mkv'`
- **Audio:** `'.aac', '.midi', '.mp3', '.oga', '.opus', '.wav', '.weba', '.3gp', '.3g2'`
- **Document:** `'.txt', '.log', '.csv', '.rtf', '.pdf', …

release: v3.15.7

---

src/hooks/useHTMLTextDirection.tsx
src/modules/Channel/components/MessageList/index.tsx
src/modules/Channel/context/ChannelProvider.tsx
src/modules/GroupChannel/components/MessageList/index.tsx
src/modules/GroupChannel/context/GroupChannelProvider.tsx
src/modules/Thread/components/ThreadUI/index.tsx
src/modules/Thread/context/ThreadProvider.tsx
src/utils/index.ts

Aim to fix https://sendbird.atlassian.net/browse/SBISSUE-17616 
Fixed an issue where the `dir` attribute was not being properly applied to message containers. Instead of using DOM manipulation through `useMessageLayoutDirection` hook, implemented a more React-friendly solution by directly setting the `dir` attribute on the message container component.
- Removed `useMessageLayoutDirection` hook
- Updated `MessageList` component to directly handle text direction through the `dir` attribute
- Simplified the implementation while maintaining the same functionality
- Ensures proper text direction propagation to child elements
Please test the following scenarios:
- Verify text direction changes properly when switching between LTR and RTL by changing the value of `forceLeftToRightMessageLayout` / …

[CLNP-5549] fix: Improve message layout direction hook reliability

---

CHANGELOG.md
package.json

- Fixed an issue where the `dir` attribute was not being properly applied to message containers:
* Removed `useMessageLayoutDirection` hook in favor of a more React-friendly solution
* Updated `MessageList` component to directly handle text direction through the `dir` attribute
- Fixed an issue in TypingIndicatorBubble component where null was returned before hook execution
- Fixed SDK initialization parameter override issue:
* Modified Object.assign order to allow proper parameter override
* Added test case to verify `localCacheEnabled` override functionality
* Ensures `sdkInitParams.localCacheEnabled` properly overrides default settings; `localCacheEnabled: true`

release: 3.15.8

---

samples/README.md

Addresses https://sendbird.atlassian.net/browse/CLNP-5460

[CLNP-5460 ]Update samples/README to address prop change info

---

src/ui/MessageContent/index.tsx

Fixes [UIKIT-4616](https://sendbird.atlassian.net/browse/UIKIT-4616)
- http://localhost:5174/group_channel?appId=833E2DC4-DFA2-4508-A283-6E5C7BFCF18A&userId=cann03&nickname=cann03&groupChannel_replyType=thread&groupChannel_enableFeedback=true
- Fixed a bug where profile bottom position not updating correctly for messages with feedback and replies
and we'll evaluate if we can …

fix: Fixed a bug where profile bottom position not updating correctly for messages with feedback and replies

---

package.json
src/modules/GroupChannel/context/GroupChannelProvider.tsx
src/modules/GroupChannel/context/__tests__/useMessageActions.spec.ts
src/modules/GroupChannel/context/hooks/useMessageActions.ts
yarn.lock

Fixes some of comments in [SBISSUE-17017](https://sendbird.atlassian.net/browse/SBISSUE-17017?focusedCommentId=298138)
Users currently need to return an empty object from `onBeforeSendFileMessage` due to type constraints. Additionally, error handling for message sending failures needs improvement to ensure `eventHandlers.message` callbacks (onSendMessageFailed, onUpdateMessageFailed, onFileUploadFailed) are properly triggered when errors occur within their corresponding `onBefore` handlers (`onBeforeSendUserMessage`, `onBeforeSendFileMessage`, etc).
- Allow void return type in `onBeforeXXX` handler
- Add proper error handling via `eventHandlers.message` for:
- onSendMessageFailed
- onUpdateMessageFailed
- onFileUploadFailed
Put an `x` in the boxes that apply. You can also fill these out …

fix: improve error handling in message handlers

---

CHANGELOG.md
package.json

* Fixed error handling in message handlers:
* Allow void return type in `onBefore-` handlers
* Add proper error handling via `eventHandlers.message` for:
* onSendMessageFailed
* onUpdateMessageFailed
* onFileUploadFailed
* Users no longer need to return an empty object from `onBefore-` due to type constraints
* Fixed a bug where profile bottom position was not updating correctly for messages with feedback and replies:
* Profile bottom position now updates properly when messages contain feedback and reply components
* Ensures consistent profile positioning across all message types and states

release: 3.15.9

---

src/lib/Sendbird/README.md
src/lib/Sendbird/__experimental__typography.scss
src/lib/Sendbird/context/SendbirdProvider.tsx
src/lib/Sendbird/context/initialState.ts
src/lib/Sendbird/index.scss
src/lib/Sendbird/index.tsx
src/lib/Sendbird/types.ts

[CLNP-5735](https://sendbird.atlassian.net/browse/CLNP-5735)
[CLNP-5735]: https://sendbird.atlassian.net/browse/CLNP-5735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: SendbirdProvider migration - (1) prepare new structure

---

src/hooks/useDeepCompareEffect.ts
src/hooks/useStore.ts
src/modules/GroupChannel/context/GroupChannelProvider.tsx
src/modules/GroupChannel/context/hooks/useMessageListScroll.tsx
src/utils/storeManager.ts

Fixes 
- https://sendbird.atlassian.net/browse/CLNP-5917
- https://sendbird.atlassian.net/browse/CLNP-5918
To fix [CLNP-5917](https://sendbird.atlassian.net/browse/CLNP-5917) introduced optimizations to prevent the "Maximum update depth exceeded" error that occurs during message searches:
1. Added useDeepCompareEffect hook:
- Performs deep comparison of dependencies instead of reference equality
- Particularly useful for handling message array updates efficiently
- Inspired by [kentcdodds/use-deep-compare-effect](https://github.com/kentcdodds/use-deep-compare-effect)
2. Enhanced useStore with state change detection:
- Added hasStateChanged helper to compare previous and next states
- Prevents unnecessary updates when state values haven't actually changed
- Optimizes performance by …

[CLNP-5817][CLNP-5918] fix: scroll & search message issues in GroupChannelProvider

---

src/modules/App/DesktopLayout.tsx
src/modules/GroupChannelList/context/GroupChannelListProvider.tsx
src/modules/GroupChannelList/context/__tests__/GroupChannelListProvider.spec.tsx
src/modules/GroupChannelList/context/__tests__/useGroupChannelList.spec.tsx
src/modules/Thread/context/ThreadProvider.tsx

* Changelog
* Fixed the broken unit tests of `GroupChannelListProvider`
* Fixed the UI error when click `open in channel` in the other channel
* Use `useDeepCompareEffect` in `ThreadProvider` and `GroupChannelListProvider`

[CLNP-5914] Fix unit tests and UI error

---

src/modules/App/DesktopLayout.tsx

* Fixed a GroupChannel UI error when the `Open in Channel` action is triggered in a different channel.
* The `Open in Channel` implementation invokes both `setCurrentChannel` and `setStartingPoint`. The `setCurrentChannel` function triggers asynchronous side effects that update `channel`, `messagesDataSource`, and `startingPoint`. If `setStartingPoint` is invoked before these updates are completed, it can result in the channel not being updated correctly or the starting point being improperly set.

[CLNP-5914] Fixed a GroupChannel UI error when the `Open in Channel` action is triggered in a different channel.

---

src/modules/GroupChannel/context/__tests__/useGroupChannel.spec.tsx
src/modules/GroupChannel/context/__tests__/useMessageListScroll.spec.tsx
src/modules/GroupChannel/context/__tests__/utils.spec.ts

- before
- after
GroupChannelProvider has some not covered lines but they're mostly from uikit-tools lib related logic. There could be a way to mock these lines too, but let me handle it separately.

[CLNP-5974] Add more GroupChannel module custom hook unit tests

---

src/hooks/useDeepCompareEffect.ts
src/modules/GroupChannelList/context/GroupChannelListProvider.tsx
src/modules/GroupChannelList/context/__tests__/GroupChannelListProvider.spec.tsx

Fixes 
- https://sendbird.atlassian.net/browse/CLNP-5966
- https://sendbird.atlassian.net/browse/CLNP-5967
- https://sendbird.atlassian.net/browse/CLNP-5969
- https://sendbird.atlassian.net/browse/CLNP-5971
- https://sendbird.atlassian.net/browse/CLNP-5973
1. **Handling objects without guaranteed immutability**
```typescript
const complexObject = {
settings: {
theme: { ... },
preferences: { ... }
},
data: [ ... ]
};
useDeepCompareEffect(() => {
// When you want to detect actual value changes
}, [complexObject]);
```
2. **Working with data from external libraries or APIs**
- When objects have new references but identical content
3. **Dealing with deeply nested objects where memoization is impractical**
- When object structures are too complex for individual memoization
1. **Detecting …

Use useEffect instead of useDeepCompareEffect in GroupChannelListProvider

---

src/modules/Thread/components/ThreadUI/__test__/ThreadUI.integration.test.tsx
src/modules/Thread/context/ThreadProvider.tsx
src/modules/Thread/context/__test__/ThreadProvider.spec.tsx
src/modules/Thread/context/__test__/useDeleteMessageCallback.spec.ts
src/modules/Thread/context/__test__/useGetAllEmoji.spec.ts
src/modules/Thread/context/__test__/useGetChannel.spec.ts
src/modules/Thread/context/__test__/useGetParentMessage.spec.ts
src/modules/Thread/context/__test__/useHandleChannelEvents.spec.ts
src/modules/Thread/context/__test__/useHandleThreadPubsubEvents.spec.ts
src/modules/Thread/context/__test__/useResendMessageCallback.spec.ts
src/modules/Thread/context/__test__/useSendFileMessage.spec.ts
src/modules/Thread/context/__test__/useSendUserMessageCallback.spec.ts
src/modules/Thread/context/__test__/useSendVoiceMessageCallback.spec.ts
src/modules/Thread/context/__test__/useThread.spec.tsx
src/modules/Thread/context/__test__/useThreadFetchers.spec.ts
src/modules/Thread/context/__test__/useToggleReactionsCallback.spec.ts
src/modules/Thread/context/__test__/useUpdateMessageCallback.spec.ts
src/modules/Thread/context/hooks/useDeleteMessageCallback.ts
src/modules/Thread/context/hooks/useResendMessageCallback.ts
src/modules/Thread/context/hooks/useSendFileMessage.ts
src/modules/Thread/context/hooks/useUpdateMessageCallback.ts
src/modules/Thread/context/useThread.ts

This PR will add the test cases for the new `ThreadProvider` and its related hooks.

Add basic test cases for the new `ThreadProvider`

---

src/modules/MessageSearch/context/__test__/MessageSearchProvider.spec.tsx
src/modules/MessageSearch/context/__test__/useGetSearchedMessages.spec.ts
src/modules/MessageSearch/context/__test__/useScrollCallback.spec.ts
src/modules/MessageSearch/context/__test__/useSearchStringEffect.spec.ts
src/modules/MessageSearch/context/__test__/useSetChannel.spec.ts

[CLNP-6010] Add more unit tests for existing message search custom hook

---

src/modules/GroupChannel/context/hooks/useGroupChannel.ts
src/modules/Thread/context/__test__/useThread.spec.tsx
src/utils/__tests__/utils.spec.ts
src/utils/utils.ts

Fixes https://sendbird.atlassian.net/browse/CLNP-6022
This PR addresses an issue where the scroll position was not correctly set to the bottom when switching from a channel with few messages to one with many messages. 
The problem was resolved by adding a delay to ensure the scroll reference is updated before attempting to scroll to the bottom. This change ensures that users always see the latest messages when switching channels.

[CLNP-6022] fix scroll position issue when switching GroupChannel

---

src/modules/GroupChannelList/components/GroupChannelListUI/GroupChannelListUIView.tsx
src/modules/GroupChannelList/components/GroupChannelListUI/index.tsx
src/modules/GroupChannelList/context/GroupChannelListProvider.tsx

[SBISSUE-17925](https://sendbird.atlassian.net/browse/SBISSUE-17925)
* Added `scrollRef` in GroupChannelList context
[SBISSUE-17925]: https://sendbird.atlassian.net/browse/SBISSUE-17925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Provide scrollRef in GroupChannelList

---

jest-setup.js
src/lib/SendbirdProvider.migration.spec.tsx
src/modules/ChannelSettings/__test__/ChannelSettings.migration.spec.tsx
src/modules/ChannelSettings/context/ChannelSettingsProvider.tsx
src/modules/CreateChannel/context/__tests__/CreateChannel.migration.spec.tsx
src/modules/GroupChannel/context/__tests__/GroupChannel.migration.spec.tsx
src/modules/GroupChannelList/context/__tests__/GroupChannelList.migration.spec.tsx
src/modules/MessageSearch/context/__tests__/MessageSearch.migration.spec.tsx
src/modules/Thread/context/__test__/Thread.migration.spec.tsx

Addresses 
- https://sendbird.atlassian.net/browse/CLNP-6019
- https://sendbird.atlassian.net/browse/CLNP-6023
- https://sendbird.atlassian.net/browse/CLNP-6024
to verify legacy Provider props compatibility  and test context hook return values.
This will help validate that the state management migration doesn't break existing implementations and maintains backward compatibility.

[CLNP-6019][CLNP-6023][CLNP-6024] Add state management migration tests

---

src/modules/ChannelSettings/components/ChannelProfile/index.tsx
src/modules/ChannelSettings/components/LeaveChannel/index.tsx
src/modules/GroupChannel/components/GroupChannelHeader/utils.ts
src/modules/GroupChannelList/components/GroupChannelListItem/utils.ts
src/modules/MessageSearch/components/MessageSearchUI/index.tsx
src/utils/__tests__/utils.spec.ts
src/utils/index.ts

https://sendbird.atlassian.net/browse/CLNP-6032
* Display members' name instead of default AI chatbot channel name, like the `Group Channel` does.

[CLNP-6032]Display members' name instead of default AI chatbot channel name

---

CHANGELOG.md
package.json

- Added `scrollRef` in GroupChannelList context
- Fixed broken UI
* MessageInput height becomes short when it's disabled.
* Empty UserListItem menu appears on the ChannelSettings member list of normal channel member who is not an operator of the channel.
- Displayed members' name instead of default AI chatbot channel name, like the `Group Channel` does.
- Fixed an issue where editing a text parent message in a channel did not update the corresponding parent message in the Thread area in real-time.
- Fixed a GroupChannel UI error when the `Open in Channel` action is triggered in a different channel.
* The `Open in Channel` implementation invokes both `setCurrentChannel` and `setStartingPoint`. The `setCurrentChannel` function triggers asynchronous side effects that update `channel`, …

release: v3.15.10

---

src/modules/GroupChannel/components/MessageList/InfiniteList.tsx
src/modules/GroupChannel/context/GroupChannelProvider.tsx
src/modules/GroupChannel/context/__tests__/useMessageListScroll.spec.tsx
src/modules/GroupChannel/context/hooks/useGroupChannel.ts
src/modules/GroupChannel/context/hooks/useMessageListScroll.tsx
src/utils/storeManager.ts

Addresses https://sendbird.atlassian.net/browse/CLNP-6022?focusedCommentId=301263
Memoized action handlers(+ scroll related functions as well) in useGroupChannel to reduced unnecessary re-rendering.

[CLNP-6022] Memoize useGroupChannel actions to prevent unnecessary re-rendering

---

src/modules/GroupChannel/components/MessageList/index.tsx

[CLNP-6036](https://sendbird.atlassian.net/browse/CLNP-6036)
* Bubble type typing indicator appears but scroll doesn't move to the bottom. So users can't see the appeared typing indicator.
* Fixed an issue where the typing indicator for bubble type messages appeared but was not visible because the scroll did not move to the bottom.
[CLNP-6036]: https://sendbird.atlassian.net/browse/CLNP-6036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: scroll to bottom when bubble TypingIndicator appears

---

src/hooks/useConnectionHandler.ts
src/hooks/useConnectionState.ts

https://sendbird.atlassian.net/browse/SBISSUE-18182

[CLNP-6072] useConnectionHandler

---

src/modules/Channel/components/ChannelHeader/index.tsx
src/modules/Channel/components/ChannelUI/index.tsx
src/modules/Channel/components/FileViewer/index.tsx
src/modules/Channel/components/Message/index.tsx
src/modules/Channel/components/MessageInputWrapper/index.tsx
src/modules/Channel/components/MessageList/index.tsx
src/modules/Channel/components/RemoveMessageModal/index.tsx
src/modules/Channel/components/SuggestedMentionList/index.tsx
src/modules/ChannelList/components/ChannelListUI/index.tsx
src/modules/ChannelList/components/ChannelPreview/index.tsx

- Added @deprecated annotation to the deprecated Channel components
Fixes [CLNP-6249](https://sendbird.atlassian.net/browse/CLNP-6249)
[CLNP-6249]: https://sendbird.atlassian.net/browse/CLNP-6249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Z …

[CLNP-6249] deprecated mark for ChannelXXX

---

src/ui/MessageInput/hooks/usePaste/index.ts

[fix]: Formatted text paste broken
When a formatted text is copied and pasted into the `MessageInput`, the sanitized text is pasted instead of the text
Fixes [CLNP-6276](https://sendbird.atlassian.net/browse/CLNP-6276)
- Fixed a bug that a formatted text is broken when pasted into the `MessageInput`
```
and we'll evaluate if we can set up a …
```

[CLNP-6276] Formatted text paste bug-fix

---

src/modules/Channel/components/MessageList/index.tsx
src/modules/GroupChannel/components/MessageList/__test__/getMessagePartsInfo.spec.js
src/modules/GroupChannel/components/MessageList/getMessagePartsInfo.ts
src/modules/GroupChannel/components/MessageList/index.tsx
src/modules/OpenChannel/components/OpenChannelMessageList/index.tsx
src/modules/Thread/components/ThreadList/index.tsx
src/utils/messages.ts

[fix]: forwardRef hook rule violation bug-fix
Fixes [CLNP-6260](https://sendbird.atlassian.net/browse/CLNP-6260)
- Fixed a bug with forwardRef Rules of Hooks violation
[CLNP-6260]: …

[CLNP-6260] forwardRef hook rule violation

---

CHANGELOG.md
package.json

- Added custom hooks for each module replacing the previous context hook. The custom hook allows access to the provider's data, which are divided into `state` and `actions` properties.
* Added `useGroupChannelList`, replacing `useGroupChannelListContext`
* Added `useCreateChannel`, replacing `useCreateChannelContext`
* Added `useChannelSettings`, replacing `useChannelSettingsContext`
* Added `useGroupChannel`, replacing `useGroupChannelContext`
* Added `useMessageSearch`, replacing `useMessageSearchContext`
* Added `useThread`, replacing `useThreadContext`
- How to Use?
```tsx
import { useGroupChannel } from '@sendbird/uikit-react/GroupChannel/context';
// Implement your code inside the react function component.
const Component = () => {
// const { currentChannel, scrollToBottom } = …
```

release: v3.15.14

---

rollup.module-exports.mjs
src/lib/Sendbird/index.tsx
src/lib/Sendbird/withSendbird.tsx

* Added the missing import paths for the deprecated interfaces; `useSendbirdStateContext` and `withSendbird`.

Add the missing import paths of deprecated interfaces

---

src/hooks/VoiceRecorder/useVoiceRecorder.tsx
src/ui/VoiceMessageInput/index.tsx

[SBISSUE-18534](https://sendbird.atlassian.net/browse/SBISSUE-18534)
* Fixed the bug where `VoiceMessageIssue` doesn't work at the first time.
[SBISSUE-18534]: https://sendbird.atlassian.net/browse/SBISSUE-18534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SBISSUE-18534] onRecordingEnded Callback Not Triggered

---

CHANGELOG.md
package.json

- Added the missing import paths for the following deprecated interfaces.
- `useSendbirdStateContext`
- `withSendbird`
- Fixed an issue where `VoiceMessageInput` failed to record the audio at first.
- Updated `@sendbird/chat` version to 4.16.4

release: v3.15.15

---

package.json
yarn.lock

Fixes [CLNP-6399](https://sendbird.atlassian.net/browse/CLNP-6399)
- `dompurity` version upgrade
[CLNP-6399]: https://sendbird.atlassian.net/browse/CLNP-6399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU …

[CLNP-6399] `dompurify` dependency upgrade

---

src/lib/Sendbird/context/SendbirdContext.tsx
src/lib/Sendbird/context/SendbirdProvider.tsx
src/modules/ChannelSettings/context/ChannelSettingsProvider.tsx
src/modules/ChannelSettings/context/types.ts
src/modules/CreateChannel/context/CreateChannelProvider.tsx
src/modules/GroupChannel/context/GroupChannelProvider.tsx
src/modules/GroupChannel/context/__tests__/useGroupChannel.spec.tsx
src/modules/GroupChannelList/context/GroupChannelListProvider.tsx
src/modules/MessageSearch/context/MessageSearchProvider.tsx
src/modules/Thread/context/ThreadProvider.tsx
src/utils/typeHelpers/partialDeep.ts

[SBISSUE-18637](https://sendbird.atlassian.net/browse/18637)
* Create store instance with the props as default value.
* Before stabilization refactoring, each provider set their context value synchronously if possible. But during refactoring, we put the all set up process in async effect hook, including initialization. This change caused various unexpected bugs.
[SBISSUE-18637]: https://sendbird.atlassian.net/browse/SBISSUE-18637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SBISSUE-18637] Create store with the props as a default value

---

src/modules/Message/utils/tokens/__tests__/asSafeUrl.spec.ts
src/modules/Message/utils/tokens/asSafeURL.ts

Fixes [CLNP-6478](https://sendbird.atlassian.net/browse/CLNP-6478)
- Added `tel` and `mailto` to supported markdown URL protocols
[CLNP-6478]: https://sendbird.atlassian.net/browse/CLNP-6478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CLNP-6478] tel and mailto to markdown URL protocol

---

src/lib/Sendbird/context/SendbirdProvider.tsx
src/ui/ContextMenu/EmojiListItems.tsx
src/ui/EmojiReactions/index.tsx
src/ui/MessageContent/index.tsx
src/ui/MessageItemReactionMenu/index.tsx
src/utils/index.ts

* Fixed unnecessary instantiation of `EmojiManager`.
* Fixed the code that lead to undefined error of `emojiCategory`.

Fix undefined error of emojiCategory

---

src/ui/QuoteMessage/index.scss

[CLNP-6496](https://sendbird.atlassian.net/browse/CLNP-6496)
* Support multiline ellipsis of quoted message.
* Not all browser supports the added css properties. We try to show ellipsis, but if the environment doesn't support it, we maintain the previous behavior.
* I expect those properties will be ignored on the unsupported browser. AFAIK, firefox is the only major browser doesn't support the properties.
[CLNP-6496]: https://sendbird.atlassian.net/browse/CLNP-6496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CLNP-6496] Support multiline ellipsis of quoted message

---

src/modules/Thread/context/useThread.ts

[CLNP-6644](https://sendbird.atlassian.net/browse/CLNP-6644)
* Fix the bug where thread messages are not loaded when the scroll at the top
* dependency list has some missing elements.
[CLNP-6644]: https://sendbird.atlassian.net/browse/CLNP-6644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CLNP-6644] Thread messages are not loaded when the scroll at the top

---

src/modules/GroupChannel/context/hooks/useGroupChannel.ts
src/modules/GroupChannel/context/hooks/useMessageActions.ts
src/modules/Thread/context/useThread.ts

[SBISSUE-18879](https://sendbird.atlassian.net/browse/SBISSUE-18879)
* Fixed a bug where `scrollToBottom` doesn't work when send a message in mobile environment.
[SBISSUE-18879]: https://sendbird.atlassian.net/browse/SBISSUE-18879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SBISSUE-18879] `scrollToBottom` doesn't work when send a message in mobile.

---

src/hooks/useUnmount.ts
src/lib/Sendbird/context/SendbirdProvider.tsx
src/lib/Sendbird/context/hooks/useSendbird.tsx
src/modules/CreateChannel/context/useCreateChannel.ts
src/modules/MessageSearch/context/hooks/useMessageSearch.ts
src/modules/Thread/context/hooks/useDeleteMessageCallback.ts
src/modules/Thread/context/hooks/useResendMessageCallback.ts
src/modules/Thread/context/hooks/useSendFileMessage.ts
src/modules/Thread/context/hooks/useSendUserMessageCallback.ts
src/modules/Thread/context/hooks/useSendVoiceMessageCallback.ts
src/modules/Thread/context/hooks/useThreadFetchers.ts
src/modules/Thread/context/hooks/useUpdateMessageCallback.ts
src/modules/Thread/context/useThread.ts

[CLNP-6660](https://sendbird.atlassian.net/browse/CLNP-6660)
[CLNP-6660]: https://sendbird.atlassian.net/browse/CLNP-6660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CLNP-6660] Check memoization of custom hooks' actions

---

src/ui/MessageContent/index.scss

[fix]: Layout issues with long messages in Mobile layout only
Fixes [CLNP-6806](https://sendbird.atlassian.net/browse/CLNP-6806)
- Added flex style option to `sendbird-message-content__left`
[CLNP-6806]: https://sendbird.atlassian.net/browse/CLNP-6806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[fix] Layout issues with long messages in Mobile layout only

---

src/modules/GroupChannel/context/GroupChannelProvider.tsx

[fix]: Set initial value for initialized and loading
iFood 쪽에서 요구한 사항 중 저 플래그 state들의 기본값을 undefined가 아닌 값으로 바꿔달라는 요청이 있어서 작업했습니다.
Fixes [CLNP-6813](https://sendbird.atlassian.net/browse/CLNP-6813)
- `GroupChannelProvider` has `loading` and `initialized` flag states as non-`undefined` value
and we'll evaluate if we can set up a …

[CLNP-6813] Set initial value for initialized and loading

---

src/modules/GroupChannelList/context/GroupChannelListProvider.tsx

[fix]: No mark as delivered if `disableMarkAsDelivered` is set to `true`
Fixes [CLNP-6874](https://sendbird.atlassian.net/browse/CLNP-6874)
- Fixed a bug that channel is marked as delivered with `disableMarkAsDelivered` set to `true`
[CLNP-6874]: https://sendbird.atlassian.net/browse/CLNP-6874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CLNP-6874] No mark as delivered if disableMarkAsDelivered is set to true

---

src/lib/Sendbird/utils.ts

[feat]: `localCacheEnabled` option should apply correcly
Fixes [CLNP-6907](https://sendbird.atlassian.net/browse/CLNP-6907)
- Applied the `localCacheEnabled` option to be `false`
[CLNP-6907]: https://sendbird.atlassian.net/browse/CLNP-6907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[feat] `localCacheEnabled` option should apply correcly

---

src/modules/CreateChannel/components/InviteUsers/invite-users.scss
src/ui/UserListItem/index.scss

[fix]: Fixed an issue where the position would break when selecting a member from the invite list.
Fixes [CLNP-7040](https://sendbird.atlassian.net/browse/CLNP-7040)
- Fixed an issue where the position would break when selecting a member from the invite list
and we'll evaluate if we can set up a [CLA](https://en.wikipedia.org/wiki/Contributor_License_Agreement) to allow for the …

Fixed an issue where the position would break when selecting a member from the invite list.

---

package.json
src/ui/MessageContent/__tests__/__snapshots__/MessageContent.spec.js.snap
src/ui/MessageContent/index.tsx
src/ui/ThreadReplies/index.tsx
yarn.lock

[fix]: Fixed an issue where `0` was displayed when a reply was added and then deleted.
Fixes [CLNP-4556](https://sendbird.atlassian.net/browse/CLNP-4556)
- Fixed a bug where `0` was displayed when a reply was added and then deleted
[CLNP-4556]: …

[CLNP-4556]Fixed a bug where 0 is displayed under the message when adding and then deleting Ripple in a thread

---

src/lib/utils/__tests__/uikitConfigMapper.spec.ts
src/lib/utils/uikitConfigMapper.ts

```
Fixes [<TICKET_ID>](https://sendbird.atlassian.net/browse/<TICKET_ID>)
// Changelogs (Recommended)
// Add (internal) at the end of …
```

added enable mark as unread uikit options 250724

---

src/modules/GroupChannel/context/GroupChannelProvider.tsx
src/modules/GroupChannelList/context/GroupChannelListProvider.tsx
src/modules/Thread/context/ThreadProvider.tsx

[fix]: Multiple Chat Windows cause unexpected behavior
PR description
- initialState안에 xxxRef들이  Object로 되어 있어서 여러 Provider 인스턴스가 생성될 때 동일한 객체 참조를 공유하는 문제가 있었습니다. 함수로 변경함으로써 각 Provider 인스턴스마다 새로운 초기 상태 객체를 생성하도록 하여 상태 격리 문제를 해결했습니다.
Fixes [CLNP-7360](https://sendbird.atlassian.net/browse/CLNP-7360)
- Fixed a bug Where Multiple Chat Windows cause unexpected behavior
and we'll …

[CLNP-7360]Multiple Chat Windows cause unexpected behavior

---

apps/testing/src/pages/PlaygroundPage.tsx
package.json
src/modules/Channel/context/hooks/useHandleChannelEvents.ts
src/modules/GroupChannel/components/MessageList/index.tsx
src/modules/Thread/components/ThreadList/ThreadListItemContent.tsx
src/modules/Thread/context/hooks/useThreadFetchers.ts
src/modules/Thread/context/useThread.ts
src/ui/Checkbox/index.scss
src/utils/storeManager.ts
yarn.lock

[fix]: Fixed RQA Issue
Fixes [CLNP-7007](https://sendbird.atlassian.net/browse/CLNP-7007)
Fixes [CLNP-7553](https://sendbird.atlassian.net/browse/CLNP-7553)
- Fixed a bug where failed message can't be resend
- Fixed a bug where Reaction is not updated in Thread
and we'll evaluate if we can set up a [CLA](https://en.wikipedia.org/wiki/Contributor_License_Agreement) to allow for …

Fixed a bug where Failed message can't be send
